import fs from 'node:fs';
let pass=0,fail=0;const c=(n,v)=>{console.log(`${v?'PASS':'FAIL'} ${n}`);v?pass++:fail++;};const page=fs.readFileSync('components/tool-062-discount-price-calculator-page.tsx','utf8'),css=fs.readFileSync('components/tool-062-discount-price-calculator.module.css','utf8');
const how='toolbox-tool-guide toolbox-tool-guide--five',expert='toolbox-tool-format-guide toolbox-tool-expert-post toolbox-tool-expert-post--wide-head',notes='toolbox-tool-info-band toolbox-tool-info-band--section-start toolbox-tool-info-band--bottom-gap toolbox-tool-info-band--left-head toolbox-tool-info-band--format-head',faq='toolbox-tool-faq';
for(const k of ['ToolboxSubpageShell','toolbox-tool-detail-hero','toolbox-tool-detail-body','toolbox-next-work',how,expert,notes,faq])c(`design contract ${k}`,page.includes(k));
c('NEXT WORK before RELATED TOOLS',page.indexOf('NEXT WORK')<page.indexOf('RELATED TOOLS'));c('lower exact order HOW -> EXPERT -> NOTES -> FAQ',page.indexOf(how)<page.indexOf(expert)&&page.indexOf(expert)<page.indexOf(notes)&&page.indexOf(notes)<page.indexOf(faq));
c('category link exact',page.includes('href={`/${locale}/category/unit-calc`}'));c('expert cards source six',(page.match(/<article key={k}>/g)||[]).length===1&&page.includes('.map(([k,h,p])=>'));
c('expert marker BASIC',page.includes('BASIC'));
c('expert marker STACKED',page.includes('STACKED'));
c('expert marker EFFECTIVE',page.includes('EFFECTIVE'));
c('expert marker REVERSE',page.includes('REVERSE'));
c('expert marker RATE',page.includes('RATE'));
c('expert marker BOUNDARY',page.includes('BOUNDARY'));
c('expert heading locale',page.includes('추가 할인은 더하지 않고 순서대로 적용합니다'));
c('expert heading locale',page.includes('Stacked discounts multiply instead of simply adding'));
c('expert heading locale',page.includes('追加割引は足さずに順番に適用します'));
for(const h of ['자주 묻는 질문','Frequently asked questions','よくある質問'])c('FAQ locale heading',page.includes(h));
c('responsive breakpoint 820px',css.includes('@media(max-width:820px)'));
c('responsive breakpoint 560px',css.includes('@media(max-width:560px)'));
c('blue token',css.includes('var(--blue)'));c('line token',css.includes('var(--tb-line)'));c('no !important',!css.includes('!important'));console.log(`RESULT DESIGN PASS=${pass} FAIL=${fail}`);if(fail)process.exit(1);
