import fs from 'node:fs'; import path from 'node:path';
const root=process.cwd(); let pass=0,fail=0; const check=(n,v)=>{console.log(`${v?'PASS':'FAIL'} ${n}`);v?pass++:fail++};
const files=['app/[locale]/unix-timestamp-converter/page.tsx','components/tool-053-unix-timestamp-tool.tsx','components/tool-053-unix-timestamp-tool.module.css','lib/tool-053-unix-timestamp.ts','docs/tool-053/REQ_MASTER_053.md']; for(const f of files)check(`file:${f}`,fs.existsSync(path.join(root,f)));
const product=fs.readFileSync(path.join(root,'components/tool-053-unix-timestamp-tool.tsx'),'utf8'); for(const id of ['tool053-root','tool053-current','tool053-now','tool053-mode-to-date','tool053-mode-to-timestamp','tool053-workspace','tool053-timestamp','tool053-unit-seconds','tool053-unit-milliseconds','tool053-date','tool053-time','tool053-result','tool053-unit-warning'])check(`selector:${id}`,product.includes(`data-testid="${id}"`));
for(const token of ['navigator.clipboard.writeText','setInterval','unitMismatchHint','timestampToDate','localDateTimeToTimestamp','aria-live="polite"'])check(`product:${token}`,product.includes(token));
const page=fs.readFileSync(path.join(root,'app/[locale]/unix-timestamp-converter/page.tsx'),'utf8'); for(const token of ['ko','en','ja','canonical','x-default','WebApplication','051','052','054','ToolboxFaqList'])check(`page:${token}`,page.includes(token));
const css=fs.readFileSync(path.join(root,'components/tool-053-unix-timestamp-tool.module.css'),'utf8');check('css:mobile',css.includes('@media(max-width:720px)'));check('css:380',css.includes('@media(max-width:380px)'));check('css:blue active',/\.active\{[^}]*background:var\(--blue\)/.test(css));check('css:overflow wrap',css.includes('overflow-wrap:anywhere'));check('css:no global import',!css.includes('globals.css'));
const globals=fs.readFileSync(path.join(root,'app/globals.css'),'utf8');check('common:no tool053 globals',!globals.includes('tool053'));
for(const f of ['styles/global-base.css','styles/toolbox-common.css','styles/toolbox-detail-common.css','styles/legacy-site-sealed.css','styles/legacy-tools-sealed.css']){const p=path.join(root,f);if(fs.existsSync(p))check(`common:${f}:no tool053`,!fs.readFileSync(p,'utf8').includes('tool053'));}
console.log(`RESULT SOURCE PASS=${pass} FAIL=${fail}`);if(fail)process.exit(1);
