import { test, expect } from "@playwright/test";
import path from "node:path";
const fixture=(name:string)=>path.join(process.cwd(),"test-fixtures",name);

test.describe("008 image cropper rotator",()=>{
  test("localized routes and primary UI",async({page})=>{for(const locale of ["ko","en","ja"]){await page.goto(`/${locale}/image-cropper-rotator`);await expect(page.locator("h1")).toBeVisible();await expect(page.getByTestId("cropper-workbench")).toBeVisible();}});
  test("uploads image and exposes real editing controls",async({page})=>{await page.goto("/ko/image-cropper-rotator");await page.getByTestId("cropper-file-input").setInputFiles(fixture("sample.jpg"));await expect(page.getByTestId("cropper-stage")).toBeVisible();await expect(page.getByRole("button",{name:"적용하고 다음"}).or(page.getByRole("button",{name:"결과 확인"}))).toBeVisible();});
  test("rotation flip undo and result flow",async({page})=>{await page.goto("/ko/image-cropper-rotator");await page.getByTestId("cropper-file-input").setInputFiles(fixture("sample.jpg"));await page.getByRole("button",{name:"회전",exact:true}).click();await page.getByRole("button",{name:"오른쪽으로 90도"}).click();await page.getByRole("button",{name:"반전",exact:true}).click();await page.getByRole("button",{name:"좌우 반전"}).click();await page.getByRole("button",{name:"실행 취소"}).click();await page.getByRole("button",{name:"결과 확인"}).click();await expect(page.getByRole("heading",{name:"편집 결과"})).toBeVisible();await expect(page.locator("[data-testid^=cropper-download-]:not([data-testid=cropper-download-zip])").first()).toBeVisible();});

  test("precise controls, selected batch target and original inclusion are available",async({page})=>{await page.goto("/ko/image-cropper-rotator");await page.getByTestId("cropper-file-input").setInputFiles([fixture("sample.jpg"),fixture("transparent.png")]);await page.getByRole("button",{name:"더보기",exact:true}).click();await expect(page.getByRole("button",{name:"좌표 적용"})).toBeVisible();await page.getByTestId("cropper-batch-details").locator("summary").click();await expect(page.getByTestId("cropper-batch-selected")).toBeVisible();await page.getByRole("button",{name:"건너뛰기"}).click();await page.getByRole("button",{name:"결과 확인"}).click();await expect(page.getByRole("button",{name:"원본으로 포함"})).toBeVisible();});
  test("crop stage exposes edge handles and wheel zoom",async({page})=>{await page.goto("/ko/image-cropper-rotator");await page.getByTestId("cropper-file-input").setInputFiles(fixture("sample.jpg"));for(const cls of ["handle-t","handle-r","handle-b","handle-l"])await expect(page.locator(`.${cls}`)).toBeVisible();await page.getByTestId("cropper-stage").hover();await page.mouse.wheel(0,-120);await expect(page.getByText(/110%|120%/)).toBeVisible();});
  test("sitemap contains localized 008 urls",async({request})=>{const r=await request.get("/sitemap.xml");const text=await r.text();for(const locale of ["ko","en","ja"])expect(text).toContain(`/${locale}/image-cropper-rotator`);});
});
