import { test, expect } from '@playwright/test';
import { TOOL017, TOOL017_TESTIDS } from './helpers/tool-017';

const PROTECTED_SLUGS=[
  'jpg-png-webp-image-converter','heic-avif-image-converter','svg-bmp-tiff-image-converter','image-compressor','target-size-image-compressor','image-resizer','web-image-optimizer','image-cropper-rotator','image-brightness-color-adjuster','image-mosaic-blur-tool','image-padding-background-tool','image-border-rounded-corners-tool','image-merger','image-collage-maker','before-after-image-maker'
] as const;
const EXPECTED_H1={ko:'이미지 워터마크 넣기',en:'Add Watermark to Images',ja:'画像ウォーターマーク追加ツール'} as const;
const EXPECTED_CONTACT={ko:'이미지 워터마크 넣기',en:'Add Watermark to Images',ja:'画像ウォーターマーク追加ツール'} as const;
const RELATED_SLUGS=['image-compressor','image-resizer','image-collage-maker'] as const;

test.describe('017 regression-only',()=>{
  test('protected 001-015 implemented routes remain reachable in ko/en/ja',async({page})=>{for(const locale of ['ko','en','ja'] as const){for(const slug of PROTECTED_SLUGS){const route=`/${locale}/${slug}`;const r=await page.goto(route,{waitUntil:'domcontentloaded'});expect(r,`HARNESS_ERROR: no response ${route}`).not.toBeNull();expect(r?.ok(),`PRODUCT_FAIL: protected route ${route}`).toBeTruthy()}}});
  for(const locale of ['ko','en','ja'] as const) test(`017 ${locale} route SEO, contact, and related tools remain connected`,async({page})=>{const route=TOOL017[locale];const r=await page.goto(route,{waitUntil:'domcontentloaded'});expect(r?.ok()).toBeTruthy();await expect(page.getByTestId(TOOL017_TESTIDS.root)).toBeVisible();await expect(page.locator('h1')).toContainText(EXPECTED_H1[locale]);await expect(page.locator('link[rel="canonical"]')).toHaveAttribute('href',new RegExp(`/${locale}/image-watermark-tool$`));for(const lang of ['ko','en','ja'])await expect(page.locator(`link[rel="alternate"][hreflang="${lang}"]`)).toHaveAttribute('href',new RegExp(`/${lang}/image-watermark-tool$`));await expect(page.locator('link[rel="alternate"][hreflang="x-default"]')).toHaveAttribute('href',/\/en\/image-watermark-tool$/);const contact=page.locator('footer a[href*="fixlgs.com/contact?app="]');await expect(contact).toHaveCount(1);expect(decodeURIComponent(await contact.getAttribute('href')||'')).toContain(`app=${EXPECTED_CONTACT[locale]}`);for(const slug of RELATED_SLUGS)await expect(page.locator(`a[href="/${locale}/${slug}"]`)).toHaveCount(1)});
  test('017 image-edit category card displays number 17 and is LIVE',async({page})=>{await page.goto('/ko/category/image-edit',{waitUntil:'domcontentloaded'});const card=page.locator('a[href="/ko/image-watermark-tool"]');await expect(card).toHaveCount(1);await expect(card).toContainText('17');await expect(card).toContainText('LIVE')});
  test('017 sitemap and robots integration are present',async({page})=>{const sm=await page.request.get('/sitemap.xml');expect(sm.ok()).toBeTruthy();const text=await sm.text();for(const locale of ['ko','en','ja'])expect(text).toContain(`/${locale}/image-watermark-tool`);const rr=await page.request.get('/robots.txt');expect(rr.ok()).toBeTruthy();expect(await rr.text()).toContain('https://toolbox.fixlgs.com/sitemap.xml')});
  test('017 structured data contains WebApplication FAQPage BreadcrumbList',async({page})=>{await page.goto(TOOL017.ko,{waitUntil:'domcontentloaded'});const joined=(await page.locator('script[type="application/ld+json"]').allTextContents()).join('\n');expect(joined).toContain('WebApplication');expect(joined).toContain('FAQPage');expect(joined).toContain('BreadcrumbList');expect(joined).toContain('/ko/image-watermark-tool')});
});
