import {expect,test} from "@playwright/test"; import {route043,setTexts} from "./helpers/tool-043";
test("line add delete change report and line numbers",async({page})=>{await page.goto(route043());await setTexts(page,"A\n가격 1000원\nX\nB","A\n가격 1200원\nB\nNEW");await page.getByTestId("tool043-run").click();await expect(page.getByTestId("tool043-result")).toBeVisible();await expect(page.getByText("변경",{exact:true}).first()).toBeVisible();await expect(page.getByTestId("tool043-report")).toContainText("[비교 요약]");await expect(page.getByTestId("tool043-diff-list")).toContainText("1");});
test("word detail preserves Japanese and emoji",async({page})=>{await page.goto(route043("ja"));await setTexts(page,"契約期間は1年です🙂","契約期間は2年です🙃");await page.getByTestId("tool043-run").click();await page.getByTestId("tool043-mode-word").click();await expect(page.getByTestId("tool043-diff-list")).toContainText("契約期間");await expect(page.getByTestId("tool043-diff-list")).toContainText("🙃");});
test("identical contract",async({page})=>{await page.goto(route043());await setTexts(page,"alpha\nbeta","alpha\nbeta");await page.getByTestId("tool043-run").click();await expect(page.getByTestId("tool043-identical")).toBeVisible();});
test("A and B file inputs load independently and swap",async({page})=>{await page.goto(route043());await page.getByTestId("tool043-file-a").setInputFiles("tests/fixtures/tool-043/file-a.txt");await page.getByTestId("tool043-file-b").setInputFiles("tests/fixtures/tool-043/file-b.txt");await expect(page.getByTestId("tool043-input-a")).toHaveValue(/old value/);await expect(page.getByTestId("tool043-input-b")).toHaveValue(/new value/);await page.getByTestId("tool043-swap").click();await expect(page.getByTestId("tool043-input-a")).toHaveValue(/new value/);await expect(page.getByTestId("tool043-input-b")).toHaveValue(/old value/);});
test("drag and drop loads the selected side only",async({page})=>{await page.goto(route043());const payload=Buffer.from("dragged A\nsecond line","utf8").toString("base64");await page.getByTestId("tool043-drop-a").evaluate((target,data)=>{const bytes=Uint8Array.from(atob(data),c=>c.charCodeAt(0));const file=new File([bytes],"drag-a.txt",{type:"text/plain"});const transfer=new DataTransfer();transfer.items.add(file);target.dispatchEvent(new DragEvent("drop",{bubbles:true,cancelable:true,dataTransfer:transfer}));},payload);await expect(page.getByTestId("tool043-input-a")).toHaveValue("dragged A\nsecond line");await expect(page.getByTestId("tool043-input-b")).toHaveValue("");});
test("changes-only filter hides unchanged blocks",async({page})=>{await page.goto(route043());await setTexts(page,"same\nold\ntail","same\nnew\ntail");await page.getByTestId("tool043-run").click();const unchanged=page.locator('[data-status="unchanged"]');await expect(unchanged.first()).toBeVisible();await page.getByTestId("tool043-changes-only").click();await expect(unchanged).toHaveCount(0);});
test("TXT report download is generated",async({page})=>{await page.goto(route043());await setTexts(page,"old","new");await page.getByTestId("tool043-run").click();const downloadPromise=page.waitForEvent("download");await page.getByTestId("tool043-download").click();const download=await downloadPromise;expect(download.suggestedFilename()).toBe("text-diff-report.txt");});

test("empty A paste activates only A editor",async({page})=>{await page.goto(route043());await page.getByTestId("tool043-empty-a").focus();await page.getByTestId("tool043-empty-a").evaluate((target)=>{const transfer=new DataTransfer();transfer.setData("text/plain","pasted baseline");target.dispatchEvent(new ClipboardEvent("paste",{bubbles:true,cancelable:true,clipboardData:transfer}));});await expect(page.getByTestId("tool043-input-a")).toHaveValue("pasted baseline");await expect(page.getByTestId("tool043-empty-b")).toBeVisible();});
