import {test,expect} from '@playwright/test';
import {readFile} from 'node:fs/promises';
import {upload019,openTool019,tool019BackgroundPanel,tool019Root,tool019TextPanel,TOOL019_TESTIDS} from './helpers/tool-019';

async function sampleDownloadedPixel(page:any,bytes:Buffer,x:number,y:number){
  return await page.evaluate(async({arr,x,y}:{arr:number[],x:number,y:number})=>{
    const blob=new Blob([new Uint8Array(arr)],{type:'image/png'});const bmp=await createImageBitmap(blob);const c=document.createElement('canvas');c.width=bmp.width;c.height=bmp.height;const ctx=c.getContext('2d')!;ctx.drawImage(bmp,0,0);return Array.from(ctx.getImageData(x,y,1,1).data);
  },{arr:Array.from(bytes),x,y});
}

test.describe('019 core-only',()=>{
 test('renders 1280x720 editor and small preview',async({page})=>{await upload019(page);const c=page.getByTestId(TOOL019_TESTIDS.preview);await expect(c).toHaveAttribute('width','1280');await expect(c).toHaveAttribute('height','720');await expect(page.getByTestId(TOOL019_TESTIDS.small)).toBeVisible();});
 test('title and subtitle are independently editable',async({page})=>{await upload019(page);await page.getByTestId(TOOL019_TESTIDS.title).fill('한글 제목');await page.getByTestId(TOOL019_TESTIDS.subtitle).fill('부제');await expect(page.getByTestId(TOOL019_TESTIDS.title)).toHaveValue('한글 제목');await expect(page.getByTestId(TOOL019_TESTIDS.subtitle)).toHaveValue('부제');});
 test('downloaded PNG is exact 1280x720 and safe guide is absent from output pixels',async({page},testInfo)=>{await openTool019(page);await tool019Root(page).getByRole('button',{name:/단색 배경/}).click();await tool019Root(page).getByLabel('출력 형식').selectOption('png');const d=page.waitForEvent('download');await page.getByTestId(TOOL019_TESTIDS.download).click();const dl=await d;const out=testInfo.outputPath('tool019.png');await dl.saveAs(out);const b=await readFile(out);expect(b.subarray(1,4).toString()).toBe('PNG');expect(b.readUInt32BE(16)).toBe(1280);expect(b.readUInt32BE(20)).toBe(720);const px=await sampleDownloadedPixel(page,b,80,50);expect(px.slice(0,3)).toEqual([17,17,17]);});
 test('font, quick position, text background and full shadow controls are wired',async({page})=>{await upload019(page);await page.getByTestId('tool019-title-font').selectOption('serif');await expect(page.getByTestId('tool019-title-font')).toHaveValue('serif');const titlePanel=tool019TextPanel(page,'title');await titlePanel.getByText('그림자 사용',{exact:true}).locator('input').check();await page.getByTestId('tool019-title-shadow-color').fill('#223344');await page.getByTestId('tool019-title-shadow-opacity').fill('70');await page.getByTestId('tool019-title-shadow-blur').fill('12');await page.getByTestId('tool019-title-shadow-x').fill('6');await page.getByTestId('tool019-title-shadow-y').fill('8');await expect(page.getByTestId('tool019-title-shadow-opacity')).toHaveValue('70');await expect(titlePanel.getByRole('button',{name:'위치 초기화'})).toBeVisible();await titlePanel.getByText('글자 배경 사용',{exact:true}).locator('input').check();await page.getByTestId('tool019-title-text-bg-opacity').fill('65');await expect(page.getByTestId('tool019-title-text-bg-opacity')).toHaveValue('65');});
 test('displayed Blob size matches downloaded file byte size',async({page},testInfo)=>{await upload019(page);await tool019Root(page).getByLabel('출력 형식').selectOption('png');await expect(page.getByTestId(TOOL019_TESTIDS.fileSize)).not.toHaveText('—',{timeout:5000});const d=page.waitForEvent('download');await page.getByTestId(TOOL019_TESTIDS.download).click();const dl=await d;const out=testInfo.outputPath('size-check.png');await dl.saveAs(out);const bytes=(await readFile(out)).length;const displayed=(await page.getByTestId(TOOL019_TESTIDS.fileSize).innerText()).trim();const expected=bytes<1024*1024?`${(bytes/1024).toFixed(0)} KB`:`${(bytes/1024/1024).toFixed(2)} MB`;expect(displayed).toBe(expected);});
 test('JPG quality changes actual output size for stable fixture',async({page},testInfo)=>{await upload019(page);const q=page.getByTestId(TOOL019_TESTIDS.quality);await q.fill('100');let d=page.waitForEvent('download');await page.getByTestId(TOOL019_TESTIDS.download).click();let dl=await d;const hi=testInfo.outputPath('q100.jpg');await dl.saveAs(hi);await q.fill('60');d=page.waitForEvent('download');await page.getByTestId(TOOL019_TESTIDS.download).click();dl=await d;const lo=testInfo.outputPath('q60.jpg');await dl.saveAs(lo);expect((await readFile(lo)).length).toBeLessThan((await readFile(hi)).length);});
});

test('high resolution output is actual 3840x2160 and preserves 16:9',async({page},testInfo)=>{await openTool019(page);await tool019Root(page).getByRole('button',{name:/단색 배경/}).click();await page.getByTestId('tool019-resolution').selectOption('high');await tool019Root(page).getByLabel('출력 형식').selectOption('png');const d=page.waitForEvent('download');await page.getByTestId(TOOL019_TESTIDS.download).click();const dl=await d;const out=testInfo.outputPath('tool019-4k.png');await dl.saveAs(out);const b=await readFile(out);expect(b.readUInt32BE(16)).toBe(3840);expect(b.readUInt32BE(20)).toBe(2160);});

test('safe content and thirds guides are preview-only',async({page},testInfo)=>{await openTool019(page);await tool019Root(page).getByRole('button',{name:/단색 배경/}).click();await tool019Root(page).getByLabel('출력 형식').selectOption('png');await expect(tool019Root(page).getByLabel('출력 형식')).toHaveValue('png');const points=[[64,36],[427,240],[853,480]] as const;async function pixels(name:string){const d=page.waitForEvent('download');await page.getByTestId(TOOL019_TESTIDS.download).click();const dl=await d;const out=testInfo.outputPath(name);await dl.saveAs(out);const b=await readFile(out);expect(b.subarray(1,4).toString()).toBe('PNG');return Promise.all(points.map(([x,y])=>sampleDownloadedPixel(page,b,x,y)));}await page.getByTestId('tool019-safe-guide').uncheck();await page.getByTestId('tool019-thirds-guide').uncheck();const withoutGuides=await pixels('guides-off-output.png');await page.getByTestId('tool019-safe-guide').check();await page.getByTestId('tool019-thirds-guide').check();const withGuides=await pixels('guides-on-preview-only-output.png');expect(withGuides).toEqual(withoutGuides);});

test('fit under 2MB control is JPG-only and bounded',async({page})=>{await openTool019(page);await tool019Root(page).getByRole('button',{name:/단색 배경/}).click();await expect(page.getByTestId('tool019-fit-2mb')).toBeVisible();await page.getByTestId('tool019-fit-2mb').click();await expect(page.getByTestId(TOOL019_TESTIDS.status)).toContainText(/2MB|2 MB/);await tool019Root(page).getByLabel('출력 형식').selectOption('png');await expect(page.getByTestId('tool019-fit-2mb')).toHaveCount(0);});

test('actual output contains title/subtitle/outline/shadow pixels',async({page},testInfo)=>{
 await openTool019(page);await tool019Root(page).getByRole('button',{name:/단색 배경/}).click();
 await page.getByTestId(TOOL019_TESTIDS.title).fill('TITLE');await page.getByTestId(TOOL019_TESTIDS.subtitle).fill('SUB');
 const titlePanel=tool019TextPanel(page,'title');await titlePanel.getByText('그림자 사용',{exact:true}).locator('input').check();
 await page.getByTestId('tool019-title-shadow-color').fill('#00ff00');await page.getByTestId('tool019-title-shadow-opacity').fill('100');await page.getByTestId('tool019-title-shadow-blur').fill('0');await page.getByTestId('tool019-title-shadow-x').fill('14');await page.getByTestId('tool019-title-shadow-y').fill('14');
 await tool019Root(page).getByLabel('출력 형식').selectOption('png');const d=page.waitForEvent('download');await page.getByTestId(TOOL019_TESTIDS.download).click();const dl=await d;const out=testInfo.outputPath('text-pixels.png');await dl.saveAs(out);const b=await readFile(out);
 const stats=await page.evaluate(async arr=>{const blob=new Blob([new Uint8Array(arr)],{type:'image/png'});const bmp=await createImageBitmap(blob);const c=document.createElement('canvas');c.width=bmp.width;c.height=bmp.height;const x=c.getContext('2d')!;x.drawImage(bmp,0,0);const p=x.getImageData(0,0,c.width,c.height).data;let light=0,dark=0,green=0;for(let i=0;i<p.length;i+=4){if(p[i]>220&&p[i+1]>220&&p[i+2]>220)light++;if(p[i]<40&&p[i+1]<40&&p[i+2]<40)dark++;if(p[i]<80&&p[i+1]>160&&p[i+2]<80)green++;}return{light,dark,green};},Array.from(b));
 expect(stats.light).toBeGreaterThan(100);expect(stats.dark).toBeGreaterThan(100);expect(stats.green).toBeGreaterThan(20);
});

test('background crop and zoom alter actual downloaded pixels',async({page},testInfo)=>{
 await openTool019(page);await page.getByTestId(TOOL019_TESTIDS.fileInput).setInputFiles('test-fixtures/crop-probe.jpg');await expect(page.getByTestId(TOOL019_TESTIDS.preview)).toBeVisible();
 await tool019Root(page).getByRole('button',{name:'배경 편집'}).click();await tool019Root(page).getByLabel('출력 형식').selectOption('png');const canvas=page.getByTestId(TOOL019_TESTIDS.preview);const box=await canvas.boundingBox();expect(box).toBeTruthy();
 // Hide text overlays so hitTarget() can only resolve the drag as background.
 for(const kind of ['title','subtitle'] as const){const panel=tool019TextPanel(page,kind);const show=panel.getByText('표시',{exact:true}).locator('input');await show.uncheck();await expect(show).not.toBeChecked();}
 async function outputBytes(name:string){const d=page.waitForEvent('download');await page.getByTestId(TOOL019_TESTIDS.download).click();const dl=await d;const out=testInfo.outputPath(name);await dl.saveAs(out);return readFile(out)}
 const settle=async()=>{await page.evaluate(()=>new Promise<void>(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve()))));await page.waitForTimeout(80)};
 const zoom=tool019BackgroundPanel(page).getByLabel('배경 확대');await zoom.fill('160');await expect(zoom).toHaveValue('160');await settle();const before=await outputBytes('crop-before.png');
 await canvas.scrollIntoViewIfNeeded();await settle();const dragBox=await canvas.boundingBox();expect(dragBox).toBeTruthy();
 if(dragBox){const x=dragBox.x+dragBox.width*.5,y=dragBox.y+dragBox.height*.5;await page.mouse.move(x,y);await page.mouse.down();await page.mouse.move(x,y-dragBox.height*.25,{steps:8});await page.mouse.up();}
 await settle();const moved=await outputBytes('crop-after.png');expect(Buffer.compare(moved,before)).not.toBe(0);
 await zoom.fill('200');await expect(zoom).toHaveValue('200');await settle();const zoomed=await outputBytes('zoom-after.png');expect(Buffer.compare(zoomed,moved)).not.toBe(0);
});

test('line height is independently adjustable for title and subtitle',async({page})=>{await upload019(page);const title=page.getByTestId('tool019-title-line-height'),subtitle=page.getByTestId('tool019-subtitle-line-height');await title.fill('1.30');await subtitle.fill('1.45');expect(Number(await title.inputValue())).toBeCloseTo(1.3,5);expect(Number(await subtitle.inputValue())).toBeCloseTo(1.45,5);});
