import { test, expect } from '@playwright/test';
import { TOOL015, TOOL015_TESTIDS } from './helpers/tool-015';

const PROTECTED_SLUGS=[
  'jpg-png-webp-image-converter','heic-avif-image-converter','svg-bmp-tiff-image-converter','image-compressor','target-size-image-compressor','image-resizer','web-image-optimizer','image-cropper-rotator','image-brightness-color-adjuster','image-mosaic-blur-tool','image-padding-background-tool','image-border-rounded-corners-tool','image-merger','image-collage-maker'
] as const;
const EXPECTED_H1={ko:'전후 비교 이미지만들기',en:'Before & AfterImage Maker',ja:'ビフォー・アフター比較画像作成'} as const;
const EXPECTED_CONTACT={ko:'전후 비교 이미지 만들기',en:'Before & After Image Maker',ja:'ビフォー・アフター比較画像作成'} as const;
const RELATED_SLUGS=['image-merger','image-collage-maker','image-compressor','image-resizer'] as const;

test.describe('015 regression-only',()=>{
  test('protected 001-014 routes remain reachable in ko/en/ja',async({page})=>{for(const locale of ['ko','en','ja'] as const){for(const slug of PROTECTED_SLUGS){const route=`/${locale}/${slug}`;const r=await page.goto(route,{waitUntil:'domcontentloaded'});expect(r,`HARNESS_ERROR: no response ${route}`).not.toBeNull();expect(r?.ok(),`PRODUCT_FAIL: protected route ${route}`).toBeTruthy()}}});
  for(const locale of ['ko','en','ja'] as const) test(`015 ${locale} route SEO, contact, and related tools remain connected`,async({page})=>{const route=TOOL015[locale];const r=await page.goto(route,{waitUntil:'domcontentloaded'});expect(r?.ok(),`PRODUCT_FAIL: ${route}`).toBeTruthy();await expect(page.getByTestId(TOOL015_TESTIDS.root)).toBeVisible();await expect(page.locator('h1')).toContainText(EXPECTED_H1[locale]);await expect(page.locator('link[rel="canonical"]')).toHaveAttribute('href',new RegExp(`/${locale}/before-after-image-maker$`));for(const lang of ['ko','en','ja'])await expect(page.locator(`link[rel="alternate"][hreflang="${lang}"]`)).toHaveAttribute('href',new RegExp(`/${lang}/before-after-image-maker$`));await expect(page.locator('link[rel="alternate"][hreflang="x-default"]')).toHaveAttribute('href',/\/en\/before-after-image-maker$/);const contact=page.locator('footer a[href*="fixlgs.com/contact?app="]');await expect(contact).toHaveCount(1);expect(decodeURIComponent(await contact.getAttribute('href')||'')).toContain(`app=${EXPECTED_CONTACT[locale]}`);for(const slug of RELATED_SLUGS)await expect(page.locator(`a[href="/${locale}/${slug}"]`),`PRODUCT_FAIL: related link /${locale}/${slug}`).toHaveCount(1)});
  test('015 image-edit category card displays actual UI number 15 and is LIVE',async({page})=>{await page.goto('/ko/category/image-edit',{waitUntil:'domcontentloaded'});const card=page.locator('a[href="/ko/before-after-image-maker"]');await expect(card).toHaveCount(1);await expect(card).toContainText('15');await expect(card).not.toContainText('015');await expect(card).toContainText('LIVE')});
  test('015 sitemap and robots integration are present after main-project integration',async({page})=>{const sm=await page.request.get('/sitemap.xml');expect(sm.ok()).toBeTruthy();const text=await sm.text();for(const locale of ['ko','en','ja'])expect(text).toContain(`/${locale}/before-after-image-maker`);const rr=await page.request.get('/robots.txt');expect(rr.ok()).toBeTruthy();expect(await rr.text()).toContain('https://toolbox.fixlgs.com/sitemap.xml')});
  test('015 structured data contains WebApplication FAQPage BreadcrumbList',async({page})=>{await page.goto(TOOL015.ko,{waitUntil:'domcontentloaded'});const joined=(await page.locator('script[type="application/ld+json"]').allTextContents()).join('\n');expect(joined).toContain('WebApplication');expect(joined).toContain('FAQPage');expect(joined).toContain('BreadcrumbList');expect(joined).toContain('/ko/before-after-image-maker')});
});
