import { test, expect, type Page } from '@playwright/test';
import { openTool016, upload016, TOOL016_TESTIDS } from './helpers/tool-016';

async function openMobileSettingsTab(page:Page,name:'글자'|'효과'){
 const tab=page.getByRole('button',{name,exact:true});
 if(await tab.isVisible()) await tab.click();
}
test.describe('016 core-only',()=>{
 test('page opens and accepts a supported image',async({page})=>{await upload016(page);await expect(page.getByTestId(TOOL016_TESTIDS.addbar)).toBeVisible();await expect(page.getByTestId(TOOL016_TESTIDS.output)).toBeVisible();});
 test('adds independent title and body layers',async({page})=>{await upload016(page);await page.getByRole('button',{name:'제목 추가'}).click();await page.getByRole('button',{name:'본문 추가'}).click();await expect(page.getByTestId('tool016-layer')).toHaveCount(2);});
 test('duplicated layers keep independent text state',async({page})=>{await upload016(page);await page.getByRole('button',{name:'제목 추가'}).click();const input=page.getByTestId(TOOL016_TESTIDS.content);await input.fill('첫 레이어');await input.blur();await page.getByRole('button',{name:'복제'}).click();await input.fill('둘째 레이어');await input.blur();await expect(page.getByTestId('tool016-layer').filter({hasText:'첫 레이어'})).toHaveCount(1);await expect(page.getByTestId('tool016-layer').filter({hasText:'둘째 레이어'})).toHaveCount(1);});
 test('selected text content and typography can be edited',async({page})=>{await upload016(page);await page.getByRole('button',{name:'제목 추가'}).click();const input=page.getByTestId(TOOL016_TESTIDS.content);await input.fill('안녕하세요 TOOLBOX');await input.blur();await openMobileSettingsTab(page,'글자');await page.getByTestId(TOOL016_TESTIDS.fontSize).fill('64');await expect(input).toHaveValue('안녕하세요 TOOLBOX');await expect(page.getByTestId(TOOL016_TESTIDS.fontSize)).toHaveValue('64');});
 test('font, alignment and text color settings update the selected layer',async({page})=>{await upload016(page);await page.getByRole('button',{name:'제목 추가'}).click();await openMobileSettingsTab(page,'글자');const settings=page.getByTestId(TOOL016_TESTIDS.settings);const font=settings.getByLabel('글꼴');await font.selectOption('serif');await expect(font).toHaveValue('serif');const left=page.getByRole('button',{name:'왼쪽',exact:true});await left.click();await expect(left).toHaveClass(/active/);const color=settings.locator('label').filter({hasText:'글자 색상'}).locator('input[type="color"]').first();await color.fill('#ff0000');await expect(color).toHaveValue('#ff0000');});
 test('outline shadow and text background controls are available',async({page})=>{await upload016(page);await page.getByRole('button',{name:'제목 추가'}).click();await openMobileSettingsTab(page,'효과');const settings=page.getByTestId(TOOL016_TESTIDS.settings);await settings.getByLabel('외곽선').check();await settings.getByLabel('그림자').check();await settings.getByLabel('글자 배경').check();await expect(settings.getByText('외곽선 두께',{exact:true})).toBeVisible();await expect(settings.getByText('그림자 흐림',{exact:true})).toBeVisible();await expect(settings.getByText('내부 여백',{exact:true})).toBeVisible();});
 test('outline, shadow and text background change the rendered preview',async({page})=>{await upload016(page);await page.getByRole('button',{name:'제목 추가'}).click();const canvas=page.getByTestId(TOOL016_TESTIDS.previewCanvas);const before=await canvas.screenshot();await openMobileSettingsTab(page,'효과');const settings=page.getByTestId(TOOL016_TESTIDS.settings);await settings.getByLabel('외곽선').check();await settings.getByLabel('그림자').check();await settings.getByLabel('글자 배경').check();await page.waitForTimeout(50);const after=await canvas.screenshot();expect(after.equals(before)).toBeFalsy();});
 test('layer duplicate visibility and order actions work',async({page})=>{await upload016(page);await page.getByRole('button',{name:'제목 추가'}).click();await page.getByRole('button',{name:'복제'}).click();await expect(page.getByTestId('tool016-layer')).toHaveCount(2);await page.getByRole('button',{name:'앞으로'}).click();});
 test('undo and redo restore a completed text edit',async({page})=>{await upload016(page);await page.getByRole('button',{name:'제목 추가'}).click();const input=page.getByTestId(TOOL016_TESTIDS.content);await expect(input).toHaveValue('제목');await input.fill('히스토리 검수');await input.blur();await page.getByRole('button',{name:'실행 취소'}).click();await expect(input).toHaveValue('제목');await page.getByRole('button',{name:'다시 실행'}).click();await expect(input).toHaveValue('히스토리 검수');});
 test('Korean IME composition does not create broken intermediate text',async({page})=>{await upload016(page);await page.getByRole('button',{name:'본문 추가'}).click();const input=page.getByTestId(TOOL016_TESTIDS.content);await input.focus();await input.fill('한글 조합 입력');await input.blur();await expect(input).toHaveValue('한글 조합 입력');await page.getByRole('button',{name:'실행 취소'}).click();await expect(input).toHaveValue('본문을 입력하세요');});

 test('adds date, location, and general text layers independently',async({page})=>{await upload016(page);await page.getByRole('button',{name:'날짜 추가'}).click();await page.getByRole('button',{name:'위치 추가'}).click();await page.getByRole('button',{name:'글자 추가'}).click();await expect(page.getByTestId('tool016-layer')).toHaveCount(3);});
 test('canvas pointer drag moves the selected text layer',async({page})=>{await upload016(page);await page.getByRole('button',{name:'제목 추가'}).click();const input=page.getByTestId(TOOL016_TESTIDS.content);await input.fill('드래그');await input.blur();const canvas=page.getByTestId(TOOL016_TESTIDS.previewCanvas);const viewport=page.viewportSize();if(viewport&&viewport.width<=500){const zoomOut=page.getByRole('button',{name:'축소',exact:true});await zoomOut.click();await zoomOut.click();await page.waitForTimeout(50);}await canvas.scrollIntoViewIfNeeded();const before=await canvas.screenshot();const box=await canvas.boundingBox();expect(box).not.toBeNull();if(!box)return;const startX=box.x+box.width*.5;const startY=box.y+box.height*.17;const endX=startX+Math.min(40,box.width*.08);const endY=startY+Math.min(40,box.height*.08);await page.mouse.move(startX,startY);await page.mouse.down();await page.mouse.move(endX,endY,{steps:8});await page.mouse.up();await page.waitForTimeout(80);const after=await canvas.screenshot();expect(after.equals(before)).toBeFalsy();});
 test('exports PNG at the original source resolution',async({page})=>{await upload016(page);await page.getByRole('button',{name:'제목 추가'}).click();const d=page.waitForEvent('download');await page.getByTestId(TOOL016_TESTIDS.download).click();const dl=await d;const path=await dl.path();expect(path).toBeTruthy();if(!path)return;const {readFile}=await import('node:fs/promises');const base64=(await readFile(path)).toString('base64');const size=await page.evaluate(async(b64)=>{const img=new Image();const ready=new Promise<{w:number,h:number}>((resolve,reject)=>{img.onload=()=>resolve({w:img.naturalWidth,h:img.naturalHeight});img.onerror=()=>reject(new Error('downloaded PNG decode failed'));});img.src='data:image/png;base64,'+b64;return await ready;},base64);expect(size).toEqual({w:800,h:600});});
 test('JPG and WebP output formats create matching download extensions',async({page})=>{await upload016(page);await page.getByRole('button',{name:'제목 추가'}).click();const format=page.getByLabel('출력 형식');for(const value of ['jpg','webp'] as const){await format.selectOption(value);const d=page.waitForEvent('download');await page.getByTestId(TOOL016_TESTIDS.download).click();const dl=await d;expect(dl.suggestedFilename()).toMatch(new RegExp(`\.${value}$`));}});
 test('downloads a real PNG without editor selection box',async({page})=>{await upload016(page);await page.getByRole('button',{name:'제목 추가'}).click();const d=page.waitForEvent('download');await page.getByTestId(TOOL016_TESTIDS.download).click();const dl=await d;expect(dl.suggestedFilename()).toMatch(/-text\.png$/);await expect(page.getByTestId(TOOL016_TESTIDS.status)).toContainText('완료');});
});
