import { test, expect } from '@playwright/test';
import { openTool015, uploadTwo, TOOL015_TESTIDS } from './helpers/tool-015';

test.describe('015 core-only',()=>{
  test('actual UI uses display number 15, not internal 015',async({page})=>{await openTool015(page,'ko');const eyebrow=page.locator('.toolbox-subpage-eyebrow');await expect(eyebrow).toContainText('15 · IMAGE EDIT');await expect(eyebrow).not.toContainText('015 · IMAGE EDIT')});
  test('two image slots become ready and download becomes enabled',async({page})=>{await uploadTwo(page);await expect(page.getByTestId(TOOL015_TESTIDS.download)).toBeEnabled()});
  test('horizontal and vertical layouts update the observable state',async({page})=>{await uploadTwo(page);const state=page.getByTestId(TOOL015_TESTIDS.state);await expect(state).toHaveAttribute('data-layout','horizontal');await page.getByTestId(TOOL015_TESTIDS.vertical).click();await expect(state).toHaveAttribute('data-layout','vertical');await page.getByTestId(TOOL015_TESTIDS.horizontal).click();await expect(state).toHaveAttribute('data-layout','horizontal')});
  test('cover and contain fit are connected to selected slot state',async({page})=>{await uploadTwo(page);const state=page.getByTestId(TOOL015_TESTIDS.state);await page.getByTestId(TOOL015_TESTIDS.contain).click();await expect(state).toHaveAttribute('data-before-fit','contain');await expect(state).toHaveAttribute('data-after-fit','contain');await page.getByTestId(TOOL015_TESTIDS.cover).click();await expect(state).toHaveAttribute('data-before-fit','cover')});
  test('swap moves image data rather than only changing visual labels',async({page})=>{await uploadTwo(page);const state=page.getByTestId(TOOL015_TESTIDS.state);const before=await state.getAttribute('data-before-name');const after=await state.getAttribute('data-after-name');await page.getByTestId(TOOL015_TESTIDS.swap).click();await expect(state).toHaveAttribute('data-before-name',after||'');await expect(state).toHaveAttribute('data-after-name',before||'')});
  test('labels and divider can be hidden without removing image state',async({page})=>{await uploadTwo(page);const state=page.getByTestId(TOOL015_TESTIDS.state);await page.getByTestId(TOOL015_TESTIDS.labels).uncheck();await expect(state).toHaveAttribute('data-labels','0');await page.getByTestId(TOOL015_TESTIDS.divider).uncheck();await expect(state).toHaveAttribute('data-divider','0');await expect(state).toHaveAttribute('data-before-ready','1')});
  test('result dimensions and format selectors update state',async({page})=>{await uploadTwo(page);const state=page.getByTestId(TOOL015_TESTIDS.state);await page.getByTestId(TOOL015_TESTIDS.width).fill('1600');await page.getByTestId(TOOL015_TESTIDS.height).fill('900');await page.getByTestId(TOOL015_TESTIDS.format).selectOption('webp');await expect(state).toHaveAttribute('data-width','1600');await expect(state).toHaveAttribute('data-height','900');await expect(state).toHaveAttribute('data-format','webp')});
});
