import {test,expect} from '@playwright/test';import {upload019,tool019Root,TOOL019_TESTIDS} from './helpers/tool-019';
test.describe('019 boundary-only',()=>{
 test('long KO EN JA title wraps without leaving the 1280 canvas',async({page})=>{await upload019(page);const input=page.getByTestId(TOOL019_TESTIDS.title),canvas=page.getByTestId(TOOL019_TESTIDS.preview);for(const text of ['아주 긴 유튜브 썸네일 제목 테스트 문장입니다 '.repeat(8),'A long YouTube thumbnail title that wraps across the selected width '.repeat(7),'空白のない日本語タイトルでも安全に折り返されます'.repeat(8)]){await input.fill(text);await expect(input).toHaveValue(text.slice(0,120));const box=await canvas.boundingBox();expect(box?.width).toBeGreaterThan(0);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth)).toBeTruthy();}});
 test('JPG quality and PNG format controls remain valid',async({page})=>{await upload019(page);const q=page.getByTestId(TOOL019_TESTIDS.quality);await q.fill('70');await expect(q).toHaveValue('70');await tool019Root(page).getByLabel('출력 형식').selectOption('png');await expect(page.getByTestId(TOOL019_TESTIDS.quality)).toHaveCount(0);});
 test('corrupt JPG with invalid signature is rejected explicitly',async({page})=>{await page.goto('/ko/youtube-thumbnail-maker');await page.getByTestId('tool019-file-input').setInputFiles('test-fixtures/corrupt.jpg');const root=tool019Root(page);await expect(root.getByRole('alert')).toContainText('파일 내용과 이미지 형식이 일치하지 않습니다.');});
 test('low resolution fixture shows warning but remains editable',async({page})=>{await upload019(page,'test-fixtures/low-640x360.jpg');await expect(tool019Root(page).getByText(/해상도가 낮아/)).toBeVisible();await expect(page.getByTestId(TOOL019_TESTIDS.title)).toBeVisible();});
});

test('empty, MIME mismatch, APNG and animated WebP are rejected explicitly',async({page})=>{await page.goto('/ko/youtube-thumbnail-maker');for(const [file,msg] of [['test-fixtures/empty.jpg','빈 파일'],['test-fixtures/mime-mismatch.jpg','일치하지 않습니다'],['test-fixtures/animated-apng.png','애니메이션'],['test-fixtures/animated.webp','애니메이션']] as const){await page.getByTestId('tool019-file-input').setInputFiles(file);await expect(tool019Root(page).getByRole('alert')).toContainText(msg);}});

test('multilingual filenames remain usable and are sanitized on download',async({page})=>{for(const file of ['test-fixtures/한국어-파일명.jpg','test-fixtures/日本語-ファイル名.jpg']){await page.goto('/ko/youtube-thumbnail-maker');await page.getByTestId('tool019-file-input').setInputFiles(file);await expect(page.getByTestId('tool019-filename')).toHaveValue(/thumbnail\.jpg$/);}});
