import fs from 'node:fs';
let pass=0,fail=0;
const c=(n,v)=>{console.log(`${v?'PASS':'FAIL'} ${n}`);v?pass++:fail++;};
const page=fs.readFileSync('components/tool-065-fraction-decimal-calculator-page.tsx','utf8');
const tool=fs.readFileSync('components/tool-065-fraction-decimal-calculator.tsx','utf8');
const css=fs.readFileSync('components/tool-065-fraction-decimal-calculator.module.css','utf8');
const common=fs.readFileSync('styles/toolbox-detail-common.css','utf8');
for(const token of ['ToolboxSubpageShell','toolbox-tool-detail-hero','toolbox-tool-detail-body','toolbox-next-work','toolbox-tool-guide toolbox-tool-guide--five','toolbox-tool-format-guide toolbox-tool-expert-post toolbox-tool-expert-post--wide-head','toolbox-tool-info-band toolbox-tool-info-band--section-start toolbox-tool-info-band--bottom-gap toolbox-tool-info-band--left-head toolbox-tool-info-band--format-head','toolbox-tool-faq'])c(`common contract ${token}`,page.includes(token));
c('lower section exact order',page.indexOf('toolbox-tool-guide toolbox-tool-guide--five')<page.indexOf('toolbox-tool-format-guide toolbox-tool-expert-post')&&page.indexOf('toolbox-tool-format-guide toolbox-tool-expert-post')<page.indexOf('toolbox-tool-info-band toolbox-tool-info-band--section-start')&&page.indexOf('toolbox-tool-info-band toolbox-tool-info-band--section-start')<page.indexOf('toolbox-tool-faq'));
for(const id of ['tool065-root','tool065-a','tool065-b','tool065-operator','tool065-reset','tool065-calculate','tool065-result','tool065-copy'])c(`runtime testid ${id}`,tool.includes(`data-testid="${id}"`));
c('dynamic tab testid template',tool.includes('data-testid={`tool065-tab-${m}`}'));
c('4-tab source contract',tool.includes("(['ops','simplify','f2d','d2f'] as Mode[])"));
c('desktop operation grid',css.includes('grid-template-columns:minmax(0,1fr) 82px minmax(0,1fr)'));
c('mobile tab and form reflow',css.includes('@media(max-width:720px)')&&css.includes('.tabs{grid-template-columns:repeat(2,minmax(0,1fr))}')&&css.includes('.operationGrid{grid-template-columns:1fr}')&&css.includes('.resultGrid{grid-template-columns:1fr}'));
c('narrow mobile action stack',css.includes('@media(max-width:420px)')&&css.includes('.actions{grid-template-columns:1fr}'));
c('common divider automatic contract',common.includes('.toolbox-tool-info-band--format-head.toolbox-tool-info-band--section-start::before')&&common.includes('width:100vw'));
c('wide-head multilingual wrap contract',common.includes('.toolbox-tool-expert-post--wide-head .toolbox-tool-format-guide-head h2{white-space:normal;overflow-wrap:anywhere;word-break:normal}'));
c('no per-tool divider modifier',!page.includes('toolbox-tool-info-band--full-divider'));
c('global pollution absent',!/(globals\.css|legacy-(site|tools)-sealed|!important)/i.test(page+css));
console.log(`RESULT DESIGN-CODE PASS=${pass} FAIL=${fail} ACTUAL_DOM=YES COMMON_DIVIDER=AUTO TOOL=065`);if(fail)process.exit(1);
