import { ToolNavigation } from "@/components/tool-navigation";
import Link from "next/link";
import { AgeLifeCalculatorTool } from "@/components/age-life-calculator-tool";
import { ToolboxFaqList } from "@/components/toolbox-faq-list";
import { ToolboxSubpageShell } from "@/components/toolbox-subpage-shell";
import type { Locale } from "@/lib/site";

const copy={
 ko:{back:"날짜·시간 도구",title:"나이·생후기간 계산기",desc:"생년월일과 기준일로 정확한 만나이, 연나이, 생후 일수와 다음 생일까지 남은 날짜를 한 번에 확인하세요.",local:"나이 계산은 브라우저 로컬에서만 처리합니다.",next:"다음 작업",related:"관련 도구",available:"사용 가능",coming:"준비 중",how:"사용 방법",guide:"나이와 생후기간을 정확하게 읽는 기준",guideDesc:"만나이와 연나이를 구분하고 윤년·월말·2월 29일 규칙과 생후 일수 기준을 명확히 확인할 수 있습니다.",caution:"주의사항",faq:"자주 묻는 질문",steps:["생년월일을 선택합니다.","기준일을 확인하거나 필요한 날짜로 변경합니다.","만나이·연나이·생후 일수·다음 생일까지 결과를 확인합니다.","필요하면 결과를 복사하고 새 계산은 초기화합니다."],points:[["CALENDAR","만나이는 달력 단위로 계산","365일로 나누지 않고 완료된 달력 연·월·일 순서로 계산합니다."],["YEAR AGE","연나이는 별도 값","연나이는 기준연도에서 출생연도를 뺀 값으로, 실제 생일 경과를 반영하는 만나이와 구분합니다."],["ELAPSED","생후 일수는 실제 경과 일수","생년월일과 기준일이 같으면 0일이며 Gregorian 달력의 실제 날짜 차이를 사용합니다."],["BIRTHDAY","다음 생일을 바로 확인","기준일의 생일이 지나지 않았으면 그해 생일, 지났으면 다음 해 생일까지 남은 일수를 계산합니다."],["LEAP","2월 29일 정책 고정","2월 29일 출생자는 비윤년의 생일을 2월 28일로 계산하여 결과와 FAQ의 정책을 일치시킵니다."]],cautions:["이 결과는 입력한 달력 날짜 기준이며 법적 연령·자격·보험·의료 판정의 단일 근거가 아닙니다.","지원 범위는 1900-01-01부터 2100-12-31까지입니다.","미래 생년월일은 정상 결과로 계산하지 않고 오류를 표시합니다.","생년월일·기준일·계산 결과 원문은 서버나 Analytics 값으로 전송하지 않습니다."],faqs:[["만나이와 연나이는 왜 다른가요?","만나이는 실제 생일을 기준으로 완료된 달력 연·월·일을 계산하고, 연나이는 기준연도-출생연도 값을 별도로 표시합니다."],["기준일을 오늘이 아닌 날짜로 바꿀 수 있나요?","네. 오늘이 기본값이지만 지원 범위 안에서 원하는 기준일로 변경할 수 있습니다."],["생후 일수는 태어난 날을 1일로 세나요?","아니요. elapsed days 기준이므로 생년월일과 기준일이 같은 날은 0일입니다."],["2월 29일 출생자는 비윤년에 어떻게 계산하나요?","이 도구는 비윤년의 생일을 2월 28일로 고정해 계산합니다."],["윤년과 월말도 반영하나요?","네. Gregorian 달력의 실제 월 길이와 윤년 규칙으로 계산합니다."],["입력값이 서버로 전송되나요?","아니요. 계산은 현재 브라우저 로컬에서 처리하며 입력 날짜와 결과 원문을 서버에 저장하지 않습니다."]]},
 en:{back:"Date & Time",title:"Age & Elapsed Life Calculator",desc:"Use a date of birth and as-of date to see exact calendar age, year age, days since birth, and the time remaining until the next birthday.",local:"Age calculations run only in your browser.",next:"Next work",related:"Related tools",available:"Available",coming:"Coming soon",how:"How to use",guide:"How to read age and elapsed life accurately",guideDesc:"Separate calendar age from year age and use explicit rules for leap years, month ends, February 29, and elapsed days.",caution:"Important notes",faq:"Frequently asked questions",steps:["Choose a date of birth.","Confirm the as-of date or change it when needed.","Review calendar age, year age, days since birth, and next birthday.","Copy the result if needed, or reset for a new calculation."],points:[["CALENDAR","Calendar age uses real calendar units","The result uses complete calendar years, months, then days instead of dividing total days by 365."],["YEAR AGE","Year age is separate","Year age is the as-of year minus birth year, so it is shown separately from birthday-based calendar age."],["ELAPSED","Days since birth use elapsed days","The same date is 0 days, using the actual Gregorian date difference."],["BIRTHDAY","Next birthday is immediate","The tool uses this year's birthday when it has not passed, otherwise next year's birthday."],["LEAP","February 29 policy is fixed","A February 29 birthday is treated as February 28 in non-leap years, consistently across results and help text."]],cautions:["Results use calendar dates and are not a sole basis for legal eligibility, insurance, or medical decisions.","The supported service range is 1900-01-01 through 2100-12-31.","A future date of birth is rejected instead of being displayed as a normal result.","Raw input dates and calculated results are not sent to a server or Analytics value."],faqs:[["Why are calendar age and year age different?","Calendar age uses completed years, months, and days from the birthday; year age is the as-of year minus birth year."],["Can I change the as-of date from today?","Yes. Today is the default, but you can choose another date within the supported range."],["Is the birth date counted as day 1?","No. This uses elapsed days, so the birth date itself is day 0."],["How is a February 29 birthday handled in a non-leap year?","This tool consistently treats February 28 as the birthday in non-leap years."],["Are leap years and month ends handled?","Yes. Calculations use Gregorian leap-year and month-length rules."],["Are my dates uploaded?","No. Input dates and result text stay in the current browser."]]},
 ja:{back:"日付・時間",title:"年齢・生後期間計算ツール",desc:"生年月日と基準日から、満年齢、年基準の年齢、生後日数、次の誕生日までの日数をまとめて確認できます。",local:"年齢計算はブラウザ内だけで処理します。",next:"次の作業",related:"関連ツール",available:"利用可能",coming:"準備中",how:"使い方",guide:"年齢と生後期間を正確に読む基準",guideDesc:"満年齢と年基準の年齢を分け、うるう年・月末・2月29日・生後日数の規則を明確にします。",caution:"注意事項",faq:"よくある質問",steps:["生年月日を選択します。","基準日を確認し、必要に応じて変更します。","満年齢・年基準の年齢・生後日数・次の誕生日までを確認します。","必要なら結果をコピーし、新しい計算はリセットします。"],points:[["CALENDAR","満年齢は暦単位で計算","365日で割らず、完了した暦年・月・日の順に計算します。"],["YEAR AGE","年基準の年齢は別表示","基準年－出生年の値であり、誕生日の経過を反映する満年齢とは分けて表示します。"],["ELAPSED","生後日数は実際の経過日数","生年月日と基準日が同じなら0日で、Gregorian暦の実際の日付差を使います。"],["BIRTHDAY","次の誕生日をすぐ確認","基準日の年の誕生日がまだならその日、過ぎていれば翌年の誕生日までを計算します。"],["LEAP","2月29日の規則を固定","2月29日生まれは、うるう年でない年の誕生日を2月28日として一貫して計算します。"]],cautions:["結果は入力した暦日基準で、法的年齢・資格・保険・医療判断の単独根拠ではありません。","対応範囲は1900-01-01から2100-12-31までです。","未来の生年月日は通常結果として表示せずエラーにします。","生年月日・基準日・結果の原文はサーバーやAnalytics値へ送信しません。"],faqs:[["満年齢と年基準の年齢はなぜ違いますか？","満年齢は誕生日を基準に完了した暦年・月・日を計算し、年基準の年齢は基準年－出生年を別表示します。"],["基準日を今日以外に変更できますか？","はい。今日が初期値ですが、対応範囲内で任意の日付に変更できます。"],["生後日数は出生日を1日目に数えますか？","いいえ。経過日数なので、生年月日と基準日が同じ日は0日です。"],["2月29日生まれは非うるう年にどう扱いますか？","このツールでは2月28日を誕生日として固定して計算します。"],["うるう年や月末も反映しますか？","はい。Gregorian暦の実際の月日数とうるう年規則を使います。"],["入力値はサーバーへ送信されますか？","いいえ。入力日付と結果文は現在のブラウザ内に留まります。"]]}
} as const;

export function AgeLifeCalculatorPage({locale}:{locale:Locale}){
 const t=copy[locale],url=`https://toolbox.fixlgs.com/${locale}/age-life-calculator`;
 const related=[{n:"045",href:`/${locale}/date-difference-calculator`,name:locale==="ko"?"날짜 차이 계산기":locale==="ja"?"日付差計算ツール":"Date Difference Calculator"},{n:"047",href:`/${locale}/dday-anniversary-calculator`,name:locale==="ko"?"디데이·기념일 계산기":locale==="ja"?"D-day・記念日計算ツール":"D-day & Anniversary Calculator"},{n:"049",href:"",name:locale==="ko"?"근속·재직기간 계산기":locale==="ja"?"勤続・在職期間計算ツール":"Employment Duration Calculator"}];
 const jsonLd={"@context":"https://schema.org","@graph":[{"@type":"WebApplication",name:t.title,applicationCategory:"UtilitiesApplication",operatingSystem:"Any",url,description:t.desc,offers:{"@type":"Offer",price:"0",priceCurrency:"USD"}},{"@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:"TOOLBOX",item:`https://toolbox.fixlgs.com/${locale}`},{"@type":"ListItem",position:2,name:t.back,item:`https://toolbox.fixlgs.com/${locale}/category/date-time`},{"@type":"ListItem",position:3,name:t.title,item:url}]},{"@type":"FAQPage",mainEntity:t.faqs.map(([q,a])=>({"@type":"Question",name:q,acceptedAnswer:{"@type":"Answer",text:a}}))}]};
 return <ToolboxSubpageShell locale={locale} appName={t.title}><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(jsonLd)}}/>
 <section className="toolbox-tool-detail-hero toolbox-tool-detail-hero--single-line-description"><Link className="toolbox-subpage-back" href={`/${locale}/category/date-time`}>← {t.back}</Link><p className="toolbox-subpage-eyebrow">048 · DATE & TIME</p><div className="toolbox-tool-detail-heading"><h1><span className="toolbox-tool-title-line">{t.title}</span></h1><p>{t.desc}</p></div><div className="toolbox-tool-detail-badge"><strong>LOCAL</strong><span>{t.local}</span></div></section>
 <section className="toolbox-tool-detail-body"><div><AgeLifeCalculatorTool locale={locale}/>
 <ToolNavigation locale={locale} currentTool={48} />
 </div></section>
 <section className="toolbox-tool-guide toolbox-tool-guide--four"><div className="toolbox-tool-guide-head"><p>HOW TO USE</p><h2>{t.how}</h2></div><ol>{t.steps.map((s,i)=><li key={s}><span>{String(i+1).padStart(2,"0")}</span><p>{s}</p></li>)}</ol></section>
 <section className="toolbox-tool-format-guide toolbox-tool-expert-post toolbox-tool-expert-post--wide-head"><div className="toolbox-tool-format-guide-head"><p>AGE GUIDE</p><h2>{t.guide}</h2><span>{t.guideDesc}</span></div><div className="toolbox-tool-format-body"><div className="toolbox-tool-format-grid">{t.points.map(([tag,title,desc])=><article key={tag}><strong>{tag}</strong><h3>{title}</h3><p>{desc}</p></article>)}</div></div></section>
 <section className="toolbox-tool-info-band toolbox-tool-info-band--section-start toolbox-tool-info-band--bottom-gap toolbox-tool-info-band--left-head toolbox-tool-info-band--format-head toolbox-tool-info-band--full-divider"><div className="toolbox-tool-info-band-head"><p>IMPORTANT NOTES</p><h2>{t.caution}</h2></div><ul className="toolbox-tool-info-band-list">{t.cautions.map(c=><li key={c}>{c}</li>)}</ul></section>
 <section className="toolbox-tool-faq"><div className="toolbox-tool-guide-head"><p>FAQ</p><h2>{t.faq}</h2></div><ToolboxFaqList items={t.faqs.map(([q,a]):readonly[string,string]=>[q,a])} initialCount={5} moreLabel={locale==="ko"?"FAQ 더보기":locale==="ja"?"FAQをもっと見る":"Show more FAQs"} collapseLabel={locale==="ko"?"FAQ 접기":locale==="ja"?"FAQを閉じる":"Collapse FAQs"} className="toolbox-tool-faq-list"/></section>
 </ToolboxSubpageShell>
}
