'use client';
import {useEffect,useMemo,useRef,useState} from 'react';
import styles from './app-icon-favicon-generator-tool.module.css';
import {ANDROID_SIZES,FAVICON_SIZES,PWA_SIZES,TOOL023_MAX_BYTES,TOOL023_MAX_PIXELS,decodeImage,downloadBlob,makeIco,makeZip,renderSquare,safeBaseName,type Layout} from '@/lib/tool-023-icon-generator';
import type {Locale} from '@/lib/site';

type Platform='android'|'pwa'|'favicon';
type ResultSet={files:{path:string;blob:Blob}[];playBytes:number};
const text={
ko:{choose:'이미지 선택',dropHint:'클릭하거나 이미지를 이 영역으로 드래그앤드롭',hint:'PNG · JPG · WebP · 최대 20MB / 40MP',fit:'원본 맞춤',contain:'전체 보기',cover:'채우기',bg:'배경색',transparent:'투명 배경',zoom:'확대·축소',x:'가로 위치',y:'세로 위치',android:'Android 아이콘',pwa:'PWA 아이콘',favicon:'파비콘',adaptive:'Adaptive 미리보기',safe:'안전영역',regular:'일반 아이콘',maskable:'Maskable 아이콘',small:'작은 크기 미리보기',generate:'아이콘 생성',download:'다운로드',downloadAll:'전체 ZIP 다운로드',androidZip:'Android ZIP',pwaZip:'PWA ZIP',faviconZip:'Favicon ZIP',newImage:'새 이미지',reset:'설정 초기화',resetAll:'전체 초기화',safeToggle:'안전영역 표시',zoomPreview:'확대 미리보기',ready:'이미지를 선택하면 미리보기와 출력 설정이 표시됩니다.',generating:'아이콘을 생성하고 있습니다…',done:'생성이 완료되었습니다. 필요한 묶음을 다운로드하세요.',playWarn:'Google Play 512×512 PNG가 1024KB를 초과했습니다. 업로드 전 용량을 확인하세요.',safeWarn:'안전영역은 미리보기용 가이드이며 최종 파일에는 포함되지 않습니다.',ico:'ICO 16·32·48 멀티프레임',error:'이미지를 처리할 수 없습니다.'},
en:{choose:'Choose Image',dropHint:'Click or drag and drop an image into this area',hint:'PNG · JPG · WebP · up to 20MB / 40MP',fit:'Fit',contain:'Contain',cover:'Cover',bg:'Background Color',transparent:'Transparent Background',zoom:'Zoom',x:'Horizontal Position',y:'Vertical Position',android:'Android Icons',pwa:'PWA Icons',favicon:'Favicon',adaptive:'Adaptive Preview',safe:'Safe Zone',regular:'Regular Icon',maskable:'Maskable Icon',small:'Small-size Preview',generate:'Generate Icons',download:'Download',downloadAll:'Download All ZIP',androidZip:'Android ZIP',pwaZip:'PWA ZIP',faviconZip:'Favicon ZIP',newImage:'New Image',reset:'Reset Settings',resetAll:'Reset All',safeToggle:'Show Safe Zone',zoomPreview:'Enlarged Preview',ready:'Choose an image to show previews and export controls.',generating:'Generating icon assets…',done:'Generation complete. Download the bundles you need.',playWarn:'The Google Play 512×512 PNG exceeds 1024KB. Check the file size before upload.',safeWarn:'Safe-zone lines are preview guides only and are not included in exports.',ico:'ICO with 16·32·48 frames',error:'The image could not be processed.'},
ja:{choose:'画像を選択',dropHint:'クリックまたは画像をこの領域へドラッグ＆ドロップ',hint:'PNG・JPG・WebP・最大20MB / 40MP',fit:'画像の合わせ方',contain:'全体を表示',cover:'塗りつぶし',bg:'背景色',transparent:'透明背景',zoom:'拡大・縮小',x:'横位置',y:'縦位置',android:'Android アイコン',pwa:'PWA アイコン',favicon:'ファビコン',adaptive:'アダプティブプレビュー',safe:'セーフゾーン',regular:'通常アイコン',maskable:'マスカブルアイコン',small:'小サイズプレビュー',generate:'アイコンを生成',download:'ダウンロード',downloadAll:'すべてダウンロード',androidZip:'Android ZIP',pwaZip:'PWA ZIP',faviconZip:'Favicon ZIP',newImage:'新しい画像',reset:'設定をリセット',resetAll:'すべてリセット',safeToggle:'セーフゾーンを表示',zoomPreview:'拡大プレビュー',ready:'画像を選択するとプレビューと出力設定が表示されます。',generating:'アイコンを生成しています…',done:'生成が完了しました。必要なファイルをダウンロードしてください。',playWarn:'Google Play 512×512 PNG が 1024KB を超えています。アップロード前に容量を確認してください。',safeWarn:'セーフゾーンはプレビュー用ガイドで、最終ファイルには含まれません。',ico:'16・32・48 フレーム入り ICO',error:'画像を処理できません。'}
} as const;

export function AppIconFaviconGeneratorTool({locale}:{locale:Locale}){
 const t=text[locale];const inputRef=useRef<HTMLInputElement>(null);const [file,setFile]=useState<File|null>(null);const [bitmap,setBitmap]=useState<ImageBitmap|null>(null);const [src,setSrc]=useState('');const [drag,setDrag]=useState(false);const [platform,setPlatform]=useState<Platform>('android');const [layout,setLayout]=useState<Layout>({fit:'contain',scale:1,x:0,y:0,background:'#ffffff',transparent:true});const [busy,setBusy]=useState(false);const [message,setMessage]=useState<string>(t.ready);const [error,setError]=useState('');const [results,setResults]=useState<ResultSet|null>(null);const [previewUrl,setPreviewUrl]=useState('');const [maskableUrl,setMaskableUrl]=useState('');const [faviconUrls,setFaviconUrls]=useState<Record<number,string>>({});const [showSafeZone,setShowSafeZone]=useState(true);
 useEffect(()=>()=>{bitmap?.close();if(src)URL.revokeObjectURL(src)},[bitmap,src]);
 useEffect(()=>{let cancelled=false;let u1='',u2='';let nextFav:Record<number,string>={};if(!bitmap){setPreviewUrl(old=>{if(old)URL.revokeObjectURL(old);return ''});setMaskableUrl(old=>{if(old)URL.revokeObjectURL(old);return ''});setFaviconUrls(old=>{Object.values(old).forEach(URL.revokeObjectURL);return {}});return;}Promise.all([renderSquare(bitmap,512,layout),renderSquare(bitmap,512,{...layout,transparent:false},true),...FAVICON_SIZES.map(size=>renderSquare(bitmap,size,layout))]).then(([a,b,...fav])=>{if(cancelled)return;u1=URL.createObjectURL(a);u2=URL.createObjectURL(b);nextFav={};fav.forEach((blob,i)=>{nextFav[FAVICON_SIZES[i]]=URL.createObjectURL(blob)});setPreviewUrl(old=>{if(old)URL.revokeObjectURL(old);return u1});setMaskableUrl(old=>{if(old)URL.revokeObjectURL(old);return u2});setFaviconUrls(old=>{Object.values(old).forEach(URL.revokeObjectURL);return nextFav})}).catch(()=>{});return()=>{cancelled=true;if(u1)URL.revokeObjectURL(u1);if(u2)URL.revokeObjectURL(u2);Object.values(nextFav).forEach(URL.revokeObjectURL)}},[bitmap,layout]);
 const base=safeBaseName(file?.name||'icon');
 async function load(next:File){setError('');setResults(null);try{const b=await decodeImage(next);bitmap?.close();if(src)URL.revokeObjectURL(src);const u=URL.createObjectURL(next);setBitmap(b);setSrc(u);setFile(next);setMessage(`${next.name} · ${b.width}×${b.height}`)}catch(e){const code=e instanceof Error?e.message:'';const msg=code==='FILE_TOO_LARGE'?`20MB ${locale==='ko'?'이하 파일을 선택하세요.':locale==='ja'?'以下のファイルを選択してください。':'maximum file size exceeded.'}`:code==='PIXELS_TOO_LARGE'?`40MP ${locale==='ko'?'이하 이미지를 선택하세요.':locale==='ja'?'以下の画像を選択してください。':'maximum pixel count exceeded.'}`:code==='ANIMATED_UNSUPPORTED'?(locale==='ko'?'애니메이션 이미지는 지원하지 않습니다. 정적 PNG·JPG·WebP를 사용하세요.':locale==='ja'?'アニメーション画像には対応していません。静止画PNG・JPG・WebPを使用してください。':'Animated images are not supported. Use a static PNG, JPG, or WebP.'):code==='MIME_MISMATCH'?(locale==='ko'?'파일 형식과 실제 이미지 내용이 일치하지 않습니다.':locale==='ja'?'ファイル形式と実際の画像内容が一致しません。':'File type and image content do not match.'):t.error;setError(msg)}}
 function reset(all=true){if(all){bitmap?.close();if(src)URL.revokeObjectURL(src);setBitmap(null);setSrc('');setFile(null);setPlatform('android');setShowSafeZone(true);setDrag(false);if(inputRef.current)inputRef.current.value=''}setLayout({fit:'contain',scale:1,x:0,y:0,background:'#ffffff',transparent:true});setResults(null);setError('');setMessage(t.ready)}
 async function generate(){if(!bitmap||!file)return;setBusy(true);setError('');setMessage(t.generating);try{const files:{path:string;blob:Blob}[]=[];
  const play=await renderSquare(bitmap,512,{...layout,transparent:false});files.push({path:'android/playstore-icon-512.png',blob:play});
  for(const s of ANDROID_SIZES)files.push({path:`android/mipmap-${s===48?'mdpi':s===72?'hdpi':s===96?'xhdpi':s===144?'xxhdpi':'xxxhdpi'}/ic_launcher.png`,blob:await renderSquare(bitmap,s,{...layout,transparent:false})});
  files.push({path:'android/adaptive/foreground-432.png',blob:await renderSquare(bitmap,432,{...layout,transparent:true})});files.push({path:'android/adaptive/background-color.txt',blob:new Blob([layout.background],{type:'text/plain'})});
  for(const s of PWA_SIZES){files.push({path:`pwa/pwa-${s}x${s}.png`,blob:await renderSquare(bitmap,s,layout)});files.push({path:`pwa/pwa-maskable-${s}x${s}.png`,blob:await renderSquare(bitmap,s,{...layout,transparent:false},true)})}
  const favFrames=[] as {size:number;blob:Blob}[];for(const s of FAVICON_SIZES){const b=await renderSquare(bitmap,s,layout);favFrames.push({size:s,blob:b});files.push({path:`favicon/favicon-${s}x${s}.png`,blob:b})}files.push({path:'favicon/favicon.ico',blob:await makeIco(favFrames)});files.push({path:'favicon/apple-touch-icon-180x180.png',blob:await renderSquare(bitmap,180,layout)});
  const usage=`FIXLGS TOOLBOX 023
Source: ${file.name}

Android
- android/playstore-icon-512.png: Google Play listing icon
- android/mipmap-*/ic_launcher.png: legacy launcher density files
- android/adaptive/foreground-432.png + background-color.txt: adaptive source package

PWA
- pwa/pwa-192x192.png / pwa-512x512.png: regular icons
- pwa/pwa-maskable-192x192.png / pwa-maskable-512x512.png: maskable icons
Manifest example:
{ "icons": [
  { "src": "/pwa-192x192.png", "sizes": "192x192", "type": "image/png", "purpose": "any" },
  { "src": "/pwa-maskable-512x512.png", "sizes": "512x512", "type": "image/png", "purpose": "maskable" }
] }

Favicon
- favicon/favicon-16x16.png / 32x32 / 48x48
- favicon/favicon.ico: multi-frame 16/32/48 ICO
HTML example:
<link rel="icon" href="/favicon.ico" sizes="any">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">

Preview safe-zone guides, checkerboard, labels, and controls are not included in exported images.
`;files.push({path:'usage.txt',blob:new Blob([usage],{type:'text/plain'})});setResults({files,playBytes:play.size});setMessage(t.done)}catch{setError(t.error)}finally{setBusy(false)}}
 const byPrefix=(prefix:string)=>results?.files.filter(f=>f.path.startsWith(prefix))||[];async function dlZip(prefix:string,name:string){const list=prefix?byPrefix(prefix):results?.files||[];if(!list.length)return;downloadBlob(await makeZip(list),`${base}-${name}.zip`)}
 function dlFile(path:string,blob:Blob){downloadBlob(blob,path.split('/').pop()||'icon.png')}
 const previewStyle=useMemo(()=>({}),[]);
 return <div className={styles.root} data-testid="tool023-root">
  {!file&&<section className={`toolbox-workbench ${styles.workspaceCard}`} data-testid="tool023-start-card"><div className={`toolbox-workbench-upload ${drag?'is-dragging':''}`} role="button" tabIndex={0} data-testid="tool023-dropzone" onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();inputRef.current?.click()}}} onDragEnter={e=>{e.preventDefault();setDrag(true)}} onDragOver={e=>{e.preventDefault();e.dataTransfer.dropEffect='copy';setDrag(true)}} onDragLeave={e=>{if(!e.currentTarget.contains(e.relatedTarget as Node|null))setDrag(false)}} onDrop={e=>{e.preventDefault();setDrag(false);const f=e.dataTransfer.files?.[0];if(f)void load(f)}}><div className="toolbox-workbench-topline"><div><span>WORKSPACE</span><strong>{locale==='ko'?'앱 아이콘·파비콘 작업장':locale==='ja'?'アプリアイコン・ファビコン作業エリア':'App icon & favicon workspace'}</strong></div></div><div className={`toolbox-upload-focus ${styles.workspaceDropFocus}`}><span className="toolbox-upload-icon" aria-hidden="true">＋</span><h2>{t.choose}</h2><p>{t.dropHint}</p><button type="button" className={styles.workspaceUploadButton} onClick={e=>{e.stopPropagation();inputRef.current?.click()}}>{t.choose}</button><small>{t.hint}</small></div>{error&&<div className="toolbox-workbench-notice"><strong>{locale==='ko'?'안내':locale==='ja'?'案内':'Notice'}</strong><span className={styles.error} role="alert">{error}</span></div>}<input data-testid="tool023-file-input" ref={inputRef} hidden type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>{const f=e.target.files?.[0];if(f)void load(f);e.currentTarget.value=''}}/></div></section>}
  {file&&<><div className={`${styles.replaceDrop} ${drag?styles.drag:''}`} role="button" tabIndex={0} data-testid="tool023-workspace-dropzone" onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();inputRef.current?.click()}}} onClick={()=>inputRef.current?.click()} onDragOver={e=>{e.preventDefault();setDrag(true)}} onDragLeave={()=>setDrag(false)} onDrop={e=>{e.preventDefault();setDrag(false);const f=e.dataTransfer.files[0];if(f)void load(f)}}><strong>{t.newImage}</strong><span>{t.dropHint}</span><small>{t.hint}</small></div><div className={styles.workspace}><section className={styles.card}><div className={styles.previewBox}><img data-testid="tool023-preview" className={styles.master} src={previewUrl||src} alt="" style={previewStyle}/></div><div className={styles.resultMeta}><div><span>SOURCE</span><strong>{bitmap?.width}×{bitmap?.height}</strong></div><div><span>LIMIT</span><strong>{Math.round(TOOL023_MAX_BYTES/1024/1024)}MB / {Math.round(TOOL023_MAX_PIXELS/1_000_000)}MP</strong></div><div><span>MODE</span><strong>{layout.fit.toUpperCase()}</strong></div></div></section>
  <aside className={`${styles.card} ${styles.settings}`}><div className={styles.group}><h3>{t.fit}</h3><div className={styles.seg}><button className={layout.fit==='contain'?styles.active:''} onClick={()=>setLayout(v=>({...v,fit:'contain'}))}>{t.contain}</button><button className={layout.fit==='cover'?styles.active:''} onClick={()=>setLayout(v=>({...v,fit:'cover'}))}>{t.cover}</button></div></div><div className={styles.group}><label className={styles.label}>{t.bg}<span className={styles.colorLine}><input type="color" value={layout.background} onChange={e=>setLayout(v=>({...v,background:e.target.value}))}/><input value={layout.background} onChange={e=>setLayout(v=>({...v,background:e.target.value}))}/></span></label><label className={styles.check}><input type="checkbox" checked={layout.transparent} onChange={e=>setLayout(v=>({...v,transparent:e.target.checked}))}/>{t.transparent}</label></div><div className={styles.group}><label className={styles.label}>{t.zoom} · {layout.scale.toFixed(2)}<input aria-label={t.zoom} type="range" min="0.5" max="2" step="0.01" value={layout.scale} onChange={e=>setLayout(v=>({...v,scale:+e.target.value}))}/></label><label className={styles.label}>{t.x}<input aria-label={t.x} type="range" min="-0.4" max="0.4" step="0.01" value={layout.x} onChange={e=>setLayout(v=>({...v,x:+e.target.value}))}/></label><label className={styles.label}>{t.y}<input aria-label={t.y} type="range" min="-0.4" max="0.4" step="0.01" value={layout.y} onChange={e=>setLayout(v=>({...v,y:+e.target.value}))}/></label></div><div className={styles.actions}><button className={styles.button} onClick={()=>{inputRef.current?.click()}}>{t.newImage}</button><button data-testid="tool023-reset-settings" className={styles.button} onClick={()=>reset(false)}>{t.reset}</button><button data-testid="tool023-reset-all" className={styles.button} onClick={()=>reset(true)}>{t.resetAll}</button></div><input data-testid="tool023-file-input-loaded" ref={inputRef} hidden type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>{const f=e.target.files?.[0];if(f)void load(f);e.currentTarget.value=''}}/></aside></div>
  <section className={styles.card}><div className={styles.tabs} role="tablist"><button className={platform==='android'?styles.active:''} onClick={()=>setPlatform('android')}>{t.android}</button><button className={platform==='pwa'?styles.active:''} onClick={()=>setPlatform('pwa')}>{t.pwa}</button><button className={platform==='favicon'?styles.active:''} onClick={()=>setPlatform('favicon')}>{t.favicon}</button></div>
   <div className={styles.platform}>{platform==='android'&&<><div className={styles.platformHead}><div><h3>{t.adaptive}</h3><p>108dp / 66dp {t.safe}</p></div><label className={styles.safeToggle}><input data-testid="tool023-safe-toggle" type="checkbox" checked={showSafeZone} onChange={e=>setShowSafeZone(e.target.checked)}/>{t.safeToggle}</label></div><div className={styles.maskGrid}>{[['circle',styles.circle],['squircle',styles.squircle],['rounded',styles.rounded],['square',styles.square]].map(([name,shape])=><div className={styles.maskCard} key={name}><div className={`${styles.previewFrame} ${styles.maskVisual} ${shape} ${showSafeZone?styles.safeAndroid:''}`}><img src={previewUrl||src} alt="" style={previewStyle}/></div><span>{name} · 512×512 preview</span></div>)}</div>{showSafeZone&&<div className={styles.warn}>{t.safeWarn}</div>}</>}
   {platform==='pwa'&&<><div className={styles.platformHead}><div><h3>{t.pwa}</h3><p>192×192 · 512×512</p></div></div><div className={styles.pwaGrid}><div className={styles.pwaCard}><strong>{t.regular}</strong><div className={`${styles.previewFrame} ${styles.pwaVisual}`}><img src={previewUrl||src} alt="" style={previewStyle}/></div><span>192×192 · 512×512</span></div><div className={styles.pwaCard}><strong>{t.maskable}</strong><div className={`${styles.previewFrame} ${styles.pwaVisual}`}><img src={maskableUrl||previewUrl||src} alt="" style={previewStyle}/></div><span>192×192 · 512×512</span></div></div></>}
   {platform==='favicon'&&<><div className={styles.platformHead}><div><h3>{t.small}</h3><p>{t.ico}</p></div></div><div className={styles.favGrid}>{FAVICON_SIZES.map(s=><div className={styles.favCard} key={s}><div className={`${styles.previewFrame} ${styles.actual}`}><img className={styles.faviconPreviewImage} src={previewUrl||src} alt=""/></div><strong>{t.zoomPreview}</strong><span>{s}×{s} {locale==='ko'?'실제 출력':locale==='ja'?'実出力':'actual output'}</span></div>)}</div></>}</div>
  </section>
  <section className={styles.card}><div className={styles.actions}><button data-testid="tool023-generate" className={styles.primary} disabled={busy} onClick={()=>void generate()}>{t.generate}</button>{results&&<><button className={styles.primary} onClick={()=>void dlZip('','all-icons')}>{t.downloadAll}</button><button className={styles.button} onClick={()=>void dlZip('android/','android-icons')}>{t.androidZip}</button><button className={styles.button} onClick={()=>void dlZip('pwa/','pwa-icons')}>{t.pwaZip}</button><button className={styles.button} onClick={()=>void dlZip('favicon/','favicon')}>{t.faviconZip}</button></>}</div><div data-testid="tool023-status" className={styles.status} aria-live="polite">{message}</div>{results&&<div className={styles.fileList} data-testid="tool023-file-list">{results.files.filter(f=>f.path!=='usage.txt'&&!f.path.endsWith('.txt')).map(f=><div className={styles.fileRow} data-file-path={f.path} key={f.path}><span>{f.path}</span><button className={styles.button} onClick={()=>dlFile(f.path,f.blob)}>{t.download}</button></div>)}</div>}{results&&results.playBytes>1024*1024&&<div className={styles.warn}>{t.playWarn}</div>}{error&&<div className={styles.error} role="alert">{error}</div>}</section></>}
 </div>
}
