import { ToolNavigation } from "@/components/tool-navigation";
import { Fragment } from 'react';
import Link from 'next/link';
import { ToolboxSubpageShell } from '@/components/toolbox-subpage-shell';
import { ToolboxFaqList } from '@/components/toolbox-faq-list';
import { BlogOpenGraphImageMakerTool } from '@/components/blog-open-graph-image-maker-tool';
import pageStyles from './blog-open-graph-image-maker-page.module.css';
import type { Locale } from '@/lib/site';

const copy={
ko:{back:'콘텐츠 이미지 제작',title:'블로그·오픈그래프 이미지 제작기',desc:'네이버 블로그·Google 블로그·웹사이트·Open Graph 용 대표 이미지를 한 번에 만들어 다운로드하세요.',local:'이미지·제목·설명·로고는 서버로 전송되지 않으며 현재 브라우저에서만 처리됩니다.',how:'사용 방법',steps:['배경 이미지를 선택하거나 빈 디자인을 시작합니다.','제목·설명·로고를 넣어 공통 대표 이미지를 만듭니다.','네이버 블로그·Google/Blogger·웹사이트·Open Graph 결과를 한눈에 확인하고 필요한 규격만 위치를 조정합니다.','원하는 이미지를 개별 다운로드하거나\nZIP으로 한 번에 저장합니다.'],faq:'자주 묻는 질문',more:'FAQ 더보기',collapse:'FAQ 접기',faqs:[['Open Graph 이미지는 왜 1200×630인가요?','프로젝트에서 확정한 핵심 기본 규격이며 링크 공유용 고해상도 대표 이미지에 널리 쓰이는 권장 크기입니다.'],['네이버 블로그 대표 이미지 공식 크기는 얼마인가요?','노출 위치에 따라 표시 방식이 달라질 수 있어 하나의 고정 픽셀값을 공식 필수 규격처럼 표시하지 않습니다. TOOLBOX 권장 preset을 제공합니다.'],['Google 블로그 이미지는 1200×630이 공식 규격인가요?','아닙니다. Blogger의 단일 고정 대표 이미지 규격으로 표현하지 않습니다. TOOLBOX는 1200px 이상 폭과 16:9 활용을 참고한 권장 preset을 제공합니다.'],['이미지가 서버로 올라가나요?','아니요. 지원되는 작업은 현재 브라우저 안에서 처리합니다.'],['OG 메타태그 코드도 만들어 주나요?','아닙니다. 이 도구는 이미지 파일 제작용이며 Open Graph 태그 코드는 별도 도구의 역할입니다.'],['여러 규격을 한 번에 받을 수 있나요?','예. 선택한 결과를 ZIP으로 저장하거나 개별 다운로드할 수 있습니다.']]},
en:{back:'Content Image Creation',title:'Blog & Open Graph Image Maker',desc:'Create featured images for Naver Blog, Google/Blogger, websites and Open Graph in one design, then download each size or a ZIP.',local:'Images, titles, descriptions and logos are processed only in this browser.',how:'How to use',steps:['Choose a background image or start with a blank design.','Add a title, description and logo to the common design.','Review Naver Blog, Google/Blogger, website and Open Graph sizes, then fine-tune only the sizes that need different crops or positions.','Download one image or save selected results as a ZIP.'],faq:'Frequently asked questions',more:'Show more FAQs',collapse:'Show fewer FAQs',faqs:[['Why is the Open Graph preset 1200×630?','It is the project-fixed core preset and a common high-resolution recommendation for link-sharing images.'],['What is the official Naver Blog featured-image size?','Display behavior varies by placement, so this tool does not present one fixed pixel size as a mandatory official rule.'],['Is 1200×630 the official Blogger image size?','No. Blogger is not presented as having one fixed featured-image size. TOOLBOX provides a recommendation informed by large-image guidance.'],['Are my images uploaded?','No. Supported editing and export happen in your current browser.'],['Does this generate OG meta tags?','No. This tool creates image files only; Open Graph tag code belongs to a separate tool.'],['Can I download several sizes together?','Yes. Download individual images or package selected results as ZIP.']]},
ja:{back:'コンテンツ画像作成',title:'ブログ・OG 画像作成ツール',desc:'NAVERブログ・Googleブログ・Webサイト・Open Graph用の代表画像を1つのデザインから作成し、サイズ別に保存できます。',local:'画像・タイトル・説明・ロゴはサーバーへ送信されず、このブラウザ内で処理されます。',how:'使い方',steps:['背景画像を選択するか、空のデザインから開始します。','タイトル・説明・ロゴを追加して共通デザインを作成します。','NAVERブログ・Google/Blogger・Webサイト・Open Graphの結果を確認し、必要なサイズだけ位置や切り抜きを調整します。','必要な画像を個別に保存するか、選択した結果をZIPでまとめて保存します。'],faq:'よくある質問',more:'FAQをもっと見る',collapse:'FAQを閉じる',faqs:[['Open Graph画像が1200×630なのはなぜですか？','プロジェクトで確定した主要プリセットで、リンク共有用の高解像度画像として広く使われる推奨サイズです。'],['NAVERブログの公式代表画像サイズは？','表示場所によって見え方が変わるため、単一の固定ピクセル値を公式必須サイズとして表示しません。'],['Googleブログは1200×630が公式ですか？','いいえ。Bloggerに単一の固定代表画像サイズがあるとは表示せず、大きな代表画像のガイドを参考にしたTOOLBOX推奨プリセットを提供します。'],['画像はサーバーにアップロードされますか？','いいえ。対応する編集と出力は現在のブラウザ内で処理します。'],['OGメタタグも作成しますか？','いいえ。このツールは画像ファイル作成専用です。'],['複数サイズをまとめて保存できますか？','はい。個別保存と選択結果のZIP保存に対応しています。']]}} as const;

export function BlogOpenGraphImageMakerPage({locale}:{locale:Locale}){
  const t=copy[locale];
  const url=`https://toolbox.fixlgs.com/${locale}/blog-open-graph-image-maker`;
  const ready=locale==='ko'?'사용 가능':locale==='en'?'AVAILABLE':'利用可能';
  const coming=locale==='ko'?'준비 중':locale==='en'?'PLANNED':'準備中';
  const next=locale==='ko'?'다음 작업':locale==='en'?'Next tool':'次のツール';
  const relatedTitle=locale==='ko'?'관련 도구':locale==='en'?'Related tools':'関連ツール';
  const titleLines=locale==='ko'?['블로그·오픈그래프','이미지 제작기']:[t.title];
  const related=[
    {n:'016',name:locale==='ko'?'이미지에 글자 넣기':locale==='en'?'Add Text to Image':'画像文字入れツール',href:`/${locale}/add-text-to-image`},
    {n:'017',name:locale==='ko'?'이미지 워터마크 넣기':locale==='en'?'Image Watermark Tool':'画像透かしツール',href:`/${locale}/image-watermark`},
    {n:'018',name:locale==='ko'?'이미지 정보·메타데이터 검사기':locale==='en'?'Image Metadata Checker':'画像情報・メタデータ確認',href:`/${locale}/image-metadata-checker`},
  ];
  const useCases=locale==='ko'?
    [['블로그 글 대표 이미지','네이버 블로그와 Blogger에 같은 콘텐츠를 올릴 때 한 번 만든 디자인을 규격별 결과로 재사용합니다.'],['회사 뉴스·공지 대표 이미지','회사 소식, 업데이트, 공지 글에 사용할 대표 이미지를 웹과 블로그 용도로 함께 만듭니다.'],['웹사이트 카드·공유 이미지','웹사이트 대표 카드와 Open Graph 공유 이미지가 같은 디자인 흐름을 유지하도록 만듭니다.'],['동시 운영 콘텐츠','네이버 블로그·Blogger·웹사이트를 함께 운영할 때 매번 이미지를 다시 만드는 반복 작업을 줄입니다.']]:
    locale==='en'?
    [['Blog featured images','Reuse one design across Naver Blog and Blogger instead of recreating the same content image.'],['Company news and notices','Create a consistent featured image for company updates, announcements, and web posts.'],['Website cards and link sharing','Keep website featured cards and Open Graph share images visually aligned.'],['Multi-channel publishing','Reduce repeated design work when publishing the same content to blogs and a website.']]:
    [['ブログ記事の代表画像','NAVERブログとBloggerで同じ内容を公開するとき、1つのデザインをサイズ別に再利用します。'],['会社ニュース・お知らせ','会社のお知らせや更新情報の代表画像をWebとブログ向けにまとめて作成します。'],['Webカード・共有画像','Webサイトの代表カードとOpen Graph共有画像のデザインを統一します。'],['複数チャネル運用','NAVERブログ・Blogger・Webサイトへ同じ内容を公開するときの作り直しを減らします。']];
  const cautions=locale==='ko'?
    ['네이버 블로그와 Blogger는 하나의 고정 대표 이미지 픽셀 규격을 공식 필수값처럼 표시하지 않습니다.','Open Graph 1200×630은 핵심 기본 preset이지만 실제 소비 서비스에서 추가 crop·압축될 수 있습니다.','Google Discover 노출은 이미지 규격만으로 보장되지 않습니다.','Google Discover의 1200px 이상 폭·16:9 가이드는 Blogger 자체의 고정 업로드 규격이 아닙니다.','타인의 이미지·로고 사용 권리는 사용자가 확인해야 합니다.']:
    locale==='en'?
    ['Naver Blog and Blogger do not have one mandatory featured-image pixel size presented by this tool.','Open Graph 1200×630 is the core preset, but consuming services may still crop or compress it.','Image dimensions alone do not guarantee Google Discover visibility.','The 1200px-wide 16:9 guidance for Discover is not a fixed Blogger upload specification.','You are responsible for rights to images and logos you use.']:
    ['NAVERブログとBloggerについて、単一の固定ピクセル値を公式必須サイズとして表示しません。','Open Graph 1200×630は主要プリセットですが、利用サービス側で追加の切り抜きや圧縮が行われる場合があります。','画像サイズだけでGoogle Discoverへの表示が保証されるわけではありません。','Discoverの幅1200px以上・16:9のガイドはBlogger固有の固定アップロード規格ではありません。','使用する画像やロゴの権利は利用者が確認してください。'];
  const expertText=locale==='ko'?
    [['한 디자인을 여러 규격에 재사용하는 기준','공통 디자인 상태에는 배경, 제목·설명 내용, 기본 색상과 로고를 두고, 규격마다 달라져야 하는 crop·위치·크기만 override로 관리하면 반복 수정이 줄어듭니다.'],['비율 차이는 늘리기가 아니라 crop으로 해결','1.91:1과 16:9처럼 비율이 다른 결과를 단순 stretch하면 인물과 로고가 찌그러질 수 있습니다. 원본 비율을 유지한 cover crop과 위치 조정으로 차이를 흡수하는 편이 안정적입니다.'],['미리보기와 실제 출력의 좌표를 하나로 유지','화면용 CSS 미리보기와 Canvas 출력이 서로 다른 계산을 사용하면 제목·로고 위치가 저장 결과에서 달라질 수 있습니다. 같은 layout model을 축소해 보여주고 실제 출력에서도 그대로 사용해야 합니다.'],['공식값과 권장값을 분리해 표시','Open Graph 1200×630처럼 프로젝트 핵심 preset과 Naver/Blogger용 TOOLBOX 권장 preset을 같은 의미로 표시하지 않으면 사용자가 플랫폼 요구사항을 오해하는 일을 줄일 수 있습니다.'],['모바일에서는 현재 규격 편집에 집중','작은 화면에서 모든 규격과 설정을 동시에 펼치면 작업이 길어집니다. 현재 preset preview를 먼저 보여주고 필요한 설정을 한 열로 정리하면 crop과 텍스트 위치 조정이 쉬워집니다.']]:
    locale==='en'?
    [['Reuse one design with per-size overrides','Keep background, copy, base colors, and logo in common state, then store only crop, position, and size differences as per-preset overrides.'],['Resolve ratio differences with crop, not stretch','Stretching between 1.91:1 and 16:9 can distort people, logos, and text. Preserve source ratio and use cover crop plus position adjustments.'],['Share one layout model between preview and export','If CSS preview and Canvas export use different calculations, text and logos can shift in the downloaded image. Scale one layout model for preview and export from the same coordinates.'],['Separate official and recommended values','Distinguish the project-fixed Open Graph preset from TOOLBOX recommendations for Naver and Blogger so users do not mistake recommendations for mandatory platform rules.'],['Keep mobile editing focused on the active size','On small screens, show the active preset preview first and stack settings in one column so crop and text adjustments remain manageable.']]:
    [['1つのデザインをサイズ別上書きで再利用','背景、文字内容、基本色、ロゴは共通状態にし、切り抜き・位置・サイズなど必要な差分だけを各プリセットの上書きとして保存します。'],['比率の違いは引き伸ばしではなく切り抜きで対応','1.91:1と16:9の間で単純に引き伸ばすと人物やロゴが変形します。元画像の比率を保ち、cover切り抜きと位置調整で合わせます。'],['プレビューと出力で同じレイアウトモデルを使用','CSSプレビューとCanvas出力で別の計算を使うと、保存画像で文字やロゴの位置がずれることがあります。同じ座標モデルを縮小表示して出力にも使います。'],['公式値と推奨値を分けて表示','Open Graphの主要プリセットとNAVER・Blogger向けTOOLBOX推奨値を区別し、推奨値を必須仕様と誤解しないようにします。'],['モバイルでは現在のサイズ編集に集中','小さい画面では現在のプリセットを優先して表示し、設定を1列にまとめると切り抜きや文字位置を調整しやすくなります。']];
  const jsonLd={'@context':'https://schema.org','@graph':[{'@type':'WebApplication',name:t.title,applicationCategory:'MultimediaApplication',operatingSystem:'Any',url,description:t.desc,offers:{'@type':'Offer',price:'0',priceCurrency:'USD'}},{'@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'TOOLBOX',item:`https://toolbox.fixlgs.com/${locale}`},{'@type':'ListItem',position:2,name:t.back,item:`https://toolbox.fixlgs.com/${locale}/category/content-image`},{'@type':'ListItem',position:3,name:t.title,item:url}]},{'@type':'FAQPage',mainEntity:t.faqs.map(([q,a])=>({'@type':'Question',name:q,acceptedAnswer:{'@type':'Answer',text:a}}))}]};
  return <ToolboxSubpageShell locale={locale} appName={t.title}>
    <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(jsonLd)}}/>
    <section className="toolbox-tool-detail-hero tool022-detail-hero">
      <Link className="toolbox-subpage-back" href={`/${locale}/category/content-image`}>← {t.back}</Link>
      <p className="toolbox-subpage-eyebrow">022 · CONTENT IMAGE</p>
      <div className="toolbox-tool-detail-heading"><h1>{titleLines.map(line=><span className="toolbox-tool-title-line" key={line}>{line}</span>)}</h1><p>{t.desc}</p></div>
      <div className="toolbox-tool-detail-badge"><strong>LOCAL</strong><span>{locale==='ko'?'브라우저에서 바로 처리':locale==='en'?'PROCESS IN YOUR BROWSER':'ブラウザ内で処理'}</span></div>
    </section>

    <section className="toolbox-tool-detail-body"><div>
      <BlogOpenGraphImageMakerTool locale={locale}/>
      <ToolNavigation locale={locale} currentTool={22} />
      
    </div></section>

    <section className="toolbox-tool-guide toolbox-tool-guide--five"><div className="toolbox-tool-guide-head"><p>HOW TO USE</p><h2>{t.how}</h2></div><ol>{t.steps.map((s,i)=><li key={s}><span>{String(i+1).padStart(2,'0')}</span><p>{s.split('\n').map((line,j)=><Fragment key={j}>{line}{j<s.split('\n').length-1?<br/>:null}</Fragment>)}</p></li>)}</ol></section>

    <section className="toolbox-tool-format-guide tool022-format-guide"><div className="toolbox-tool-format-guide-head"><p>FORMAT GUIDE</p><h2>{locale==='ko'?'대표 이미지 규격을 사용할 때 알아둘 점':locale==='en'?'What to know about featured-image sizes':'代表画像サイズについて知っておくこと'}</h2><span>{locale==='ko'?'공식값과 TOOLBOX 권장값을 구분하고, 실제 서비스에서 추가 crop·압축될 수 있다는 점까지 함께 확인합니다.':locale==='en'?'Separate official or project-fixed values from TOOLBOX recommendations and account for downstream cropping or compression.':'公式値・プロジェクト固定値とTOOLBOX推奨値を区別し、利用サービス側の切り抜きや圧縮も考慮します。'}</span></div><div className="toolbox-tool-result-grid"><article><span>01</span><div><h4>Open Graph</h4><p>1200×630 · 1.91:1</p></div></article><article><span>02</span><div><h4>Google / Blogger</h4><p>1200×675 · 16:9 · TOOLBOX recommendation</p></div></article><article><span>03</span><div><h4>Naver Blog</h4><p>1200×675 · 16:9 · TOOLBOX recommendation</p></div></article></div></section>

    <section className="toolbox-tool-format-guide toolbox-tool-expert-post tool022-use-cases"><div className="toolbox-tool-format-guide-head"><p>USE CASES</p><h2>{locale==='ko'?'이럴 때 활용하세요':locale==='en'?'Useful publishing scenarios':'こんな場面で活用できます'}</h2></div><div className="toolbox-tool-result-grid">{useCases.map(([title,description],index)=><article key={title}><span>{String(index+1).padStart(2,'0')}</span><div><h4>{title}</h4><p>{description}</p></div></article>)}</div></section>

    <section className="toolbox-tool-format-guide toolbox-tool-expert-post toolbox-tool-expert-post--wide-head tool022-expert-post"><div className="toolbox-tool-format-guide-head"><p>EXPERT POST</p><h2>{locale==='ko'?'블로그·웹 대표 이미지를 안정적으로 재사용하는 실전 기준':locale==='en'?'Practical criteria for reusable blog and web featured images':'ブログ・Web代表画像を安定して再利用する実践基準'}</h2><span>{locale==='ko'?'규격별 잘림, 텍스트 위치, 로고와 출력 결과 차이를 줄이는 핵심 기준입니다.':locale==='en'?'Reduce crop failures and differences in text, logo, and exported placement across sizes.':'サイズごとの切り抜き、文字位置、ロゴ、出力結果の差を減らすための基準です。'}</span></div><div className="toolbox-tool-format-body"><div className="toolbox-tool-direction-grid toolbox-tool-practical-grid">{expertText.map(([title,description])=><article key={title}><h4>{title}</h4><p>{description}</p></article>)}</div></div></section>

    <section className="toolbox-tool-info-band toolbox-tool-info-band--section-start toolbox-tool-info-band--bottom-gap"><div className="toolbox-tool-info-band-head"><p>IMPORTANT NOTES</p><h2>{locale==='ko'?'주의사항':locale==='en'?'Important notes':'注意事項'}</h2><span>{locale==='ko'?'플랫폼별 권장값과 실제 표시 차이를 구분해 대표 이미지가 예상과 다르게 잘리거나 압축되는 일을 줄이세요.':locale==='en'?'Separate recommendations from actual platform display behavior to reduce unexpected cropping or compression.':'推奨値と実際の表示差を区別し、代表画像の予期しない切り抜きや圧縮を減らします。'}</span></div><ul className="toolbox-tool-info-band-list">{cautions.map(item=><li key={item}>{item}</li>)}</ul></section>

    <section className="toolbox-tool-faq"><div className="toolbox-tool-guide-head"><p>FAQ</p><h2>{t.faq}</h2></div><ToolboxFaqList items={t.faqs} initialCount={5} moreLabel={t.more} collapseLabel={t.collapse} className="toolbox-tool-faq-list"/></section>
    <section className="toolbox-tool-processing-note"><p>{t.local}</p></section>
  </ToolboxSubpageShell>;
}
