'use client';

import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { StableMobileImageFileInput } from "@/components/stable-mobile-image-file-input";
import type { Locale } from '@/lib/site';
import { createStoredZip } from '@/lib/zip';
import { TOOL022_LIMITS, TOOL022_PRESETS, type Tool022PresetId } from '@/lib/tool-022-blog-og';
import styles from './blog-open-graph-image-maker.module.css';

type Format='jpg'|'png';
type Align='left'|'center'|'right';
type Common={title:string;description:string;backgroundColor:string;overlay:number;titleColor:string;descriptionColor:string;titleSize:number;descriptionSize:number;titleX:number;titleY:number;descriptionX:number;descriptionY:number;align:Align;logoX:number;logoY:number;logoScale:number;logoOpacity:number;cropX:number;cropY:number;zoom:number};
type Override=Partial<Pick<Common,'titleSize'|'descriptionSize'|'titleX'|'titleY'|'descriptionX'|'descriptionY'|'logoX'|'logoY'|'logoScale'|'cropX'|'cropY'|'zoom'>>;
type Result={id:Tool022PresetId;blob:Blob;name:string;width:number;height:number};

const initial:Common={title:'BLOG TITLE',description:'A clear featured image for your blog and website.',backgroundColor:'#1769d2',overlay:18,titleColor:'#ffffff',descriptionColor:'#ffffff',titleSize:66,descriptionSize:30,titleX:.08,titleY:.54,descriptionX:.08,descriptionY:.71,align:'left',logoX:.82,logoY:.12,logoScale:.14,logoOpacity:100,cropX:0,cropY:0,zoom:1};
const cp={
 ko:{workspace:'블로그·OG 이미지 작업장',choose:'배경 이미지 선택',blank:'빈 디자인 시작',support:'JPG, PNG, WebP · 브라우저 로컬 처리',scopeAll:'모든 규격에 적용',scopeOne:'이 규격만 조정',scopeNow:'현재 편집 범위',preview:'규격 미리보기',background:'배경',position:'배경 위치',zoom:'확대·축소',overlay:'배경 오버레이',title:'제목',description:'설명',logo:'로고',chooseLogo:'로고 선택',removeLogo:'로고 제거',size:'크기',opacity:'투명도',alignment:'정렬',left:'왼쪽',center:'가운데',right:'오른쪽',resetOne:'이 규격 초기화',format:'파일 형식',quality:'이미지 품질',download:'개별 다운로드',zip:'선택 결과 ZIP 다운로드',continue:'계속 편집',newImage:'새 이미지',resetAll:'전체 초기화',guide:'가독성 여백 가이드',select:'출력 선택',official:'공식 권장',toolbox:'TOOLBOX 권장',fixed:'프로젝트 기본',result:'생성 결과',ogPreview:'Open Graph 카드 미리보기',local:'이미지·제목·설명·로고는 서버로 전송되지 않습니다.',tooLarge:'배경 파일은 20MB 이하를 권장 서비스 한도로 사용합니다.',tooPixels:'이미지 해상도가 서비스 권장 한도 40MP를 초과합니다.',bad:'지원되지 않거나 손상된 이미지입니다.',none:'출력할 규격을 하나 이상 선택하세요.',done:'결과 이미지가 생성되었습니다.',zipDone:'선택한 결과를 ZIP으로 만들었습니다.',logoBad:'지원되지 않거나 손상된 로고입니다.',ogWarn:'Open Graph 결과가 8MB를 초과해 링크 공유 권장 범위를 넘을 수 있습니다.',drag:'미리보기를 드래그하면 현재 규격의 배경 위치를 조정합니다.'},
 en:{workspace:'Blog & OG image workspace',choose:'Choose Background Image',blank:'Start Blank',support:'JPG, PNG, WebP · processed locally',scopeAll:'Apply to All Sizes',scopeOne:'Adjust This Size Only',scopeNow:'Editing scope',preview:'Size Preview',background:'Background',position:'Background Position',zoom:'Zoom',overlay:'Background Overlay',title:'Title',description:'Description',logo:'Logo',chooseLogo:'Choose Logo',removeLogo:'Remove Logo',size:'Size',opacity:'Opacity',alignment:'Alignment',left:'Left',center:'Center',right:'Right',resetOne:'Reset This Size',format:'File Format',quality:'Image Quality',download:'Download',zip:'Download Selected as ZIP',continue:'Continue Editing',newImage:'New Image',resetAll:'Reset All',guide:'Readability margin guide',select:'Include in export',official:'Official Recommendation',toolbox:'TOOLBOX Recommendation',fixed:'Project default',result:'Generated results',ogPreview:'Open Graph card preview',local:'Images, text, logo and crop coordinates stay in this browser.',tooLarge:'The service limit for a background image is 20MB.',tooPixels:'The image exceeds the 40MP service limit.',bad:'This image is unsupported or damaged.',none:'Select at least one output size.',done:'Result images are ready.',zipDone:'Selected results were packaged as ZIP.',logoBad:'This logo is unsupported or damaged.',ogWarn:'The Open Graph result exceeds 8MB and may be outside link-sharing guidance.',drag:'Drag the preview to adjust background position for the current size.'},
 ja:{workspace:'ブログ・OG 画像作成ワークスペース',choose:'背景画像を選択',blank:'空のデザインから開始',support:'JPG・PNG・WebP · ブラウザ内処理',scopeAll:'すべてのサイズに適用',scopeOne:'このサイズのみ調整',scopeNow:'現在の編集範囲',preview:'サイズプレビュー',background:'背景',position:'背景位置',zoom:'拡大・縮小',overlay:'背景オーバーレイ',title:'タイトル',description:'説明',logo:'ロゴ',chooseLogo:'ロゴを選択',removeLogo:'ロゴを削除',size:'サイズ',opacity:'不透明度',alignment:'配置',left:'左',center:'中央',right:'右',resetOne:'このサイズをリセット',format:'ファイル形式',quality:'画質',download:'ダウンロード',zip:'選択した画像を ZIP でダウンロード',continue:'編集を続ける',newImage:'新しい画像',resetAll:'すべてリセット',guide:'読みやすさ余白ガイド',select:'出力対象',official:'公式推奨',toolbox:'TOOLBOX 推奨',fixed:'プロジェクト基本',result:'生成結果',ogPreview:'Open Graph カードプレビュー',local:'画像・文字・ロゴ・切り抜き位置はサーバーへ送信されません。',tooLarge:'背景画像のサービス上限は20MBです。',tooPixels:'画像が40MPのサービス上限を超えています。',bad:'未対応または破損した画像です。',none:'出力サイズを1つ以上選択してください。',done:'結果画像を生成しました。',zipDone:'選択した結果をZIPにまとめました。',logoBad:'未対応または破損したロゴです。',ogWarn:'Open Graph結果が8MBを超え、リンク共有の推奨範囲を超える可能性があります。',drag:'プレビューをドラッグすると現在サイズの背景位置を調整できます。'}
} as const;

function download(blob:Blob,name:string){const u=URL.createObjectURL(blob);const a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1200)}
async function decode(file:Blob){if(!/^image\/(jpeg|png|webp)$/i.test(file.type))throw new Error('type');if(typeof createImageBitmap==='function'){const b=await createImageBitmap(file,{imageOrientation:'from-image'});return {src:b as CanvasImageSource,w:b.width,h:b.height,close:()=>b.close()}}const u=URL.createObjectURL(file);try{const im=new Image();im.src=u;await im.decode();return {src:im as CanvasImageSource,w:im.naturalWidth,h:im.naturalHeight,close:()=>{}}}finally{URL.revokeObjectURL(u)}}
function fitCover(sw:number,sh:number,dw:number,dh:number,zoom:number,cx:number,cy:number){const s=Math.max(dw/sw,dh/sh)*zoom;const rw=sw*s,rh=sh*s;const maxX=Math.max(0,(rw-dw)/2),maxY=Math.max(0,(rh-dh)/2);return {x:(dw-rw)/2-cx*maxX,y:(dh-rh)/2-cy*maxY,w:rw,h:rh}}
function lines(ctx:CanvasRenderingContext2D,text:string,max:number){const out:string[]=[];for(const para of text.split(/\n/)){let cur='';const tokens=/\s/.test(para)?para.split(/(\s+)/):Array.from(para);for(const token of tokens){const next=cur+token;if(cur&&ctx.measureText(next).width>max){out.push(cur.trimEnd());cur=token.trimStart()}else cur=next}if(cur)out.push(cur);if(!para)out.push('')}return out.slice(0,6)}
function drawText(ctx:CanvasRenderingContext2D,text:string,x:number,y:number,size:number,color:string,align:Align,maxW:number,weight:number){ctx.save();ctx.fillStyle=color;ctx.font=`${weight} ${size}px Arial, "Noto Sans", sans-serif`;ctx.textAlign=align;ctx.textBaseline='top';const ls=lines(ctx,text,maxW);ls.forEach((l,i)=>ctx.fillText(l,x,y+i*size*1.18,maxW));ctx.restore()}

export function BlogOpenGraphImageMakerTool({locale}:{locale:Locale}){
 const t=cp[locale];const canvasRef=useRef<HTMLCanvasElement>(null);const bgRef=useRef<{src:CanvasImageSource;w:number;h:number;close:()=>void}|null>(null);const logoRef=useRef<{src:CanvasImageSource;w:number;h:number;close:()=>void}|null>(null);
 const [started,setStarted]=useState(false),[preset,setPreset]=useState<Tool022PresetId>('og'),[selected,setSelected]=useState<Set<Tool022PresetId>>(new Set(TOOL022_PRESETS.map(p=>p.id))),[common,setCommon]=useState<Common>(initial),[overrides,setOverrides]=useState<Partial<Record<Tool022PresetId,Override>>>({}),[one,setOne]=useState(false),[format,setFormat]=useState<Format>('jpg'),[quality,setQuality]=useState(90),[guide,setGuide]=useState(true),[bgName,setBgName]=useState('design'),[logoName,setLogoName]=useState(''),[status,setStatus]=useState(''),[error,setError]=useState(''),[results,setResults]=useState<Result[]>([]),[mobile,setMobile]=useState<'edit'|'preview'>('edit'),[dragActive,setDragActive]=useState(false),[bgRevision,setBgRevision]=useState(0);
 const currentPreset=TOOL022_PRESETS.find(p=>p.id===preset)!;const eff=useMemo(()=>({...common,...(overrides[preset]||{})}),[common,overrides,preset]);
 const setValue=<K extends keyof Common>(key:K,value:Common[K])=>{setResults([]);if(one&&(['cropX','cropY','zoom','titleSize','descriptionSize','titleX','titleY','descriptionX','descriptionY','logoX','logoY','logoScale'] as string[]).includes(String(key))){setOverrides(o=>({...o,[preset]:{...(o[preset]||{}),[key]:value}}))}else setCommon(c=>({...c,[key]:value}))};
 const render=useCallback((canvas:HTMLCanvasElement,p=currentPreset,scale=1)=>{const w=Math.max(1,Math.round(p.width*scale)),h=Math.max(1,Math.round(p.height*scale));canvas.width=w;canvas.height=h;const ctx=canvas.getContext('2d');if(!ctx)return;const s={...common,...(overrides[p.id]||{})};ctx.fillStyle=s.backgroundColor;ctx.fillRect(0,0,w,h);if(bgRef.current){const d=fitCover(bgRef.current.w,bgRef.current.h,w,h,s.zoom,s.cropX,s.cropY);ctx.drawImage(bgRef.current.src,d.x,d.y,d.w,d.h)}if(s.overlay>0){ctx.fillStyle=`rgba(0,0,0,${s.overlay/100})`;ctx.fillRect(0,0,w,h)}const pad=w*.08,max=w*.84;const ax=s.align==='left'?'left':s.align==='right'?'right':'center';const tx=s.titleX*w,dx=s.descriptionX*w;drawText(ctx,s.title,tx,s.titleY*h,s.titleSize*(w/p.width),s.titleColor,ax,max,800);drawText(ctx,s.description,dx,s.descriptionY*h,s.descriptionSize*(w/p.width),s.descriptionColor,ax,max,500);if(logoRef.current){const lw=w*s.logoScale,lh=lw*(logoRef.current.h/logoRef.current.w);ctx.save();ctx.globalAlpha=s.logoOpacity/100;ctx.drawImage(logoRef.current.src,s.logoX*w-lw/2,s.logoY*h-lh/2,lw,lh);ctx.restore()}},[common,overrides,currentPreset,bgRevision]);
 useEffect(()=>{const c=canvasRef.current;if(c)render(c,currentPreset,Math.min(1,760/currentPreset.width))},[render,currentPreset]);
 useEffect(()=>()=>{bgRef.current?.close();logoRef.current?.close()},[]);
 const chooseBg=async(file?:File)=>{if(!file)return;setError('');if(file.size>TOOL022_LIMITS.maxBackgroundBytes){setError(t.tooLarge);return}try{const d=await decode(file);if(d.w*d.h>TOOL022_LIMITS.maxPixels){d.close();setError(t.tooPixels);return}bgRef.current?.close();bgRef.current=d;setBgName(file.name.replace(/\.[^.]+$/,''));setCommon(c=>({...c,cropX:0,cropY:0,zoom:1}));setOverrides(o=>Object.fromEntries(Object.entries(o).map(([id,v])=>{if(!v)return [id,v];const {cropX:_cropX,cropY:_cropY,zoom:_zoom,...rest}=v;return [id,rest]})) as Partial<Record<Tool022PresetId,Override>>);setStarted(true);setResults([]);setStatus('');setBgRevision(v=>v+1)}catch{setError(t.bad)}};
 const chooseLogo=async(file?:File)=>{if(!file)return;setError('');try{const d=await decode(file);logoRef.current?.close();logoRef.current=d;setLogoName(file.name);setResults([])}catch{setError(t.logoBad)}};
 const exportOne=async(p=currentPreset)=>{const canvas=document.createElement('canvas');render(canvas,p,1);const mime=format==='png'?'image/png':'image/jpeg';const blob=await new Promise<Blob|null>(r=>canvas.toBlob(r,mime,format==='jpg'?quality/100:undefined));canvas.width=1;canvas.height=1;if(!blob)throw new Error('encode');const ext=format==='png'?'png':'jpg';return {id:p.id,blob,name:`${bgName||'design'}-${p.suffix}.${ext}`,width:p.width,height:p.height} as Result};
 const makeResults=async()=>{setError('');setStatus('');if(!selected.size){setError(t.none);return []}const out:Result[]=[];for(const p of TOOL022_PRESETS){if(selected.has(p.id))out.push(await exportOne(p))}setResults(out);const og=out.find(r=>r.id==='og');setStatus(`${t.done}${og&&og.blob.size>8*1024*1024?' '+t.ogWarn:''}`);return out};
 const downloadCurrent=async()=>{try{const r=await exportOne();download(r.blob,r.name);setResults(v=>[...v.filter(x=>x.id!==r.id),r]);setStatus(t.done)}catch{setError(t.bad)}};
 const downloadZip=async()=>{try{const out=await makeResults();if(!out.length)return;const zip=await createStoredZip(out.map(r=>({name:r.name,blob:r.blob})));download(zip,'fixlgs-blog-og-images.zip');setStatus(t.zipDone)}catch{setError('ZIP export failed.')}};
 const resetAll=()=>{bgRef.current?.close();logoRef.current?.close();bgRef.current=null;logoRef.current=null;setCommon(initial);setOverrides({});setPreset('og');setSelected(new Set(TOOL022_PRESETS.map(p=>p.id)));setResults([]);setLogoName('');setBgName('design');setStarted(false);setError('');setStatus('')};
 const pointer=useRef<{x:number;y:number;cx:number;cy:number}|null>(null);const onPointerDown=(e:React.PointerEvent<HTMLCanvasElement>)=>{if(!bgRef.current)return;e.currentTarget.setPointerCapture(e.pointerId);pointer.current={x:e.clientX,y:e.clientY,cx:eff.cropX,cy:eff.cropY};if(!one)setOne(true)};const onPointerMove=(e:React.PointerEvent<HTMLCanvasElement>)=>{const p=pointer.current;if(!p)return;const rect=e.currentTarget.getBoundingClientRect();setValue('cropX',Math.max(-1,Math.min(1,p.cx-(e.clientX-p.x)/Math.max(80,rect.width)*2)));setValue('cropY',Math.max(-1,Math.min(1,p.cy-(e.clientY-p.y)/Math.max(80,rect.height)*2)))};const onPointerUp=()=>{pointer.current=null};
 const sourceLabel=(id:string)=>id==='official-recommended'?t.official:id==='toolbox-recommended'?t.toolbox:t.fixed;
 return <div className={`${styles.root} tool022-root`} data-testid="tool-022-root">
   {!started&&<>
   <p className={styles.localLine}>{t.local}</p>
   <section className={`toolbox-workbench ${styles.workspaceCard}`} data-testid="tool022-start-card"><div className={`toolbox-workbench-upload ${dragActive?'is-dragging':''}`} data-testid="tool022-drop-zone" onDragEnter={e=>{e.preventDefault();setDragActive(true)}} onDragOver={e=>{e.preventDefault();e.dataTransfer.dropEffect='copy';setDragActive(true)}} onDragLeave={e=>{if(!e.currentTarget.contains(e.relatedTarget as Node|null))setDragActive(false)}} onDrop={e=>{e.preventDefault();setDragActive(false);const file=e.dataTransfer.files?.[0];if(file)void chooseBg(file)}}><div className="toolbox-workbench-topline"><div><span>WORKSPACE</span><strong>{t.workspace}</strong></div></div><div className={`toolbox-upload-focus ${styles.workspaceDropFocus}`}><span className="toolbox-upload-icon" aria-hidden="true">＋</span><h2>{t.choose}</h2><p>{locale==='ko'?'이미지를 여기로 드래그하거나 버튼으로 선택하세요. 배경 없이 만들려면 아래 빈 디자인 시작을 선택할 수 있습니다.':locale==='en'?'Drag an image here or choose one with the button. Use the blank-design option below to start without a background.':'画像をここへドラッグするか、ボタンから選択してください。背景なしの場合は下の空デザイン開始を選べます。'}</p><label className={styles.workspaceUploadButton}><StableMobileImageFileInput data-testid="tool022-background-input" className={styles.hidden} type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>{const file=e.target.files?.[0];if(file)void chooseBg(file);e.currentTarget.value=''}}/>{t.choose}</label><small>{t.support}</small></div>{error&&<div className="toolbox-workbench-notice"><strong>{locale==='ko'?'안내':locale==='en'?'Notice':'案内'}</strong><span data-testid="tool022-error" className={`${styles.status} ${styles.error}`} role="alert">{error}</span></div>}</div><div className={styles.blankStartRow}><button data-testid="tool022-start-blank" type="button" className={styles.secondaryStartButton} onClick={()=>{setStarted(true);setBgName('blank-design');setError('')}}>{t.blank}</button></div></section></>}
   {started&&<>
   <div className={styles.mobileTabs}><button className={mobile==='edit'?styles.active:''} onClick={()=>setMobile('edit')}>EDIT</button><button className={mobile==='preview'?styles.active:''} onClick={()=>setMobile('preview')}>PREVIEW / EXPORT</button></div>
   <div className={styles.workspace}>
    <section className={`${styles.card} ${styles.mobilePanel} ${mobile==='preview'?styles.mobileActive:''}`}>
      <div className={styles.head}><div><h3>{currentPreset.label[locale]}</h3><small>{currentPreset.width}×{currentPreset.height} · {sourceLabel(currentPreset.sourceType)}</small></div><label className={styles.check}><input data-testid="tool022-select-current" type="checkbox" checked={selected.has(preset)} onChange={e=>{setResults([]);setSelected(s=>{const n=new Set(s);e.target.checked?n.add(preset):n.delete(preset);return n})}}/>{t.select}</label></div>
      <div className={styles.presetGrid}>{TOOL022_PRESETS.map(p=><button key={p.id} data-testid={`tool022-preset-${p.id}`} aria-pressed={preset===p.id} className={`${styles.preset} ${preset===p.id?styles.active:''} ${selected.has(p.id)?styles.selected:''}`} onClick={()=>setPreset(p.id)}><strong>{p.label[locale]}</strong><span>{p.width}×{p.height}</span><small>{sourceLabel(p.sourceType)}</small></button>)}</div>
      <div className={styles.previewWrap}><canvas ref={canvasRef} aria-label={`${currentPreset.label[locale]} ${t.preview}`} onPointerDown={onPointerDown} onPointerMove={onPointerMove} onPointerUp={onPointerUp} onPointerCancel={onPointerUp}/>{guide&&<div className={styles.guide}/>}</div><p className={styles.muted}>{t.drag}</p>
      <div className={styles.toolbar}><label className={styles.check}><input type="checkbox" checked={guide} onChange={e=>setGuide(e.target.checked)}/>{t.guide}</label><button className={styles.button} onClick={()=>{setResults([]);setOverrides(o=>{const n={...o};delete n[preset];return n})}}>{t.resetOne}</button></div>
    </section>
    <aside className={`${styles.card} ${styles.settingsHorizontal} ${styles.mobilePanel} ${mobile==='edit'?styles.mobileActive:''}`} data-testid="tool022-settings-horizontal">
      <div className={styles.scope}><b>{t.scopeNow}: {one?t.scopeOne:t.scopeAll}</b><div className={styles.seg}><button className={!one?styles.active:''} onClick={()=>setOne(false)}>{t.scopeAll}</button><button className={one?styles.active:''} onClick={()=>setOne(true)}>{t.scopeOne}</button></div></div>
      <div className={styles.section}><div className={styles.sectionTitle}><b>{t.background}</b><label className={styles.button}><StableMobileImageFileInput data-testid="tool022-background-replace-input" className={styles.hidden} type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>{const file=e.currentTarget.files?.[0];if(file)void chooseBg(file);e.currentTarget.value=''}}/>{bgRef.current?(locale==='ko'?'배경 이미지 교체':locale==='en'?'Replace Background Image':'背景画像を変更'):t.choose}</label></div><div className={styles.row}><label className={styles.label}>X<div className={styles.range}><input aria-label="crop x" type="range" min="-100" max="100" value={Math.round(eff.cropX*100)} onChange={e=>setValue('cropX',+e.target.value/100)}/><output>{Math.round(eff.cropX*100)}</output></div></label><label className={styles.label}>Y<div className={styles.range}><input aria-label="crop y" type="range" min="-100" max="100" value={Math.round(eff.cropY*100)} onChange={e=>setValue('cropY',+e.target.value/100)}/><output>{Math.round(eff.cropY*100)}</output></div></label></div><label className={styles.label}>{t.zoom}<div className={styles.range}><input aria-label="zoom" type="range" min="100" max="250" value={Math.round(eff.zoom*100)} onChange={e=>setValue('zoom',+e.target.value/100)}/><output>{Math.round(eff.zoom*100)}%</output></div></label><label className={styles.label}>{t.overlay}<div className={styles.range}><input type="range" min="0" max="80" value={common.overlay} onChange={e=>setValue('overlay',+e.target.value)}/><output>{common.overlay}%</output></div></label><label className={styles.label}>Background color<input type="color" value={common.backgroundColor} onChange={e=>setValue('backgroundColor',e.target.value)}/></label></div>
      <div className={styles.section}><div className={styles.sectionTitle}><b>{t.title}</b><span className={styles.selectHint}>{common.title.length}/{TOOL022_LIMITS.maxTitleChars}</span></div><label className={styles.label}>{t.title}<textarea maxLength={TOOL022_LIMITS.maxTitleChars} value={common.title} onChange={e=>setValue('title',e.target.value)}/></label><div className={styles.row}><label className={styles.label}>{t.size}<input type="number" min="24" max="130" value={eff.titleSize} onChange={e=>setValue('titleSize',+e.target.value)}/></label><label className={styles.label}>Color<input type="color" value={common.titleColor} onChange={e=>setValue('titleColor',e.target.value)}/></label></div><div className={styles.row}><label className={styles.label}>X<div className={styles.range}><input aria-label="title x" type="range" min="0" max="100" value={Math.round(eff.titleX*100)} onChange={e=>setValue('titleX',+e.target.value/100)}/><output>{Math.round(eff.titleX*100)}%</output></div></label><label className={styles.label}>Y<div className={styles.range}><input aria-label="title y" type="range" min="0" max="100" value={Math.round(eff.titleY*100)} onChange={e=>setValue('titleY',+e.target.value/100)}/><output>{Math.round(eff.titleY*100)}%</output></div></label></div><div className={styles.quick}>{(['left','center','right'] as Align[]).map(a=><button key={a} className={common.align===a?styles.active:''} onClick={()=>setValue('align',a)}>{a==='left'?t.left:a==='center'?t.center:t.right}</button>)}</div></div>
      <div className={styles.section}><div className={styles.sectionTitle}><b>{t.description}</b><span className={styles.selectHint}>{common.description.length}/{TOOL022_LIMITS.maxDescriptionChars}</span></div><label className={styles.label}>{t.description}<textarea maxLength={TOOL022_LIMITS.maxDescriptionChars} value={common.description} onChange={e=>setValue('description',e.target.value)}/></label><div className={styles.row}><label className={styles.label}>{t.size}<input type="number" min="14" max="72" value={eff.descriptionSize} onChange={e=>setValue('descriptionSize',+e.target.value)}/></label><label className={styles.label}>Color<input type="color" value={common.descriptionColor} onChange={e=>setValue('descriptionColor',e.target.value)}/></label></div><div className={styles.row}><label className={styles.label}>X<div className={styles.range}><input aria-label="description x" type="range" min="0" max="100" value={Math.round(eff.descriptionX*100)} onChange={e=>setValue('descriptionX',+e.target.value/100)}/><output>{Math.round(eff.descriptionX*100)}%</output></div></label><label className={styles.label}>Y<div className={styles.range}><input aria-label="description y" type="range" min="0" max="100" value={Math.round(eff.descriptionY*100)} onChange={e=>setValue('descriptionY',+e.target.value/100)}/><output>{Math.round(eff.descriptionY*100)}%</output></div></label></div></div>
      <div className={styles.section}><div className={styles.sectionTitle}><b>{t.logo}</b><div className={styles.logoRow}><label className={styles.button}><StableMobileImageFileInput className={styles.hidden} type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>chooseLogo(e.target.files?.[0])}/>{t.chooseLogo}</label>{logoName&&<button className={styles.button} onClick={()=>{logoRef.current?.close();logoRef.current=null;setLogoName('');setResults([])}}>{t.removeLogo}</button>}</div></div>{logoName&&<p className={styles.muted}>{logoName}</p>}<div className={styles.row}><label className={styles.label}>{t.size}<div className={styles.range}><input type="range" min="5" max="40" value={Math.round(eff.logoScale*100)} onChange={e=>setValue('logoScale',+e.target.value/100)}/><output>{Math.round(eff.logoScale*100)}%</output></div></label><label className={styles.label}>{t.opacity}<div className={styles.range}><input type="range" min="10" max="100" value={common.logoOpacity} onChange={e=>setValue('logoOpacity',+e.target.value)}/><output>{common.logoOpacity}%</output></div></label></div><div className={styles.row}><label className={styles.label}>X<div className={styles.range}><input aria-label="logo x" type="range" min="0" max="100" value={Math.round(eff.logoX*100)} onChange={e=>setValue('logoX',+e.target.value/100)}/><output>{Math.round(eff.logoX*100)}%</output></div></label><label className={styles.label}>Y<div className={styles.range}><input aria-label="logo y" type="range" min="0" max="100" value={Math.round(eff.logoY*100)} onChange={e=>setValue('logoY',+e.target.value/100)}/><output>{Math.round(eff.logoY*100)}%</output></div></label></div></div>
      {error&&<p data-testid="tool022-error" className={`${styles.status} ${styles.error}`} role="alert">{error}</p>}
    </aside>
   </div>
   <section className={styles.card}><div className={styles.head}><div><h3>EXPORT</h3><small>{t.local}</small></div></div><div className={styles.row}><label className={styles.label}>{t.format}<select value={format} onChange={e=>{setResults([]);setFormat(e.target.value as Format)}}><option value="jpg">JPG</option><option value="png">PNG</option></select></label><label className={styles.label}>{t.quality}<input type="range" min="60" max="100" value={quality} disabled={format==='png'} onChange={e=>{setResults([]);setQuality(+e.target.value)}}/></label></div><div className={styles.actions}><button className={styles.primary} data-testid="tool022-download-current" onClick={downloadCurrent}>{t.download}</button><button className={styles.primary} data-testid="tool022-download-zip" onClick={downloadZip}>{t.zip}</button><button className={styles.button} onClick={()=>setResults([])}>{t.continue}</button><label className={styles.button}><StableMobileImageFileInput className={styles.hidden} type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>chooseBg(e.target.files?.[0])}/>{t.newImage}</label><button className={styles.button} onClick={resetAll}>{t.resetAll}</button></div><p data-testid="tool022-status" className={styles.status} aria-live="polite">{status}</p>{results.length>0&&<div className={styles.resultGrid}>{results.map(r=><div className={styles.result} key={r.id}><strong>{TOOL022_PRESETS.find(p=>p.id===r.id)?.label[locale]}</strong><span>{r.width}×{r.height} · {(r.blob.size/1024).toFixed(0)} KB</span><button className={styles.button} onClick={()=>download(r.blob,r.name)}>{t.download}</button></div>)}</div>}</section>
   <section className={styles.card}><div className={styles.head}><div><h3>{t.preview}</h3><small>{selected.size} / {TOOL022_PRESETS.length}</small></div></div><div className={styles.thumbs}>{TOOL022_PRESETS.map(p=><Preview key={p.id} preset={p} locale={locale} render={render} onClick={()=>setPreset(p.id)}/>)}</div></section>
   <section className={styles.card}><div className={styles.head}><div><h3>{t.ogPreview}</h3><small>Preview only · not exported</small></div></div><div className={styles.ogCard}><OgPreview render={render}/><div className={styles.ogBody}><span>toolbox.fixlgs.com</span><strong>{common.title||'Open Graph title'}</strong><p className={styles.muted}>{common.description}</p></div></div></section>

   </>}
 </div>
}

function Preview({preset,locale,render,onClick}:{preset:(typeof TOOL022_PRESETS)[number];locale:Locale;render:(c:HTMLCanvasElement,p:(typeof TOOL022_PRESETS)[number],s?:number)=>void;onClick:()=>void}){const ref=useRef<HTMLCanvasElement>(null);useEffect(()=>{if(ref.current)render(ref.current,preset,.4)},[render,preset]);return <button className={styles.thumb} onClick={onClick}><canvas ref={ref}/><strong>{preset.label[locale]}</strong><small>{preset.width}×{preset.height}</small></button>}
function OgPreview({render}:{render:(c:HTMLCanvasElement,p:(typeof TOOL022_PRESETS)[number],s?:number)=>void}){const ref=useRef<HTMLCanvasElement>(null);const p=TOOL022_PRESETS.find(x=>x.id==='og')!;useEffect(()=>{if(ref.current)render(ref.current,p,.42)},[render,p]);return <canvas ref={ref}/>} 
