import { ToolNavigation } from "@/components/tool-navigation";
import Link from "next/link";
import { DateAddSubtractCalculatorTool } from "@/components/date-add-subtract-calculator-tool";
import { ToolboxFaqList } from "@/components/toolbox-faq-list";
import { ToolboxSubpageShell } from "@/components/toolbox-subpage-shell";
import type { Locale } from "@/lib/site";

const copy={
 ko:{back:"날짜·시간 도구",title:"날짜 더하기·빼기 계산기",desc:"기준 날짜에 일·주·개월·년을 더하거나 빼서 결과 날짜와 요일까지 바로 확인하세요.",local:"날짜 계산은 브라우저 로컬에서만 처리합니다.",next:"다음 작업",related:"관련 도구",available:"사용 가능",coming:"준비 중",how:"사용 방법",guide:"날짜를 더하고 뺄 때 꼭 알아둘 기준",guideDesc:"일·주와 달력 월·년의 차이, 월말 보정, 윤년 처리, 0 입력과 날짜 범위를 명확히 구분해 계산합니다.",caution:"주의사항",faq:"자주 묻는 질문",steps:["기준 날짜를 선택합니다.","더하기 또는 빼기와 일·주·개월·년 단위를 선택합니다.","0 이상의 정수 수량을 입력하고 계산합니다.","결과 날짜와 요일을 확인하고 필요하면 복사합니다."],points:[["DAY","일은 연속된 달력일","1일은 다음 달력 날짜로 한 칸 이동합니다. 시간과 timezone을 섞지 않고 date-only 기준으로 계산합니다."],["WEEK","1주는 정확히 7일","주는 달력 주차가 아니라 7개의 연속 달력일로 계산합니다."],["MONTH","개월은 달력 월 단위","30일을 1개월로 바꾸지 않습니다. 목표 월에 같은 날짜가 없으면 그 달의 마지막 날짜로 맞춥니다."],["YEAR","년은 달력 연도 단위","365일을 1년으로 바꾸지 않습니다. 2월 29일에서 평년으로 이동하면 2월 28일로 보정합니다."],["LOCAL","입력값은 로컬에서 처리","선택한 날짜와 계산 결과는 서버 저장이나 전송 없이 현재 브라우저에서만 처리합니다."]],cautions:["수량은 0 이상의 정수만 사용할 수 있습니다.","1개월과 30일, 1년과 365일은 서로 같은 계산이 아닙니다.","계산 결과가 지원 날짜 범위를 벗어나면 결과 대신 오류를 표시합니다.","영업일·공휴일 제외 계산은 TOOL050의 범위이며 여기서는 적용하지 않습니다."],faqs:[["1월 31일에 1개월을 더하면 어떻게 되나요?","목표 월에 31일이 없으면 그 달의 마지막 날로 계산합니다. 2026년에는 2월 28일입니다."],["윤년 2월 29일에 1년을 더하면요?","다음 해가 평년이면 2월 28일로 계산합니다."],["30일과 1개월은 같은가요?","아닙니다. 30일은 연속 달력일이고 1개월은 달력 월을 이동하는 계산입니다."],["0일을 더하거나 빼면 어떻게 되나요?","기준 날짜와 같은 날짜가 결과로 표시됩니다."],["입력한 날짜가 서버로 전송되나요?","아니요. 계산은 현재 브라우저 로컬에서만 수행합니다."]]},
 en:{back:"Date & Time",title:"Date Add & Subtract Calculator",desc:"Add or subtract days, weeks, months, or years from a date and instantly see the resulting date and weekday.",local:"Date calculations run only in your browser.",next:"Next work",related:"Related tools",available:"Available",coming:"Coming soon",how:"How to use",guide:"Rules for adding and subtracting dates",guideDesc:"Keep days and weeks separate from calendar months and years, with explicit month-end, leap-year, zero-value, and supported-range behavior.",caution:"Important notes",faq:"Frequently asked questions",steps:["Choose a start date.","Choose Add or Subtract and select days, weeks, months, or years.","Enter a non-negative whole-number quantity and calculate.","Review the resulting date and weekday, then copy it if needed."],points:[["DAY","Days are consecutive calendar days","One day moves to the next calendar date. The calculation uses date-only values rather than time or timezone offsets."],["WEEK","One week is exactly seven days","Weeks are calculated as seven consecutive calendar days, not by calendar week number."],["MONTH","Months use calendar-month arithmetic","The tool never converts 30 days into one month. If the target month lacks the same day, it clamps to the last day of that month."],["YEAR","Years use calendar-year arithmetic","The tool never converts 365 days into one year. February 29 clamps to February 28 when the target year is not a leap year."],["LOCAL","Inputs stay in the browser","Selected dates and results are processed locally without server storage or transmission."]],cautions:["Quantity must be a non-negative integer.","One month is not the same as 30 days, and one year is not the same as 365 days.","If the result would exceed the supported date range, the tool shows an error instead of a result.","Business-day and holiday exclusion belongs to TOOL050 and is not applied here."],faqs:[["What is January 31 plus one month?","If the target month has no 31st, the result is clamped to that month’s last day. In 2026 that is February 28."],["What is February 29 plus one year?","If the target year is not a leap year, the result is February 28."],["Are 30 days and one month the same?","No. Thirty days means consecutive calendar days, while one month moves by the calendar month."],["What happens when I add or subtract zero days?","The result stays on the same date."],["Are my dates uploaded?","No. The calculation runs locally in the current browser."]]},
 ja:{back:"日付・時間",title:"日付加算・減算計算ツール",desc:"基準日に日・週・か月・年を加算または減算し、結果の日付と曜日をすぐ確認できます。",local:"日付計算はブラウザ内だけで処理します。",next:"次の作業",related:"関連ツール",available:"利用可能",coming:"準備中",how:"使い方",guide:"日付を加算・減算するときの基準",guideDesc:"日・週と暦上の月・年を分け、月末補正、うるう年、0入力、対応範囲を明確にして計算します。",caution:"注意事項",faq:"よくある質問",steps:["基準日を選択します。","加算・減算と日・週・か月・年の単位を選択します。","0以上の整数を入力して計算します。","結果の日付と曜日を確認し、必要ならコピーします。"],points:[["DAY","日は連続する暦日","1日は次の暦日へ1日移動します。時刻やtimezoneを混ぜず、date-onlyで計算します。"],["WEEK","1週間は正確に7日","週番号ではなく、連続する7暦日として計算します。"],["MONTH","か月は暦月単位","30日を1か月に換算しません。対象月に同じ日がない場合は、その月の最終日に調整します。"],["YEAR","年は暦年単位","365日を1年に換算しません。2月29日から平年へ移動する場合は2月28日に調整します。"],["LOCAL","入力値はブラウザ内で処理","選択した日付と計算結果はサーバーへ保存・送信せず、現在のブラウザ内だけで処理します。"]],cautions:["数量は0以上の整数のみ使用できます。","1か月と30日、1年と365日は同じ計算ではありません。","結果が対応日付範囲を超える場合は、結果の代わりにエラーを表示します。","営業日・祝日を除外する計算はTOOL050の範囲で、このツールでは適用しません。"],faqs:[["1月31日に1か月を加えるとどうなりますか？","対象月に31日がない場合、その月の最終日になります。2026年なら2月28日です。"],["うるう年の2月29日に1年を加えると？","翌年が平年なら2月28日になります。"],["30日と1か月は同じですか？","いいえ。30日は連続する暦日で、1か月は暦月を移動する計算です。"],["0日を加算・減算するとどうなりますか？","基準日と同じ日付が結果になります。"],["入力した日付はサーバーへ送信されますか？","いいえ。計算は現在のブラウザ内だけで行います。"]]}
} as const;

export function DateAddSubtractCalculatorPage({locale}:{locale:Locale}){
 const t=copy[locale],url=`https://toolbox.fixlgs.com/${locale}/date-add-subtract-calculator`;
 const related=[
  {n:"045",slug:"date-difference-calculator",name:locale==="ko"?"날짜 차이 계산기":locale==="ja"?"日付差計算ツール":"Date Difference Calculator",available:true},
  {n:"047",slug:"dday-anniversary-calculator",name:locale==="ko"?"디데이·기념일 계산기":locale==="ja"?"Dデイ・記念日計算ツール":"D-Day & Anniversary Calculator",available:true},
  {n:"050",slug:"business-day-calculator",name:locale==="ko"?"평일·영업일 계산기":locale==="ja"?"平日・営業日計算ツール":"Weekday & Business Day Calculator",available:false},
  {n:"051",slug:"time-calculator",name:locale==="ko"?"시간 계산기":locale==="ja"?"時間計算ツール":"Time Calculator",available:false}
 ];
 const jsonLd={"@context":"https://schema.org","@graph":[{"@type":"WebApplication",name:t.title,applicationCategory:"UtilitiesApplication",operatingSystem:"Any",url,description:t.desc,offers:{"@type":"Offer",price:"0",priceCurrency:"USD"}},{"@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:"TOOLBOX",item:`https://toolbox.fixlgs.com/${locale}`},{"@type":"ListItem",position:2,name:t.back,item:`https://toolbox.fixlgs.com/${locale}/category/date-time`},{"@type":"ListItem",position:3,name:t.title,item:url}]},{"@type":"FAQPage",mainEntity:t.faqs.map(([q,a])=>({"@type":"Question",name:q,acceptedAnswer:{"@type":"Answer",text:a}}))}]};
 return <ToolboxSubpageShell locale={locale} appName={t.title}><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(jsonLd)}}/>
 <section className="toolbox-tool-detail-hero toolbox-tool-detail-hero--single-line-description"><Link className="toolbox-subpage-back" href={`/${locale}/category/date-time`}>← {t.back}</Link><p className="toolbox-subpage-eyebrow">046 · DATE & TIME</p><div className="toolbox-tool-detail-heading"><h1><span className="toolbox-tool-title-line">{t.title}</span></h1><p>{t.desc}</p></div><div className="toolbox-tool-detail-badge"><strong>LOCAL</strong><span>{t.local}</span></div></section>
 <section className="toolbox-tool-detail-body"><div><DateAddSubtractCalculatorTool locale={locale}/><ToolNavigation locale={locale} currentTool={46} /></div></section>
 <section className="toolbox-tool-guide toolbox-tool-guide--five"><div className="toolbox-tool-guide-head"><p>HOW TO USE</p><h2>{t.how}</h2></div><ol>{t.steps.map((s,i)=><li key={s}><span>{String(i+1).padStart(2,"0")}</span><p>{s}</p></li>)}</ol></section>
 <section className="toolbox-tool-format-guide toolbox-tool-expert-post toolbox-tool-expert-post--wide-head"><div className="toolbox-tool-format-guide-head"><p>DATE ARITHMETIC GUIDE</p><h2>{t.guide}</h2><span>{t.guideDesc}</span></div><div className="toolbox-tool-format-body"><div className="toolbox-tool-format-grid">{t.points.map(([n,h,p])=><article key={n}><strong>{n}</strong><h3>{h}</h3><p>{p}</p></article>)}</div></div></section>
 <section className="toolbox-tool-info-band toolbox-tool-info-band--section-start toolbox-tool-info-band--bottom-gap toolbox-tool-info-band--left-head toolbox-tool-info-band--format-head toolbox-tool-info-band--full-divider"><div className="toolbox-tool-info-band-head"><p>IMPORTANT NOTES</p><h2>{t.caution}</h2></div><ul className="toolbox-tool-info-band-list">{t.cautions.map(x=><li key={x}>{x}</li>)}</ul></section>
 <section className="toolbox-tool-faq"><div className="toolbox-tool-guide-head"><p>FAQ</p><h2>{t.faq}</h2></div><ToolboxFaqList items={t.faqs.map(([q,a]):readonly[string,string]=>[q,a])} initialCount={5} moreLabel={locale==="ko"?"FAQ 더보기":locale==="ja"?"FAQをもっと見る":"Show more FAQs"} collapseLabel={locale==="ko"?"FAQ 접기":locale==="ja"?"FAQを閉じる":"Collapse FAQs"} className="toolbox-tool-faq-list"/></section>
 </ToolboxSubpageShell>;
}
