import Link from "next/link";
import { DateDifferenceCalculatorTool } from "@/components/date-difference-calculator-tool";
import { ToolboxFaqList } from "@/components/toolbox-faq-list";
import { ToolboxSubpageShell } from "@/components/toolbox-subpage-shell";
import type { Locale } from "@/lib/site";
import styles from "@/components/date-difference-calculator-tool.module.css";
const copy={
 ko:{back:"날짜·시간 도구",title:"날짜 차이 계산기",desc:"두 날짜 사이의 정확한 일수와 달력 기간을 계산하고, 시작일 포함 여부에 따라 평일·주말 수까지 바로 확인하세요.",local:"날짜 계산은 브라우저 로컬에서만 처리합니다.",next:"다음 작업",related:"관련 도구",available:"사용 가능",coming:"준비 중",how:"사용 방법",guide:"날짜 차이를 정확하게 읽는 기준",guideDesc:"총 일수와 달력 기간을 분리하고 시작일 포함 규칙, 윤년·월말, 평일·주말 경계를 명확히 이해할 수 있습니다.",caution:"주의사항",faq:"자주 묻는 질문",steps:["시작일과 종료일을 선택합니다.","필요하면 시작일 포함을 켭니다.","총 일수, 주/일, 달력 기간, 평일·주말 결과를 확인합니다.","새 계산은 초기화를 누르고 다시 날짜를 선택합니다."],points:[["ELAPSED","총 일수는 실제 날짜 차이","기본 총 일수는 종료일에서 시작일을 뺀 실제 Gregorian 달력 일수입니다. 같은 날짜는 기본 0일입니다."],["INCLUDE","시작일 포함은 1일 추가","시작일 포함을 켜면 시작일을 1일째로 세며 평일·주말 분류에도 같은 경계 규칙을 적용합니다."],["CALENDAR","달력 기간은 달력 단위로 계산","30일=1개월, 365일=1년으로 단정하지 않습니다. 완전히 지난 달력 연·월·일을 총 일수와 별도 표시합니다."],["WEEKDAY","평일·주말 합계 검증","평일과 주말 수의 합은 화면에 적용된 총 날짜 수와 항상 같도록 계산합니다."],["LOCAL","시간대는 계산에서 제외","date-only 값을 직접 Gregorian serial로 계산하여 시각과 timezone 차이 때문에 날짜가 바뀌는 문제를 피합니다."]],cautions:["시작일이 종료일보다 늦으면 자동으로 두 날짜를 바꾸지 않고 오류를 표시합니다.","공휴일은 평일에서 제외하지 않습니다. 국가별 공휴일·영업일 계산은 TOOL050 범위입니다.","달력 기간은 총 일수의 단순 환산값이 아닙니다. 총 일수를 기본 기준으로 확인하세요.","입력 날짜는 서버나 Analytics 이벤트 값으로 전송하지 않는 로컬 계산 구조입니다."],faqs:[["같은 날짜를 선택하면 며칠인가요?","기본은 0일이고 시작일 포함을 켜면 1일입니다."],["1월 31일부터 2월 28일까지는 한 달인가요?","총 일수는 28일입니다. 달력 기간은 단순 30일 환산이 아니라 완전히 지난 달력 단위로 별도 계산합니다."],["윤년 2월 29일도 처리하나요?","네. Gregorian 윤년 규칙을 사용해 실제 월 길이를 계산합니다."],["평일 계산에서 공휴일도 제외하나요?","아니요. 이 도구는 토·일만 주말로 분류합니다. 국가별 공휴일은 TOOL050에서 다룹니다."],["시작일과 종료일을 거꾸로 넣으면 자동으로 바뀌나요?","아니요. 계산 기준을 숨기지 않기 위해 순서 오류를 표시합니다."],["선택한 날짜가 서버로 전송되나요?","아니요. 계산은 현재 브라우저 로컬에서만 수행합니다."]]},
 en:{back:"Date & Time",title:"Date Difference Calculator",desc:"Calculate exact days and calendar duration between two dates, with optional start-date inclusion plus weekday and weekend counts.",local:"Date calculations run only in your browser.",next:"Next work",related:"Related tools",available:"Available",coming:"Coming soon",how:"How to use",guide:"How to read date differences accurately",guideDesc:"Keep total elapsed days separate from calendar duration and use explicit rules for start-date inclusion, leap years, month ends, weekdays, and weekends.",caution:"Important notes",faq:"Frequently asked questions",steps:["Choose a start date and an end date.","Enable Include start date when needed.","Review total days, weeks/remainder, calendar period, weekdays, and weekends.","Use Reset before starting a new calculation."],points:[["ELAPSED","Total days use the real date gap","The default total is the Gregorian calendar difference between end and start. The same date is 0 days by default."],["INCLUDE","Including the start adds exactly one day","When enabled, the start date becomes day 1 and the same boundary rule applies to weekday/weekend classification."],["CALENDAR","Calendar period is not a simple conversion","The tool does not declare 30 days as one month or 365 days as one year. Complete calendar years, months, and days are shown separately."],["WEEKDAY","Weekday and weekend invariant","Weekday plus weekend counts always equal the number of dates included in the displayed total."],["LOCAL","Timezone is excluded from the math","Date-only values are converted to Gregorian serial days directly so time and timezone offsets cannot shift the result."]],cautions:["If the start date is after the end date, the tool shows an error and never swaps them automatically.","Public holidays are not excluded from weekdays. Country-specific business-day logic belongs to TOOL050.","Calendar period is not a simple conversion of total days; use total days as the primary reference.","Selected dates stay local and are not sent as Analytics event values."],faqs:[["What happens if both dates are the same?","The default result is 0 days; including the start date makes it 1 day."],["Is January 31 to February 28 simply one month?","The total is 28 days. Calendar duration is calculated separately instead of using a 30-day month conversion."],["Does it handle February 29 in leap years?","Yes. It follows Gregorian leap-year and month-length rules."],["Are public holidays excluded from weekdays?","No. Only Saturday and Sunday are weekends here; country-specific holidays belong to TOOL050."],["Will reversed dates be swapped automatically?","No. The tool reports an order error so the boundary rule remains explicit."],["Are my dates uploaded?","No. All calculations run locally in the current browser."]]},
 ja:{back:"日付・時間",title:"日付差計算ツール",desc:"2つの日付の正確な日数とカレンダー期間を計算し、開始日を含める設定に応じて平日・週末の日数も確認できます。",local:"日付計算はブラウザ内だけで処理します。",next:"次の作業",related:"関連ツール",available:"利用可能",coming:"準備中",how:"使い方",guide:"日付差を正確に読む基準",guideDesc:"合計日数とカレンダー期間を分け、開始日を含める規則、うるう年、月末、平日・週末の境界を明確にします。",caution:"注意事項",faq:"よくある質問",steps:["開始日と終了日を選択します。","必要に応じて開始日を含めるをオンにします。","合計日数、週/残り日数、カレンダー期間、平日・週末を確認します。","新しい計算はリセットしてから日付を選び直します。"],points:[["ELAPSED","合計日数は実際の日付差","基本の合計日数は終了日から開始日を引いたGregorian暦の日数です。同じ日付は基本0日です。"],["INCLUDE","開始日を含めると正確に1日追加","オンにすると開始日を1日目として数え、平日・週末の分類にも同じ境界規則を使います。"],["CALENDAR","カレンダー期間は単純換算しない","30日=1か月、365日=1年とは断定せず、完全に経過した年・月・日を合計日数と分けて表示します。"],["WEEKDAY","平日・週末の合計を一致","平日数と週末数の合計は画面で適用された合計日数と常に一致します。"],["LOCAL","タイムゾーンを計算から除外","日付だけをGregorian serialへ直接変換し、時刻・timezone差で日付がずれる問題を避けます。"]],cautions:["開始日が終了日より後の場合は自動入れ替えせず、順序エラーを表示します。","祝日は平日から除外しません。国別の祝日・営業日計算はTOOL050の範囲です。","カレンダー期間は合計日数の単純換算ではありません。合計日数を基本基準として確認してください。","入力した日付はサーバーやAnalyticsイベント値へ送信しないローカル計算です。"],faqs:[["同じ日付を選ぶと何日ですか？","基本は0日で、開始日を含めるをオンにすると1日です。"],["1月31日から2月28日は単純に1か月ですか？","合計日数は28日です。カレンダー期間は30日換算ではなく別に計算します。"],["うるう年の2月29日も処理できますか？","はい。Gregorian暦のうるう年規則と実際の月日数を使います。"],["平日計算では祝日も除外しますか？","いいえ。ここでは土日だけを週末とし、国別祝日はTOOL050で扱います。"],["日付を逆に入れると自動で入れ替わりますか？","いいえ。境界規則を明確にするため順序エラーを表示します。"],["入力した日付はサーバーへ送信されますか？","いいえ。すべて現在のブラウザ内で計算します。"]]}
} as const;
export function DateDifferenceCalculatorPage({locale}:{locale:Locale}){
 const t=copy[locale],url=`https://toolbox.fixlgs.com/${locale}/date-difference-calculator`;
 const related=[{n:"046",name:locale==="ko"?"날짜 더하기·빼기 계산기":locale==="ja"?"日付加算・減算計算ツール":"Date Add & Subtract Calculator"},{n:"047",name:locale==="ko"?"디데이·기념일 계산기":locale==="ja"?"D-day・記念日計算ツール":"D-day & Anniversary Calculator"},{n:"050",name:locale==="ko"?"평일·영업일 계산기":locale==="ja"?"平日・営業日計算ツール":"Weekday & Business Day Calculator"}];
 const jsonLd={"@context":"https://schema.org","@graph":[{"@type":"WebApplication",name:t.title,applicationCategory:"UtilitiesApplication",operatingSystem:"Any",url,description:t.desc,offers:{"@type":"Offer",price:"0",priceCurrency:"USD"}},{"@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:"TOOLBOX",item:`https://toolbox.fixlgs.com/${locale}`},{"@type":"ListItem",position:2,name:t.back,item:`https://toolbox.fixlgs.com/${locale}/category/date-time`},{"@type":"ListItem",position:3,name:t.title,item:url}]},{"@type":"FAQPage",mainEntity:t.faqs.map(([q,a])=>({"@type":"Question",name:q,acceptedAnswer:{"@type":"Answer",text:a}}))}]};
 return <ToolboxSubpageShell locale={locale} appName={t.title}><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(jsonLd)}}/>
 <section className="toolbox-tool-detail-hero toolbox-tool-detail-hero--single-line-description"><Link className="toolbox-subpage-back" href={`/${locale}/category/date-time`}>← {t.back}</Link><p className="toolbox-subpage-eyebrow">045 · DATE & TIME</p><div className="toolbox-tool-detail-heading"><h1><span className="toolbox-tool-title-line">{t.title}</span></h1><p>{t.desc}</p></div><div className="toolbox-tool-detail-badge"><strong>LOCAL</strong><span>{t.local}</span></div></section>
 <section className="toolbox-tool-detail-body"><div><DateDifferenceCalculatorTool locale={locale}/><section className="toolbox-next-work"><div className="toolbox-next-work-head"><p>NEXT WORK</p><h2>{t.next}</h2></div><div className="toolbox-next-work-grid"><Link href={`/${locale}/date-add-subtract-calculator`} className="toolbox-next-work-card"><span>046</span><h3>{related[0].name}</h3><div className="toolbox-next-work-card-foot"><span>{t.available}</span><strong>↗</strong></div></Link></div></section><section className="toolbox-next-work"><div className="toolbox-next-work-head"><p>RELATED TOOLS</p><h2>{t.related}</h2></div><div className="toolbox-next-work-grid">{related.slice(1).map(x=><div key={x.n} className="toolbox-next-work-card is-disabled"><span>{x.n}</span><h3>{x.name}</h3><div className="toolbox-next-work-card-foot"><span>{t.coming}</span><strong>·</strong></div></div>)}</div></section></div></section>
 <section className="toolbox-tool-guide toolbox-tool-guide--five"><div className="toolbox-tool-guide-head"><p>HOW TO USE</p><h2>{t.how}</h2></div><ol>{t.steps.map((s,i)=><li key={s}><span>{String(i+1).padStart(2,"0")}</span><p>{s}</p></li>)}</ol></section>
 <section className={`${styles.expertPost45} toolbox-tool-format-guide toolbox-tool-expert-post toolbox-tool-expert-post--wide-head toolbox-tool-expert-post--045`}><div className="toolbox-tool-format-guide-head"><p>DATE DIFFERENCE GUIDE</p><h2>{t.guide}</h2><span>{t.guideDesc}</span></div><div className="toolbox-tool-format-body"><div className="toolbox-tool-format-grid">{t.points.map(([n,h,p])=><article key={n}><strong>{n}</strong><h3>{h}</h3><p>{p}</p></article>)}</div></div></section>
 <section className="toolbox-tool-info-band toolbox-tool-info-band--section-start toolbox-tool-info-band--bottom-gap toolbox-tool-info-band--left-head toolbox-tool-info-band--format-head toolbox-tool-info-band--full-divider"><div className="toolbox-tool-info-band-head"><p>IMPORTANT NOTES</p><h2>{t.caution}</h2></div><ul className="toolbox-tool-info-band-list">{t.cautions.map(x=><li key={x}>{x}</li>)}</ul></section>
 <section className="toolbox-tool-faq"><div className="toolbox-tool-guide-head"><p>FAQ</p><h2>{t.faq}</h2></div><ToolboxFaqList items={t.faqs.map(([q,a]):readonly[string,string]=>[q,a])} initialCount={5} moreLabel={locale==="ko"?"FAQ 더보기":locale==="ja"?"FAQをもっと見る":"Show more FAQs"} collapseLabel={locale==="ko"?"FAQ 접기":locale==="ja"?"FAQを閉じる":"Collapse FAQs"} className="toolbox-tool-faq-list"/></section>
 </ToolboxSubpageShell>
}
