"use client";
import {useMemo,useState} from "react";
import type {Locale} from "@/lib/site";
import {calculateTool049Period,totalTool049Periods,TOOL049_LIMITS} from "@/lib/tool-049-employment-tenure";
import styles from "./employment-tenure-calculator-tool.module.css";

type Row={id:number;start:string;end:string;current:boolean};
const copy={
 ko:{local:"입사일·퇴사일·기준일은 서버로 전송하거나 저장하지 않고 현재 브라우저에서만 계산합니다.",eyebrow:"TENURE WORKSPACE",title:"근속기간을 계산하세요",start:"입사일",end:"퇴사일",current:"현재 재직",currentHelp:"켜면 퇴사일 대신 기준일까지 계산합니다.",asof:"기준일",today:"오늘",calculate:"계산",reset:"초기화",copy:"결과 복사",copied:"결과를 복사했습니다.",period:"재직기간",totalDays:"총 일수",empty:"입사일과 퇴사일을 입력하거나 현재 재직을 선택하세요.",invalid:"올바른 날짜를 입력해 주세요.",order:"입사일은 퇴사일 또는 기준일보다 늦을 수 없습니다.",add:"경력 추가",career:"경력",remove:"삭제",total:"총 경력",rows:"여러 경력 합산",rowsHelp:"입력한 각 경력을 그대로 합산합니다. 겹치는 기간은 자동으로 제거하지 않습니다.",rowIncomplete:"추가한 경력의 입사일과 퇴사일을 모두 입력해 주세요.",max:`경력은 최대 ${TOOL049_LIMITS.maxRows}건까지 추가할 수 있습니다.`,years:"년",months:"개월",days:"일",live:"근속·재직기간 계산 결과가 갱신되었습니다."},
 en:{local:"Start, end, and as-of dates stay in this browser and are not sent to or stored on a server.",eyebrow:"TENURE WORKSPACE",title:"Calculate employment tenure",start:"Start Date",end:"End Date",current:"Currently Employed",currentHelp:"Use the as-of date instead of an end date.",asof:"As-of Date",today:"Today",calculate:"Calculate",reset:"Reset",copy:"Copy result",copied:"Result copied.",period:"Employment Period",totalDays:"Total days",empty:"Enter a start and end date, or choose Currently Employed.",invalid:"Enter valid dates.",order:"The start date cannot be later than the end or as-of date.",add:"Add Employment",career:"Employment",remove:"Remove",total:"Total Experience",rows:"Add multiple employment periods",rowsHelp:"Periods are summed exactly as entered. Overlapping dates are not removed automatically.",rowIncomplete:"Complete the start and end date for every added employment period.",max:`You can add up to ${TOOL049_LIMITS.maxRows} employment periods.`,years:"yr",months:"mo",days:"days",live:"Employment tenure result updated."},
 ja:{local:"入社日・退職日・基準日はサーバーへ送信・保存せず、このブラウザ内だけで計算します。",eyebrow:"TENURE WORKSPACE",title:"勤続期間を計算",start:"入社日",end:"退職日",current:"現在在職中",currentHelp:"退職日の代わりに基準日まで計算します。",asof:"基準日",today:"今日",calculate:"計算",reset:"リセット",copy:"結果をコピー",copied:"結果をコピーしました。",period:"勤続期間",totalDays:"合計日数",empty:"入社日と退職日を入力するか、現在在職中を選択してください。",invalid:"正しい日付を入力してください。",order:"入社日は退職日または基準日より後にできません。",add:"経歴を追加",career:"職歴",remove:"削除",total:"職歴合計",rows:"複数の職歴を合算",rowsHelp:"入力した職歴をそのまま合算します。重複期間は自動削除しません。",rowIncomplete:"追加した職歴の入社日と退職日をすべて入力してください。",max:`職歴は最大${TOOL049_LIMITS.maxRows}件まで追加できます。`,years:"年",months:"か月",days:"日",live:"勤続・在職期間の計算結果を更新しました。"}
} as const;
function todayIso(){const d=new Date();const y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,"0"),day=String(d.getDate()).padStart(2,"0");return `${String(y).padStart(4,"0")}-${m}-${day}`}
export function EmploymentTenureCalculatorTool({locale}:{locale:Locale}){
 const t=copy[locale];const [start,setStart]=useState("");const [end,setEnd]=useState("");const [current,setCurrent]=useState(false);const [asOf,setAsOf]=useState("");const [rows,setRows]=useState<Row[]>([]);const [nextId,setNextId]=useState(1);const [error,setError]=useState("");const [status,setStatus]=useState("");const [submitted,setSubmitted]=useState(false);
 const resolvedEnd=current?asOf:end;
 const mainResult=useMemo(()=>{if(!submitted||!start||!resolvedEnd)return null;try{return calculateTool049Period(start,resolvedEnd)}catch{return null}},[submitted,start,resolvedEnd]);
 const rowResults=useMemo(()=>rows.map(r=>{const e=r.current?r.end:r.end;if(!r.start||!e)return null;try{return calculateTool049Period(r.start,e)}catch{return null}}),[rows]);
 const totalResult=useMemo(()=>{if(!submitted||!mainResult)return null;const periods=[{start,end:resolvedEnd},...rows.map(r=>({start:r.start,end:r.end}))];if(periods.some(p=>!p.start||!p.end))return null;try{return totalTool049Periods(periods)}catch{return null}},[submitted,mainResult,start,resolvedEnd,rows]);
 function run(){setStatus("");setSubmitted(false);if(!start||!resolvedEnd){setError(t.empty);return}try{calculateTool049Period(start,resolvedEnd)}catch(e){setError(e instanceof RangeError&&e.message==="START_AFTER_END"?t.order:t.invalid);return}for(const r of rows){if(!r.start||!r.end){setError(t.rowIncomplete);return}try{calculateTool049Period(r.start,r.end)}catch(e){setError(e instanceof RangeError&&e.message==="START_AFTER_END"?t.order:t.invalid);return}}setError("");setSubmitted(true)}
 function reset(){setStart("");setEnd("");setCurrent(false);setAsOf("");setRows([]);setNextId(1);setError("");setStatus("");setSubmitted(false)}
 function toggleCurrent(v:boolean){setCurrent(v);setStatus("");setSubmitted(false);if(v&&!asOf)setAsOf(todayIso())}
 function addRow(){if(rows.length>=TOOL049_LIMITS.maxRows-1){setError(t.max);return}setRows([...rows,{id:nextId,start:"",end:"",current:false}]);setNextId(nextId+1);setError("");setSubmitted(false)}
 function updateRow(id:number,key:"start"|"end",value:string){setRows(rows.map(r=>r.id===id?{...r,[key]:value}:r));setSubmitted(false);setStatus("")}
 async function copyResult(){if(!mainResult||!totalResult)return;const text=rows.length?`${t.total}: ${totalResult.duration.years} ${t.years} ${totalResult.duration.months} ${t.months} ${totalResult.duration.days} ${t.days} · ${t.totalDays}: ${totalResult.totalDays.toLocaleString()} ${t.days}`:`${t.period}: ${mainResult.duration.years} ${t.years} ${mainResult.duration.months} ${t.months} ${mainResult.duration.days} ${t.days} · ${t.totalDays}: ${mainResult.totalDays.toLocaleString()} ${t.days}`;await navigator.clipboard.writeText(text);setStatus(t.copied)}
 const shown=rows.length&&totalResult?totalResult:mainResult;
 return <div className={styles.root} data-testid="tool049-root"><div className={styles.localNotice}><strong>LOCAL</strong><span>{t.local}</span></div><section className={styles.workspace} data-testid="tool049-workspace"><div className={styles.workspaceHead}><div><span>{t.eyebrow}</span><h2>{t.title}</h2></div><button type="button" className={styles.button} onClick={reset} data-testid="tool049-reset">{t.reset}</button></div><div className={styles.dateGrid}><label className={styles.field}><span>{t.start}</span><input type="date" min="0001-01-01" max="9999-12-31" value={start} onChange={e=>{setStart(e.target.value);setSubmitted(false)}} data-testid="tool049-start"/></label>{current?<label className={styles.field}><span>{t.asof}</span><div className={styles.dateWithAction}><input type="date" min="0001-01-01" max="9999-12-31" value={asOf} onChange={e=>{setAsOf(e.target.value);setSubmitted(false)}} data-testid="tool049-asof"/><button type="button" className={styles.smallButton} onClick={()=>{setAsOf(todayIso());setSubmitted(false)}} data-testid="tool049-today">{t.today}</button></div></label>:<label className={styles.field}><span>{t.end}</span><input type="date" min="0001-01-01" max="9999-12-31" value={end} onChange={e=>{setEnd(e.target.value);setSubmitted(false)}} data-testid="tool049-end"/></label>}</div><label className={styles.toggleCard}><input type="checkbox" checked={current} onChange={e=>toggleCurrent(e.target.checked)} data-testid="tool049-current"/><span><strong>{t.current}</strong><small>{t.currentHelp}</small></span></label><div className={styles.actionRow}><button type="button" className={styles.secondaryButton} onClick={addRow} data-testid="tool049-add-row">{t.add}</button><button type="button" className={styles.primaryButton} onClick={run} data-testid="tool049-calculate">{t.calculate}</button></div>{error&&<p className={styles.error} role="alert" aria-live="polite" data-testid="tool049-error">{error}</p>}</section>
 {rows.length>0&&<section className={styles.careers} data-testid="tool049-careers"><div className={styles.sectionHead}><div><span>MULTI CAREER</span><h3>{t.rows}</h3></div><p>{t.rowsHelp}</p></div>{rows.map((r,i)=><article key={r.id} className={styles.careerCard} data-testid={`tool049-row-${i+1}`}><div className={styles.careerHead}><strong>{t.career} {i+2}</strong><button type="button" className={styles.linkButton} onClick={()=>{setRows(rows.filter(x=>x.id!==r.id));setSubmitted(false)}} data-testid={`tool049-remove-${i+1}`}>{t.remove}</button></div><div className={styles.dateGrid}><label className={styles.field}><span>{t.start}</span><input type="date" value={r.start} onChange={e=>updateRow(r.id,"start",e.target.value)} data-testid={`tool049-row-start-${i+1}`}/></label><label className={styles.field}><span>{t.end}</span><input type="date" value={r.end} onChange={e=>updateRow(r.id,"end",e.target.value)} data-testid={`tool049-row-end-${i+1}`}/></label></div>{submitted&&rowResults[i]&&<p className={styles.rowResult} data-testid={`tool049-row-result-${i+1}`}>{rowResults[i]!.duration.years} {t.years} · {rowResults[i]!.duration.months} {t.months} · {rowResults[i]!.duration.days} {t.days}</p>}</article>)}</section>}
 {!shown?<div className={styles.emptyResult} data-testid="tool049-empty-result"><span>RESULT</span><p>{t.empty}</p></div>:<section className={styles.results} aria-live="polite" data-testid="tool049-result"><div className={styles.primaryCard}><span>{rows.length?t.total:t.period}</span><strong data-testid="tool049-duration">{shown.duration.years} {t.years} · {shown.duration.months} {t.months} · {shown.duration.days} {t.days}</strong></div><div className={styles.totalDaysCard}><span>{t.totalDays}</span><strong data-testid="tool049-total-days">{shown.totalDays.toLocaleString()}</strong><em>{t.days}</em></div><div className={styles.resultActions}><button type="button" className={styles.button} onClick={copyResult} data-testid="tool049-copy">{t.copy}</button></div>{status&&<p className={styles.status} role="status" data-testid="tool049-status">{status}</p>}<span className={styles.srOnly}>{t.live}</span></section>}</div>
}
