"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import type { Locale } from "@/lib/site";
import { loadBrowserImage } from "@/lib/mobile-image-loader";
import { openFilePicker } from "@/lib/file-picker";

type InputFormat="jpg"|"png"|"webp";
type OutputFormat="original"|"jpg"|"png"|"webp";
type CanvasMode="original"|"padding"|"square"|"ratio"|"custom";
type BackgroundMode="solid"|"transparent"|"blur";
type Align="center"|"top"|"bottom"|"left"|"right"|"top-left"|"top-right"|"bottom-left"|"bottom-right";
type State={mode:CanvasMode,padding:{top:number,bottom:number,left:number,right:number},linked:boolean,ratioW:number,ratioH:number,customW:number,customH:number,bg:BackgroundMode,color:string,blur:number,brightness:number,bgPosX:number,bgPosY:number,scale:number,align:Align,posX:number,posY:number};

type Loaded={file:File,img:CanvasImageSource,close:()=>void,width:number,height:number,format:InputFormat,hasAlpha:boolean};
const HISTORY_MAX=60;
const INITIAL:State={mode:"original",padding:{top:0,bottom:0,left:0,right:0},linked:true,ratioW:1,ratioH:1,customW:1200,customH:1200,bg:"solid",color:"#ffffff",blur:22,brightness:88,bgPosX:0,bgPosY:0,scale:100,align:"center",posX:0,posY:0};
const copy={
ko:{workspace:"이미지 여백·배경 작업장",drop:"이미지를 여기에 놓거나 선택하세요",select:"이미지 선택",support:"JPG, PNG, WebP · 한 번에 한 장",local:"이미지는 서버로 전송되지 않으며 현재 브라우저에서만 처리됩니다.",chosen:"선택한 이미지",replace:"이미지 교체",canvas:"캔버스",original:"원본 크기",padding:"여백 추가",square:"정사각형 맞춤",ratio:"비율 맞춤",custom:"사용자 지정 크기",all:"전체 여백",link:"값 연결",separate:"값 개별 설정",top:"위",bottom:"아래",left:"왼쪽",right:"오른쪽",background:"배경",solid:"단색 배경",transparent:"투명 배경",blur:"블러 배경",color:"배경색",blurStrength:"블러 강도",brightness:"배경 밝기",image:"이미지",imageSize:"이미지 크기",position:"이미지 위치",center:"가운데",resetPos:"위치 초기화",view:"보기",viewOriginal:"원본 보기",viewResult:"결과 보기",zoomOut:"축소",zoomIn:"확대",fit:"화면 맞춤",undo:"실행 취소",redo:"다시 실행",output:"출력",format:"출력 형식",quality:"출력 품질",filename:"파일명",download:"이미지 다운로드",again:"다시 다운로드",resetSettings:"모든 설정 초기화",resetAll:"전체 초기화",result:"결과 정보",originalSize:"원본 크기",resultSize:"결과 크기",resultRatio:"결과 비율",notCropped:"원본 전체가 잘리지 않고 표시됩니다.",jpgNote:"JPG는 투명 배경을 저장할 수 없어 선택한 배경색으로 합성됩니다.",checking:"이미지 확인 중",ready:"다운로드 준비 완료",failed:"실패",unsupported:"지원하지 않는 이미지 형식입니다.",empty:"빈 파일은 사용할 수 없습니다.",unreadable:"이미지를 읽을 수 없습니다.",invalid:"올바른 값을 입력해 주세요.",tooLarge:"결과 이미지는 한 변 16,384px 또는 총 100,000,000px를 초과할 수 없습니다.",complete:"완료"},
en:{workspace:"Image padding & background workspace",drop:"Drop an image here or choose a file",select:"Select Image",support:"JPG, PNG, WebP · one image at a time",local:"Your image is processed only in this browser and is not uploaded to a server.",chosen:"Selected image",replace:"Replace Image",canvas:"Canvas",original:"Original Size",padding:"Add Padding",square:"Make Square",ratio:"Fit Aspect Ratio",custom:"Custom Size",all:"All Sides",link:"Link Values",separate:"Set Separately",top:"Top",bottom:"Bottom",left:"Left",right:"Right",background:"Background",solid:"Solid Background",transparent:"Transparent Background",blur:"Blurred Background",color:"Background Color",blurStrength:"Blur Strength",brightness:"Background Brightness",image:"Image",imageSize:"Image Size",position:"Image Position",center:"Center",resetPos:"Reset Position",view:"View",viewOriginal:"View Original",viewResult:"View Result",zoomOut:"Zoom Out",zoomIn:"Zoom In",fit:"Fit to Screen",undo:"Undo",redo:"Redo",output:"Output",format:"Output Format",quality:"Output Quality",filename:"File Name",download:"Download Image",again:"Download Again",resetSettings:"Reset All Settings",resetAll:"Reset All",result:"Result information",originalSize:"Original Size",resultSize:"Result Size",resultRatio:"Result Ratio",notCropped:"The entire foreground image is shown and not cropped.",jpgNote:"JPG cannot preserve transparency, so the selected background color will be composited.",checking:"Checking Image",ready:"Ready to Download",failed:"Failed",unsupported:"This image format is not supported.",empty:"Empty files cannot be used.",unreadable:"The image could not be read.",invalid:"Enter a valid value.",tooLarge:"The result cannot exceed 16,384px on either side or 100,000,000 total pixels.",complete:"Complete"},
ja:{workspace:"画像余白・背景ワークスペース",drop:"画像をここにドロップするか選択してください",select:"画像を選択",support:"JPG・PNG・WebP · 1枚ずつ処理",local:"画像はサーバーに送信されず、現在のブラウザ内だけで処理されます。",chosen:"選択した画像",replace:"画像を変更",canvas:"キャンバス",original:"元のサイズ",padding:"余白を追加",square:"正方形に合わせる",ratio:"比率に合わせる",custom:"サイズを指定",all:"全体の余白",link:"値を連動",separate:"個別に設定",top:"上",bottom:"下",left:"左",right:"右",background:"背景",solid:"単色背景",transparent:"透明背景",blur:"ぼかし背景",color:"背景色",blurStrength:"ぼかしの強さ",brightness:"背景の明るさ",image:"画像",imageSize:"画像サイズ",position:"画像位置",center:"中央",resetPos:"位置をリセット",view:"表示",viewOriginal:"元画像を表示",viewResult:"結果を表示",zoomOut:"縮小",zoomIn:"拡大",fit:"画面に合わせる",undo:"元に戻す",redo:"やり直す",output:"出力",format:"出力形式",quality:"出力画質",filename:"ファイル名",download:"画像をダウンロード",again:"もう一度ダウンロード",resetSettings:"すべての設定をリセット",resetAll:"すべて初期化",result:"結果情報",originalSize:"元画像サイズ",resultSize:"結果サイズ",resultRatio:"結果の比率",notCropped:"前面の元画像は切り取られず全体が表示されます。",jpgNote:"JPGは透明背景を保存できないため、選択した背景色で合成されます。",checking:"画像を確認中",ready:"ダウンロードの準備完了",failed:"失敗",unsupported:"対応していない画像形式です。",empty:"空のファイルは使用できません。",unreadable:"画像を読み込めませんでした。",invalid:"正しい値を入力してください。",tooLarge:"結果画像は一辺16,384pxまたは合計100,000,000ピクセルを超えることはできません。",complete:"完了"}
} as const;

function fmtBytes(n:number){return n<1024?`${n} B`:n<1048576?`${(n/1024).toFixed(1)} KB`:`${(n/1048576).toFixed(2)} MB`;}
function safeName(v:string){return (v.trim()||"image-padded").replace(/[\\/:*?"<>|]+/g,"-").replace(/\s+/g,"-").slice(0,120)}
function formatOf(file:File):InputFormat|null{const e=file.name.toLowerCase().split('.').pop();if((file.type==='image/jpeg'||file.type==='image/jpg')&&(e==='jpg'||e==='jpeg'))return'jpg';if(file.type==='image/png'&&e==='png')return'png';if(file.type==='image/webp'&&e==='webp')return'webp';return null}
async function signatureOk(file:File,f:InputFormat){const b=new Uint8Array(await file.slice(0,16).arrayBuffer());if(f==='jpg')return b[0]===255&&b[1]===216&&b[2]===255;if(f==='png')return b[0]===137&&b[1]===80&&b[2]===78&&b[3]===71;return String.fromCharCode(...b.slice(0,4))==='RIFF'&&String.fromCharCode(...b.slice(8,12))==='WEBP'}
function gcd(a:number,b:number){while(b){[a,b]=[b,a%b]}return a||1}
function normalizedRatio(w:number,h:number){const g=gcd(Math.round(w),Math.round(h));return `${Math.round(w/g)}:${Math.round(h/g)}`}

export function ImagePaddingBackgroundTool({locale}:{locale:Locale}){
 const t=copy[locale]; const input=useRef<HTMLInputElement>(null); const canvas=useRef<HTMLCanvasElement>(null); const wrap=useRef<HTMLDivElement>(null); const drag=useRef<{id:number,x:number,y:number,startX:number,startY:number,original:State}|null>(null);
 const [loaded,setLoaded]=useState<Loaded|null>(null); const [history,setHistory]=useState<State[]>([INITIAL]); const [index,setIndex]=useState(0); const state=history[index];
 const [zoom,setZoom]=useState(1); const [showOriginal,setShowOriginal]=useState(false); const [status,setStatus]=useState(''); const [error,setError]=useState(''); const [resultBytes,setResultBytes]=useState<number|null>(null); const [filename,setFilename]=useState('image-padded'); const [format,setFormat]=useState<OutputFormat>('original'); const [quality,setQuality]=useState(92); const [jpgColor,setJpgColor]=useState('#ffffff');
 const commit=useCallback((next:State)=>{setHistory(prev=>{const base=prev.slice(0,index+1);const out=[...base,next];return out.slice(Math.max(0,out.length-HISTORY_MAX))});setIndex(prev=>Math.min(prev+1,HISTORY_MAX-1));setResultBytes(null)},[index]);
 const mutate=(patch:Partial<State>)=>commit({...state,...patch});
 const modeSize=useMemo(()=>{if(!loaded)return{width:0,height:0};const w=loaded.width,h=loaded.height;if(state.mode==='original')return{width:w,height:h};if(state.mode==='padding')return{width:w+state.padding.left+state.padding.right,height:h+state.padding.top+state.padding.bottom};if(state.mode==='square'){const side=Math.max(w,h);return{width:side,height:side}}if(state.mode==='custom')return{width:Math.max(1,Math.round(state.customW)),height:Math.max(1,Math.round(state.customH))};const rw=Math.max(1,state.ratioW),rh=Math.max(1,state.ratioH),target=rw/rh,source=w/h;if(source>target)return{width:w,height:Math.max(1,Math.round(w/target))};return{width:Math.max(1,Math.round(h*target)),height:h}},[loaded,state]);
 const provisionalTooLarge=modeSize.width>16384||modeSize.height>16384||modeSize.width*modeSize.height>100_000_000;
 const placement=useMemo(()=>{if(!loaded||!modeSize.width||!modeSize.height)return{x:0,y:0,w:0,h:0};let base=Math.min(1,modeSize.width/loaded.width,modeSize.height/loaded.height);base*=Math.min(1,Math.max(.1,state.scale/100));const w=loaded.width*base,h=loaded.height*base;let x=(modeSize.width-w)/2,y=(modeSize.height-h)/2;if(state.mode==='padding'&&state.scale===100&&state.align==='center'&&state.posX===0&&state.posY===0){x=state.padding.left;y=state.padding.top}else{const map:{[K in Align]:[number,number]}={center:[.5,.5],top:[.5,0],bottom:[.5,1],left:[0,.5],right:[1,.5],'top-left':[0,0],'top-right':[1,0],'bottom-left':[0,1],'bottom-right':[1,1]};const [ax,ay]=map[state.align];x=(modeSize.width-w)*ax;y=(modeSize.height-h)*ay;x+=state.posX*(modeSize.width-w)/100;y+=state.posY*(modeSize.height-h)/100;x=Math.max(0,Math.min(modeSize.width-w,x));y=Math.max(0,Math.min(modeSize.height-h,y))}return{x,y,w,h}},[loaded,modeSize,state]);
 const resolvedFormat:InputFormat= format==='original'?(loaded?.format??'png'):format;
 const render=useCallback((ctx:CanvasRenderingContext2D,w:number,h:number,preview=false)=>{if(!loaded)return;ctx.clearRect(0,0,w,h);const sx=w/modeSize.width,sy=h/modeSize.height;if(showOriginal&&preview){ctx.drawImage(loaded.img,0,0,w,h);return}if(state.bg==='solid'){ctx.fillStyle=state.color;ctx.fillRect(0,0,w,h)} else if(state.bg==='blur'){ctx.save();ctx.filter=`blur(${Math.max(1,state.blur*Math.min(sx,sy))}px) brightness(${state.brightness}%)`;const cover=Math.max(w/loaded.width,h/loaded.height);const bw=loaded.width*cover,bh=loaded.height*cover;const bx=(w-bw)/2+(state.bgPosX/100)*Math.max(0,bw-w)/2;const by=(h-bh)/2+(state.bgPosY/100)*Math.max(0,bh-h)/2;ctx.drawImage(loaded.img,bx,by,bw,bh);ctx.restore()}ctx.drawImage(loaded.img,placement.x*sx,placement.y*sy,placement.w*sx,placement.h*sy)},[loaded,modeSize,placement,showOriginal,state.bg,state.blur,state.brightness,state.bgPosX,state.bgPosY,state.color]);
 useEffect(()=>{if(!loaded||!canvas.current||!wrap.current)return;const maxW=Math.min(760,Math.max(280,wrap.current.clientWidth-28)),maxH=560;const s=Math.min(maxW/modeSize.width,maxH/modeSize.height,1);const c=canvas.current;c.width=Math.max(1,Math.round(modeSize.width*s));c.height=Math.max(1,Math.round(modeSize.height*s));const ctx=c.getContext('2d');if(ctx)render(ctx,c.width,c.height,true)},[loaded,modeSize,render,state,showOriginal]);
 useEffect(()=>()=>{loaded?.close()},[loaded]);
 const load=async(file:File)=>{setError('');setStatus(t.checking);if(file.size===0){setError(t.empty);setStatus('');return}const f=formatOf(file);if(!f){setError(t.unsupported);setStatus('');return}if(!(await signatureOk(file,f))){setError(t.unreadable);setStatus('');return}try{const decoded=await loadBrowserImage(file,'from-image');const hasAlpha=f!=='jpg';loaded?.close();setLoaded({file,img:decoded.source,close:decoded.close,width:decoded.width,height:decoded.height,format:f,hasAlpha});const next={...INITIAL,customW:decoded.width,customH:decoded.height,bg:(hasAlpha?'transparent':'solid') as BackgroundMode};setHistory([next]);setIndex(0);setFilename(`${file.name.replace(/\.[^.]+$/,'')}-padded`);setFormat('original');setStatus(t.complete);setZoom(1);setShowOriginal(false);setResultBytes(null)}catch{setError(t.unreadable);setStatus('')}};
 const setMode=(mode:CanvasMode)=>mutate({mode,posX:0,posY:0,align:'center'});
 const setPad=(key:keyof State['padding'],raw:string)=>{if(raw==='')return;let n=Number(raw);if(!Number.isFinite(n))n=0;n=Math.max(0,Math.round(n));const padding=state.linked?{top:n,bottom:n,left:n,right:n}:{...state.padding,[key]:n};commit({...state,padding})};
 const chooseRatio=(w:number,h:number)=>commit({...state,mode:'ratio',ratioW:w,ratioH:h,posX:0,posY:0,align:'center'});
 const pointerDown=(e:React.PointerEvent<HTMLCanvasElement>)=>{if(!loaded||showOriginal)return;e.currentTarget.setPointerCapture(e.pointerId);drag.current={id:e.pointerId,x:e.clientX,y:e.clientY,startX:state.posX,startY:state.posY,original:structuredClone(state)}};
 const pointerMove=(e:React.PointerEvent<HTMLCanvasElement>)=>{if(!drag.current||drag.current.id!==e.pointerId||!canvas.current)return;const dx=(e.clientX-drag.current.x)/Math.max(1,canvas.current.clientWidth)*100,dy=(e.clientY-drag.current.y)/Math.max(1,canvas.current.clientHeight)*100;setHistory(prev=>prev.map((s,i)=>i===index?{...s,posX:Math.max(-50,Math.min(50,drag.current!.startX+dx)),posY:Math.max(-50,Math.min(50,drag.current!.startY+dy)),align:'center'}:s))};
 const pointerUp=(e:React.PointerEvent<HTMLCanvasElement>)=>{if(e.currentTarget.hasPointerCapture(e.pointerId))e.currentTarget.releasePointerCapture(e.pointerId);const d=drag.current;if(d){const final=state;setHistory(prev=>{const out=[...prev.slice(0,index),d.original,final];return out.slice(Math.max(0,out.length-HISTORY_MAX))});setIndex(i=>Math.min(i+1,HISTORY_MAX-1));}drag.current=null;setResultBytes(null)};
 const resetSettings=()=>{const next={...INITIAL,customW:loaded?.width??1200,customH:loaded?.height??1200,bg:(loaded?.hasAlpha?'transparent':'solid') as BackgroundMode};commit(next)};
 const resetAll=()=>{loaded?.close();setLoaded(null);setHistory([INITIAL]);setIndex(0);setError('');setStatus('');setResultBytes(null);setFormat('original');setFilename('image-padded')};
 const download=async()=>{if(!loaded||provisionalTooLarge)return;setStatus(locale==='ko'?'결과 생성 중':locale==='en'?'Creating Result':'結果を作成中');setError('');try{const out=document.createElement('canvas');out.width=modeSize.width;out.height=modeSize.height;const ctx=out.getContext('2d');if(!ctx)throw new Error();const was=showOriginal;if(was)setShowOriginal(false);if(resolvedFormat==='jpg'&&state.bg==='transparent'){ctx.fillStyle=jpgColor;ctx.fillRect(0,0,out.width,out.height);const sx=out.width/modeSize.width,sy=out.height/modeSize.height;ctx.drawImage(loaded.img,placement.x*sx,placement.y*sy,placement.w*sx,placement.h*sy)}else render(ctx,out.width,out.height,false);const mime=resolvedFormat==='png'?'image/png':resolvedFormat==='webp'?'image/webp':'image/jpeg';const blob=await new Promise<Blob|null>(r=>out.toBlob(r,mime,resolvedFormat==='png'?undefined:quality/100));if(!blob)throw new Error();const href=URL.createObjectURL(blob);const a=document.createElement('a');a.href=href;a.download=`${safeName(filename)}.${resolvedFormat}`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(href),0);setResultBytes(blob.size);setStatus(t.ready)}catch{setError(t.unreadable);setStatus(t.failed)}};
 if(!loaded)return <div className="toolbox-tool-workflow" data-testid="tool011-root"><section className="toolbox-workbench"><div className="toolbox-workbench-upload" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();const f=e.dataTransfer.files[0];if(f)void load(f)}}><div className="toolbox-workbench-topline"><div><span>WORKSPACE</span><strong>{t.workspace}</strong></div></div><div className="toolbox-upload-focus"><span className="toolbox-upload-icon" aria-hidden="true">＋</span><h2>{t.drop}</h2><p>{t.local}</p><button className="toolbox-primary-action" type="button" onClick={()=>openFilePicker(input.current)}>{t.select}</button><small>{t.support}</small></div><input data-testid="tool011-file" ref={input} className="hidden" type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>{const f=e.target.files?.[0];if(f)void load(f);e.target.value=''}}/></div>{error&&<p className="mosaic-error" role="alert" data-testid="tool011-error">{error}</p>}</section></div>;
 const ratio=normalizedRatio(modeSize.width,modeSize.height);
 return <div className="toolbox-tool-workflow" data-testid="tool011-root"><section className="toolbox-workbench padding-workbench" data-testid="tool011-editor"><div className="toolbox-workbench-upload is-active-workspace"><div className="toolbox-workbench-topline"><div><span>WORKSPACE</span><strong>{t.workspace}</strong></div></div><div className="toolbox-upload-active"><div className="toolbox-upload-active-head"><div><span>{t.chosen}</span><p>{t.local}</p></div><div className="toolbox-upload-active-actions"><div className="toolbox-file-stats"><span data-testid="tool011-original-size">{loaded.width} × {loaded.height}px</span><span>{fmtBytes(loaded.file.size)}</span><span>{loaded.format.toUpperCase()}</span></div><button type="button" onClick={()=>openFilePicker(input.current)}>＋ {t.replace}</button></div></div><div className="toolbox-upload-selected-file"><strong title={loaded.file.name}>{loaded.file.name}</strong><span>{status}</span></div><input data-testid="tool011-file" ref={input} className="hidden" type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>{const f=e.target.files?.[0];if(f)void load(f);e.target.value=''}}/></div></div>
 <div className="padding-editor-grid toolbox-workbench-editor-grid"><section className="padding-canvas-card toolbox-workbench-preview-card"><div className="padding-toolbar"><button data-testid="tool011-undo" disabled={index===0} onClick={()=>setIndex(i=>Math.max(0,i-1))}>{t.undo}</button><button data-testid="tool011-redo" disabled={index===history.length-1} onClick={()=>setIndex(i=>Math.min(history.length-1,i+1))}>{t.redo}</button><span/><button className={showOriginal?'is-active':''} onClick={()=>setShowOriginal(true)}>{t.viewOriginal}</button><button className={!showOriginal?'is-active':''} onClick={()=>setShowOriginal(false)}>{t.viewResult}</button></div><div ref={wrap} className={`padding-canvas-wrap ${state.bg==='transparent'?'is-transparent':''}`} data-testid="tool011-canvas-wrap"><canvas data-testid="tool011-canvas" ref={canvas} style={{transform:`scale(${zoom})`,touchAction:'none',cursor:'move'}} onPointerDown={pointerDown} onPointerMove={pointerMove} onPointerUp={pointerUp} onPointerCancel={pointerUp}/></div><div className="padding-viewbar"><button onClick={()=>setZoom(v=>Math.max(.5,v-.25))} aria-label={t.zoomOut}>−</button><strong>{Math.round(zoom*100)}%</strong><button onClick={()=>setZoom(v=>Math.min(2,v+.25))} aria-label={t.zoomIn}>＋</button><button onClick={()=>setZoom(1)}>{t.fit}</button><button onClick={()=>setZoom(1)}>{locale==='ko'?'100% 보기':locale==='en'?'View at 100%':'100%表示'}</button></div><p className="padding-crop-state" data-testid="tool011-crop-state">{t.notCropped}</p></section>
 <aside className="padding-panel toolbox-workbench-settings-card"><div className="padding-section"><div className="toolbox-workbench-settings-head"><div><span>{t.canvas}</span><p data-testid="tool011-result-size">{modeSize.width} × {modeSize.height}px</p></div></div><div className="padding-mode-grid">{([['original',t.original],['padding',t.padding],['square',t.square],['ratio',t.ratio],['custom',t.custom]] as const).map(([m,l])=><button data-testid={`tool011-mode-${m}`} className={state.mode===m?'is-active':''} aria-pressed={state.mode===m} key={m} onClick={()=>setMode(m)}>{l}</button>)}</div>{state.mode==='padding'&&<div className="padding-controls"><button data-testid="tool011-link-padding" className={state.linked?'is-active':''} onClick={()=>mutate({linked:!state.linked})}>{state.linked?t.link:t.separate}</button>{state.linked?<label>{t.all}<input data-testid="tool011-padding-all" inputMode="numeric" value={state.padding.top} onChange={e=>setPad('top',e.target.value)}/><span>px</span><input className="padding-inline-range" type="range" min="0" max="500" value={Math.min(500,state.padding.top)} onChange={e=>setPad('top',e.target.value)}/></label>:<div className="padding-four">{(['top','bottom','left','right'] as const).map(k=><label key={k}>{t[k]}<input data-testid={`tool011-padding-${k}`} inputMode="numeric" value={state.padding[k]} onChange={e=>setPad(k,e.target.value)}/><span>px</span></label>)}</div>}</div>}{state.mode==='ratio'&&<><div className="padding-ratios">{[[1,1],[4,5],[5,4],[3,2],[2,3],[16,9],[9,16]].map(([w,h])=><button key={`${w}-${h}`} data-testid={`tool011-ratio-${w}-${h}`} className={state.ratioW===w&&state.ratioH===h?'is-active':''} onClick={()=>chooseRatio(w,h)}>{w}:{h}</button>)}</div><div className="padding-two"><label>{locale==='ko'?'가로 비율':locale==='en'?'Width ratio':'横比率'}<input value={state.ratioW} onChange={e=>mutate({ratioW:Math.max(1,Math.round(Number(e.target.value)||1))})}/></label><label>{locale==='ko'?'세로 비율':locale==='en'?'Height ratio':'縦比率'}<input value={state.ratioH} onChange={e=>mutate({ratioH:Math.max(1,Math.round(Number(e.target.value)||1))})}/></label></div></>}{state.mode==='custom'&&<div className="padding-two"><label>{locale==='ko'?'결과 가로':locale==='en'?'Result width':'出力幅'}<input data-testid="tool011-custom-width" inputMode="numeric" value={state.customW} onChange={e=>mutate({customW:Math.max(1,Math.round(Number(e.target.value)||1))})}/><span>px</span></label><label>{locale==='ko'?'결과 세로':locale==='en'?'Result height':'出力高さ'}<input data-testid="tool011-custom-height" inputMode="numeric" value={state.customH} onChange={e=>mutate({customH:Math.max(1,Math.round(Number(e.target.value)||1))})}/><span>px</span></label></div>}</div>
 <div className="padding-section" data-testid="tool011-background-state" data-background={state.bg}><div className="toolbox-workbench-settings-head"><div><span>{t.background}</span><p>{state.bg}</p></div></div><div className="padding-segment">{([['solid',t.solid],['transparent',t.transparent],['blur',t.blur]] as const).map(([b,l])=><button data-testid={`tool011-bg-${b}`} key={b} className={state.bg===b?'is-active':''} onClick={()=>mutate({bg:b})}>{l}</button>)}</div>{state.bg==='solid'&&<div className="padding-color-row"><button onClick={()=>mutate({color:'#ffffff'})}>{locale==='ja'?'白':locale==='en'?'White':'흰색'}</button><button onClick={()=>mutate({color:'#000000'})}>{locale==='ja'?'黒':locale==='en'?'Black':'검정색'}</button><label>{t.color}<input type="color" value={state.color} onChange={e=>mutate({color:e.target.value})}/></label></div>}{state.bg==='blur'&&<><label className="padding-range">{t.blurStrength}<input data-testid="tool011-blur-strength" type="range" min="2" max="60" value={state.blur} onChange={e=>mutate({blur:+e.target.value})}/><span>{state.blur}</span></label><label className="padding-range">{t.brightness}<input type="range" min="50" max="120" value={state.brightness} onChange={e=>mutate({brightness:+e.target.value})}/><span>{state.brightness}%</span></label><label className="padding-range">{locale==='ko'?'배경 가로 위치':locale==='en'?'Background horizontal position':'背景の横位置'}<input type="range" min="-100" max="100" value={state.bgPosX} onChange={e=>mutate({bgPosX:+e.target.value})}/><span>{state.bgPosX}</span></label><label className="padding-range">{locale==='ko'?'배경 세로 위치':locale==='en'?'Background vertical position':'背景の縦位置'}<input type="range" min="-100" max="100" value={state.bgPosY} onChange={e=>mutate({bgPosY:+e.target.value})}/><span>{state.bgPosY}</span></label></>}</div>
 <div className="padding-section"><div className="toolbox-workbench-settings-head"><div><span>{t.image}</span><p>{t.notCropped}</p></div></div><label className="padding-range">{t.imageSize}<input data-testid="tool011-scale" type="range" min="25" max="100" value={state.scale} onChange={e=>mutate({scale:+e.target.value})}/><span>{state.scale}%</span></label><label className="padding-range">{locale==='ko'?'가로 위치':locale==='en'?'Horizontal position':'横位置'}<input data-testid="tool011-position-x" type="range" min="-50" max="50" value={state.posX} onChange={e=>mutate({posX:+e.target.value,align:'center'})}/><span>{Math.round(state.posX)}</span></label><label className="padding-range">{locale==='ko'?'세로 위치':locale==='en'?'Vertical position':'縦位置'}<input data-testid="tool011-position-y" type="range" min="-50" max="50" value={state.posY} onChange={e=>mutate({posY:+e.target.value,align:'center'})}/><span>{Math.round(state.posY)}</span></label><div className="padding-align-grid">{([['top-left','↖'],['top','↑'],['top-right','↗'],['left','←'],['center','•'],['right','→'],['bottom-left','↙'],['bottom','↓'],['bottom-right','↘']] as const).map(([a,l])=><button key={a} data-testid={`tool011-align-${a}`} className={state.align===a?'is-active':''} aria-label={a} onClick={()=>mutate({align:a,posX:0,posY:0})}>{l}</button>)}</div><button onClick={()=>mutate({align:'center',posX:0,posY:0})}>{t.resetPos}</button></div></aside></div>
 <div className="padding-output-card adjuster-output-card"><div className="toolbox-workbench-settings-head adjuster-output-head"><div><span>{t.output}</span><p>{modeSize.width} × {modeSize.height}px · {ratio}</p></div></div><section className="toolbox-workbench-actions adjuster-output padding-output-controls"><div><label>{t.format}<select data-testid="tool011-output-format" value={format} onChange={e=>{setFormat(e.target.value as OutputFormat);setResultBytes(null)}}><option value="original">{locale==='ko'?'원본 형식 유지':locale==='en'?'Keep original format':'元の形式を維持'}</option><option value="jpg">JPG</option><option value="png">PNG</option><option value="webp">WebP</option></select></label><label>{t.quality}<input type="range" min="40" max="100" disabled={resolvedFormat==='png'} value={quality} onChange={e=>setQuality(+e.target.value)}/><span>{resolvedFormat==='png'?'—':`${quality}%`}</span></label><label>{t.filename}<input value={filename} onChange={e=>setFilename(e.target.value)} onBlur={()=>setFilename(safeName(filename))}/></label>{resolvedFormat==='jpg'&&state.bg==='transparent'&&<label data-testid="tool011-jpg-transparency-note">{t.jpgNote}<input type="color" value={jpgColor} onChange={e=>setJpgColor(e.target.value)}/></label>}</div><div><button className="toolbox-primary-action" data-testid="tool011-download" disabled={provisionalTooLarge} onClick={download}>{resultBytes!==null?t.again:t.download}</button><button onClick={resetSettings}>{t.resetSettings}</button><button onClick={resetAll}>{t.resetAll}</button></div></section><section className="toolbox-workbench-result-card padding-result" data-testid="tool011-result"><strong>{t.result}</strong><span>{t.originalSize}: {loaded.width} × {loaded.height}px</span><span>{t.resultSize}: {modeSize.width} × {modeSize.height}px</span><span>{t.resultRatio}: {ratio}</span><span>{resolvedFormat.toUpperCase()}</span>{resultBytes!==null&&<span>{fmtBytes(resultBytes)}</span>}</section>{provisionalTooLarge&&<p className="padding-limit-warning" data-testid="tool011-limit-warning">{t.tooLarge}</p>}<p className="adjuster-status" id="tool011-status" data-testid="tool011-status" aria-live="polite">{status}</p>{error&&<p className="mosaic-error" role="alert" data-testid="tool011-error">{error}</p>}</div></section></div>
}
