import { ToolNavigation } from "@/components/tool-navigation";
import Link from "next/link";
import { ImageCollageMakerTool } from "@/components/image-collage-maker-tool";
import { ToolboxFaqList } from "@/components/toolbox-faq-list";
import { ToolboxSubpageShell } from "@/components/toolbox-subpage-shell";
import type { Locale } from "@/lib/site";

const copy={
 ko:{back:"이미지 편집",title:"이미지 콜라주 만들기",desc:"여러 사진을 2·3·4분할과 격자 레이아웃으로 배치해 한 장의 콜라주로 만드세요.",steps:["이미지 여러 장을 선택합니다.","2·3·4분할 또는 격자 레이아웃을 선택합니다.","필요하면 이미지 목록 순서를 바꾸거나 셀에 다른 이미지를 배치합니다.","셀을 선택해 채우기·전체 보기와 사진 확대를 조절합니다.","미리보기에서 사진을 드래그해 보이는 위치를 맞춥니다.","결과 비율과 픽셀 크기를 확인합니다.","이미지 간격과 외곽 여백을 조절합니다.","테두리와 배경색 또는 투명 배경을 설정합니다.","PNG·JPG·WebP 중 출력 형식을 선택합니다.","다운로드해 한 장의 콜라주 이미지로 저장합니다."],faqs:[["몇 장까지 넣을 수 있나요?","기본 서비스에서는 최대 12장을 선택할 수 있으며, 레이아웃은 최대 3×3의 9셀까지 제공합니다."],["사진이 셀에 맞지 않으면 찌그러지나요?","아니요. 원본 비율을 유지한 채 채우기 또는 전체 보기 방식으로 배치합니다."],["사진에서 보이는 위치를 바꿀 수 있나요?","예. 셀을 선택한 뒤 미리보기에서 사진을 드래그해 위치를 조절할 수 있습니다."],["레이아웃을 바꾸면 사진이 삭제되나요?","아니요. 업로드한 파일은 유지되고 가능한 셀 연결도 유지합니다. 셀보다 많은 이미지는 대기 목록에 남습니다."],["빈 셀도 만들 수 있나요?","예. 이미지 수가 셀보다 적거나 셀의 이미지를 비우면 출력에서는 배경색 또는 투명 영역으로 남습니다."],["투명 배경을 지원하나요?","PNG와 WebP는 투명 배경을 사용할 수 있습니다. JPG는 투명도를 지원하지 않아 흰 배경으로 합성됩니다."],["결과 크기 제한은 어떻게 되나요?","일반 사용자 안정성을 위해 결과는 한 변 최대 3000px, 총 900만 픽셀까지 지원합니다."],["큰 원본 사진도 사용할 수 있나요?","개별 파일 15MiB, 총 80MiB, 원본 24MP까지 기본 서비스 범위로 지원합니다."],["모바일에서도 사용할 수 있나요?","예. 모바일에서도 레이아웃 선택, 셀 선택, 확대 슬라이더와 사진 위치 이동을 사용할 수 있습니다."],["이미지가 서버로 전송되나요?","아니요. 이미지는 현재 브라우저에서 로컬로 처리됩니다."]],more:"FAQ 더보기",collapse:"FAQ 접기"},
 en:{back:"Image Edit",title:"Image Collage Maker",desc:"Arrange multiple photos in 2-, 3-, 4-split and grid layouts to create one collage image.",steps:["Select multiple images.","Choose a 2-, 3-, 4-split or grid layout.","Reorder the image list or assign another image to a cell when needed.","Select a cell and choose Fill or Fit Whole Image, then adjust photo zoom.","Drag the photo in the preview to adjust its visible position.","Check the output ratio and pixel dimensions.","Adjust image gap and outer padding.","Set cell borders and a solid or transparent background.","Choose PNG, JPG, or WebP output.","Download the finished collage as one image."],faqs:[["How many images can I add?","The basic service accepts up to 12 selected images and layouts up to a 3×3 grid with 9 cells."],["Will photos be stretched to fit cells?","No. Original aspect ratio is preserved with Fill or Fit Whole Image modes."],["Can I reposition a photo inside a cell?","Yes. Select a cell and drag the photo in the preview."],["Are photos deleted when I change layouts?","No. Uploaded files remain available and excess images stay in the waiting list."],["Can a collage contain empty cells?","Yes. Empty cells render as the selected background or transparency."],["Is transparency supported?","PNG and WebP can preserve transparency. JPG is composited on white when transparency is selected."],["What is the output-size limit?","For stable general use, output is limited to 3000 px per side and 9 million total pixels."],["What source-image limits apply?","The basic service supports up to 15 MiB per file, 80 MiB total, and 24 MP per source image."],["Does it work on mobile?","Yes. Layout selection, cell selection, zoom control, and photo positioning work on mobile."],["Are images uploaded to a server?","No. Processing stays in your current browser."]],more:"Show more FAQs",collapse:"Collapse FAQs"},
 ja:{back:"画像編集",title:"画像コラージュ作成ツール",desc:"複数の写真を2・3・4分割やグリッドレイアウトに配置し、1枚のコラージュ画像を作成します。",steps:["画像を複数選択します。","2・3・4分割またはグリッドレイアウトを選択します。","必要に応じて画像一覧の順番を変更したり、セルに別の画像を割り当てます。","セルを選択し、塗りつぶす・全体表示と画像の拡大率を調整します。","プレビュー内で画像をドラッグして表示位置を調整します。","出力比率とピクセルサイズを確認します。","画像間隔と外側余白を調整します。","枠線と背景色、または透明背景を設定します。","PNG・JPG・WebPから出力形式を選択します。","ダウンロードして1枚のコラージュ画像として保存します。"],faqs:[["画像は何枚まで追加できますか？","基本サービスでは最大12枚を選択でき、レイアウトは最大3×3の9セルまで対応します。"],["セルに合わせると画像が変形しますか？","いいえ。元の縦横比を維持し、塗りつぶすまたは全体表示で配置します。"],["セル内の画像位置を変更できますか？","はい。セルを選択してプレビュー上の画像をドラッグできます。"],["レイアウト変更で画像は削除されますか？","いいえ。アップロード済み画像は維持され、セル数を超えた画像は待機一覧に残ります。"],["空のセルも使えますか？","はい。空のセルは出力時に選択した背景色または透明領域になります。"],["透明背景に対応していますか？","PNGとWebPは透明背景に対応します。JPGでは透明部分を白で合成します。"],["出力サイズの上限は？","一般利用の安定性を優先し、一辺3000px、合計900万画素まで対応します。"],["大きな元画像も使えますか？","基本サービスでは1ファイル15MiB、合計80MiB、元画像24MPまで対応します。"],["モバイルでも使えますか？","はい。レイアウト選択、セル選択、拡大スライダー、画像位置調整が利用できます。"],["画像はサーバーへ送信されますか？","いいえ。現在のブラウザ内でローカル処理されます。"]],more:"FAQをもっと見る",collapse:"FAQを閉じる"}
} as const;

export function ImageCollageMakerPage({locale}:{locale:Locale}){
 const t=copy[locale];
 const nextTitle=locale==="ko"?"다음 작업":locale==="en"?"Next steps":"次の作業";
 const ready=locale==="ko"?"사용 가능":locale==="en"?"Available":"利用可能";
 const soon=locale==="ko"?"준비 중":locale==="en"?"Coming soon":"準備中";
 const nextCards=[
  {n:"015",name:locale==="ko"?"전후 비교 이미지 만들기":locale==="en"?"Before & After Image Maker":"ビフォー・アフター画像作成",href:null},
  {n:"016",name:locale==="ko"?"이미지에 글자 넣기":locale==="en"?"Add Text to Image":"画像に文字を追加",href:null},
  {n:"013",name:locale==="ko"?"이미지 합치기":locale==="en"?"Image Merger":"画像結合ツール",href:`/${locale}/image-merger`}
 ];
 const jsonLd={"@context":"https://schema.org","@graph":[{"@type":"WebApplication",name:t.title,applicationCategory:"MultimediaApplication",operatingSystem:"Any",url:`https://toolbox.fixlgs.com/${locale}/image-collage-maker`,description:t.desc,offers:{"@type":"Offer",price:"0",priceCurrency:"USD"}},{"@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:"TOOLBOX",item:`https://toolbox.fixlgs.com/${locale}`},{"@type":"ListItem",position:2,name:t.back,item:`https://toolbox.fixlgs.com/${locale}/category/image-edit`},{"@type":"ListItem",position:3,name:t.title,item:`https://toolbox.fixlgs.com/${locale}/image-collage-maker`}]},{"@type":"FAQPage",mainEntity:t.faqs.map(([q,a])=>({"@type":"Question",name:q,acceptedAnswer:{"@type":"Answer",text:a}}))}]};
 return <ToolboxSubpageShell locale={locale} appName={t.title}>
  <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(jsonLd)}}/>
  <section className="toolbox-tool-detail-hero tool014-detail-hero"><Link className="toolbox-subpage-back" href={`/${locale}/category/image-edit`}>← {t.back}</Link><p className="toolbox-subpage-eyebrow">014 · IMAGE EDIT</p><div className="toolbox-tool-detail-heading"><h1>{t.title}</h1><p>{t.desc}</p></div><div className="toolbox-tool-detail-badge"><strong>LOCAL</strong><span>{locale==="ko"?"브라우저에서 바로 처리":locale==="en"?"PROCESS IN YOUR BROWSER":"ブラウザ内で処理"}</span></div></section>
  <section className="toolbox-tool-detail-body"><div><ImageCollageMakerTool locale={locale}/><ToolNavigation locale={locale} currentTool={14} /></div></section>
  <section className="toolbox-tool-guide tool014-how-to tool013-how-to-grid"><div className="toolbox-tool-guide-head"><p>HOW TO USE</p><h2>{locale==="ko"?"사용 방법":locale==="en"?"How to use":"使い方"}</h2></div><ol>{t.steps.map((s,i)=><li key={s}><span>{String(i+1).padStart(2,"0")}</span><p>{s}</p></li>)}</ol></section>
  <section className="toolbox-tool-format-guide toolbox-tool-expert-post tool014-format-guide">
   <div className="toolbox-tool-format-guide-head"><p>COLLAGE GUIDE</p><h2>{locale==="ko"?"사진을 자연스럽고 깨끗하게 배치하는 콜라주 실무 기준":locale==="en"?"Practical standards for clean, balanced photo collages":"写真を自然できれいに配置するコラージュの実務基準"}</h2><span>{locale==="ko"?"콜라주는 사진을 칸에 넣는 것보다 레이아웃 비율, 이미지 맞춤, 시선 중심, 간격, 배경과 최종 출력 크기를 함께 맞추는 것이 중요합니다.":locale==="en"?"A good collage is not just about placing photos in cells. Balance layout ratio, image fit, visual focus, spacing, background, and final output size together.":"コラージュは画像をセルに入れるだけではなく、レイアウト比率、画像の合わせ方、視線の中心、間隔、背景、最終出力サイズをまとめて調整することが重要です。"}</span></div>
   <div className="toolbox-tool-format-body">
    <div className="toolbox-tool-format-grid">
     {(locale==="ko"?[["2·3·4분할","사진 수가 적은 콜라주","사진마다 충분한 면적을 확보하기 쉬워 인물·상품·전후 장면처럼 각 사진을 또렷하게 보여줄 때 적합합니다.","사진 수와 셀 수를 먼저 맞추면 빈 셀과 대기 이미지가 줄어듭니다."],["격자형","여러 사진을 균형 있게 정리","2×3·3×2·3×3처럼 규칙적인 셀을 사용해 여행·행사·상품 묶음처럼 여러 장을 한 화면에 정리하기 좋습니다.","사진마다 비율이 크게 다르면 채우기와 위치 조정을 함께 확인하세요."],["큰 칸 + 작은 칸","대표 이미지가 있는 구성","시선을 먼저 끌어야 하는 대표 사진을 크게 두고 보조 사진을 작은 셀에 배치하면 정보의 우선순위가 분명해집니다.","대표 사진의 인물·제품이 잘리지 않도록 중심 위치를 조정하세요."]]:locale==="en"?[["2 / 3 / 4 split","Collages with fewer photos","Large cells keep each image readable, which works well for portraits, products, before-and-after scenes, or short sequences.","Match the number of photos to the number of cells first to reduce empty cells and waiting images."],["Grid layouts","Organize many photos evenly","2×3, 3×2, and 3×3 grids work well for trips, events, product sets, and other groups of images.","When aspect ratios vary widely, check both Fill mode and image positioning."],["Large cell + small cells","Layouts with a hero image","Use one large cell for the primary photo and smaller cells for supporting images to create a clear visual hierarchy.","Reposition the hero image so faces or products are not clipped."]]:[["2・3・4分割","少ない写真のコラージュ","各写真の面積を十分に確保しやすく、人物・商品・ビフォーアフターなどをはっきり見せたい場合に向いています。","写真数とセル数を先に合わせると、空きセルや待機画像を減らせます。"],["グリッド","複数写真を均等に整理","2×3・3×2・3×3の規則的なセルは、旅行・イベント・商品セットなど多くの写真を1枚にまとめる場合に便利です。","縦横比が大きく異なる写真では、塗りつぶしと位置調整を一緒に確認します。"],["大きいセル + 小さいセル","代表画像を強調する構成","主役の写真を大きく、補助写真を小さく配置すると視覚的な優先順位が明確になります。","人物や商品が切れないよう主画像の表示位置を調整します。"]]).map(([name,use,strengths,note])=><article key={name}><strong>{name}</strong><h3>{use}</h3><p>{strengths}</p><small>{note}</small></article>)}
    </div>
    <section className="toolbox-tool-format-notes-section" aria-label="Additional guide notes"><div className="toolbox-tool-format-notes">
     <article><h3>{locale==="ko"?"레이아웃 선택 기준":locale==="en"?"How to choose a layout":"レイアウト選択の基準"}</h3><ul>{(locale==="ko"?["사진 수가 적을수록 셀 하나의 크기를 크게 확보해 각 이미지가 답답해 보이지 않게 하는 것이 좋습니다.","사진 수가 많으면 규칙적인 격자형이 전체 균형을 잡기 쉽고 순서도 이해하기 쉽습니다.","대표 사진이 있다면 동일한 크기의 격자보다 큰 칸이 포함된 레이아웃이 시선 흐름을 만들기 쉽습니다."]:locale==="en"?["With fewer photos, larger cells keep individual images from feeling cramped.","With many photos, a regular grid is easier to balance and easier to scan in order.","When one image is clearly primary, a layout with one larger cell usually creates a stronger visual hierarchy."]:["写真数が少ない場合は各セルを大きくし、画像が窮屈に見えないようにします。","写真数が多い場合は規則的なグリッドの方が全体のバランスと順序を整理しやすくなります。","代表画像がある場合は、同じ大きさのグリッドより大きいセルを含むレイアウトが視線の流れを作りやすくなります。"]).map(x=><li key={x}>{x}</li>)}</ul></article>
     <article><h3>{locale==="ko"?"주의사항":locale==="en"?"Important notes":"注意事項"}</h3><ul>{(locale==="ko"?["채우기는 셀을 빈틈없이 채우지만 사진 일부가 잘릴 수 있고, 전체 보기는 사진 전체가 보이는 대신 빈 공간이 생길 수 있습니다.","이미지 간격과 외곽 여백은 서로 다른 값입니다. 셀 사이 간격과 결과 전체 바깥 여백을 별도로 확인하세요.","투명 배경은 PNG·WebP에서 유지할 수 있지만 JPG는 투명도를 저장하지 못해 배경색과 합성됩니다."]:locale==="en"?["Fill covers the cell completely but can crop part of a photo; Fit shows the whole photo but may leave empty space.","Image gap and outer padding are separate values. Check spacing between cells and space around the whole canvas independently.","PNG and WebP can preserve transparency, while JPG must composite transparent areas onto a background color."]:["塗りつぶしはセル全体を埋めますが画像の一部が切れる場合があります。全体表示は画像全体を見せる代わりに空きスペースが生じる場合があります。","画像間隔と外側余白は別の値です。セル間の間隔とキャンバス外周の余白を個別に確認します。","透明背景はPNG・WebPで維持できますが、JPGは透明度を保存できないため背景色と合成されます。"]).map(x=><li key={x}>{x}</li>)}</ul></article>
    </div></section>
    <div className="toolbox-tool-direction-guide"><div className="toolbox-tool-section-intro"><p>LAYOUT ROUTES</p><h3>{locale==="ko"?"사진 구성에 맞는 콜라주 선택":locale==="en"?"Choose a collage route for the photo set":"写真構成に合うコラージュの選び方"}</h3><span>{locale==="ko"?"사진 수와 대표 이미지 유무, 사진 비율을 먼저 보고 레이아웃을 고르면 이후 보정량을 줄일 수 있습니다.":locale==="en"?"Choose the layout from photo count, whether there is a hero image, and the source aspect ratios to reduce later adjustments.":"写真数、代表画像の有無、元画像の縦横比からレイアウトを選ぶと、後の調整を減らせます。"}</span></div><div className="toolbox-tool-direction-grid">{(locale==="ko"?[["2장","2분할","전후·한 쌍의 사진","좌우 또는 상하 흐름이 명확하고 각 사진을 크게 보여줄 수 있습니다."],["3장","큰 칸 + 2","대표 사진 + 보조 사진","대표 사진에 시선을 모으면서 두 장의 보조 이미지를 함께 배치합니다."],["4장","2×2","균형 잡힌 기본 콜라주","사진마다 동일한 비중을 주기 쉬워 가장 무난한 기본 구성입니다."],["6~9장","격자","여행·행사·상품 묶음","규칙적인 셀로 여러 사진을 빠르게 정리하고 전체 균형을 유지합니다."]]:locale==="en"?[["2 photos","2 split","Before/after or paired images","A clear left-right or top-bottom flow keeps both photos large."],["3 photos","Large + 2","Hero photo with supporting images","Draw attention to one image while keeping two secondary photos visible."],["4 photos","2×2","Balanced default collage","Equal cell sizes make this the most neutral layout when all photos have similar importance."],["6–9 photos","Grid","Trips, events, product groups","Regular cells organize many images quickly while maintaining overall balance."]]:[["2枚","2分割","ビフォーアフター・ペア写真","左右または上下の流れが明確で、両方の写真を大きく見せられます。"],["3枚","大 + 2","代表写真 + 補助写真","1枚を強調しながら2枚の補助写真も同時に見せます。"],["4枚","2×2","バランスの良い基本構成","各写真を同じ比重で見せやすい標準的なレイアウトです。"],["6〜9枚","グリッド","旅行・イベント・商品セット","規則的なセルで多くの写真を素早く整理し、全体のバランスを保ちます。"]]).map(([from,to,title,description])=><article key={`${from}-${to}`}><div className="toolbox-tool-direction-route"><strong>{from}</strong><span>→</span><strong>{to}</strong></div><h4>{title}</h4><p>{description}</p></article>)}</div></div>
    <div className="toolbox-tool-result-guide"><div className="toolbox-tool-section-intro toolbox-tool-section-intro-compact"><p>PRACTICAL DETAILS</p><h3>{locale==="ko"?"다운로드 전에 확인할 실전 기준":locale==="en"?"Practical checks before download":"ダウンロード前の実用チェック"}</h3></div><div className="toolbox-tool-result-grid">{(locale==="ko"?[["01","사진 비율","세로·가로 사진이 섞여 있으면 같은 셀에서도 잘리는 위치가 다릅니다. 각 셀을 선택해 실제 보이는 영역을 확인하세요."],["02","채우기와 전체 보기","인물·상품처럼 잘리면 안 되는 사진은 전체 보기를 먼저 확인하고, 배경 공간이 어색하면 채우기로 전환해 위치를 조절하세요."],["03","시선 중심","얼굴·제품·텍스트처럼 중요한 부분이 셀 중앙에 오도록 미리보기에서 사진 위치를 조절하면 결과가 안정적입니다."],["04","간격과 테두리","간격을 크게 쓰면서 두꺼운 테두리까지 추가하면 사진 면적이 빠르게 줄어듭니다. 둘을 함께 조절하세요."],["05","출력 비율","게시할 곳의 비율을 먼저 정한 뒤 콜라주를 구성하면 마지막에 강제로 자르거나 다시 만드는 일을 줄일 수 있습니다."],["06","투명 배경","미리보기의 체크 패턴은 투명 영역 표시용이며 실제 이미지에 포함되지 않습니다. JPG에서는 투명이 유지되지 않습니다."],["07","큰 원본","원본 파일 용량이 작아도 해상도가 매우 크면 브라우저 메모리 사용량이 커질 수 있습니다. 서비스 상한 경고가 나오면 더 작은 원본을 사용하세요."],["08","최종 확인","다운로드 전 셀별 잘림, 사진 순서, 빈 셀, 간격, 배경색과 결과 픽셀 크기를 한 번 더 확인하세요."]]:locale==="en"?[["01","Photo aspect ratios","Portrait and landscape sources crop differently even inside the same cell. Select each cell and inspect the visible area."],["02","Fill vs Fit","For faces or products that must not be cropped, check Fit first. If the empty space looks awkward, switch to Fill and reposition the image."],["03","Visual focus","Keep faces, products, or important text near the intended focal area by repositioning the image in the preview."],["04","Gap and border","Large gaps plus thick borders can quickly reduce usable photo area. Adjust them together."],["05","Output ratio","Choose the destination ratio before arranging the collage to avoid a final forced crop or rebuild."],["06","Transparency","The checkerboard only indicates transparent areas in preview and is not exported. JPG cannot preserve transparency."],["07","Large sources","A small compressed file can still have very large pixel dimensions and consume substantial browser memory. Use smaller sources when service-limit warnings appear."],["08","Final inspection","Before downloading, recheck crop, order, empty cells, spacing, background, and final pixel dimensions."]]:[["01","画像の縦横比","縦写真と横写真が混在すると、同じセルでも切れる位置が異なります。各セルを選択して表示範囲を確認します。"],["02","塗りつぶしと全体表示","人物や商品のように切れてはいけない画像は全体表示を先に確認し、余白が不自然なら塗りつぶしへ切り替えて位置を調整します。"],["03","視線の中心","顔・商品・文字など重要な部分が適切な位置に来るようプレビューで画像位置を調整します。"],["04","間隔と枠線","大きい間隔と太い枠線を同時に使うと写真の表示面積が急に小さくなります。両方を一緒に調整します。"],["05","出力比率","掲載先の比率を先に決めてから構成すると、最後に強制的な切り抜きや作り直しを減らせます。"],["06","透明背景","チェック柄は透明領域の表示用で出力には含まれません。JPGでは透明度を維持できません。"],["07","大きい元画像","圧縮ファイルが小さくてもピクセル数が非常に大きいとブラウザメモリを多く使用します。上限警告が出る場合は小さい元画像を使用します。"],["08","最終確認","保存前にセルごとの切れ方、順序、空きセル、間隔、背景、最終ピクセルサイズを再確認します。"]]).map(([number,title,description])=><article key={number}><span>{number}</span><div><h4>{title}</h4><p>{description}</p></div></article>)}</div></div>
   </div>
  </section>
  <section className="toolbox-tool-faq"><div className="toolbox-tool-guide-head"><p>FAQ</p><h2>{locale==="ko"?"자주 묻는 질문":locale==="en"?"Frequently asked questions":"よくある質問"}</h2></div><ToolboxFaqList items={t.faqs} initialCount={5} moreLabel={t.more} collapseLabel={t.collapse} className="toolbox-tool-faq-list"/></section>
  <section className="toolbox-tool-processing-note"><p>{locale==="ko"?"원본 이미지는 수정되지 않으며 서버로 전송되지 않습니다. 결과가 서비스 상한을 넘으면 사용자 모르게 축소하지 않고 크기를 낮춰 다시 만들 수 있도록 안내합니다.":locale==="en"?"Source images are not modified or uploaded. If the result exceeds the service ceiling, it is never silently downscaled; reduce the output size and generate again.":"元画像は変更されず、サーバーへ送信されません。結果がサービス上限を超える場合も自動縮小せず、出力サイズを下げて再作成できるよう案内します。"}</p></section>
 </ToolboxSubpageShell>;
}
