import Link from "next/link";
import { ImageCropperRotatorTool } from "@/components/image-cropper-rotator-tool";
import { ToolboxFaqList } from "@/components/toolbox-faq-list";
import { ToolboxSubpageShell } from "@/components/toolbox-subpage-shell";
import type { Locale } from "@/lib/site";

const copy = {
  ko: { back:"이미지 편집", title:"이미지 자르기·회전기", desc:"이미지에서 필요한 영역을 자르고 회전·반전해 원하는 구도로 저장합니다.", how:"사용 방법", steps:["JPG, PNG 또는 WebP 이미지를 선택합니다.","자유 자르기 또는 원하는 비율을 선택합니다.","이미지와 자르기 영역을 움직여 필요한 구도를 맞춥니다.","필요한 경우 회전·미세 회전·반전을 적용합니다.","적용하고 다음을 눌러 다음 이미지를 편집합니다.","편집 완료 후 결과를 개별 파일 또는 ZIP으로 저장합니다."], guide:"자르기와 회전을 함께 사용할 때 결과가 달라지는 이유",guideDesc:"좋은 자르기는 단순히 영역을 줄이는 작업이 아닙니다. 비율, 회전, 확대 상태와 결과 픽셀 크기를 함께 확인해야 필요한 구도와 선명도를 유지할 수 있습니다.",guideCards:[["비율을 먼저 정합니다","자유·원본·고정 비율","사용 목적에 맞는 비율을 먼저 정하면 파일마다 구도만 조정해도 일관된 결과를 만들 수 있습니다."],["회전 후 다시 확인합니다","중심·빈 영역·결과 크기","90도 또는 미세 회전 뒤에는 이미지 중심과 잘리는 가장자리, 실제 출력 픽셀을 다시 확인해야 합니다."],["파일별 위치를 유지합니다","같은 비율, 다른 구도","여러 이미지에 같은 비율은 적용할 수 있지만 자르기 위치와 확대 상태는 파일마다 다르게 유지하는 것이 안전합니다."]],practicalTitle:"실제 편집에서 확인할 기준",practical:[["작은 영역은 결과도 작아집니다","자르기 범위가 줄어들수록 출력 픽셀도 함께 줄어듭니다. 정확한 출력 크기 변경은 이미지 크기 변경기를 사용하세요."],["미세 회전은 가장자리를 더 자를 수 있습니다","빈 영역을 없애기 위한 자동 확대 때문에 이미지 가장자리 일부가 추가로 잘릴 수 있습니다."],["반전은 문자와 로고에도 적용됩니다","좌우·상하 반전은 이미지 전체에 적용되므로 문자와 로고 방향도 함께 바뀝니다."],["메타데이터는 기본적으로 제거됩니다","결과 저장 시 EXIF·GPS 등 메타데이터는 기본적으로 제거되고 표시 방향은 결과 픽셀에 정상 반영됩니다."]],faqTitle:"자주 묻는 질문", more:"FAQ 더보기", collapse:"FAQ 접기", faqs:[["여러 이미지를 한 번에 자를 수 있나요?","여러 이미지를 불러온 뒤 같은 비율을 적용하고 각 이미지를 한 장씩 조정할 수 있습니다."],["모든 이미지에 같은 자르기 위치가 적용되나요?","아니요. 비율은 공유할 수 있지만 위치와 확대 상태는 이미지마다 직접 설정합니다."],["어떤 비율을 지원하나요?","자유, 원본, 1:1, 4:3, 3:2, 16:9와 사용자 지정 비율을 지원합니다."],["미세 회전도 가능한가요?","네. 90도 회전 외에 기울어진 사진을 바로잡는 미세 회전을 제공합니다."],["파일이 서버로 업로드되나요?","아니요. 파일은 브라우저 내부에서 처리됩니다."]]},
  en: { back:"Image Edit", title:"Image Cropper & Rotator", desc:"Crop the area you need, rotate or flip the image, and save it with your preferred composition.", how:"How to use", steps:["Choose JPG, PNG, or WebP images.","Select free crop or a fixed ratio.","Move the image and crop area to frame the composition.","Apply rotation, fine rotation, or flips when needed.","Select Apply & Next to edit the next image.","Download completed results individually or as ZIP."], guide:"Why crop, rotation, and output dimensions must be checked together",guideDesc:"Cropping is more than reducing an area. Ratio, rotation, zoom, and output dimensions should be reviewed together to preserve composition and usable detail.",guideCards:[["Choose the ratio first","Free, original, or fixed ratios","A clear ratio makes it easier to keep a consistent result while adjusting the composition of each file."],["Review after rotation","Centering, empty edges, and output size","After 90-degree or fine rotation, check the image center, cropped edges, and final pixel dimensions again."],["Keep positions file-specific","Shared ratio, individual composition","A ratio can be shared across files, but crop position and zoom should remain specific to each image."]],practicalTitle:"What to check in real editing",practical:[["Smaller crops produce fewer pixels","The smaller the selected area, the smaller the output dimensions. Use Image Resizer when exact output dimensions are required."],["Fine rotation may crop more edges","Automatic zoom removes empty corners, which can trim additional parts of the image."],["Flipping also affects text and logos","Horizontal and vertical flips apply to the entire image, including readable text and brand marks."],["Metadata is removed by default","EXIF and GPS metadata are removed on export while visual orientation is baked into the output pixels."],],faqTitle:"Frequently asked questions", more:"View more FAQs", collapse:"Show fewer FAQs", faqs:[["Can I crop multiple images?","Yes. Load multiple images, share a ratio, and adjust each image one at a time."],["Is the same crop position used for every image?","No. Ratio can be shared, but position and zoom remain file-specific."],["Which ratios are supported?","Free, original, 1:1, 4:3, 3:2, 16:9, and custom ratios are available."],["Can I fine-tune rotation?","Yes. Fine rotation is available in addition to 90-degree rotation."],["Are files uploaded?","No. Files are processed in your browser."]]},
  ja: { back:"画像編集", title:"画像切り抜き・回転ツール", desc:"画像の必要な範囲を切り抜き、回転・反転して希望する構図で保存します。", how:"使い方", steps:["JPG・PNG・WebP画像を選択します。","自由切り抜きまたは希望する比率を選択します。","画像と切り抜き範囲を動かして構図を調整します。","必要に応じて回転・角度微調整・反転を適用します。","適用して次へを押して次の画像を編集します。","編集完了後、個別またはZIPで保存します。"], guide:"切り抜き・回転・出力サイズを一緒に確認する理由",guideDesc:"切り抜きは範囲を小さくするだけの作業ではありません。比率、回転、拡大状態、出力ピクセルをまとめて確認すると、構図と鮮明さを保ちやすくなります。",guideCards:[["最初に比率を決める","自由・元の比率・固定比率","用途に合う比率を先に決めると、各画像では構図だけを調整しながら統一感を保てます。"],["回転後に再確認する","中心・空白・出力サイズ","90度回転や微調整回転の後は、画像の中心、切れる端、実際の出力ピクセルを再確認します。"],["位置は画像ごとに保持する","同じ比率、異なる構図","複数画像で比率は共有できますが、切り抜き位置と拡大率は画像ごとに保持する方が安全です。"]],practicalTitle:"実際の編集で確認する基準",practical:[["小さい範囲ほど出力も小さくなります","切り抜き範囲が小さくなるほど出力ピクセルも減ります。正確な出力サイズ変更には画像サイズ変更ツールを使用してください。"],["微調整回転では端がさらに切れる場合があります","空白をなくす自動拡大により、画像の端が追加で切り取られることがあります。"],["反転は文字やロゴにも適用されます","左右・上下反転は画像全体に適用されるため、文字やロゴの向きも変わります。"],["メタデータは基本的に削除されます","保存時にEXIF・GPSなどは削除され、表示方向は出力画像のピクセルに反映されます。"]],faqTitle:"よくある質問", more:"FAQをもっと見る", collapse:"FAQを閉じる", faqs:[["複数画像を切り抜けますか？","はい。複数画像を読み込み、同じ比率を共有しながら1枚ずつ調整できます。"],["すべて同じ切り抜き位置になりますか？","いいえ。比率は共有できますが、位置と拡大率は画像ごとに設定します。"],["どの比率に対応していますか？","自由、元の比率、1:1、4:3、3:2、16:9、カスタム比率に対応します。"],["角度を微調整できますか？","はい。90度回転に加えて角度の微調整ができます。"],["ファイルはアップロードされますか？","いいえ。ブラウザ内で処理されます。"]]},
} as const;

export function ImageCropperRotatorPage({ locale }: { locale: Locale }) {
  const t = copy[locale];
  const jsonLd = [{"@context":"https://schema.org","@type":"WebApplication",name:t.title,applicationCategory:"MultimediaApplication",operatingSystem:"Any",offers:{"@type":"Offer",price:"0",priceCurrency:"USD"},url:`https://toolbox.fixlgs.com/${locale}/image-cropper-rotator`,description:t.desc},{"@context":"https://schema.org","@type":"FAQPage",mainEntity:t.faqs.map(([q,a])=>({"@type":"Question",name:q,acceptedAnswer:{"@type":"Answer",text:a}}))},{"@context":"https://schema.org","@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:"TOOLBOX",item:`https://toolbox.fixlgs.com/${locale}`},{"@type":"ListItem",position:2,name:t.back,item:`https://toolbox.fixlgs.com/${locale}/category/image-edit`},{"@type":"ListItem",position:3,name:t.title,item:`https://toolbox.fixlgs.com/${locale}/image-cropper-rotator`}]}];
  return <ToolboxSubpageShell locale={locale} appName={t.title}>
    <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(jsonLd)}} />
    <section className="toolbox-tool-detail-hero"><Link className="toolbox-subpage-back" href={`/${locale}/category/image-edit`}>← {t.back}</Link><p className="toolbox-subpage-eyebrow">008 · IMAGE EDIT</p><div className="toolbox-tool-detail-heading"><h1>{t.title}</h1><p>{t.desc}</p></div><div className="toolbox-tool-detail-badge"><strong>LOCAL</strong><span>{locale==="ko"?"브라우저에서 바로 처리":locale==="en"?"PROCESS IN YOUR BROWSER":"ブラウザ内で処理"}</span></div></section>
    <section className="toolbox-tool-detail-body"><div><ImageCropperRotatorTool locale={locale}/><section className="toolbox-next-work"><div><p>NEXT WORK</p><h2>{locale==="ko"?"다음 작업":locale==="en"?"Next steps":"次の作業"}</h2></div><div className="toolbox-next-work-grid">{[["006",locale==="ko"?"이미지 크기 변경기":locale==="en"?"Image Resizer":"画像サイズ変更ツール","image-resizer"],["004",locale==="ko"?"이미지 압축기":locale==="en"?"Image Compressor":"画像圧縮ツール","image-compressor"],["007",locale==="ko"?"웹 이미지 최적화기":locale==="en"?"Web Image Optimizer":"Web画像最適化ツール","web-image-optimizer"]].map(([n,name,slug])=><Link key={n} href={`/${locale}/${slug}`} className="toolbox-next-work-card"><span>{n}</span><h3>{name}</h3><div className="toolbox-next-work-card-foot"><span>LIVE</span><strong>↗</strong></div></Link>)}</div></section></div></section>
    <section className="toolbox-tool-guide toolbox-tool-guide--six"><div className="toolbox-tool-guide-head"><p>HOW TO USE</p><h2>{t.how}</h2></div><ol>{t.steps.map((step,i)=><li key={step}><span>{String(i+1).padStart(2,"0")}</span><p>{step}</p></li>)}</ol></section>
    <section className="toolbox-tool-format-guide"><div className="toolbox-tool-format-guide-head"><p>IMAGE EDITING GUIDE</p><h2>{t.guide}</h2><span>{t.guideDesc}</span></div><div className="toolbox-tool-format-body"><div className="toolbox-tool-format-grid">{t.guideCards.map(([title,subtitle,description])=><article key={title}><strong>{title}</strong><h3>{subtitle}</h3><p>{description}</p></article>)}</div><div className="toolbox-tool-result-guide"><div className="toolbox-tool-section-intro toolbox-tool-section-intro-compact"><p>PRACTICAL DETAILS</p><h3>{t.practicalTitle}</h3></div><div className="toolbox-tool-result-grid">{t.practical.map(([title,description],index)=><article key={title}><span>{String(index+1).padStart(2,"0")}</span><div><h4>{title}</h4><p>{description}</p></div></article>)}</div></div></div></section>
    <section className="toolbox-tool-faq"><div className="toolbox-tool-guide-head"><p>FAQ</p><h2>{t.faqTitle}</h2></div><ToolboxFaqList items={t.faqs} initialCount={3} moreLabel={t.more} collapseLabel={t.collapse} className="toolbox-tool-faq-list"/></section>
    <section className="toolbox-tool-processing-note"><p>{locale==="ko"?"파일은 서버로 전송되지 않고 브라우저에서 처리됩니다.":locale==="en"?"Your files are processed in your browser and are not uploaded to a server.":"ファイルはサーバーに送信されず、ブラウザ内で処理されます。"}</p></section>
  </ToolboxSubpageShell>;
}
