"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import type { Locale } from "@/lib/site";

type OutputFormat = "png" | "jpg" | "webp";
type FitMode = "cover" | "contain";
type BackgroundMode = "solid" | "transparent";
type ImageItem = { id:string; file:File; name:string; size:number; width:number; height:number; url:string; img:CanvasImageSource|null; status:"checking"|"ready"|"failed"; error?:string };
type CellState = { imageId:string|null; fit:FitMode; zoom:number; offsetX:number; offsetY:number };
type CellRect = { id:string; x:number; y:number; w:number; h:number };
type LayoutDef = { id:string; group:"2"|"3"|"4"|"grid"; label:Record<Locale,string>; cells:(w:number,h:number)=>CellRect[] };

const LIMITS = { files:12, fileBytes:15*1024*1024, totalBytes:80*1024*1024, sourcePixels:24_000_000, maxSide:3000, maxPixels:9_000_000, cells:9 } as const;
const ratios = [{id:"1:1",w:1,h:1},{id:"4:5",w:4,h:5},{id:"5:4",w:5,h:4},{id:"3:2",w:3,h:2},{id:"2:3",w:2,h:3},{id:"16:9",w:16,h:9},{id:"9:16",w:9,h:16}] as const;
const mkGrid=(rows:number,cols:number)=>(w:number,h:number)=>{const a:CellRect[]=[];for(let r=0;r<rows;r++)for(let c=0;c<cols;c++)a.push({id:`${rows}x${cols}-${r}-${c}`,x:c/cols*w,y:r/rows*h,w:w/cols,h:h/rows});return a};
const layouts:LayoutDef[]=[
 {id:"2-cols",group:"2",label:{ko:"좌우 2분할",en:"2 columns",ja:"左右2分割"},cells:mkGrid(1,2)},
 {id:"2-rows",group:"2",label:{ko:"상하 2분할",en:"2 rows",ja:"上下2分割"},cells:mkGrid(2,1)},
 {id:"3-cols",group:"3",label:{ko:"3열",en:"3 columns",ja:"3列"},cells:mkGrid(1,3)},
 {id:"3-rows",group:"3",label:{ko:"3행",en:"3 rows",ja:"3行"},cells:mkGrid(3,1)},
 {id:"3-left-big",group:"3",label:{ko:"왼쪽 큰 칸 + 2",en:"Large left + 2",ja:"左大 + 2"},cells:(w,h)=>[{id:"a",x:0,y:0,w:w*.58,h},{id:"b",x:w*.58,y:0,w:w*.42,h:h/2},{id:"c",x:w*.58,y:h/2,w:w*.42,h:h/2}]},
 {id:"3-top-big",group:"3",label:{ko:"위 큰 칸 + 2",en:"Large top + 2",ja:"上大 + 2"},cells:(w,h)=>[{id:"a",x:0,y:0,w,h:h*.58},{id:"b",x:0,y:h*.58,w:w/2,h:h*.42},{id:"c",x:w/2,y:h*.58,w:w/2,h:h*.42}]},
 {id:"3-right-big",group:"3",label:{ko:"오른쪽 큰 칸 + 2",en:"Large right + 2",ja:"右大 + 2"},cells:(w,h)=>[{id:"a",x:0,y:0,w:w*.42,h:h/2},{id:"b",x:0,y:h/2,w:w*.42,h:h/2},{id:"c",x:w*.42,y:0,w:w*.58,h}]},
 {id:"3-bottom-big",group:"3",label:{ko:"아래 큰 칸 + 2",en:"Large bottom + 2",ja:"下大 + 2"},cells:(w,h)=>[{id:"a",x:0,y:0,w:w/2,h:h*.42},{id:"b",x:w/2,y:0,w:w/2,h:h*.42},{id:"c",x:0,y:h*.42,w,h:h*.58}]},
 {id:"4-grid",group:"4",label:{ko:"2×2",en:"2×2",ja:"2×2"},cells:mkGrid(2,2)},
 {id:"4-cols",group:"4",label:{ko:"4열",en:"4 columns",ja:"4列"},cells:mkGrid(1,4)},
 {id:"4-rows",group:"4",label:{ko:"4행",en:"4 rows",ja:"4行"},cells:mkGrid(4,1)},
 {id:"2x3",group:"grid",label:{ko:"2×3 격자",en:"2×3 grid",ja:"2×3グリッド"},cells:mkGrid(2,3)},
 {id:"3x2",group:"grid",label:{ko:"3×2 격자",en:"3×2 grid",ja:"3×2グリッド"},cells:mkGrid(3,2)},
 {id:"3x3",group:"grid",label:{ko:"3×3 격자",en:"3×3 grid",ja:"3×3グリッド"},cells:mkGrid(3,3)},
];

const copy={
 ko:{select:"이미지 여러 장 선택",add:"이미지 추가",drop:"여기에 이미지를 놓아 추가할 수 있습니다.",support:"JPG · PNG · WebP · 최대 12장",layout:"레이아웃",groups:{"2":"2분할","3":"3분할","4":"4분할",grid:"격자"},images:"이미지 목록",waiting:"대기",movePrev:"이전",moveNext:"다음",remove:"삭제",reflow:"순서대로 다시 배치",preview:"콜라주 미리보기",cell:"선택 셀",empty:"빈 셀",pickCell:"셀을 선택하면 사진 위치와 확대를 조절할 수 있습니다.",replace:"다른 이미지",uploadReplace:"새 이미지 업로드",swapPrev:"이전 셀과 교환",swapNext:"다음 셀과 교환",fit:"이미지 맞춤",cover:"채우기",contain:"전체 보기",zoom:"사진 확대",center:"가운데 맞춤",resetCell:"이미지 맞춤 초기화",style:"전체 설정",ratio:"결과 비율",custom:"사용자 지정",width:"결과 너비",height:"결과 높이",gap:"이미지 간격",padding:"외곽 여백",border:"테두리",borderWidth:"테두리 두께",borderColor:"테두리 색상",background:"배경",solid:"색상",transparent:"투명",bgColor:"배경색",output:"출력",result:"결과 크기",placed:"배치된 이미지",format:"형식",quality:"품질",filename:"파일명",download:"다운로드",again:"다시 다운로드",resetStyle:"스타일 초기화",resetAll:"전체 초기화",needTwo:"콜라주를 만들려면 이미지를 한 장 더 추가하세요.",tooMany:"이미지는 최대 12장까지 선택할 수 있습니다.",tooBigFile:"개별 파일은 15 MiB 이하만 사용할 수 있습니다.",tooBigTotal:"선택한 파일의 총 용량은 80 MiB 이하만 사용할 수 있습니다.",tooBigSource:"24MP를 초과하는 이미지는 기본 서비스에서 사용할 수 없습니다.",unsupported:"지원하지 않거나 손상된 이미지입니다.",outputLimit:"결과 이미지는 한 변 3000px, 총 900만 픽셀까지 지원합니다.",pending:(n:number)=>`${n}장의 이미지가 아직 배치되지 않았습니다.`,local:"이미지는 서버로 전송되지 않고 현재 브라우저에서만 처리됩니다."},
 en:{select:"Select multiple images",add:"Add images",drop:"Drop images here to add them.",support:"JPG · PNG · WebP · up to 12",layout:"Layout",groups:{"2":"2 split","3":"3 split","4":"4 split",grid:"Grid"},images:"Image list",waiting:"Waiting",movePrev:"Previous",moveNext:"Next",remove:"Remove",reflow:"Place in list order",preview:"Collage preview",cell:"Selected cell",empty:"Empty cell",pickCell:"Select a cell to adjust image position and zoom.",replace:"Choose another image",uploadReplace:"Upload new image",swapPrev:"Swap with previous cell",swapNext:"Swap with next cell",fit:"Image fit",cover:"Fill",contain:"Fit whole image",zoom:"Photo zoom",center:"Center",resetCell:"Reset image fit",style:"Overall settings",ratio:"Output ratio",custom:"Custom",width:"Output width",height:"Output height",gap:"Image gap",padding:"Outer padding",border:"Border",borderWidth:"Border width",borderColor:"Border color",background:"Background",solid:"Color",transparent:"Transparent",bgColor:"Background color",output:"Output",result:"Result size",placed:"Images placed",format:"Format",quality:"Quality",filename:"Filename",download:"Download",again:"Download again",resetStyle:"Reset style",resetAll:"Reset all",needTwo:"Add one more image to make a collage.",tooMany:"You can select up to 12 images.",tooBigFile:"Each file must be 15 MiB or smaller.",tooBigTotal:"Selected files must total 80 MiB or less.",tooBigSource:"Images over 24 MP are outside the basic service limit.",unsupported:"Unsupported or damaged image.",outputLimit:"Output is limited to 3000 px per side and 9 million total pixels.",pending:(n:number)=>`${n} image${n===1?" is":"s are"} not placed yet.`,local:"Images stay in your browser and are not sent to a server."},
 ja:{select:"画像を複数選択",add:"画像を追加",drop:"ここに画像をドロップして追加できます。",support:"JPG・PNG・WebP・最大12枚",layout:"レイアウト",groups:{"2":"2分割","3":"3分割","4":"4分割",grid:"グリッド"},images:"画像一覧",waiting:"待機",movePrev:"前へ",moveNext:"次へ",remove:"削除",reflow:"一覧順に再配置",preview:"コラージュプレビュー",cell:"選択セル",empty:"空のセル",pickCell:"セルを選択すると画像位置と拡大率を調整できます。",replace:"別の画像を選択",uploadReplace:"新しい画像を追加",swapPrev:"前のセルと交換",swapNext:"次のセルと交換",fit:"画像の合わせ方",cover:"塗りつぶす",contain:"全体表示",zoom:"画像の拡大",center:"中央に合わせる",resetCell:"画像の合わせ方をリセット",style:"全体設定",ratio:"出力比率",custom:"カスタム",width:"出力幅",height:"出力高さ",gap:"画像間隔",padding:"外側余白",border:"枠線",borderWidth:"枠線の太さ",borderColor:"枠線の色",background:"背景",solid:"色",transparent:"透明",bgColor:"背景色",output:"出力",result:"出力サイズ",placed:"配置済み画像",format:"形式",quality:"画質",filename:"ファイル名",download:"ダウンロード",again:"もう一度ダウンロード",resetStyle:"スタイルをリセット",resetAll:"すべて初期化",needTwo:"コラージュを作るには画像をもう1枚追加してください。",tooMany:"画像は最大12枚まで選択できます。",tooBigFile:"1ファイル15 MiB以下の画像を使用してください。",tooBigTotal:"選択ファイルの合計は80 MiB以下にしてください。",tooBigSource:"24MPを超える画像は基本サービスの対象外です。",unsupported:"対応していない、または破損した画像です。",outputLimit:"出力画像は一辺3000px、合計900万画素まで対応します。",pending:(n:number)=>`${n}枚の画像がまだ配置されていません。`,local:"画像はサーバーへ送信されず、現在のブラウザ内で処理されます。"}
} as const;

function uid(){return `${Date.now()}-${Math.random().toString(36).slice(2)}`}
function safeName(v:string){return (v.trim()||"collage").replace(/[\\/:*?"<>|]+/g,"-").replace(/\s+/g,"-").slice(0,120)}
function isSupported(f:File){return ["image/jpeg","image/png","image/webp"].includes(f.type)&&/\.(jpe?g|png|webp)$/i.test(f.name)}
function closeSource(s:CanvasImageSource|null){if(typeof ImageBitmap!=="undefined"&&s instanceof ImageBitmap)s.close()}
function defaultCells(n:number,ids:string[]):CellState[]{return Array.from({length:n},(_,i)=>({imageId:ids[i]??null,fit:"cover",zoom:1,offsetX:0,offsetY:0}))}

export function ImageCollageMakerTool({locale}:{locale:Locale}){
 const t=copy[locale], inputRef=useRef<HTMLInputElement>(null), replaceRef=useRef<HTMLInputElement>(null), canvasRef=useRef<HTMLCanvasElement>(null), itemsRef=useRef<ImageItem[]>([]), dragFileId=useRef<string|null>(null), pointerRef=useRef<{idx:number,x:number,y:number}|null>(null);
 const [items,setItems]=useState<ImageItem[]>([]),[layoutId,setLayoutId]=useState("4-grid"),[cells,setCells]=useState<CellState[]>([]),[selected,setSelected]=useState(0),[group,setGroup]=useState<"2"|"3"|"4"|"grid">("4"),[ratio,setRatio]=useState("1:1"),[customRatio,setCustomRatio]=useState({w:1,h:1}),[width,setWidth]=useState(1200),[height,setHeight]=useState(1200),[gap,setGap]=useState(12),[padding,setPadding]=useState(24),[borderOn,setBorderOn]=useState(false),[borderWidth,setBorderWidth]=useState(2),[borderColor,setBorderColor]=useState("#111111"),[background,setBackground]=useState<BackgroundMode>("solid"),[backgroundColor,setBackgroundColor]=useState("#ffffff"),[format,setFormat]=useState<OutputFormat>("png"),[quality,setQuality]=useState(92),[filename,setFilename]=useState("collage"),[externalDrag,setExternalDrag]=useState(false),[error,setError]=useState(""),[status,setStatus]=useState(""),[resultBytes,setResultBytes]=useState<number|null>(null);
 useEffect(()=>{itemsRef.current=items},[items]); useEffect(()=>()=>{itemsRef.current.forEach(i=>{closeSource(i.img);URL.revokeObjectURL(i.url)})},[]);
 const layout=useMemo(()=>layouts.find(l=>l.id===layoutId)??layouts[8],[layoutId]);
 const rects=useMemo(()=>layout.cells(Math.max(1,width-padding*2),Math.max(1,height-padding*2)),[layout,width,height,padding]);
 useEffect(()=>setCells(prev=>Array.from({length:rects.length},(_,i)=>prev[i]??{imageId:itemsRef.current[i]?.id??null,fit:"cover",zoom:1,offsetX:0,offsetY:0})),[rects.length]);
 const ready=items.filter(i=>i.status==="ready"); const placedIds=new Set(cells.map(c=>c.imageId).filter(Boolean)); const waiting=ready.filter(i=>!placedIds.has(i.id)); const selectedCell=cells[selected];
 const outputBlocked=width>LIMITS.maxSide||height>LIMITS.maxSide||width*height>LIMITS.maxPixels;
 const setPresetRatio=(id:string)=>{setRatio(id);const r=ratios.find(x=>x.id===id);if(r){const nextH=Math.round(width*r.h/r.w);if(nextH<=LIMITS.maxSide&&width*nextH<=LIMITS.maxPixels)setHeight(nextH)}};
 const decode=useCallback(async(item:ImageItem)=>{try{if(!item.file.size||!isSupported(item.file)||item.file.size>LIMITS.fileBytes)throw new Error(item.file.size>LIMITS.fileBytes?t.tooBigFile:t.unsupported);let img:CanvasImageSource,w=0,h=0;if(typeof createImageBitmap==="function"){const b=await createImageBitmap(item.file,{imageOrientation:"from-image"});img=b;w=b.width;h=b.height}else{const im=new Image();im.src=item.url;await im.decode();img=im;w=im.naturalWidth;h=im.naturalHeight}if(w*h>LIMITS.sourcePixels){closeSource(img);throw new Error(t.tooBigSource)}setItems(p=>p.map(x=>x.id===item.id?{...x,img,width:w,height:h,status:"ready"}:x))}catch(e){setItems(p=>p.map(x=>x.id===item.id?{...x,status:"failed",error:e instanceof Error?e.message:t.unsupported}:x))}},[t]);
 const addFiles=useCallback((list:FileList|File[])=>{const files=Array.from(list);if(!files.length)return;const remaining=Math.max(0,LIMITS.files-itemsRef.current.length);if(remaining===0){setError(t.tooMany);return}const accepted=files.slice(0,remaining);const baseTotal=itemsRef.current.reduce((a,i)=>a+i.size,0);let total=baseTotal;const additions:ImageItem[]=[];for(const file of accepted){if(total+file.size>LIMITS.totalBytes){setError(t.tooBigTotal);break}total+=file.size;const x:ImageItem={id:uid(),file,name:file.name,size:file.size,width:0,height:0,url:URL.createObjectURL(file),img:null,status:"checking"};additions.push(x)}if(files.length>remaining)setError(t.tooMany);setItems(p=>[...p,...additions]);setCells(prev=>{const next=[...prev];for(const a of additions){const idx=next.findIndex(c=>!c.imageId);if(idx>=0)next[idx]={...next[idx],imageId:a.id}}return next});additions.forEach(x=>void decode(x));setResultBytes(null)},[decode,t]);
 const removeItem=(id:string)=>{const item=itemsRef.current.find(x=>x.id===id);if(item){closeSource(item.img);URL.revokeObjectURL(item.url)}setItems(p=>p.filter(x=>x.id!==id));setCells(p=>p.map(c=>c.imageId===id?{...c,imageId:null,zoom:1,offsetX:0,offsetY:0}:c));setResultBytes(null)};
 const moveItem=(id:string,delta:number)=>setItems(p=>{const i=p.findIndex(x=>x.id===id),j=Math.max(0,Math.min(p.length-1,i+delta));if(i<0||i===j)return p;const n=[...p],[x]=n.splice(i,1);n.splice(j,0,x);return n});
 const reflow=()=>setCells(defaultCells(rects.length,ready.map(i=>i.id)));
 const changeLayout=(id:string)=>{const next=layouts.find(l=>l.id===id);if(!next)return;setLayoutId(id);setGroup(next.group);const n=next.cells(width,height).length;setCells(prev=>{const kept=prev.slice(0,n).map(c=>({...c}));while(kept.length<n)kept.push({imageId:null,fit:"cover",zoom:1,offsetX:0,offsetY:0});const placed=new Set(kept.map(c=>c.imageId).filter((v):v is string=>Boolean(v)));const queue=ready.filter(item=>!placed.has(item.id));let q=0;return kept.map(cell=>{if(cell.imageId||q>=queue.length)return cell;const imageId=queue[q++].id;placed.add(imageId);return {...cell,imageId,fit:"cover",zoom:1,offsetX:0,offsetY:0}})});setSelected(s=>Math.min(s,n-1));setResultBytes(null)};
 const selectImageForCell=(id:string|null)=>setCells(p=>p.map((c,i)=>i===selected?{...c,imageId:id,zoom:1,offsetX:0,offsetY:0}:c));
 const updateCell=(patch:Partial<CellState>)=>setCells(p=>p.map((c,i)=>i===selected?{...c,...patch}:c));
 const swapCell=(delta:number)=>setCells(p=>{const j=selected+delta;if(j<0||j>=p.length)return p;const n=[...p],[a,b]=[n[selected],n[j]];n[selected]=b;n[j]=a;setSelected(j);return n});
 const normalizeBg=(ctx:CanvasRenderingContext2D)=>{ctx.clearRect(0,0,width,height);if(background==="solid"||format==="jpg"){ctx.fillStyle=background==="transparent"&&format==="jpg"?"#ffffff":backgroundColor;ctx.fillRect(0,0,width,height)}};
 const draw=useCallback((ctx:CanvasRenderingContext2D,forPreview=false)=>{normalizeBg(ctx);ctx.save();for(let i=0;i<rects.length;i++){const r=rects[i],c=cells[i],inset=gap/2, x=r.x+padding+inset,y=r.y+padding+inset,w=Math.max(1,r.w-gap),h=Math.max(1,r.h-gap);ctx.save();ctx.beginPath();ctx.rect(x,y,w,h);ctx.clip();const item=items.find(it=>it.id===c?.imageId&&it.status==="ready"&&it.img);if(item&&c){const base=c.fit==="cover"?Math.max(w/item.width,h/item.height):Math.min(w/item.width,h/item.height);const s=base*Math.max(1,c.zoom),dw=item.width*s,dh=item.height*s;const maxX=Math.max(0,(dw-w)/2),maxY=Math.max(0,(dh-h)/2);const ox=Math.max(-maxX,Math.min(maxX,c.offsetX*w)),oy=Math.max(-maxY,Math.min(maxY,c.offsetY*h));ctx.drawImage(item.img!,x+(w-dw)/2+ox,y+(h-dh)/2+oy,dw,dh)}ctx.restore();if(forPreview&&!item){ctx.save();ctx.setLineDash([Math.max(6,width/180),Math.max(4,width/240)]);ctx.strokeStyle="rgba(8,104,215,.55)";ctx.lineWidth=Math.max(2,width/600);ctx.strokeRect(x+2,y+2,Math.max(1,w-4),Math.max(1,h-4));ctx.setLineDash([]);ctx.fillStyle="rgba(8,104,215,.7)";ctx.textAlign="center";ctx.textBaseline="middle";ctx.font=`${Math.max(20,Math.min(44,w/7))}px sans-serif`;ctx.fillText("+",x+w/2,y+h/2);ctx.restore()}if(borderOn&&borderWidth>0){ctx.strokeStyle=borderColor;ctx.lineWidth=borderWidth;ctx.strokeRect(x+borderWidth/2,y+borderWidth/2,Math.max(0,w-borderWidth),Math.max(0,h-borderWidth))}if(forPreview&&i===selected){ctx.save();ctx.strokeStyle="#0868D7";ctx.lineWidth=Math.max(3,width/350);ctx.strokeRect(x,y,w,h);ctx.restore()}}ctx.restore()},[background,backgroundColor,format,width,height,rects,cells,gap,padding,items,borderOn,borderColor,borderWidth,selected]);
 useEffect(()=>{const c=canvasRef.current;if(!c)return;const scale=Math.min(1,900/width,620/height),pw=Math.max(1,Math.round(width*scale)),ph=Math.max(1,Math.round(height*scale));c.width=width;c.height=height;c.style.aspectRatio=`${width}/${height}`;const ctx=c.getContext("2d");if(ctx)draw(ctx,true)},[draw,width,height]);
 const download=async()=>{if(outputBlocked){setError(t.outputLimit);return}if(ready.length<2){setError(t.needTwo);return}setStatus(locale==="ko"?"결과를 생성 중입니다.":locale==="en"?"Generating result.":"出力画像を作成しています。");const c=document.createElement("canvas");c.width=width;c.height=height;const ctx=c.getContext("2d");if(!ctx)return;draw(ctx,false);const mime=format==="jpg"?"image/jpeg":format==="webp"?"image/webp":"image/png";const blob=await new Promise<Blob|null>(r=>c.toBlob(r,mime,format==="png"?undefined:quality/100));if(!blob){setError(t.unsupported);return}const url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=`${safeName(filename)}.${format}`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setResultBytes(blob.size);setStatus(locale==="ko"?"완료되었습니다.":locale==="en"?"Done.":"完了しました。");setError("")};
 const resetStyle=()=>{setGap(12);setPadding(24);setBorderOn(false);setBorderWidth(2);setBorderColor("#111111");setBackground("solid");setBackgroundColor("#ffffff")};
 const resetAll=()=>{itemsRef.current.forEach(i=>{closeSource(i.img);URL.revokeObjectURL(i.url)});setItems([]);setCells([]);setLayoutId("4-grid");setGroup("4");setSelected(0);setRatio("1:1");setWidth(1200);setHeight(1200);resetStyle();setError("");setStatus("");setResultBytes(null)};
 const onPointerDown=(e:React.PointerEvent<HTMLCanvasElement>)=>{const c=e.currentTarget,box=c.getBoundingClientRect(),x=(e.clientX-box.left)/box.width*width,y=(e.clientY-box.top)/box.height*height;const idx=rects.findIndex(r=>x>=r.x+padding&&x<=r.x+padding+r.w&&y>=r.y+padding&&y<=r.y+padding+r.h);if(idx>=0){setSelected(idx);pointerRef.current={idx,x:e.clientX,y:e.clientY};c.setPointerCapture(e.pointerId)}};
 const onPointerMove=(e:React.PointerEvent<HTMLCanvasElement>)=>{const p=pointerRef.current;if(!p||p.idx!==selected)return;const c=cells[selected];if(!c?.imageId)return;const dx=(e.clientX-p.x)/(e.currentTarget.getBoundingClientRect().width||1),dy=(e.clientY-p.y)/(e.currentTarget.getBoundingClientRect().height||1);p.x=e.clientX;p.y=e.clientY;updateCell({offsetX:c.offsetX+dx*2,offsetY:c.offsetY+dy*2})};
 const onPointerUp=(e:React.PointerEvent<HTMLCanvasElement>)=>{pointerRef.current=null;try{e.currentTarget.releasePointerCapture(e.pointerId)}catch{}};
 return <div className="toolbox-tool-workflow tool014-workflow" data-testid="tool014-root">
  <section className="tool014-workbench toolbox-workbench" data-testid="tool014-workbench">
   <div className={`toolbox-workbench-upload${externalDrag?" is-dragging":""}`} data-testid="tool014-upload" onDragEnter={e=>{if(Array.from(e.dataTransfer.types).includes("Files")){e.preventDefault();setExternalDrag(true)}}} onDragOver={e=>{if(Array.from(e.dataTransfer.types).includes("Files")){e.preventDefault();setExternalDrag(true)}}} onDragLeave={e=>{if(!e.currentTarget.contains(e.relatedTarget as Node))setExternalDrag(false)}} onDrop={e=>{if(e.dataTransfer.files.length){e.preventDefault();e.stopPropagation();setExternalDrag(false);addFiles(e.dataTransfer.files)}}}>
    <div className="toolbox-workbench-topline"><div><span>WORKSPACE</span><strong>{locale==="ko"?"콜라주 작업장":locale==="en"?"Collage workspace":"コラージュ作業エリア"}</strong></div></div>
    <input ref={inputRef} hidden multiple type="file" accept="image/jpeg,image/png,image/webp" data-testid="tool014-file-input" onChange={e=>{if(e.target.files)addFiles(e.target.files);e.target.value=""}}/><input ref={replaceRef} hidden multiple={false} type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>{if(e.target.files?.[0]){const f=e.target.files[0];addFiles([f]);setTimeout(()=>{const newest=itemsRef.current.at(-1);if(newest)selectImageForCell(newest.id)},0)}e.target.value=""}}/>
    {items.length===0?(
     <div className="toolbox-upload-focus">
      <span className="toolbox-upload-icon" aria-hidden="true">＋</span>
      <h2>{t.drop}</h2>
      <p>{t.local}</p>
      <button type="button" data-testid="tool014-select" onClick={()=>inputRef.current?.click()}>{t.select}</button>
      <small>{t.support}</small>
     </div>
    ):(
     <div className="toolbox-upload-active tool014-upload-active">
      <div className="toolbox-upload-active-head">
       <div><span>{locale==="ko"?"선택한 이미지":locale==="en"?"Selected images":"選択した画像"}</span><p>{t.local}</p></div>
       <div className="toolbox-upload-active-actions"><div className="toolbox-file-stats"><span>{items.length} / {LIMITS.files}</span><span>{ready.length} {locale==="ko"?"준비":locale==="en"?"ready":"準備完了"}</span></div><button type="button" onClick={()=>inputRef.current?.click()}>＋ {t.add}</button></div>
      </div>
      <div className="toolbox-upload-selected-file"><strong>{locale==="ko"?"콜라주에 사용할 이미지":locale==="en"?"Images for this collage":"コラージュに使う画像"}</strong><span>{t.support}</span></div>
     </div>
    )}
   </div>
  {items.length>0&&<div className={`tool014-editor${externalDrag?" is-dragging":""}`} onDragEnter={e=>{if(Array.from(e.dataTransfer.types).includes("Files")){e.preventDefault();setExternalDrag(true)}}} onDragOver={e=>{if(Array.from(e.dataTransfer.types).includes("Files")){e.preventDefault();setExternalDrag(true)}}} onDragLeave={e=>{if(!e.currentTarget.contains(e.relatedTarget as Node))setExternalDrag(false)}} onDrop={e=>{if(e.dataTransfer.files.length){e.preventDefault();e.stopPropagation();setExternalDrag(false);addFiles(e.dataTransfer.files)}}}>
   <aside className="toolbox-workbench-settings-card tool014-left"><div className="toolbox-workbench-settings-head"><div><span>{t.layout}</span></div></div><div className="tool014-groups">{(["2","3","4","grid"] as const).map(g=><button key={g} className={group===g?"is-active":""} onClick={()=>setGroup(g)}>{t.groups[g]}</button>)}</div><div className="tool014-layouts">{layouts.filter(l=>l.group===group).map(l=><button key={l.id} data-testid={`tool014-layout-${l.id}`} className={layoutId===l.id?"is-active":""} onClick={()=>changeLayout(l.id)}><span className="tool014-layout-icon">{l.id.includes("3x3")?"▦":l.id.includes("2x3")||l.id.includes("3x2")?"▥":l.group==="2"?"▥":l.group==="3"?"▥":"▦"}</span><small>{l.label[locale]}</small></button>)}</div>
    <div className="toolbox-workbench-settings-head"><div><span>{t.images}</span><p>{ready.length} / {LIMITS.files}</p></div></div><div className="tool014-files">{items.map((it,i)=><article key={it.id} draggable onDragStart={()=>dragFileId.current=it.id} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();if(dragFileId.current&&dragFileId.current!==it.id){const from=items.findIndex(x=>x.id===dragFileId.current),to=items.findIndex(x=>x.id===it.id);setItems(p=>{const n=[...p],[x]=n.splice(from,1);n.splice(to,0,x);return n})}dragFileId.current=null}} className={it.status==="failed"?"is-failed":""}><img src={it.url} alt=""/><div><strong>{i+1}. {it.name}</strong><small>{it.status==="failed"?it.error:`${it.width||"…"} × ${it.height||"…"}`}</small><div><button onClick={()=>moveItem(it.id,-1)} disabled={i===0}>{t.movePrev}</button><button onClick={()=>moveItem(it.id,1)} disabled={i===items.length-1}>{t.moveNext}</button><button onClick={()=>removeItem(it.id)}>{t.remove}</button></div></div></article>)}</div><button className="tool014-reflow" onClick={reflow}>{t.reflow}</button>{waiting.length>0&&<p className="tool014-warning">{t.pending(waiting.length)}</p>}
   </aside>
   <main className="toolbox-workbench-preview-card tool014-preview-card"><div className="toolbox-workbench-settings-head"><div><span>{t.preview}</span><p>{width} × {height}px · {rects.length} {locale==="ko"?"칸":locale==="en"?"cells":"セル"}</p></div></div><div className={`tool014-canvas-wrap${background==="transparent"?" is-transparent":""}`}><canvas ref={canvasRef} data-testid="tool014-preview-canvas" onPointerDown={onPointerDown} onPointerMove={onPointerMove} onPointerUp={onPointerUp} onPointerCancel={onPointerUp}/></div><p className="tool014-preview-hint">{t.pickCell}</p><span hidden data-testid="tool014-state" data-unplaced={waiting.length} data-cells={cells.length} data-files={items.length}/>
   </main>
   <aside className="toolbox-workbench-settings-card tool014-right"><div className="toolbox-workbench-settings-head"><div><span>{t.cell} {selected+1}</span><p>{selectedCell?.imageId?items.find(i=>i.id===selectedCell.imageId)?.name:t.empty}</p></div></div><label>{t.replace}<select value={selectedCell?.imageId??""} onChange={e=>selectImageForCell(e.target.value||null)}><option value="">{t.empty}</option>{ready.map(i=><option key={i.id} value={i.id}>{i.name}</option>)}</select></label><button className="tool014-reflow" onClick={()=>replaceRef.current?.click()}>{t.uploadReplace}</button><div className="tool014-row-actions"><button onClick={()=>swapCell(-1)} disabled={selected===0}>{t.swapPrev}</button><button onClick={()=>swapCell(1)} disabled={selected===cells.length-1}>{t.swapNext}</button></div><div className="tool014-segment"><button className={selectedCell?.fit==="cover"?"is-active":""} onClick={()=>updateCell({fit:"cover",zoom:1,offsetX:0,offsetY:0})}>{t.cover}</button><button className={selectedCell?.fit==="contain"?"is-active":""} onClick={()=>updateCell({fit:"contain",zoom:1,offsetX:0,offsetY:0})}>{t.contain}</button></div><label>{t.zoom}<input type="range" min="100" max="300" value={Math.round((selectedCell?.zoom??1)*100)} onChange={e=>updateCell({zoom:+e.target.value/100})}/><span>{Math.round((selectedCell?.zoom??1)*100)}%</span></label><div className="tool014-row-actions"><button onClick={()=>updateCell({offsetX:0,offsetY:0})}>{t.center}</button><button onClick={()=>updateCell({fit:"cover",zoom:1,offsetX:0,offsetY:0})}>{t.resetCell}</button></div>
    <div className="toolbox-workbench-settings-head"><div><span>{t.style}</span></div></div><label>{t.ratio}<select value={ratio} onChange={e=>{const v=e.target.value;setPresetRatio(v)}}>{ratios.map(r=><option key={r.id}>{r.id}</option>)}<option value="custom">{t.custom}</option></select></label>{ratio==="custom"&&<div className="tool014-two"><label>{t.width}<input type="number" min="1" max={LIMITS.maxSide} value={customRatio.w} onChange={e=>{const nw=Math.max(1,+e.target.value||1);setCustomRatio(v=>({...v,w:nw}));setHeight(Math.max(1,Math.round(width*customRatio.h/nw)))}}/></label><label>{t.height}<input type="number" min="1" max={LIMITS.maxSide} value={customRatio.h} onChange={e=>{const nh=Math.max(1,+e.target.value||1);setCustomRatio(v=>({...v,h:nh}));setHeight(Math.max(1,Math.round(width*nh/customRatio.w)))}}/></label></div>}<div className="tool014-two"><label>{t.width}<input data-testid="tool014-width" type="number" min="1" max={LIMITS.maxSide} value={width} onChange={e=>setWidth(Math.max(1,+e.target.value||1))}/></label><label>{t.height}<input data-testid="tool014-height" type="number" min="1" max={LIMITS.maxSide} value={height} onChange={e=>setHeight(Math.max(1,+e.target.value||1))}/></label></div><div className="tool014-two"><label>{t.gap}<input type="number" min="0" max="200" value={gap} onChange={e=>setGap(Math.max(0,Math.min(200,+e.target.value||0)))}/></label><label>{t.padding}<input type="number" min="0" max="300" value={padding} onChange={e=>setPadding(Math.max(0,Math.min(300,+e.target.value||0)))}/></label></div><label className="tool014-check"><input type="checkbox" checked={borderOn} onChange={e=>setBorderOn(e.target.checked)}/>{t.border}</label>{borderOn&&<div className="tool014-two"><label>{t.borderWidth}<input type="number" min="0" max="40" value={borderWidth} onChange={e=>setBorderWidth(Math.max(0,Math.min(40,+e.target.value||0)))}/></label><label>{t.borderColor}<input type="color" value={borderColor} onChange={e=>setBorderColor(e.target.value)}/></label></div>}<div className="tool014-segment"><button className={background==="solid"?"is-active":""} onClick={()=>setBackground("solid")}>{t.solid}</button><button className={background==="transparent"?"is-active":""} onClick={()=>setBackground("transparent")}>{t.transparent}</button></div>{background==="solid"&&<label>{t.bgColor}<input type="color" value={backgroundColor} onChange={e=>setBackgroundColor(e.target.value)}/></label>}
   </aside>
  </div>}
  {items.length>0&&<section className="toolbox-workbench-settings-card tool014-output"><div className="toolbox-workbench-settings-head"><div><span>{t.output}</span><p>{t.result}: {width} × {height}px · {t.placed}: {cells.filter(c=>c.imageId).length}/{cells.length}</p></div></div><div className="tool014-output-controls"><label>{t.format}<select value={format} onChange={e=>setFormat(e.target.value as OutputFormat)}><option value="png">PNG</option><option value="jpg">JPG</option><option value="webp">WebP</option></select></label><label>{t.quality}<input type="range" min="40" max="100" value={quality} disabled={format==="png"} onChange={e=>setQuality(+e.target.value)}/><span>{format==="png"?"—":`${quality}%`}</span></label><label>{t.filename}<input value={filename} onChange={e=>setFilename(e.target.value)}/></label></div>{outputBlocked&&<p className="tool014-warning" data-testid="tool014-limit-blocked">{t.outputLimit}</p>}{ready.length===1&&<p className="tool014-warning">{t.needTwo}</p>}<div className="tool014-actions"><button className="toolbox-primary-action" data-testid="tool014-download" disabled={ready.length<2||outputBlocked} onClick={download}>{resultBytes!==null?t.again:t.download}</button><button onClick={resetStyle}>{t.resetStyle}</button><button onClick={resetAll}>{t.resetAll}</button></div>{resultBytes!==null&&<div className="toolbox-workbench-result-card"><strong>{locale==="ko"?"완료":locale==="en"?"Complete":"完了"}</strong><span>{width} × {height}px</span><span>{format.toUpperCase()}</span><span>{(resultBytes/1024).toFixed(1)} KB</span></div>}<p aria-live="polite">{status}</p>{error&&<p role="alert" className="tool014-error" data-testid="tool014-error">{error}</p>}</section>}
  </section>
 </div>
}
