import Link from "next/link";
import { ImageMergerTool } from "@/components/image-merger-tool";
import { ToolboxFaqList } from "@/components/toolbox-faq-list";
import { ToolboxSubpageShell } from "@/components/toolbox-subpage-shell";
import type { Locale } from "@/lib/site";

const copy = {
 ko:{back:"이미지 편집",title:"이미지 합치기",desc:"여러 이미지를 원하는 순서대로 세로 또는 가로로 합쳐 한 장으로 만드세요.",steps:["합칠 이미지 여러 장을 선택합니다.","썸네일을 드래그하거나 이동 버튼으로 순서를 정합니다.","세로 또는 가로 합치기를 선택합니다.","원본 크기 유지 또는 너비·높이 맞춤 방식을 선택합니다.","이미지 정렬을 선택합니다.","이미지 사이 간격과 외곽 여백을 조절합니다.","배경색 또는 투명 배경을 선택합니다.","결과 크기와 미리보기를 확인합니다.","출력 형식과 품질을 선택합니다.","다운로드를 눌러 한 장의 이미지로 저장합니다."],faqs:[["여러 이미지를 한 장으로 합칠 수 있나요?","예. 여러 JPG·PNG·WebP 이미지를 한 장으로 합칠 수 있습니다."],["세로와 가로 모두 지원하나요?","예. 위에서 아래로 이어 붙이는 세로 방식과 왼쪽에서 오른쪽으로 이어 붙이는 가로 방식을 지원합니다."],["이미지 순서를 바꿀 수 있나요?","예. 드래그 또는 이동 버튼으로 순서를 변경할 수 있습니다."],["이미지 크기가 서로 달라도 되나요?","예. 원본 크기를 유지하거나 공통 너비·높이에 맞출 수 있습니다."],["이미지가 찌그러지나요?","아니요. 크기를 맞출 때 원본 가로세로 비율을 유지합니다."],["이미지 사이에 간격을 넣을 수 있나요?","예. 픽셀 단위로 이미지 사이 간격을 설정할 수 있습니다."],["투명 배경도 가능한가요?","예. PNG 또는 투명도를 지원하는 WebP 출력에서 사용할 수 있습니다."],["많은 이미지를 합칠 수 있나요?","한 번에 최대 20장까지 합칠 수 있습니다. 결과 이미지는 한 변 최대 10,000px, 총 2,500만 픽셀까지 지원합니다."],["긴 스크린샷도 만들 수 있나요?","예. 스크린샷을 순서대로 세로로 이어 붙일 수 있습니다. 겹치는 부분을 자동 제거하지는 않습니다."],["이미지는 서버에 업로드되나요?","아니요. 현재 브라우저 안에서 처리됩니다."],["파노라마 사진을 만들 수 있나요?","이 도구는 이미지를 순서대로 붙이는 도구이며 특징점 기반 파노라마 자동 합성은 제공하지 않습니다."],["모바일에서도 순서를 바꿀 수 있나요?","예. 드래그 외에도 위·아래·맨 앞·맨 뒤 이동 버튼을 제공합니다."]],more:"FAQ 더보기",collapse:"FAQ 접기"},
 en:{back:"Image Edit",title:"Image Merger",desc:"Combine multiple images vertically or horizontally in any order.",steps:["Select multiple images to merge.","Reorder thumbnails by dragging or using move buttons.","Choose vertical or horizontal merging.","Keep original size or match width or height.","Choose cross-axis alignment.","Adjust image gap and outer padding.","Choose a solid or transparent background.","Check the preview and result dimensions.","Choose output format and quality.","Download the merged image."],faqs:[["Can I combine multiple images into one?","Yes. You can combine multiple JPG, PNG, and WebP images."],["Are vertical and horizontal layouts supported?","Yes. Merge top-to-bottom or left-to-right."],["Can I change image order?","Yes. Use drag-and-drop or dedicated move buttons."],["Can the images have different sizes?","Yes. Keep original sizes or match a common width or height."],["Will images be distorted?","No. Aspect ratio is preserved when sizing changes."],["Can I add spacing?","Yes. Set image gap in pixels."],["Can I use transparency?","Yes with PNG or transparency-capable WebP output."],["Can I merge many images?","You can merge up to 20 images at a time. The result is limited to 10,000 px on either side and 25 million total pixels."],["Can I make a long screenshot?","Yes by merging screenshots vertically in order. Overlap removal is not automatic."],["Are images uploaded to a server?","No. Processing stays in your browser."],["Does this create panoramas?","No. It does not perform feature matching, perspective warping, or panorama blending."],["Can I reorder on mobile?","Yes. Dragging and move controls are available."]],more:"Show more FAQs",collapse:"Collapse FAQs"},
 ja:{back:"画像編集",title:"画像結合ツール",desc:"複数の画像を好きな順番で縦または横に結合できます。",steps:["結合する画像を複数選択します。","サムネイルをドラッグするか移動ボタンで順番を整えます。","縦または横の結合方向を選択します。","元サイズ維持または幅・高さ合わせを選択します。","配置を選択します。","画像間隔と外側余白を調整します。","背景色または透明背景を選択します。","結果サイズとプレビューを確認します。","出力形式と画質を選択します。","ダウンロードして1枚の画像として保存します。"],faqs:[["複数画像を1枚に結合できますか？","はい。複数のJPG・PNG・WebP画像を1枚に結合できます。"],["縦と横の両方に対応していますか？","はい。上から下への縦結合と左から右への横結合に対応しています。"],["画像の順番を変更できますか？","はい。ドラッグまたは移動ボタンで変更できます。"],["画像サイズが違っても使えますか？","はい。元サイズを維持するか、共通の幅・高さに合わせられます。"],["画像が変形しますか？","いいえ。サイズ変更時も縦横比を維持します。"],["画像の間に余白を入れられますか？","はい。ピクセル単位で画像間隔を設定できます。"],["透明背景にできますか？","はい。PNGまたは透明度対応WebPで使用できます。"],["多くの画像を結合できますか？","一度に最大20枚まで結合できます。結果画像は一辺10,000px、総画素数2,500万ピクセルまで対応します。"],["長いスクリーンショットを作れますか？","はい。スクリーンショットを順番に縦結合できます。重複部分の自動削除は行いません。"],["画像はサーバーへ送信されますか？","いいえ。現在のブラウザ内で処理されます。"],["パノラマを作れますか？","特徴点マッチングや遠近補正を使う自動パノラマ合成には対応していません。"],["モバイルでも並び替えできますか？","はい。ドラッグに加え、上・下・先頭・最後への移動ボタンを利用できます。" ]],more:"FAQをもっと見る",collapse:"FAQを閉じる"}
} as const;

export function ImageMergerPage({locale}:{locale:Locale}){
 const t=copy[locale];
 const nextTitle=locale==="ko"?"다음 작업":locale==="en"?"Next steps":"次の作業";
 const ready=locale==="ko"?"사용 가능":locale==="en"?"Available":"利用可能";
 const soon=locale==="ko"?"준비 중":locale==="en"?"Coming soon":"準備中";
 const nextCards=[
   {n:"014",name:locale==="ko"?"이미지 콜라주 만들기":locale==="en"?"Image Collage Maker":"画像コラージュ作成",href:null},
   {n:"015",name:locale==="ko"?"전후 비교 이미지 만들기":locale==="en"?"Before & After Image Maker":"ビフォー・アフター画像作成",href:null},
   {n:"012",name:locale==="ko"?"이미지 테두리·둥근 모서리 도구":locale==="en"?"Image Border & Rounded Corners":"画像枠線・角丸ツール",href:`/${locale}/image-border-rounded-corners-tool`}
 ];
 const jsonLd={"@context":"https://schema.org","@graph":[{"@type":"WebApplication",name:t.title,applicationCategory:"MultimediaApplication",operatingSystem:"Any",url:`https://toolbox.fixlgs.com/${locale}/image-merger`,description:t.desc,offers:{"@type":"Offer",price:"0",priceCurrency:"USD"}},{"@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:"TOOLBOX",item:`https://toolbox.fixlgs.com/${locale}`},{"@type":"ListItem",position:2,name:t.back,item:`https://toolbox.fixlgs.com/${locale}/category/image-edit`},{"@type":"ListItem",position:3,name:t.title,item:`https://toolbox.fixlgs.com/${locale}/image-merger`}]},{"@type":"FAQPage",mainEntity:t.faqs.map(([q,a])=>({"@type":"Question",name:q,acceptedAnswer:{"@type":"Answer",text:a}}))}]};
 return <ToolboxSubpageShell locale={locale} appName={t.title}>
   <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(jsonLd)}}/>
   <section className="toolbox-tool-detail-hero tool013-detail-hero">
     <Link className="toolbox-subpage-back" href={`/${locale}/category/image-edit`}>← {t.back}</Link>
     <p className="toolbox-subpage-eyebrow">013 · IMAGE EDIT</p>
     <div className="toolbox-tool-detail-heading"><h1>{t.title}</h1><p>{t.desc}</p></div>
     <div className="toolbox-tool-detail-badge"><strong>LOCAL</strong><span>{locale==="ko"?"브라우저에서 바로 처리":locale==="en"?"PROCESS IN YOUR BROWSER":"ブラウザ内で処理"}</span></div>
   </section>
   <section className="toolbox-tool-detail-body"><div><ImageMergerTool locale={locale}/><section className="toolbox-next-work"><div><p>NEXT WORK</p><h2>{nextTitle}</h2></div><div className="toolbox-next-work-grid">{nextCards.map(c=>c.href?<Link key={c.n} href={c.href} className="toolbox-next-work-card"><span>{c.n}</span><h3>{c.name}</h3><div className="toolbox-next-work-card-foot"><span>{ready}</span><strong>↗</strong></div></Link>:<div key={c.n} className="toolbox-next-work-card is-disabled"><span>{c.n}</span><h3>{c.name}</h3><div className="toolbox-next-work-card-foot"><span>{soon}</span><strong>·</strong></div></div>)}</div></section></div></section>
   <section className="toolbox-tool-guide tool013-how-to tool013-how-to-grid"><div className="toolbox-tool-guide-head"><p>HOW TO USE</p><h2>{locale==="ko"?"사용 방법":locale==="en"?"How to use":"使い方"}</h2></div><ol>{t.steps.map((s,i)=><li key={s}><span>{String(i+1).padStart(2,"0")}</span><p>{s}</p></li>)}</ol></section>
   <section className="toolbox-tool-format-guide toolbox-tool-expert-post tool013-format-guide">
     <div className="toolbox-tool-format-guide-head"><p>IMAGE MERGING GUIDE</p><h2>{locale==="ko"?"이미지를 자연스럽고 안전하게 합치는 기준":locale==="en"?"How to merge images cleanly and safely":"画像を自然かつ安全に結合する基準"}</h2><span>{locale==="ko"?"방향, 크기 기준, 정렬, 간격, 배경과 출력 형식을 목적에 맞게 선택하면 이미지 왜곡과 불필요한 화질 저하를 줄일 수 있습니다.":locale==="en"?"Choose direction, sizing basis, alignment, spacing, background, and output format for the job to avoid distortion and unnecessary quality loss.":"方向、サイズ基準、配置、間隔、背景、出力形式を目的に合わせて選ぶと、変形や不要な画質低下を抑えられます。"}</span></div>
     <div className="toolbox-tool-format-body">
       <div className="toolbox-tool-format-grid">
         {(locale==="ko"?[["세로 합치기","스크린샷·문서·상품 상세","위에서 아래로 읽는 긴 이미지에 적합합니다. 서로 다른 크기는 공통 너비 맞춤을 우선 검토하세요.","1번 이미지가 가장 위에 배치됩니다."],["가로 합치기","사진·전후 과정·나란한 비교","왼쪽에서 오른쪽으로 이어 붙일 때 적합합니다. 높이 맞춤을 사용하면 행이 고르게 정리됩니다.","1번 이미지가 가장 왼쪽에 배치됩니다."],["원본 크기 유지","원본 픽셀 우선","각 파일의 원본 크기를 그대로 유지해 불필요한 리사이즈를 피합니다.","크기 차이는 정렬과 배경 공간으로 보입니다."]]:locale==="en"?[["Vertical merge","Screenshots, documents, product details","Best for long top-to-bottom images. Matching width is usually the first sizing option to consider.","Image 1 is placed at the top."],["Horizontal merge","Photos, processes, side-by-side views","Best for left-to-right sequences. Matching height keeps the row visually even.","Image 1 is placed at the far left."],["Keep original size","Preserve source pixels","Avoids unnecessary resizing by keeping each source image at its native dimensions.","Size differences appear as alignment and background space."]]:[["縦結合","スクリーンショット・文書・商品詳細","上から下へ読む長い画像に適しています。サイズが異なる場合は幅合わせを優先して検討します。","1番の画像が一番上に配置されます。"],["横結合","写真・工程・横並び比較","左から右へ並べる用途に適しています。高さ合わせを使うと行が整いやすくなります。","1番の画像が一番左に配置されます。"],["元サイズを維持","元のピクセルを優先","各画像の元サイズを維持して不要なサイズ変更を避けます。","サイズ差は配置と背景スペースとして見えます。"]]).map(([name,use,strengths,note])=><article key={name}><strong>{name}</strong><h3>{use}</h3><p>{strengths}</p><small>{note}</small></article>)}
       </div>
       <section className="toolbox-tool-format-notes-section" aria-label="Additional guide notes"><div className="toolbox-tool-format-notes">
         <article><h3>{locale==="ko"?"선택 기준":locale==="en"?"Sizing choices":"サイズ選択の基準"}</h3><ul>{(locale==="ko"?["세로 합치기는 너비 맞춤, 가로 합치기는 높이 맞춤이 가장 이해하기 쉽습니다.","작은 크기 기준은 작은 이미지를 강제로 확대하지 않아 화질 저하를 줄이는 안전한 기본값입니다.","가장 큰 크기나 큰 사용자 지정 크기는 업스케일이 발생할 수 있으므로 결과를 확대해 확인하세요."]:locale==="en"?["Matching width is the most intuitive choice for vertical merging; matching height is usually best for horizontal merging.","The smallest basis avoids forced enlargement of smaller images and is the safer default for quality.","Largest or oversized custom dimensions can upscale images, so inspect the result at full size."]:["縦結合は幅合わせ、横結合は高さ合わせが最も分かりやすい選択です。","最小サイズ基準は小さい画像を無理に拡大しないため、画質を保ちやすい安全な初期設定です。","最大サイズや大きいカスタム値では拡大が発生するため、結果を100%表示で確認してください。"]).map(x=><li key={x}>{x}</li>)}</ul></article>
         <article><h3>{locale==="ko"?"주의사항":locale==="en"?"Important notes":"注意事項"}</h3><ul>{(locale==="ko"?["이미지 N장의 간격은 N-1개이며 외곽 여백은 결과 전체 바깥에 적용됩니다.","투명 배경은 PNG·WebP에서 유지할 수 있지만 JPG는 선택한 배경색으로 합성됩니다.","매우 긴 결과는 Canvas·메모리 한계에 도달할 수 있으므로 결과 픽셀과 경고를 확인하세요."]:locale==="en"?["For N images there are N-1 internal gaps; outer padding surrounds the entire merged canvas.","PNG and WebP can preserve transparency, while JPG composites transparent areas onto the selected background.","Very long outputs may reach canvas or memory limits, so check the calculated dimensions and warnings."]:["画像N枚の内部間隔はN-1個で、外側余白は結合後キャンバス全体の外側に適用されます。","透明背景はPNG・WebPで維持できますが、JPGでは選択した背景色で合成されます。","非常に長い結果はCanvasやメモリ上限に達する場合があるため、結果サイズと警告を確認してください。"]).map(x=><li key={x}>{x}</li>)}</ul></article>
       </div></section>
       <div className="toolbox-tool-direction-guide">
         <div className="toolbox-tool-section-intro"><p>MERGE ROUTES</p><h3>{locale==="ko"?"목적에 맞는 합치기 방향":locale==="en"?"Choose the right merge route":"目的に合う結合ルート"}</h3><span>{locale==="ko"?"이미지를 읽는 방향과 최종 게시 형태에 맞춰 세로 또는 가로를 선택하세요.":locale==="en"?"Choose vertical or horizontal based on reading direction and the final publishing layout.":"読む方向と最終的な掲載形態に合わせて縦または横を選びます。"}</span></div>
         <div className="toolbox-tool-direction-grid">
           {(locale==="ko"?[["스크린샷","세로","긴 화면·채팅·문서 캡처","위에서 아래로 자연스럽게 이어집니다."],["사진 묶음","가로","나란한 사진·과정 이미지","왼쪽에서 오른쪽으로 한 줄에 정리합니다."],["크기가 다른 이미지","맞춤","너비 또는 높이 통일","비율을 유지한 채 공통 축만 맞춥니다."],["원본 우선","유지","픽셀 변경 최소화","크기 차이는 정렬과 배경 공간으로 처리합니다."]]:locale==="en"?[["Screenshots","Vertical","Long pages, chats, documents","Creates a natural top-to-bottom sequence."],["Photo sets","Horizontal","Side-by-side photos and process images","Builds a single left-to-right row."],["Different sizes","Fit","Match width or height","Keeps aspect ratio while aligning one shared axis."],["Source first","Original","Minimize pixel changes","Handles size differences with alignment and background space."]]:[["スクリーンショット","縦","長い画面・チャット・文書","上から下へ自然に連結します。"],["写真セット","横","横並び写真・工程画像","左から右へ1列に整理します。"],["異なるサイズ","合わせる","幅または高さを統一","縦横比を維持しながら共通軸だけを合わせます。"],["元画像優先","維持","ピクセル変更を最小化","サイズ差は配置と背景スペースで処理します。"]]).map(([from,to,title,description])=><article key={`${from}-${to}`}><div className="toolbox-tool-direction-route"><strong>{from}</strong><span>→</span><strong>{to}</strong></div><h4>{title}</h4><p>{description}</p></article>)}
         </div>
       </div>
       <div className="toolbox-tool-result-guide">
         <div className="toolbox-tool-section-intro toolbox-tool-section-intro-compact"><p>PRACTICAL DETAILS</p><h3>{locale==="ko"?"다운로드 전에 확인할 실전 기준":locale==="en"?"Practical checks before download":"ダウンロード前の実用チェック"}</h3></div>
         <div className="toolbox-tool-result-grid">
           {(locale==="ko"?[["01","순서","화면의 파일 순서가 최종 배치 순서입니다. 비동기 로딩 완료 순서 때문에 바뀌지 않습니다."],["02","정렬","세로에서는 좌·중앙·우, 가로에서는 위·중앙·아래 정렬이 남는 공간의 위치를 결정합니다."],["03","간격과 외곽 여백","이미지 사이 공간과 결과 바깥 공간은 별도 값이므로 목적에 맞게 구분해 사용하세요."],["04","투명 배경","체크 패턴은 미리보기용이며 다운로드에는 포함되지 않습니다. JPG는 투명도를 저장하지 못합니다."],["05","큰 결과","결과 너비·높이·총 픽셀을 확인하고 경고가 뜨면 크기 기준을 낮춰 다시 생성하세요."],["06","긴 스크린샷","겹치는 영역을 자동으로 찾아 제거하지 않습니다. 필요한 경우 원본 캡처 단계에서 중복을 정리하세요."],["07","품질","PNG는 무손실이지만 커질 수 있고, JPG·WebP는 품질을 낮추면 용량이 줄지만 압축 흔적이 생길 수 있습니다."],["08","최종 확인","다운로드 전 100% 보기에서 이미지 경계, 간격, 배경, 순서와 작은 글자를 한 번 더 확인하세요."]]:locale==="en"?[["01","Order","The visible file list is the final placement order and never changes because one image decodes later."],["02","Alignment","Vertical merging uses left/center/right; horizontal merging uses top/center/bottom to position extra space."],["03","Gap vs padding","Internal image gaps and outer canvas padding are separate values and should be adjusted for different purposes."],["04","Transparency","The checkerboard is preview-only and is never exported. JPG cannot store transparent pixels."],["05","Large results","Check width, height, and total pixels. If a warning appears, lower the sizing basis before generating again."],["06","Long screenshots","The tool does not detect or remove overlapping capture regions. Remove duplication at the capture stage when necessary."],["07","Quality","PNG is lossless but can be large. Lower JPG/WebP quality reduces size but may introduce compression artifacts."],["08","Final inspection","Use the 100% view before downloading to check edges, spacing, background, order, and small text."]]:[["01","順番","画面のファイル順が最終配置順です。読み込み完了が遅い画像があっても順番は変わりません。"],["02","配置","縦結合は左・中央・右、横結合は上・中央・下で余ったスペースの位置を決めます。"],["03","間隔と外側余白","画像間のスペースと結果全体の外側スペースは別の値として目的に応じて調整します。"],["04","透明背景","チェック柄はプレビュー専用で出力には含まれません。JPGは透明度を保存できません。"],["05","大きな結果","幅・高さ・総ピクセルを確認し、警告が出た場合はサイズ基準を下げて再生成してください。"],["06","長いスクリーンショット","重複部分を自動検出・削除しません。必要ならキャプチャ段階で重複を整理してください。"],["07","画質","PNGは可逆ですが大きくなりやすく、JPG・WebPは品質を下げると容量が減る一方で圧縮ノイズが出る場合があります。"],["08","最終確認","ダウンロード前に100%表示で境界、間隔、背景、順番、小さな文字を再確認してください。"]]).map(([number,title,description])=><article key={number}><span>{number}</span><div><h4>{title}</h4><p>{description}</p></div></article>)}
         </div>
       </div>
     </div>
   </section>
   <section className="toolbox-tool-faq"><div className="toolbox-tool-guide-head"><p>FAQ</p><h2>{locale==="ko"?"자주 묻는 질문":locale==="en"?"Frequently asked questions":"よくある質問"}</h2></div><ToolboxFaqList items={t.faqs} initialCount={5} moreLabel={t.more} collapseLabel={t.collapse} className="toolbox-tool-faq-list"/></section>
   <section className="toolbox-tool-processing-note"><p>{locale==="ko"?"원본 파일은 수정되지 않습니다. 결과가 지나치게 큰 경우 사용자 모르게 자동 축소하지 않으며, 크기 기준을 낮춰 다시 생성할 수 있도록 안내합니다.":locale==="en"?"Original files are not modified. Oversized results are never silently downscaled; reduce the sizing basis and generate again.":"元ファイルは変更されません。結果が大きすぎる場合も自動で縮小せず、サイズ基準を下げて再生成できるよう案内します。"}</p></section>
 </ToolboxSubpageShell>;
}
