"use client";
import {useMemo,useRef,useState} from "react";
import type {DragEvent} from "react";
import type {Locale} from "@/lib/site";
import {analyzeTool044,TOOL044_SERVICE_LIMITS,validateTool044,type Tool044Result} from "@/lib/tool-044-keyword-analyzer";
import styles from "./keyword-frequency-duplicate-tool.module.css";
import inputCommon from "./text-tool-input-common.module.css";
const ACCEPTED_EXTENSIONS=["txt","md","csv"] as const;
type LoadedFile=Readonly<{name:string;size:number}>;
const copy={
ko:{inputTitle:"텍스트를 입력·붙여넣거나 파일을 넣으세요",dropHint:"TXT · MD · CSV 파일을 이 작업영역에 끌어다 놓아도 됩니다.",chooseFile:"텍스트 파일 선택",replaceFile:"새 파일 불러오기",loadedFile:"불러온 파일",supported:".txt · .md · .csv",invalidFile:"TXT, MD, CSV 텍스트 파일만 사용할 수 있습니다.",readFailed:"파일 내용을 읽지 못했습니다. 다른 파일로 다시 시도해 주세요.",replaceWarning:"새 파일을 불러오면 현재 입력과 분석 결과가 초기화됩니다. 계속하시겠습니까?",cancelReplace:"취소",confirmReplace:"확인",inputLabel:"원문 텍스트",inputHelp:"키워드 빈도와 중복 문장을 분석할 원문입니다.",privacy:"로컬 처리 · 서버 업로드 없음",local:"입력한 원문과 분석 결과는 서버로 전송하거나 저장하지 않고 현재 브라우저에서만 처리합니다.",placeholder:"분석할 글·원고·상품 설명을 붙여넣으세요.",analyze:"분석하기",sample:"예시 넣기",reset:"전체 지우기",summary:"분석 요약",total:"전체 단어",unique:"고유 단어",dup:"중복 문장",sentences:"전체 문장",top:"상위 키워드",all:"전체 단어 빈도",repeat:"반복·중복 문장",rank:"순위",keyword:"키워드",count:"횟수",density:"밀도",positions:"문장 위치",none:"반복·중복 문장이 없습니다.",more:"전체 보기",less:"상위 20개만",empty:"분석할 텍스트를 입력해 주세요.",noWords:"분석 가능한 단어가 없습니다.",limit:"입력량이 서비스 상한을 초과했습니다.",limitInfo:`현재 서비스 상한: ${TOOL044_SERVICE_LIMITS.maxCharacters.toLocaleString("ko-KR")}자 · ${TOOL044_SERVICE_LIMITS.maxSentences.toLocaleString("ko-KR")}문장 · 고유 키워드 ${TOOL044_SERVICE_LIMITS.maxUniqueKeywords.toLocaleString("ko-KR")}개`,occ:"회"},
en:{inputTitle:"Type, paste, or drop a text file",dropHint:"You can also drop a TXT, MD, or CSV file anywhere in this workspace.",chooseFile:"Choose text file",replaceFile:"Load another file",loadedFile:"Loaded file",supported:".txt · .md · .csv",invalidFile:"Only TXT, MD, and CSV text files are supported.",readFailed:"Could not read this file. Please try another file.",replaceWarning:"Loading a new file will reset the current input and analysis result. Continue?",cancelReplace:"Cancel",confirmReplace:"Continue",inputLabel:"Source text",inputHelp:"Source text used for keyword frequency and duplicate-sentence analysis.",privacy:"Local processing · No server upload",local:"Your source text and analysis stay in this browser and are not sent to or stored on a server.",placeholder:"Paste an article, draft, or product description to analyze.",analyze:"Analyze",sample:"Insert sample",reset:"Clear all",summary:"Analysis summary",total:"Total words",unique:"Unique words",dup:"Duplicate sentences",sentences:"Sentences",top:"Top keywords",all:"All word frequencies",repeat:"Repeated & duplicate sentences",rank:"Rank",keyword:"Keyword",count:"Count",density:"Density",positions:"Sentence positions",none:"No repeated or duplicate sentences.",more:"Show all",less:"Top 20 only",empty:"Enter text to analyze.",noWords:"No analyzable words were found.",limit:"The input exceeds the service limit.",limitInfo:`Service limit: ${TOOL044_SERVICE_LIMITS.maxCharacters.toLocaleString("en-US")} characters · ${TOOL044_SERVICE_LIMITS.maxSentences.toLocaleString("en-US")} sentences · ${TOOL044_SERVICE_LIMITS.maxUniqueKeywords.toLocaleString("en-US")} unique keywords`,occ:"times"},
ja:{inputTitle:"テキストを入力・貼り付け・ファイル読込",dropHint:"TXT・MD・CSVファイルをこの作業エリアへドラッグ＆ドロップできます。",chooseFile:"テキストファイルを選択",replaceFile:"別のファイルを読み込む",loadedFile:"読み込んだファイル",supported:".txt · .md · .csv",invalidFile:"TXT・MD・CSVのテキストファイルのみ使用できます。",readFailed:"ファイルを読み込めませんでした。別のファイルで再試行してください。",replaceWarning:"新しいファイルを読み込むと現在の入力と分析結果が初期化されます。続けますか？",cancelReplace:"キャンセル",confirmReplace:"確認",inputLabel:"原文テキスト",inputHelp:"キーワード頻度と重複文を分析する原文です。",privacy:"ローカル処理 · サーバー送信なし",local:"入力した原文と分析結果はサーバーへ送信・保存せず、このブラウザ内だけで処理します。",placeholder:"分析する記事・原稿・商品説明を貼り付けてください。",analyze:"分析する",sample:"サンプル入力",reset:"すべてクリア",summary:"分析サマリー",total:"総単語数",unique:"固有単語",dup:"重複文",sentences:"文数",top:"上位キーワード",all:"全単語頻度",repeat:"反復・重複文",rank:"順位",keyword:"キーワード",count:"回数",density:"密度",positions:"文の位置",none:"反復・重複文はありません。",more:"すべて表示",less:"上位20件のみ",empty:"分析するテキストを入力してください。",noWords:"分析できる単語がありません。",limit:"入力がサービス上限を超えています。",limitInfo:`サービス上限: ${TOOL044_SERVICE_LIMITS.maxCharacters.toLocaleString("ja-JP")}文字 · ${TOOL044_SERVICE_LIMITS.maxSentences.toLocaleString("ja-JP")}文 · 固有キーワード${TOOL044_SERVICE_LIMITS.maxUniqueKeywords.toLocaleString("ja-JP")}件`,occ:"回"}
} as const;
function isSupportedTextFile(file:File){const extension=file.name.split(".").pop()?.toLowerCase()??"";return ACCEPTED_EXTENSIONS.includes(extension as (typeof ACCEPTED_EXTENSIONS)[number]);}
function formatBytes(size:number,locale:Locale){if(size<1024)return `${size.toLocaleString()} B`;const localeId=locale==="ko"?"ko-KR":locale==="ja"?"ja-JP":"en-US";return `${(size/1024).toLocaleString(localeId,{maximumFractionDigits:1})} KB`;}
export function KeywordFrequencyDuplicateTool({locale}:{locale:Locale}){
 const t=copy[locale],localeId=locale==="ko"?"ko-KR":locale==="ja"?"ja-JP":"en-US";
 const [text,setText]=useState(""),[result,setResult]=useState<Tool044Result|null>(null),[error,setError]=useState(""),[showAll,setShowAll]=useState(false),[loadedFile,setLoadedFile]=useState<LoadedFile|null>(null),[hasStarted,setHasStarted]=useState(false),[dragActive,setDragActive]=useState(false),[pendingFile,setPendingFile]=useState<File|null>(null);
 const fileInput=useRef<HTMLInputElement>(null);
 const rows=useMemo(()=>result?(showAll?result.keywords:result.topKeywords):[],[result,showAll]);
 const hasCurrentWork=Boolean(hasStarted||text||loadedFile||result||error);
 const invalidate=()=>{setResult(null);setError("");setShowAll(false);};
 const updateText=(value:string)=>{setHasStarted(true);setText(value);invalidate();};
 const run=()=>{setError("");setShowAll(false);if(!text.trim()){setResult(null);setError(t.empty);return;}const errs=validateTool044(text,locale);if(errs.length){setResult(null);setError(t.limit);return;}const next=analyzeTool044(text,locale);setResult(next);if(next.totalWords===0)setError(t.noWords);};
 const reset=()=>{setText("");setResult(null);setError("");setShowAll(false);setLoadedFile(null);setHasStarted(false);setDragActive(false);setPendingFile(null);if(fileInput.current)fileInput.current.value="";};
 const sample=()=>{setLoadedFile(null);updateText(locale==="ko"?"사과와 배를 소개합니다. 사과는 달콤합니다.\n배도 맛있습니다. 사과는 달콤합니다.\n사과 사과 배":locale==="ja"?"猫が好きです。犬も好きです。猫が好きです。\n猫 犬 猫":`Apple and banana are useful keywords. Apple is popular.\nBanana is useful. Apple is popular.\napple apple banana`);};
 const loadFile=async(file:File)=>{setDragActive(false);try{const content=await file.text();setText(content);setResult(null);setError("");setShowAll(false);setLoadedFile({name:file.name,size:file.size});setHasStarted(true);}catch{setError(t.readFailed);}finally{if(fileInput.current)fileInput.current.value="";}};
 const requestFileLoad=(file:File)=>{setDragActive(false);if(!isSupportedTextFile(file)){setError(t.invalidFile);if(fileInput.current)fileInput.current.value="";return;}if(hasCurrentWork){setPendingFile(file);return;}void loadFile(file);};
 const cancelFileReplace=()=>{setPendingFile(null);if(fileInput.current)fileInput.current.value="";};
 const confirmFileReplace=()=>{const file=pendingFile;setPendingFile(null);if(file)void loadFile(file);};
 const onDragEnter=(e:DragEvent<HTMLElement>)=>{if(!Array.from(e.dataTransfer.types).includes("Files"))return;e.preventDefault();setDragActive(true);};
 const onDragOver=(e:DragEvent<HTMLElement>)=>{if(!Array.from(e.dataTransfer.types).includes("Files"))return;e.preventDefault();e.dataTransfer.dropEffect="copy";setDragActive(true);};
 const onDragLeave=(e:DragEvent<HTMLElement>)=>{const next=e.relatedTarget as Node|null;if(!next||!e.currentTarget.contains(next))setDragActive(false);};
 const onDrop=(e:DragEvent<HTMLElement>)=>{if(!Array.from(e.dataTransfer.types).includes("Files"))return;e.preventDefault();setDragActive(false);const file=e.dataTransfer.files?.[0];if(file)requestFileLoad(file);};
 return <div className={inputCommon.root} data-testid="tool044-root">
  <div className={inputCommon.localNotice} data-testid="tool044-local-notice"><strong>LOCAL</strong><span>{t.local}</span></div>
  <input ref={fileInput} className={inputCommon.hiddenInput} type="file" accept=".txt,.md,.csv,text/plain,text/markdown,text/csv" data-testid="tool044-file-input" onChange={e=>{const f=e.currentTarget.files?.[0];if(f)requestFileLoad(f)}}/>
  <section className={`${inputCommon.workspaceSurface} ${dragActive?inputCommon.workspaceDragging:""}`} data-testid="tool044-workspace" data-drag-active={dragActive?"true":"false"} onDragEnter={onDragEnter} onDragOver={onDragOver} onDragLeave={onDragLeave} onDrop={onDrop}>
   <div className={inputCommon.editorCard} data-testid="tool044-input-zone">
    {loadedFile&&<div className={inputCommon.fileBar} data-testid="tool044-file-info"><div><span>{t.loadedFile}</span><strong>{loadedFile.name}</strong><small>{formatBytes(loadedFile.size,locale)} · {t.supported}</small></div><button type="button" className={inputCommon.button} onClick={()=>fileInput.current?.click()}>{t.replaceFile}</button></div>}
    <div className={inputCommon.textareaShell}>
     {!hasStarted&&!loadedFile&&<div className={inputCommon.startDropzone} data-testid="tool044-start-dropzone"><span className={inputCommon.plusIcon} aria-hidden="true">+</span><h2>{t.inputTitle}</h2><p>{t.dropHint}</p><button type="button" className={inputCommon.fileButton} onClick={()=>fileInput.current?.click()} data-testid="tool044-file-button">{t.chooseFile}</button></div>}
     <label className={inputCommon.visibleLabel} htmlFor="tool044-input">{t.inputLabel}</label>
     <textarea id="tool044-input" data-testid="tool044-input" className={`${inputCommon.textarea} ${hasStarted||loadedFile?inputCommon.textareaLoaded:inputCommon.textareaInitial}`} value={text} maxLength={TOOL044_SERVICE_LIMITS.maxCharacters+1} onChange={e=>updateText(e.currentTarget.value)} placeholder={t.placeholder} aria-describedby="tool044-limit"/>
     <div className={inputCommon.editorHead}><span>{t.inputHelp}</span><em>{text.length.toLocaleString(localeId)} / {TOOL044_SERVICE_LIMITS.maxCharacters.toLocaleString(localeId)}</em></div>
    </div>
    <div className={inputCommon.editorFoot}><p className={inputCommon.privacy} id="tool044-limit">{t.privacy} · {t.limitInfo}</p><div className={inputCommon.textActions}><button type="button" className={inputCommon.button} onClick={sample} data-testid="tool044-sample">{t.sample}</button><button type="button" data-testid="tool044-reset" className={inputCommon.button} onClick={reset} disabled={!hasCurrentWork}>{t.reset}</button></div></div>
   </div>
   <div className={inputCommon.actionRow}><button type="button" data-testid="tool044-run" className={inputCommon.primaryButton} onClick={run} disabled={!text.trim()}>{t.analyze}</button></div>
   {error&&<p className={inputCommon.error} role="status" data-testid="tool044-error">{error}</p>}
   {result&&<>
    <section className={inputCommon.editorCard} data-testid="tool044-result">
     <div className={styles.resultTitle}><p>RESULT</p><h2>{t.summary}</h2></div>
     <div className={`${inputCommon.secondaryGrid} ${styles.summaryGrid}`}><Stat label={t.total} value={result.totalWords}/><Stat label={t.unique} value={result.uniqueWords}/><Stat label={t.sentences} value={result.sentenceCount}/><Stat label={t.dup} value={result.duplicateSentenceGroups}/></div>
     <section className={styles.section}><div className={styles.sectionHead}><div><p>KEYWORDS</p><h3>{showAll?t.all:t.top}</h3></div>{result.keywords.length>TOOL044_SERVICE_LIMITS.defaultVisibleKeywords&&<button type="button" data-testid="tool044-toggle-all" className={inputCommon.button} onClick={()=>setShowAll(v=>!v)}>{showAll?t.less:t.more}</button>}</div><KeywordTable rows={rows} t={t}/></section>
     <section className={styles.section}><div className={styles.sectionHead}><div><p>SENTENCES</p><h3>{t.repeat}</h3></div></div>{result.duplicates.length?<div className={styles.duplicateList} data-testid="tool044-duplicates">{result.duplicates.map((g,i)=><article className={styles.duplicateCard} key={`${g.positions[0]}-${i}`}><header><strong>{g.count} {t.occ}</strong><span>{t.positions}: {g.positions.join(", ")}</span></header><p>{g.representative}</p></article>)}</div>:<div className={styles.emptyResult} data-testid="tool044-no-duplicates">{t.none}</div>}</section>
    </section>
   </>}
  </section>
  {pendingFile&&<div className={inputCommon.dialogBackdrop} role="presentation"><section className={inputCommon.confirmDialog} role="dialog" aria-modal="true" aria-labelledby="tool044-replace-title"><h2 id="tool044-replace-title">{t.replaceFile}</h2><p>{t.replaceWarning}</p><div className={inputCommon.dialogActions}><button type="button" className={inputCommon.button} onClick={cancelFileReplace}>{t.cancelReplace}</button><button type="button" className={inputCommon.primaryButton} onClick={confirmFileReplace}>{t.confirmReplace}</button></div></section></div>}
 </div>
}
function Stat({label,value}:{label:string;value:number}){return <div className={inputCommon.secondaryCard}><span>{label}</span><strong>{value.toLocaleString()}</strong></div>}
function KeywordTable({rows,t}:{rows:readonly {rank:number;keyword:string;count:number;density:number}[];t:(typeof copy)[keyof typeof copy]}){return <div className={styles.tableWrap}><table data-testid="tool044-keyword-table"><thead><tr><th>{t.rank}</th><th>{t.keyword}</th><th>{t.count}</th><th>{t.density}</th></tr></thead><tbody>{rows.map(r=><tr key={`${r.rank}-${r.keyword}`}><td>{r.rank}</td><td>{r.keyword}</td><td>{r.count}</td><td>{r.density.toFixed(2)}%</td></tr>)}</tbody></table></div>}
