import { ToolNavigation } from "@/components/tool-navigation";
import Link from "next/link";
import { ListSorterDuplicateRemoverTool } from "@/components/list-sorter-duplicate-remover-tool";
import { ToolboxFaqList } from "@/components/toolbox-faq-list";
import { ToolboxSubpageShell } from "@/components/toolbox-subpage-shell";
import type { Locale } from "@/lib/site";

const copy={
  ko:{back:"텍스트 도구",title:"목록 정렬·중복 제거기",desc:"한 줄에 하나씩 붙여넣은 목록에서 중복을 제거하고 가나다·알파벳·숫자순, 역순, 무작위 섞기를 브라우저에서 바로 실행하세요.",local:"원문과 결과는 브라우저 로컬에서만 처리합니다.",next:"다음 작업",related:"관련 도구",available:"사용 가능",coming:"준비 중",how:"사용 방법",guide:"목록을 안전하게 정렬하는 기준",guideDesc:"중복 판정, 언어별 정렬, 숫자 비교, 역순과 무작위 섞기의 차이를 구분하면 원문 의미를 바꾸지 않고 목록을 정리할 수 있습니다.",caution:"주의사항",faq:"자주 묻는 질문",steps:["한 줄에 항목 하나씩 원본 목록을 붙여넣습니다.","중복 제거·가나다/알파벳·숫자순·역순·무작위 섞기 중 하나를 선택합니다.","입력 줄 수와 결과를 확인합니다.","결과를 복사하거나 초기화해 새 작업을 시작합니다."],points:[["EXACT","중복은 완전히 같은 줄만 제거","기본 중복 판정은 대소문자와 앞뒤 공백까지 포함한 줄 전체의 정확 일치입니다. 첫 출현은 유지하고 이후 같은 줄만 제거합니다."],["LOCALE","페이지 언어 기준 텍스트 정렬","한국어 페이지는 ko, 영어는 en, 일본어는 ja Intl.Collator를 사용합니다. 혼합 언어의 상대 순서는 페이지 언어에 따라 달라질 수 있습니다."],["NUMERIC","숫자는 문자열과 별도 비교","1, 2, 10을 문자열순이 아니라 실제 수치순으로 정렬합니다. 비숫자 줄은 숫자 뒤에서 원래 상대 순서를 유지합니다."],["REVERSE","역순은 내림차순이 아님","역순은 가나다나 숫자 comparator를 호출하지 않고 현재 원본 줄 순서만 통째로 뒤집습니다."],["SHUFFLE","섞기는 항목 개수를 보존","무작위 섞기는 같은 항목 집합과 중복 개수를 유지하고 순서만 바꿉니다. 추첨 인증 도구로 사용하지 않습니다."]],cautions:["039는 공백·빈 줄을 자동 삭제하거나 trim하지 않습니다. 그런 정리는 037의 역할입니다.","숫자순은 -3, +2, .5, 1e3 같은 유한 숫자 형식만 숫자로 보고 1,000·12px·Infinity·NaN은 비숫자로 처리합니다.","혼합 언어 텍스트 정렬은 페이지 언어의 collation 규칙에 따라 결과가 달라질 수 있습니다.","서비스 상한은 현재 후보값이며 최종값은 사용자 승인 후 동기화해야 합니다."],faqs:[["숫자 10이 2 뒤로 가나요?","네. 숫자순 모드는 실제 Number 값으로 비교하므로 1, 2, 10 순서가 됩니다."],["Apple과 apple은 같은 중복인가요?","아닙니다. 기본 중복 제거는 대소문자와 공백까지 포함한 exact line match입니다."],["역순과 내림차순은 무엇이 다른가요?","역순은 현재 원본 줄 순서를 뒤집을 뿐이며 가나다·알파벳·숫자 기준으로 다시 정렬하지 않습니다."],["무작위 섞기 결과를 다시 재현할 수 있나요?","기본적으로 재현을 보장하지 않습니다. 다시 섞기를 누를 때 새 순서를 만듭니다."],["한글·영어·일본어가 섞이면 어떤 순서인가요?","현재 페이지 언어의 Intl.Collator 기준으로 정렬하므로 언어별 결과가 달라질 수 있습니다."],["입력한 목록이 서버로 전송되나요?","아니요. 입력과 결과는 현재 브라우저 메모리에서만 처리합니다."]]},
  en:{back:"Text Tools",title:"List Sorter & Duplicate Remover",desc:"Paste one item per line to remove duplicate lines, sort alphabetically or numerically, reverse the order, or shuffle the list directly in your browser.",local:"Source and result are processed locally in your browser.",next:"Next work",related:"Related tools",available:"Available",coming:"Coming soon",how:"How to use",guide:"How to sort lists without changing their meaning",guideDesc:"Separate exact duplicate matching, locale-aware text sorting, numeric comparison, reverse order, and shuffling to keep list transformations predictable.",caution:"Important notes",faq:"Frequently asked questions",steps:["Paste one list item per line.","Choose duplicate removal, alphabetical, numeric, reverse, or shuffle.","Review the line counts and actual result.","Copy the result or reset for a new list."],points:[["EXACT","Only exact duplicate lines are removed","Matching is case- and whitespace-sensitive by default. The first occurrence remains and later identical lines are removed."],["LOCALE","Text sort follows the page language","The Korean page uses ko, English uses en, and Japanese uses ja with Intl.Collator. Mixed-language order may differ by page locale."],["NUMERIC","Numeric comparison is separate","Numeric mode compares actual finite numbers, so 1, 2, 10 is different from string sorting. Non-numeric lines remain at the end in stable order."],["REVERSE","Reverse is not descending sort","Reverse changes only the source line order and does not call the text or numeric comparator."],["SHUFFLE","Shuffle preserves the multiset","Shuffling changes order only; item counts and duplicates remain. It is not marketed as a certified drawing tool."]],cautions:["This tool does not silently trim whitespace or remove blank lines; that belongs to tool 037.","Numeric mode accepts finite numeric forms such as -3, +2, .5, and 1e3, while 1,000, 12px, Infinity, and NaN stay non-numeric.","Mixed-language text sort order depends on the current page locale.","The current service limits are candidates and must be synchronized after user approval."],faqs:[["Will 10 sort after 2?","Yes. Numeric mode compares Number values, giving 1, 2, 10."],["Are Apple and apple duplicates?","No. Default duplicate removal uses exact, case-sensitive and whitespace-sensitive line matching."],["How is reverse different from descending sort?","Reverse simply flips the current source line order without sorting by text or number."],["Can I reproduce a shuffle later?","Not by default. Shuffle again creates a new permutation."],["How are mixed languages sorted?","Intl.Collator uses the current page locale, so results can differ by language page."],["Is my list uploaded?","No. Source and result stay in browser memory."]]},
  ja:{back:"テキストツール",title:"一覧並べ替え・重複削除ツール",desc:"1行に1項目ずつ貼り付けた一覧から重複行を削除し、五十音・アルファベット・数値順、逆順、シャッフルをブラウザですぐ実行できます。",local:"原文と結果はブラウザ内だけで処理します。",next:"次の作業",related:"関連ツール",available:"利用可能",coming:"準備中",how:"使い方",guide:"一覧を安全に並べ替える基準",guideDesc:"完全一致の重複判定、言語別ソート、数値比較、逆順、シャッフルを分けて扱うと、原文の意味を変えずに整理できます。",caution:"注意事項",faq:"よくある質問",steps:["1行に1項目ずつ元の一覧を貼り付けます。","重複削除・五十音/アルファベット・数値順・逆順・シャッフルから選びます。","入力行数と実際の結果を確認します。","結果をコピーするかリセットして新しい作業を始めます。"],points:[["EXACT","重複は完全に同じ行だけ削除","大文字小文字と前後空白を含む行全体の完全一致が基本です。最初の出現を残し、後の同一行だけ削除します。"],["LOCALE","ページ言語を基準に文字列ソート","韓国語ページはko、英語はen、日本語はjaのIntl.Collatorを使います。混在言語の順序はページ言語によって変わる場合があります。"],["NUMERIC","数値は文字列と別に比較","1、2、10を文字列順ではなく実数値で並べます。非数値行は数値の後ろで元の相対順序を維持します。"],["REVERSE","逆順は降順ソートではありません","逆順は文字列・数値比較を行わず、現在の元リストの行順だけを反転します。"],["SHUFFLE","シャッフルは項目数を保持","同じ項目集合と重複数を保ったまま順序だけを変更します。抽選認証ツールではありません。"]],cautions:["039は空白や空行を自動削除・trimしません。これは037の役割です。","数値順は-3、+2、.5、1e3などの有限数値だけを数値として扱い、1,000・12px・Infinity・NaNは非数値です。","混在言語の文字列順は現在のページ言語の照合規則によって変わる場合があります。","サービス上限は現在候補値で、最終値はユーザー承認後に同期する必要があります。"],faqs:[["10は2の後ろに並びますか？","はい。数値順では実際のNumber値を比較するため1、2、10になります。"],["Appleとappleは同じ重複ですか？","いいえ。標準では大文字小文字と空白を含む完全一致で重複判定します。"],["逆順と降順は何が違いますか？","逆順は現在の元リストを反転するだけで、文字列や数値で再ソートしません。"],["シャッフル結果を再現できますか？","標準では再現を保証しません。もう一度シャッフルすると新しい順序になります。"],["日本語・英語・韓国語が混在するとどう並びますか？","現在のページ言語のIntl.Collator基準で並べるため、言語ページごとに結果が変わる場合があります。"],["入力一覧はサーバーへ送信されますか？","いいえ。入力と結果はブラウザメモリ内だけで処理します。"]]}
} as const;

export function ListSorterDuplicateRemoverPage({locale}:{locale:Locale}){
 const t=copy[locale]; const url=`https://toolbox.fixlgs.com/${locale}/list-sorter-duplicate-remover`;
 const related=[{n:"037",slug:"text-whitespace-linebreak-cleaner",name:locale==="ko"?"텍스트 공백·줄바꿈 정리기":locale==="ja"?"テキスト空白・改行整理ツール":"Text Whitespace & Line Break Cleaner",active:true},{n:"038",slug:"case-sentence-format-converter",name:locale==="ko"?"대소문자·문장 형식 변환기":locale==="ja"?"大文字・小文字・文形式変換ツール":"Case & Sentence Format Converter",active:true},{n:"036",slug:"character-document-counter",name:locale==="ko"?"글자 수·문서 통계 계산기":locale==="ja"?"文字数・文書統計カウンター":"Character & Document Statistics Counter",active:true}];
 const jsonLd={"@context":"https://schema.org","@graph":[{"@type":"WebApplication",name:t.title,applicationCategory:"UtilitiesApplication",operatingSystem:"Any",url,description:t.desc,offers:{"@type":"Offer",price:"0",priceCurrency:"USD"}},{"@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:"TOOLBOX",item:`https://toolbox.fixlgs.com/${locale}`},{"@type":"ListItem",position:2,name:t.back,item:`https://toolbox.fixlgs.com/${locale}/category/text`},{"@type":"ListItem",position:3,name:t.title,item:url}]},{"@type":"FAQPage",mainEntity:t.faqs.map(([q,a])=>({"@type":"Question",name:q,acceptedAnswer:{"@type":"Answer",text:a}}))}]};
 return <ToolboxSubpageShell locale={locale} appName={t.title}>
  <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(jsonLd)}}/>
  <section className="toolbox-tool-detail-hero toolbox-tool-detail-hero--single-line-description"><Link className="toolbox-subpage-back" href={`/${locale}/category/text`}>← {t.back}</Link><p className="toolbox-subpage-eyebrow">039 · TEXT</p><div className="toolbox-tool-detail-heading"><h1><span className="toolbox-tool-title-line">{t.title}</span></h1><p>{t.desc}</p></div><div className="toolbox-tool-detail-badge"><strong>LOCAL</strong><span>{t.local}</span></div></section>
  <section className="toolbox-tool-detail-body"><div><ListSorterDuplicateRemoverTool locale={locale}/><ToolNavigation locale={locale} currentTool={39} /></div></section>
  <section className="toolbox-tool-guide toolbox-tool-guide--five"><div className="toolbox-tool-guide-head"><p>HOW TO USE</p><h2>{t.how}</h2></div><ol>{t.steps.map((step,index)=><li key={step}><span>{String(index+1).padStart(2,"0")}</span><p>{step}</p></li>)}</ol></section>
  <section className="toolbox-tool-format-guide toolbox-tool-expert-post toolbox-tool-expert-post--wide-head"><div className="toolbox-tool-format-guide-head"><p>LIST SORTING GUIDE</p><h2>{t.guide}</h2><span>{t.guideDesc}</span></div><div className="toolbox-tool-format-body"><div className="toolbox-tool-format-grid">{t.points.map(([n,h,p])=><article key={n}><strong>{n}</strong><h3>{h}</h3><p>{p}</p></article>)}</div></div></section>
  <section className="toolbox-tool-info-band toolbox-tool-info-band--section-start toolbox-tool-info-band--bottom-gap toolbox-tool-info-band--left-head toolbox-tool-info-band--format-head toolbox-tool-info-band--full-divider"><div className="toolbox-tool-info-band-head"><p>IMPORTANT NOTES</p><h2>{t.caution}</h2></div><ul className="toolbox-tool-info-band-list">{t.cautions.map(item=><li key={item}>{item}</li>)}</ul></section>
  <section className="toolbox-tool-faq"><div className="toolbox-tool-guide-head"><p>FAQ</p><h2>{t.faq}</h2></div><ToolboxFaqList items={t.faqs.map(([q,a]):readonly[string,string]=>[q,a])} initialCount={5} moreLabel={locale==="ko"?"FAQ 더보기":locale==="ja"?"FAQをもっと見る":"Show more FAQs"} collapseLabel={locale==="ko"?"FAQ 접기":locale==="ja"?"FAQを閉じる":"Collapse FAQs"} className="toolbox-tool-faq-list"/></section>
 </ToolboxSubpageShell>;
}
