import Link from "next/link";
import type { Locale } from "@/lib/site";
import { ToolboxSubpageShell } from "./toolbox-subpage-shell";
import { ToolboxFaqList } from "./toolbox-faq-list";
import { PdfPageOrganizerTool } from "./pdf-page-organizer-tool";
import { TOOL030_LIMIT_DISPLAY } from "@/lib/tool-030-pdf";

const copy = {
  ko: {
    back: "PDF 도구", title: "PDF 페이지 정리 도구", desc: "PDF 한 개의 페이지를 삭제·이동·복제·회전하고 역순 정렬이나 빈 페이지 추가까지 한 화면에서 정리하세요.",
    local: "PDF는 서버로 전송하거나 저장하지 않고 현재 브라우저에서 처리합니다.", next: "다음 작업", related: "관련 도구", how: "사용 방법", caution: "주의사항", faq: "자주 묻는 질문", more: "FAQ 더보기", less: "FAQ 접기",
    steps: ["PDF를 선택하면 전체 페이지 썸네일과 현재 순서를 확인합니다.", "한 장 또는 여러 장을 선택해 삭제·이동·복제·회전하고 필요하면 빈 페이지를 추가합니다.", "전체 순서가 반대로 들어온 문서는 역순 정렬을 사용하고, 실수하면 실행 취소로 되돌립니다.", "변경 요약과 결과 파일명을 확인한 뒤 PDF를 저장합니다.", "생성된 PDF의 페이지 수·회전·크기를 재검증한 결과를 확인하고 다운로드합니다."],
    examples: [["역순으로 스캔된 문서 바로잡기", "스캔 앱에서 마지막 장부터 들어온 문서는 역순 정렬 한 번으로 전체 페이지를 뒤집고, 표지용 빈 페이지를 맨 앞에 추가할 수 있습니다."], ["불필요한 페이지 삭제 + 순서 교정", "계약서 중 중복 스캔된 페이지를 여러 장 선택해 삭제하고, 잘못 끼어든 페이지를 드래그 또는 이동 버튼으로 제자리로 옮깁니다."], ["서명 페이지 복제 + 가로 페이지 회전", "서명용 페이지를 원본 바로 뒤에 복제하고, 가로로 누운 스캔 페이지만 90도 회전해 한 PDF 안에서 정리합니다."]],
    expertTitle: "PDF 페이지를 품질 저하 없이 정리하는 실전 기준", expertLead: "페이지 객체 복사, 회전 metadata, 빈 페이지 크기, 모바일 이동과 실행 취소까지 결과 PDF 구조를 안전하게 유지하는 기준입니다.",
    expert: [["페이지 정리와 PDF 내용 편집을 구분", "030은 문서의 텍스트나 이미지를 수정하는 편집기가 아니라 페이지 단위 구조를 정리하는 도구입니다. 삭제·이동·복제·회전·빈 페이지 추가처럼 페이지 배열을 바꾸는 작업만 수행하므로 OCR, 서명, 워터마크, 페이지 번호와 같은 기능은 다른 도구로 분리하는 것이 맞습니다."], ["결과 PDF는 썸네일 캡처로 만들지 않기", "화면 미리보기는 Canvas 썸네일을 사용할 수 있지만 저장 결과는 원본 페이지 객체를 복사해 새 PDF에 배치하는 방식을 사용합니다. 이렇게 해야 원본의 벡터·텍스트·이미지를 다시 픽셀 이미지로 만들면서 발생하는 불필요한 화질 저하를 피할 수 있습니다."], ["현재 번호와 원본 번호를 따로 보기", "페이지를 삭제하거나 이동하면 현재 페이지 번호는 계속 바뀝니다. 원본 출처 번호를 함께 표시하면 복제 페이지가 어디에서 왔는지, 이동 후 어떤 원본 페이지를 보고 있는지 추적하기 쉬워집니다."], ["회전은 미리보기와 실제 PDF를 같은 값으로 유지", "화면만 CSS로 돌리고 PDF rotation 값을 바꾸지 않으면 다운로드 후 다시 옆으로 누울 수 있습니다. 0·90·180·270도로 정규화한 회전값을 편집 state와 결과 PDF에 동일하게 적용하고 저장 후 재열기에서 다시 확인하는 것이 안전합니다."], ["모바일에서는 drag만 유일한 이동 수단으로 쓰지 않기", "작은 화면에서는 페이지 카드 드래그가 세로 스크롤과 충돌하기 쉽습니다. 위·아래·맨앞·맨뒤 이동 버튼을 함께 제공하면 긴 문서에서도 터치로 페이지를 안정적으로 옮길 수 있고 접근성 대체 조작도 확보됩니다."], ["빈 페이지 크기는 인접 문서 기준이 자연스럽기", "스캔 PDF에 표지나 메모용 빈 페이지를 넣을 때 기존 페이지와 크기가 달라지면 인쇄 결과가 어색해질 수 있습니다. 기본은 인접 페이지 크기를 따라가고 A4·Letter가 필요한 경우만 명시적으로 선택하는 방식이 실사용에 적합합니다."], ["Undo/Redo는 PDF 바이너리가 아니라 편집 state를 저장", "작업마다 PDF 전체 파일을 복제해 history로 남기면 페이지 수가 늘수록 메모리가 급격히 커집니다. 페이지 배열과 회전·출처·빈 페이지 정보만 기록하면 삭제·이동·복제·회전·역순을 빠르게 되돌리면서 브라우저 메모리를 줄일 수 있습니다."], ["큰 PDF는 페이지 수와 썸네일 렌더링을 함께 제한", "파일 용량만 작아도 페이지가 매우 많으면 썸네일 렌더링과 state 관리가 무거워질 수 있습니다. 따라서 입력 용량, 원본 페이지 수, 편집 후 페이지 수, 썸네일 동시 처리량을 별도 기준으로 관리하고 PC·모바일에서 안정적인 낮은 값을 우선해야 합니다."]],
    cautions: ["원본 PDF 파일 자체는 수정하지 않고 새 결과 PDF를 생성합니다.", "암호화된 PDF의 비밀번호를 우회하거나 해제하지 않습니다.", "전자서명·디지털 서명이 있는 PDF는 페이지 재구성 후 기존 서명 유효성이 달라질 수 있습니다.", "PDF 압축·OCR·텍스트 편집·워터마크·페이지 번호는 이 도구의 범위가 아닙니다.", `서비스 상한은 ${TOOL030_LIMIT_DISPLAY.maxFileMiB}MB, 원본 ${TOOL030_LIMIT_DISPLAY.maxSourcePages}페이지, 편집 후 ${TOOL030_LIMIT_DISPLAY.maxEditedPages}페이지입니다. 썸네일은 동시 2개, 실행 취소·다시 실행 이력은 30단계까지 유지합니다.`],
    faqs: [["페이지를 삭제하면 원본 PDF도 바뀌나요?", "아니요. 브라우저에서 새 결과 PDF를 만들며 사용자가 가진 원본 파일 자체는 수정하지 않습니다."], ["페이지 순서를 바꾸면 화질이 떨어지나요?", "페이지 객체를 가능한 그대로 복사하는 방식으로 설계하며 썸네일을 캡처해 결과 PDF를 만들지 않습니다."], ["여러 페이지를 한 번에 회전할 수 있나요?", "예. 여러 페이지를 선택한 뒤 왼쪽 또는 오른쪽으로 90도 단위 일괄 회전할 수 있습니다."], ["빈 페이지 크기는 어떻게 정해지나요?", "기본은 인접 페이지 크기를 따라가며, 필요하면 A4 또는 Letter를 선택할 수 있습니다."], ["역순 정렬을 잘못 누르면 되돌릴 수 있나요?", "예. 역순 정렬을 포함한 주요 페이지 편집은 실행 취소와 다시 실행 history에 포함됩니다."], ["여러 PDF를 한 번에 합칠 수 있나요?", "아니요. 030은 한 PDF 내부 페이지 정리에 집중합니다. 여러 PDF 병합은 028 PDF 합치기를 사용합니다."], ["페이지를 별도 PDF로 추출할 수 있나요?", "아니요. 페이지 추출·분할은 029 PDF 분할·페이지 추출기의 역할입니다."], ["파일이 서버에 올라가나요?", "아니요. 지원 가능한 처리는 현재 브라우저에서 수행하며 사용자 PDF를 FIXLGS 서버에 저장하지 않습니다."]],
  },
  en: {
    back: "PDF Tools", title: "PDF Page Organizer", desc: "Delete, reorder, duplicate and rotate pages inside one PDF, reverse the full order, or insert blank pages in one workspace.", local: "Your PDF is processed in the current browser and is not uploaded or stored on our server.", next: "Next work", related: "Related tools", how: "How to use", caution: "Important notes", faq: "FAQ", more: "Show more FAQ", less: "Hide FAQ",
    steps: ["Choose one PDF and review all page thumbnails and the current order.", "Select one or multiple pages, then delete, move, duplicate, rotate, or insert a blank page.", "Use Reverse Order for fully reversed scans and Undo if the change was not intended.", "Review the change summary and output filename, then save the new PDF.", "Confirm the result recheck for page count, rotation, and page sizes, then download the file."],
    examples: [["Fix a PDF scanned in reverse", "Reverse the entire page order in one action and insert a blank cover page at the beginning."], ["Remove unwanted scans and fix order", "Delete duplicate scans in a batch, then use drag or movement buttons to return misplaced pages to their proper positions."], ["Duplicate a signature page and rotate landscape scans", "Duplicate the signature page directly after its source and rotate only the pages that were scanned sideways."]],
    expertTitle: "Practical standards for organizing PDF pages without quality loss", expertLead: "Page-object copying, rotation metadata, blank-page sizing, mobile movement, and state history all matter when preserving a stable result PDF.",
    expert: [["Keep page organization separate from content editing", "Tool 030 changes the page-level structure rather than editing text or images inside pages. OCR, signatures, watermarks, page numbers, and document-content editing belong in separate tools."], ["Never build the result from thumbnail screenshots", "Canvas thumbnails are useful for preview, but the saved PDF should copy original page objects into a new document. This avoids unnecessary rasterization of original vector, text, and image content."], ["Show current page numbers and original source numbers", "Current numbers change after deletion and movement. Keeping the original source page number visible makes it easier to identify duplicates and understand where a page came from."], ["Keep preview rotation and PDF rotation identical", "A CSS-only preview rotation can look correct while the downloaded PDF remains sideways. Normalize rotation to 0, 90, 180, or 270 degrees and apply the same value to both edit state and output PDF."], ["Do not make drag the only mobile reorder method", "Dragging page cards can conflict with vertical scrolling on phones. Dedicated move up, move down, first, and last controls provide a reliable touch and accessibility path."], ["Match blank pages to the surrounding document by default", "A cover or note page with a different size can look awkward in print. Matching the adjacent page is the safest default, with explicit A4 or Letter choices when needed."], ["Store Undo/Redo as edit state rather than PDF binaries", "Saving a full PDF copy for every history step wastes memory. Store the page array and page metadata instead so delete, move, duplicate, rotate, reverse, and blank-page operations remain lightweight."], ["Large PDFs need page and rendering limits, not file size alone", "A small file can still contain hundreds of pages. Manage file size, source page count, edited page count, and thumbnail concurrency separately, and prefer limits that remain stable on normal laptops and phones."]],
    cautions: ["The source PDF is never modified; a new result PDF is created.", "Encrypted PDFs are not bypassed or decrypted.", "Rebuilding pages can affect the validity of existing electronic or digital signatures.", "PDF compression, OCR, content editing, watermarks, and page numbers are outside this tool.", `Service limits are ${TOOL030_LIMIT_DISPLAY.maxFileMiB}MB, ${TOOL030_LIMIT_DISPLAY.maxSourcePages} source pages, and ${TOOL030_LIMIT_DISPLAY.maxEditedPages} edited pages. Thumbnail rendering is limited to 2 concurrent jobs and Undo/Redo history to 30 steps.`],
    faqs: [["Does deleting pages change my original PDF?", "No. The original file stays unchanged and a new PDF is created in the browser."], ["Will reordering pages reduce quality?", "The tool is designed to copy original PDF page objects rather than rebuilding the result from thumbnail images."], ["Can I rotate multiple pages at once?", "Yes. Select multiple pages and rotate them left or right in 90-degree steps."], ["How is blank-page size chosen?", "The default follows the adjacent page, with A4 and Letter available as explicit options."], ["Can I undo Reverse Order?", "Yes. Reverse Order is included in the edit-state history and can be undone in one step."], ["Can I merge multiple PDFs here?", "No. Tool 030 organizes one PDF. Use Tool 028 for merging multiple PDFs."], ["Can I extract selected pages into another PDF?", "No. Extraction and splitting belong to Tool 029."], ["Is my PDF uploaded to a server?", "No. Supported processing runs in the current browser and the PDF is not stored on the FIXLGS server."]],
  },
  ja: {
    back: "PDFツール", title: "PDF ページ整理ツール", desc: "1つのPDF内でページの削除・移動・複製・回転・逆順・空白ページ追加をまとめて行えます。", local: "PDFはサーバーへ送信・保存せず、現在のブラウザ内で処理します。", next: "次の作業", related: "関連ツール", how: "使い方", caution: "注意事項", faq: "よくある質問", more: "FAQをもっと見る", less: "FAQを閉じる",
    steps: ["PDFを選択し、全ページのサムネイルと現在の順番を確認します。", "1ページまたは複数ページを選択して、削除・移動・複製・回転・空白ページ追加を行います。", "完全に逆順でスキャンされた文書は逆順に並べ、間違えた場合は元に戻します。", "変更概要と結果ファイル名を確認して新しいPDFを保存します。", "ページ数・回転・ページサイズの結果再検証を確認してダウンロードします。"],
    examples: [["逆順スキャンを一度で修正", "最後のページから取り込まれたPDFを逆順に並べ、表紙用の空白ページを先頭へ追加できます。"], ["不要ページを削除して順番を修正", "重複スキャンを複数選択して削除し、間違った位置のページをドラッグまたは移動ボタンで戻します。"], ["署名ページを複製して横向きページを回転", "署名ページを元ページの直後に複製し、横向きで読み込まれたページだけ90度回転します。"]],
    expertTitle: "画質を落とさずPDFページを整理する実践基準", expertLead: "ページオブジェクトのコピー、回転情報、空白ページサイズ、モバイル移動、履歴管理まで安定したPDF結果のための基準です。",
    expert: [["ページ整理と内容編集を分ける", "030は本文の文字や画像を編集するツールではなく、ページ単位の構造を整理します。OCR、署名、透かし、ページ番号などは別ツールの役割です。"], ["結果PDFをサムネイル画像から作らない", "画面表示にはCanvasサムネイルを使えますが、保存時は元PDFのページオブジェクトを新しいPDFへコピーします。ベクターや文字を不要に画像化する画質低下を避けられます。"], ["現在番号と元ページ番号を分けて表示", "削除や移動後は現在番号が変わるため、元ページ番号を残すと複製元や移動したページを追跡しやすくなります。"], ["プレビュー回転と実PDF回転を一致させる", "画面だけをCSSで回転するとダウンロード後に向きが戻る場合があります。0・90・180・270度に正規化した値を編集状態と結果PDFの両方に適用します。"], ["モバイルでドラッグだけに依存しない", "ページカードのドラッグは縦スクロールと衝突しやすいため、上・下・先頭・末尾への移動ボタンも提供します。"], ["空白ページは隣接ページと同じサイズを基本にする", "表紙やメモ用ページだけサイズが違うと印刷時に不自然になります。通常は隣接ページに合わせ、必要な場合だけA4やLetterを選びます。"], ["Undo/RedoはPDF全体ではなく編集stateを保存", "操作ごとにPDFバイナリ全体を複製するとメモリ消費が大きくなります。ページ配列と回転・元番号・空白ページ情報だけを履歴として保存します。"], ["大きなPDFは容量だけでなくページ数も制限", "容量が小さくてもページ数が多いPDFはサムネイル生成とstate管理が重くなります。容量・元ページ数・編集後ページ数・同時レンダリング数を別々に管理します。"]],
    cautions: ["元PDFファイル自体は変更せず、新しい結果PDFを作成します。", "暗号化PDFのパスワード回避・解除は行いません。", "電子署名・デジタル署名付きPDFはページ再構成で署名の有効性が変わる場合があります。", "PDF圧縮・OCR・本文編集・透かし・ページ番号は本ツールの範囲外です。", `サービス上限は ${TOOL030_LIMIT_DISPLAY.maxFileMiB}MB、元PDF ${TOOL030_LIMIT_DISPLAY.maxSourcePages}ページ、編集後 ${TOOL030_LIMIT_DISPLAY.maxEditedPages}ページです。サムネイル同時処理は2件、Undo/Redo履歴は30段階まで保持します。`],
    faqs: [["ページを削除すると元PDFも変わりますか？", "いいえ。元ファイルは変更せず、ブラウザ内で新しいPDFを作成します。"], ["ページ順を変えると画質が落ちますか？", "サムネイル画像から作り直さず、元PDFページオブジェクトをコピーする設計です。"], ["複数ページをまとめて回転できますか？", "はい。複数選択して90度単位で左・右へ回転できます。"], ["空白ページのサイズはどう決まりますか？", "基本は隣接ページに合わせ、必要に応じてA4またはLetterを選べます。"], ["逆順を間違えたら戻せますか？", "はい。逆順は編集履歴に入り、1回の元に戻す操作で復元できます。"], ["複数PDFを結合できますか？", "いいえ。030は1つのPDF内部の整理に特化しています。複数PDF結合は028を使用します。"], ["ページを別PDFとして抽出できますか？", "いいえ。抽出・分割は029の役割です。"], ["PDFはサーバーへアップロードされますか？", "いいえ。対応する処理は現在のブラウザ内で行い、FIXLGSサーバーへ保存しません。"]],
  },
} as const;

export function PdfPageOrganizerPage({ locale }: { locale: Locale }) {
  const t = copy[locale];
  const url = `https://toolbox.fixlgs.com/${locale}/pdf-page-organizer`;
  const jsonLd = { "@context": "https://schema.org", "@graph": [{ "@type": "WebApplication", name: t.title, applicationCategory: "UtilitiesApplication", operatingSystem: "Any", url, description: t.desc, offers: { "@type": "Offer", price: "0", priceCurrency: "USD" }, featureList: ["Delete PDF pages", "Reorder PDF pages", "Duplicate pages", "Rotate pages", "Reverse page order", "Add blank pages", "Undo and redo", "Local browser processing"] }, { "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "TOOLBOX", item: `https://toolbox.fixlgs.com/${locale}` }, { "@type": "ListItem", position: 2, name: t.back, item: `https://toolbox.fixlgs.com/${locale}/category/pdf` }, { "@type": "ListItem", position: 3, name: t.title, item: url }] }, { "@type": "FAQPage", mainEntity: t.faqs.map(([q, a]) => ({ "@type": "Question", name: q, acceptedAnswer: { "@type": "Answer", text: a } })) }] };
  const related = [
    { n: "026", name: locale === "ko" ? "이미지 PDF 변환기" : locale === "en" ? "Image to PDF Converter" : "画像 PDF 変換ツール", href: `/${locale}/image-to-pdf` },
    { n: "028", name: locale === "ko" ? "PDF 합치기" : locale === "en" ? "Merge PDF" : "PDF 結合ツール", href: `/${locale}/merge-pdf` },
    { n: "029", name: locale === "ko" ? "PDF 분할·페이지 추출기" : locale === "en" ? "Split & Extract PDF" : "PDF 分割・ページ抽出ツール", href: `/${locale}/split-extract-pdf` },
  ];
  return <ToolboxSubpageShell locale={locale} appName={t.title}>
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} />
    <section className="toolbox-tool-detail-hero toolbox-tool-detail-hero--single-line-description"><Link className="toolbox-subpage-back" href={`/${locale}/category/pdf`}>← {t.back}</Link><p className="toolbox-subpage-eyebrow">030 · PDF</p><div className="toolbox-tool-detail-heading"><h1><span className="toolbox-tool-title-line">{t.title}</span></h1><p>{t.desc}</p></div><div className="toolbox-tool-detail-badge"><strong>LOCAL</strong><span>{t.local}</span></div></section>
    <section className="toolbox-tool-detail-body"><div><PdfPageOrganizerTool locale={locale} />
      <section className="toolbox-next-work"><div className="toolbox-next-work-head"><p>NEXT WORK</p><h2>{t.next}</h2></div><div className="toolbox-next-work-grid"><div className="toolbox-next-work-card is-disabled"><span>031</span><h3>{locale === "ko" ? "PDF 페이지 번호·워터마크 도구" : locale === "en" ? "PDF Page Number & Watermark Tool" : "PDF ページ番号・透かしツール"}</h3><div className="toolbox-next-work-card-foot"><span>{locale === "ko" ? "준비 중" : locale === "en" ? "COMING SOON" : "準備中"}</span><strong>·</strong></div></div></div></section>
      <section className="toolbox-next-work"><div className="toolbox-next-work-head"><p>RELATED TOOLS</p><h2>{t.related}</h2></div><div className="toolbox-next-work-grid">{related.map((x) => <Link key={x.n} href={x.href} className="toolbox-next-work-card"><span>{x.n}</span><h3>{x.name}</h3><div className="toolbox-next-work-card-foot"><span>{locale === "ko" ? "사용 가능" : locale === "en" ? "AVAILABLE" : "利用可能"}</span><strong>↗</strong></div></Link>)}</div></section>
    </div></section>
    <section className="toolbox-tool-guide toolbox-tool-guide--five"><div className="toolbox-tool-guide-head"><p>HOW TO USE</p><h2>{t.how}</h2></div><ol>{t.steps.map((s, i) => <li key={s}><span>{String(i + 1).padStart(2, "0")}</span><p>{s}</p></li>)}</ol></section>
    <section className="toolbox-tool-format-guide toolbox-tool-use-cases--editorial"><div className="toolbox-tool-format-guide-head"><p>USE CASES</p><h2>{locale === "ko" ? "활용 예시" : locale === "en" ? "Use cases" : "活用例"}</h2></div><div className="toolbox-tool-format-body"><div className="toolbox-tool-format-grid">{t.examples.map(([title, description], i) => <article key={title}><strong>{String(i + 1).padStart(2, "0")}</strong><h3>{title}</h3><p>{description}</p></article>)}</div></div></section>
    <section className="toolbox-tool-format-guide toolbox-tool-expert-post toolbox-tool-expert-post--wide-head toolbox-tool-expert-post--compact-copy"><div className="toolbox-tool-format-guide-head"><p>EXPERT POST</p><h2>{t.expertTitle}</h2><span>{t.expertLead}</span></div><div className="toolbox-tool-format-body"><div className="toolbox-tool-direction-grid toolbox-tool-practical-grid">{t.expert.map(([title, description]) => <article key={title}><h4>{title}</h4><p>{description}</p></article>)}</div></div></section>
    <section className="toolbox-tool-info-band toolbox-tool-info-band--section-start toolbox-tool-info-band--bottom-gap toolbox-tool-info-band--left-head toolbox-tool-info-band--format-head toolbox-tool-info-band--full-divider"><div className="toolbox-tool-info-band-head"><p>IMPORTANT NOTES</p><h2>{t.caution}</h2><span>{t.local}</span></div><ul className="toolbox-tool-info-band-list">{t.cautions.map((x) => <li key={x}>{x}</li>)}</ul></section>
    <section className="toolbox-tool-faq"><div className="toolbox-tool-guide-head"><p>FAQ</p><h2>{t.faq}</h2></div><ToolboxFaqList items={t.faqs.map(([q, a]): readonly [string, string] => [q, a])} initialCount={5} moreLabel={t.more} collapseLabel={t.less} className="toolbox-tool-faq-list" /></section>
    <section className="toolbox-tool-processing-note"><p>{t.local}</p></section>
  </ToolboxSubpageShell>;
}
