"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import type { DragEvent } from "react";
import type { Locale } from "@/lib/site";
import styles from "./pdf-page-number-watermark-tool.module.css";
import { TOOL031_LIMITS, TOOL031_LIMIT_DISPLAY, formatPageNumber, resolvePages, safeOutputName, type Anchor, type NumberFormat, type PageRangeMode } from "@/lib/tool-031-pdf";

type PdfLib = typeof import("pdf-lib");
type Tab = "number" | "header" | "watermark";

type Settings = {
  numberEnabled:boolean; numberStartPage:number; numberStart:number; numberFormat:NumberFormat; numberAnchor:Anchor; numberSize:number; numberColor:string; numberMargin:number;
  headerEnabled:boolean; headerText:string; headerAlign:"left"|"center"|"right"; footerEnabled:boolean; footerText:string; footerAlign:"left"|"center"|"right";
  watermarkMode:"text"|"logo"; watermarkEnabled:boolean; watermarkText:string; watermarkSize:number; watermarkColor:string; watermarkOpacity:number; watermarkRotation:number; watermarkAnchor:Anchor; logoScale:number;
  rangeMode:PageRangeMode; customRange:string; filename:string;
};

const labels = {
  ko:{drop:"PDF 파일을 여기에 놓으세요",sub:"페이지 구조를 유지한 채 번호·머리말·꼬리말·워터마크를 브라우저에서 추가합니다.",choose:"PDF 선택",local:"파일과 결과 PDF는 서버로 전송하지 않습니다.",number:"페이지 번호",header:"머리말·꼬리말",watermark:"워터마크",settings:"설정",enabled:"사용",startPage:"표시 시작 페이지",startNumber:"시작 번호",format:"번호 형식",position:"위치",size:"크기",color:"색상",margin:"가장자리 여백",headerText:"머리말",footerText:"꼬리말",align:"정렬",left:"왼쪽",center:"가운데",right:"오른쪽",text:"텍스트",logo:"로고",wmText:"워터마크 텍스트",opacity:"투명도",rotation:"회전",logoFile:"로고 이미지",logoSize:"로고 크기",range:"적용 페이지",all:"전체",exceptFirst:"첫 페이지 제외",exceptLast:"마지막 페이지 제외",odd:"홀수",even:"짝수",custom:"사용자 범위",rangeHint:"예: 1-3,5,8-10",preview:"대표 페이지 미리보기",createPreview:"미리보기 갱신",create:"결과 PDF 생성",creating:"생성 중…",download:"결과 PDF 다운로드",reset:"초기화",newPdf:"새 PDF",replace:"새 PDF",fileInfo:"업로드한 PDF",result:"결과",pages:"페이지",applyPages:"적용",prev:"이전",next:"다음",badPdf:"손상되었거나 지원하지 않는 PDF입니다.",encrypted:"암호화·비밀번호 PDF는 지원하지 않습니다.",tooLarge:`PDF는 ${TOOL031_LIMIT_DISPLAY.maxPdfMiB}MB 이하만 사용할 수 있습니다.`,tooMany:`최대 ${TOOL031_LIMIT_DISPLAY.maxPages}페이지까지 사용할 수 있습니다.`,logoLarge:`로고는 ${TOOL031_LIMIT_DISPLAY.maxLogoMiB}MB 이하만 사용할 수 있습니다.`,rangeError:"적용 페이지 범위를 확인하세요.",needOne:"페이지 번호·머리말/꼬리말·워터마크 중 하나 이상을 켜세요.",done:"PDF 생성 완료",dependency:"PDF 편집 엔진을 불러오지 못했습니다."},
  en:{drop:"Drop a PDF here",sub:"Add page numbers, headers, footers, and watermarks in your browser while preserving PDF pages.",choose:"Choose PDF",local:"Files and output PDFs are not uploaded to a server.",number:"Page Numbers",header:"Header & Footer",watermark:"Watermark",settings:"Settings",enabled:"Enable",startPage:"Display from page",startNumber:"Starting number",format:"Number format",position:"Position",size:"Size",color:"Color",margin:"Edge margin",headerText:"Header",footerText:"Footer",align:"Align",left:"Left",center:"Center",right:"Right",text:"Text",logo:"Logo",wmText:"Watermark text",opacity:"Opacity",rotation:"Rotation",logoFile:"Logo image",logoSize:"Logo size",range:"Pages to apply",all:"All",exceptFirst:"Except first",exceptLast:"Except last",odd:"Odd",even:"Even",custom:"Custom",rangeHint:"e.g. 1-3,5,8-10",preview:"Representative page preview",createPreview:"Refresh preview",create:"Create PDF",creating:"Creating…",download:"Download PDF",reset:"Reset",newPdf:"New PDF",replace:"New PDF",fileInfo:"Uploaded PDF",result:"Result",pages:"pages",applyPages:"applied",prev:"Previous",next:"Next",badPdf:"This PDF is damaged or unsupported.",encrypted:"Encrypted or password-protected PDFs are not supported.",tooLarge:`PDF must be ${TOOL031_LIMIT_DISPLAY.maxPdfMiB}MB or smaller.`,tooMany:`Up to ${TOOL031_LIMIT_DISPLAY.maxPages} pages are supported.`,logoLarge:`Logo must be ${TOOL031_LIMIT_DISPLAY.maxLogoMiB}MB or smaller.`,rangeError:"Check the page range.",needOne:"Enable page numbers, header/footer, or watermark.",done:"PDF created",dependency:"The PDF editing engine could not be loaded."},
  ja:{drop:"PDFファイルをここにドロップ",sub:"ページ構造を維持したまま、番号・ヘッダー・フッター・透かしをブラウザ内で追加します。",choose:"PDFを選択",local:"ファイルと生成PDFはサーバーへ送信しません。",number:"ページ番号",header:"ヘッダー・フッター",watermark:"透かし",settings:"設定",enabled:"使用",startPage:"表示開始ページ",startNumber:"開始番号",format:"番号形式",position:"位置",size:"サイズ",color:"色",margin:"端からの余白",headerText:"ヘッダー",footerText:"フッター",align:"配置",left:"左",center:"中央",right:"右",text:"テキスト",logo:"ロゴ",wmText:"透かしテキスト",opacity:"不透明度",rotation:"回転",logoFile:"ロゴ画像",logoSize:"ロゴサイズ",range:"適用ページ",all:"すべて",exceptFirst:"最初のページを除外",exceptLast:"最後のページを除外",odd:"奇数",even:"偶数",custom:"指定範囲",rangeHint:"例: 1-3,5,8-10",preview:"代表ページプレビュー",createPreview:"プレビュー更新",create:"PDFを作成",creating:"作成中…",download:"PDFをダウンロード",reset:"リセット",newPdf:"新しいPDF",replace:"新しいPDF",fileInfo:"アップロードしたPDF",result:"結果",pages:"ページ",applyPages:"適用",prev:"前へ",next:"次へ",badPdf:"破損しているか未対応のPDFです。",encrypted:"暗号化・パスワード保護PDFには対応していません。",tooLarge:`PDFは${TOOL031_LIMIT_DISPLAY.maxPdfMiB}MB以下です。`,tooMany:`最大${TOOL031_LIMIT_DISPLAY.maxPages}ページまで対応します。`,logoLarge:`ロゴは${TOOL031_LIMIT_DISPLAY.maxLogoMiB}MB以下です。`,rangeError:"適用ページ範囲を確認してください。",needOne:"ページ番号・ヘッダー/フッター・透かしのいずれかを有効にしてください。",done:"PDF作成完了",dependency:"PDF編集エンジンを読み込めませんでした。"}
} as const;

const defaultSettings: Settings = { numberEnabled:true, numberStartPage:1, numberStart:1, numberFormat:"1", numberAnchor:"bottom-center", numberSize:11, numberColor:"#111111", numberMargin:24, headerEnabled:false, headerText:"", headerAlign:"center", footerEnabled:false, footerText:"", footerAlign:"center", watermarkMode:"text", watermarkEnabled:false, watermarkText:"CONFIDENTIAL", watermarkSize:42, watermarkColor:"#808080", watermarkOpacity:0.18, watermarkRotation:-45, watermarkAnchor:"center", logoScale:24, rangeMode:"all", customRange:"", filename:"document-numbered-watermarked.pdf" };
const anchors: Anchor[]=["top-left","top-center","top-right","middle-left","center","middle-right","bottom-left","bottom-center","bottom-right"];
const anchorGlyph:Record<Anchor,string>={"top-left":"↖","top-center":"↑","top-right":"↗","middle-left":"←",center:"●","middle-right":"→","bottom-left":"↙","bottom-center":"↓","bottom-right":"↘"};
const hexToRgb=(hex:string)=>{const v=hex.replace("#","");return [parseInt(v.slice(0,2),16)/255,parseInt(v.slice(2,4),16)/255,parseInt(v.slice(4,6),16)/255] as const};

async function textPng(text:string,color:string,fontSize:number,opacity:number,maxWidth:number){
  const scale=2; const canvas=document.createElement("canvas"); const ctx=canvas.getContext("2d"); if(!ctx) throw new Error("CANVAS");
  ctx.font=`700 ${fontSize*scale}px system-ui, sans-serif`; const measured=Math.min(Math.ceil(ctx.measureText(text).width)+24*scale,Math.max(80,Math.floor(maxWidth*scale)));
  canvas.width=measured;canvas.height=Math.ceil(fontSize*1.65*scale);ctx.clearRect(0,0,canvas.width,canvas.height);ctx.globalAlpha=opacity;ctx.fillStyle=color;ctx.font=`700 ${fontSize*scale}px system-ui, sans-serif`;ctx.textBaseline="middle";ctx.fillText(text,12*scale,canvas.height/2);
  const blob=await new Promise<Blob|null>(r=>canvas.toBlob(r,"image/png"));canvas.width=1;canvas.height=1;if(!blob) throw new Error("CANVAS");return new Uint8Array(await blob.arrayBuffer());
}
function placement(width:number,height:number,drawW:number,drawH:number,anchor:Anchor,margin:number){const left=margin, right=width-margin-drawW, bottom=margin, top=height-margin-drawH, midX=(width-drawW)/2, midY=(height-drawH)/2;const x=anchor.endsWith("left")?left:anchor.endsWith("right")?right:midX;const y=anchor.startsWith("top")?top:anchor.startsWith("bottom")?bottom:midY;return{x:Math.max(0,x),y:Math.max(0,y)}}

const toBlobPart=(bytes:Uint8Array):ArrayBuffer=>bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength) as ArrayBuffer;

export function PdfPageNumberWatermarkTool({locale}:{locale:Locale}){
  const c=labels[locale]; const inputRef=useRef<HTMLInputElement>(null); const logoRef=useRef<HTMLInputElement>(null); const resultUrlRef=useRef(""); const previewUrlRef=useRef("");
  const [pdfFile,setPdfFile]=useState<File|null>(null);const [pdfBytes,setPdfBytes]=useState<Uint8Array|null>(null);const [dragging,setDragging]=useState(false);const [workspaceDragging,setWorkspaceDragging]=useState(false);const [pageCount,setPageCount]=useState(0);const [tab,setTab]=useState<Tab>("number");const [settings,setSettings]=useState<Settings>(defaultSettings);const [logo,setLogo]=useState<File|null>(null);const [error,setError]=useState("");const [status,setStatus]=useState("");const [busy,setBusy]=useState(false);const [result,setResult]=useState<Blob|null>(null);const [previewUrl,setPreviewUrl]=useState("");const [previewPage,setPreviewPage]=useState(1);
  useEffect(()=>()=>{if(resultUrlRef.current)URL.revokeObjectURL(resultUrlRef.current);if(previewUrlRef.current)URL.revokeObjectURL(previewUrlRef.current)},[]);
  const applied=useMemo(()=>{try{return pageCount?resolvePages(settings.rangeMode,pageCount,settings.customRange).length:0}catch{return 0}},[pageCount,settings.rangeMode,settings.customRange]);
  const dragActive=dragging||workspaceDragging;
  const patch=<K extends keyof Settings>(k:K,v:Settings[K])=>{setSettings(s=>({...s,[k]:v}));setResult(null);setStatus("")};
  const hasFiles=(e:DragEvent<HTMLElement>)=>Array.from(e.dataTransfer.types).includes("Files");
  const dropPdf=(e:DragEvent<HTMLElement>)=>{e.preventDefault();e.stopPropagation();setDragging(false);setWorkspaceDragging(false);if(busy)return;const file=e.dataTransfer.files?.[0];if(file)void loadPdf(file)};
  async function loadPdf(file:File){setError("");setStatus("");setResult(null);if(file.size>TOOL031_LIMITS.maxPdfBytes){setError(c.tooLarge);return}try{const bytes=new Uint8Array(await file.arrayBuffer());const {PDFDocument}=await import("pdf-lib");const doc=await PDFDocument.load(bytes,{ignoreEncryption:false});const count=doc.getPageCount();if(count<1)throw new Error("EMPTY");if(count>TOOL031_LIMITS.maxPages){setError(c.tooMany);return}setPdfFile(file);setPdfBytes(bytes);setPageCount(count);setPreviewPage(1);setSettings(s=>({...s,filename:safeOutputName(file.name)}));await buildPreview(bytes,1,count);}catch(e){setError(String(e).toLowerCase().includes("encrypt")?c.encrypted:c.badPdf)}}
  async function buildOverlay(doc:any,page:any,pageIndex:number,total:number,pdfLib:PdfLib){const {degrees}=pdfLib;const {width,height}=page.getSize();const isApplied=resolvePages(settings.rangeMode,total,settings.customRange).includes(pageIndex);if(!isApplied)return;const drawRasterText=async(text:string,size:number,color:string,opacity:number,anchor:Anchor,margin:number,rotation=0)=>{if(!text)return;const png=await textPng(text,color,size,opacity,width*.82);const img=await doc.embedPng(png);let drawW=img.width/2,drawH=img.height/2;if(drawW>width*.82){const r=(width*.82)/drawW;drawW*=r;drawH*=r}const p=placement(width,height,drawW,drawH,anchor,margin);page.drawImage(img,{x:p.x,y:p.y,width:drawW,height:drawH,rotate:degrees(rotation),opacity:1})};
    if(settings.numberEnabled && pageIndex+1>=settings.numberStartPage){const n=settings.numberStart+(pageIndex+1-settings.numberStartPage);const text=formatPageNumber(n,total,settings.numberFormat,locale);await drawRasterText(text,settings.numberSize,settings.numberColor,1,settings.numberAnchor,settings.numberMargin);}
    const slotAnchor=(top:boolean,align:"left"|"center"|"right"):Anchor=>`${top?"top":"bottom"}-${align}` as Anchor;
    if(settings.headerEnabled&&settings.headerText)await drawRasterText(settings.headerText,11,"#222222",1,slotAnchor(true,settings.headerAlign),24);
    if(settings.footerEnabled&&settings.footerText)await drawRasterText(settings.footerText,11,"#222222",1,slotAnchor(false,settings.footerAlign),24);
    if(settings.watermarkEnabled){if(settings.watermarkMode==="text"&&settings.watermarkText)await drawRasterText(settings.watermarkText,settings.watermarkSize,settings.watermarkColor,settings.watermarkOpacity,settings.watermarkAnchor,24,settings.watermarkRotation);if(settings.watermarkMode==="logo"&&logo){let bytes=new Uint8Array(await logo.arrayBuffer());let isPng=logo.type.includes("png");if(logo.type.includes("webp")){const bitmap=await createImageBitmap(logo);try{const canvas=document.createElement("canvas");canvas.width=bitmap.width;canvas.height=bitmap.height;const ctx=canvas.getContext("2d");if(!ctx)throw new Error("CANVAS");ctx.drawImage(bitmap,0,0);const blob=await new Promise<Blob|null>(r=>canvas.toBlob(r,"image/png"));canvas.width=1;canvas.height=1;if(!blob)throw new Error("CANVAS");bytes=new Uint8Array(await blob.arrayBuffer());isPng=true}finally{bitmap.close()}}const img=isPng?await doc.embedPng(bytes):await doc.embedJpg(bytes);const target=width*(settings.logoScale/100);const ratio=target/img.width;const drawW=target,drawH=img.height*ratio;const p=placement(width,height,drawW,drawH,settings.watermarkAnchor,24);page.drawImage(img,{x:p.x,y:p.y,width:drawW,height:drawH,opacity:settings.watermarkOpacity});}}
  }
  async function buildPreview(bytes=pdfBytes,pageNo=previewPage,total=pageCount){if(!bytes||!total)return;setError("");try{const pdfLib=await import("pdf-lib");const src=await pdfLib.PDFDocument.load(bytes);const out=await pdfLib.PDFDocument.create();const [copied]=await out.copyPages(src,[Math.max(0,Math.min(pageNo-1,total-1))]);out.addPage(copied);await buildOverlay(out,copied,pageNo-1,total,pdfLib);const resultBytes=await out.save();const blob=new Blob([toBlobPart(resultBytes)],{type:"application/pdf"});if(previewUrlRef.current)URL.revokeObjectURL(previewUrlRef.current);const url=URL.createObjectURL(blob);previewUrlRef.current=url;setPreviewUrl(url);}catch(e){setError(String(e).includes("RANGE")?c.rangeError:c.dependency)}}
  async function createPdf(){if(!pdfBytes||!pageCount)return;if(!settings.numberEnabled&&!settings.headerEnabled&&!settings.footerEnabled&&!settings.watermarkEnabled){setError(c.needOne);return}setBusy(true);setError("");setStatus(c.creating);try{const pdfLib=await import("pdf-lib");const doc=await pdfLib.PDFDocument.load(pdfBytes);resolvePages(settings.rangeMode,pageCount,settings.customRange);for(let i=0;i<pageCount;i++)await buildOverlay(doc,doc.getPage(i),i,pageCount,pdfLib);const out=await doc.save();const check=await pdfLib.PDFDocument.load(out);if(check.getPageCount()!==pageCount)throw new Error("PAGECOUNT");setResult(new Blob([toBlobPart(out)],{type:"application/pdf"}));setStatus(c.done)}catch(e){setError(String(e).includes("RANGE")?c.rangeError:c.badPdf)}finally{setBusy(false)}}
  function download(){if(!result)return;if(resultUrlRef.current)URL.revokeObjectURL(resultUrlRef.current);const url=URL.createObjectURL(result);resultUrlRef.current=url;const a=document.createElement("a");a.href=url;a.download=safeOutputName(settings.filename);a.click()}
  function reset(all=true){setSettings(defaultSettings);setLogo(null);setResult(null);setStatus("");setError("");setDragging(false);setWorkspaceDragging(false);if(all){setPdfFile(null);setPdfBytes(null);setPageCount(0);if(previewUrlRef.current){URL.revokeObjectURL(previewUrlRef.current);previewUrlRef.current=""}setPreviewUrl("");if(inputRef.current)inputRef.current.value=""}if(logoRef.current)logoRef.current.value=""}
  const rangeOptions:[PageRangeMode,string][]=[["all",c.all],["except-first",c.exceptFirst],["except-last",c.exceptLast],["odd",c.odd],["even",c.even],["custom",c.custom]];
  return <div className={styles.wrapper} data-tool="031" data-testid="tool031-root">
    <div className={styles.localNote}><strong>LOCAL</strong><span>{c.local}</span></div>
    <input ref={inputRef} data-testid="tool031-file-input" className={styles.hidden} type="file" accept="application/pdf,.pdf" onChange={e=>{const f=e.target.files?.[0];if(f)void loadPdf(f)}}/>
    {!pdfFile&&error&&<div className={styles.error} role="alert" aria-live="polite">{error}</div>}
    {!pdfFile?<div className={`${styles.dropzone} ${dragActive?styles.dragging:""}`} data-testid="tool031-dropzone" data-drag-active={dragActive?"true":"false"} onClick={()=>{if(!busy)inputRef.current?.click()}} onDragEnter={e=>{if(hasFiles(e)){e.preventDefault();if(!busy)setDragging(true)}}} onDragOver={e=>{if(hasFiles(e)){e.preventDefault();if(!busy)setDragging(true)}}} onDragLeave={e=>{const next=e.relatedTarget as Node|null;if(!next||!e.currentTarget.contains(next))setDragging(false)}} onDrop={dropPdf}><h2>{c.drop}</h2><p>{c.sub}</p><button type="button" className={styles.chooseButton} onClick={e=>{e.stopPropagation();inputRef.current?.click()}}>{c.choose}</button></div>:
    <><div className={`${styles.uploadedFileBar} ${dragActive?styles.dragging:""}`} data-testid="tool031-file-info" data-drag-active={dragActive?"true":"false"}><div className={styles.uploadedFileInfo}><strong>{pdfFile.name}</strong><span>{(pdfFile.size/1048576).toFixed(2)} MB · {pageCount} {c.pages} · {applied} {c.applyPages}</span></div><button type="button" className={styles.chooseButton} disabled={busy} onClick={()=>inputRef.current?.click()}>{c.replace}</button></div><div className={`${styles.workspace} ${dragActive?styles.workspaceDragging:""}`} data-testid="tool031-workspace" data-drop-target="pdf-replace" data-drag-active={dragActive?"true":"false"} onDragEnter={e=>{if(hasFiles(e)){e.preventDefault();if(!busy)setWorkspaceDragging(true)}}} onDragOver={e=>{if(hasFiles(e)){e.preventDefault();if(!busy)setWorkspaceDragging(true)}}} onDragLeave={e=>{const next=e.relatedTarget as Node|null;if(!next||!e.currentTarget.contains(next))setWorkspaceDragging(false)}} onDrop={dropPdf}>
      <section className={styles.panel}><div className={styles.panelHead}><div><p>PREVIEW</p><h2>{c.preview}</h2></div></div>{previewUrl?<iframe title={c.preview} className={styles.previewFrame} src={`${previewUrl}#toolbar=0&navpanes=0`}/>:<div className={styles.previewEmpty}>{c.preview}</div>}<div className={styles.previewNav}><button className={styles.secondary} disabled={previewPage<=1} onClick={()=>{const p=previewPage-1;setPreviewPage(p);void buildPreview(pdfBytes,p,pageCount)}}>{c.prev}</button><input aria-label={c.preview} type="number" min={1} max={pageCount} value={previewPage} onChange={e=>setPreviewPage(Math.max(1,Math.min(pageCount,Number(e.target.value)||1)))}/><button className={styles.secondary} disabled={previewPage>=pageCount} onClick={()=>{const p=previewPage+1;setPreviewPage(p);void buildPreview(pdfBytes,p,pageCount)}}>{c.next}</button></div><button className={styles.ghost} style={{marginTop:10}} onClick={()=>void buildPreview()}>{c.createPreview}</button></section>
      <section className={styles.panel}><div className={styles.panelHead}><div><p>031 · PDF</p><h2>{c.settings}</h2></div></div><div className={styles.tabs}><button data-active={tab==="number"} onClick={()=>setTab("number")}>{c.number}</button><button data-active={tab==="header"} onClick={()=>setTab("header")}>{c.header}</button><button data-active={tab==="watermark"} onClick={()=>setTab("watermark")}>{c.watermark}</button></div><div className={styles.settings}>
        {tab==="number"&&<div className={styles.group}><div className={styles.groupHead}><h3>{c.number}</h3><label className={styles.switch}><input type="checkbox" checked={settings.numberEnabled} onChange={e=>patch("numberEnabled",e.target.checked)}/>{c.enabled}</label></div><div className={styles.two}><label className={styles.field}>{c.startPage}<input type="number" min={1} max={pageCount} value={settings.numberStartPage} onChange={e=>patch("numberStartPage",Math.max(1,Number(e.target.value)||1))}/></label><label className={styles.field}>{c.startNumber}<input type="number" min={1} value={settings.numberStart} onChange={e=>patch("numberStart",Math.max(1,Number(e.target.value)||1))}/></label></div><label className={styles.field}>{c.format}<select value={settings.numberFormat} onChange={e=>patch("numberFormat",e.target.value as NumberFormat)}><option value="1">1</option><option value="01">01</option><option value="page">Page 1</option><option value="of-total">1 / N</option></select></label><label className={styles.field}>{c.size}<input type="range" min={8} max={28} value={settings.numberSize} onChange={e=>patch("numberSize",Number(e.target.value))}/><span>{settings.numberSize}px</span></label><label className={styles.field}>{c.color}<div className={styles.colorRow}><input type="color" value={settings.numberColor} onChange={e=>patch("numberColor",e.target.value)}/><input value={settings.numberColor} onChange={e=>patch("numberColor",e.target.value)}/></div></label><label className={styles.field}>{c.margin}<input type="range" min={8} max={72} value={settings.numberMargin} onChange={e=>patch("numberMargin",Number(e.target.value))}/><span>{settings.numberMargin} pt</span></label><label className={styles.field}>{c.position}<div className={styles.anchor}>{anchors.map(a=><button type="button" key={a} data-active={settings.numberAnchor===a} aria-label={a} onClick={()=>patch("numberAnchor",a)}>{anchorGlyph[a]}</button>)}</div></label></div>}
        {tab==="header"&&<><div className={styles.group}><div className={styles.groupHead}><h3>{c.headerText}</h3><label className={styles.switch}><input type="checkbox" checked={settings.headerEnabled} onChange={e=>patch("headerEnabled",e.target.checked)}/>{c.enabled}</label></div><label className={styles.field}>{c.headerText}<input maxLength={TOOL031_LIMITS.maxHeaderFooterChars} value={settings.headerText} onChange={e=>patch("headerText",e.target.value)}/></label><label className={styles.field}>{c.align}<select value={settings.headerAlign} onChange={e=>patch("headerAlign",e.target.value as Settings["headerAlign"])}><option value="left">{c.left}</option><option value="center">{c.center}</option><option value="right">{c.right}</option></select></label></div><div className={styles.group}><div className={styles.groupHead}><h3>{c.footerText}</h3><label className={styles.switch}><input type="checkbox" checked={settings.footerEnabled} onChange={e=>patch("footerEnabled",e.target.checked)}/>{c.enabled}</label></div><label className={styles.field}>{c.footerText}<input maxLength={TOOL031_LIMITS.maxHeaderFooterChars} value={settings.footerText} onChange={e=>patch("footerText",e.target.value)}/></label><label className={styles.field}>{c.align}<select value={settings.footerAlign} onChange={e=>patch("footerAlign",e.target.value as Settings["footerAlign"])}><option value="left">{c.left}</option><option value="center">{c.center}</option><option value="right">{c.right}</option></select></label></div></>}
        {tab==="watermark"&&<div className={styles.group}><div className={styles.groupHead}><h3>{c.watermark}</h3><label className={styles.switch}><input type="checkbox" checked={settings.watermarkEnabled} onChange={e=>patch("watermarkEnabled",e.target.checked)}/>{c.enabled}</label></div><div className={styles.tabs}><button data-active={settings.watermarkMode==="text"} onClick={()=>patch("watermarkMode","text")}>{c.text}</button><button data-active={settings.watermarkMode==="logo"} onClick={()=>patch("watermarkMode","logo")}>{c.logo}</button></div>{settings.watermarkMode==="text"?<><label className={styles.field}>{c.wmText}<textarea maxLength={TOOL031_LIMITS.maxWatermarkChars} value={settings.watermarkText} onChange={e=>patch("watermarkText",e.target.value)}/></label><label className={styles.field}>{c.size}<input type="range" min={14} max={96} value={settings.watermarkSize} onChange={e=>patch("watermarkSize",Number(e.target.value))}/><span>{settings.watermarkSize}px</span></label><label className={styles.field}>{c.color}<div className={styles.colorRow}><input type="color" value={settings.watermarkColor} onChange={e=>patch("watermarkColor",e.target.value)}/><input value={settings.watermarkColor} onChange={e=>patch("watermarkColor",e.target.value)}/></div></label><label className={styles.field}>{c.rotation}<select value={settings.watermarkRotation} onChange={e=>patch("watermarkRotation",Number(e.target.value))}>{[-45,-30,0,30,45].map(v=><option key={v} value={v}>{v}°</option>)}</select></label></>:<label className={styles.field}>{c.logoFile}<input ref={logoRef} type="file" accept="image/png,image/jpeg,image/webp,.png,.jpg,.jpeg,.webp" onChange={e=>{const f=e.target.files?.[0];if(!f)return;if(f.size>TOOL031_LIMITS.maxLogoBytes){setError(c.logoLarge);return}setLogo(f)}}/></label>}<label className={styles.field}>{c.opacity}<input type="range" min={0.05} max={1} step={0.05} value={settings.watermarkOpacity} onChange={e=>patch("watermarkOpacity",Number(e.target.value))}/><span>{Math.round(settings.watermarkOpacity*100)}%</span></label>{settings.watermarkMode==="logo"&&<label className={styles.field}>{c.logoSize}<input type="range" min={5} max={70} value={settings.logoScale} onChange={e=>patch("logoScale",Number(e.target.value))}/><span>{settings.logoScale}%</span></label>}<label className={styles.field}>{c.position}<div className={styles.anchor}>{anchors.map(a=><button type="button" key={a} data-active={settings.watermarkAnchor===a} aria-label={a} onClick={()=>patch("watermarkAnchor",a)}>{anchorGlyph[a]}</button>)}</div></label></div>}
        <div className={styles.group}><label className={styles.field}>{c.range}<select value={settings.rangeMode} onChange={e=>patch("rangeMode",e.target.value as PageRangeMode)}>{rangeOptions.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>{settings.rangeMode==="custom"&&<label className={styles.field}>{c.custom}<input placeholder={c.rangeHint} value={settings.customRange} onChange={e=>patch("customRange",e.target.value)}/></label>}<label className={styles.field}>Filename<input value={settings.filename} onChange={e=>patch("filename",e.target.value)}/></label></div>
      </div></section></div>{error&&<div className={styles.error} role="alert" aria-live="polite">{error}</div>}{status&&<p className={styles.status} aria-live="polite">{status}</p>}<div className={styles.actions}><button data-testid="tool031-create" className={styles.primary} disabled={busy} onClick={()=>void createPdf()}>{busy?c.creating:c.create}</button>{result&&<button data-testid="tool031-download" className={styles.secondary} onClick={download}>{c.download}</button>}<button className={styles.ghost} onClick={()=>reset(false)}>{c.reset}</button><button className={styles.ghost} onClick={()=>reset(true)}>{c.newPdf}</button></div>{result&&<div data-testid="tool031-result" className={styles.result}><div><strong>{c.result}</strong><span>{pageCount} {c.pages} · {applied} {c.applyPages} · {(result.size/1048576).toFixed(2)} MB</span></div><button className={styles.primary} onClick={download}>{c.download}</button></div>}<p className={styles.note}>{c.local}</p></>}
  </div>
}
