import Link from "next/link";
import type { Locale } from "@/lib/site";
import { ToolboxSubpageShell } from "./toolbox-subpage-shell";
import { ToolboxFaqList } from "./toolbox-faq-list";
import { PdfTextImageExtractorTool } from "./pdf-text-image-extractor-tool";

const copy = {
  ko: {
    back: "PDF 도구", title: "PDF 텍스트·이미지 추출기", desc: "PDF 내부의 텍스트 레이어와 실제 임베디드 이미지를 페이지별로 분리해 TXT·개별 이미지·ZIP으로 저장하세요.",
    local: "PDF와 추출 결과는 서버로 전송하거나 저장하지 않고 현재 브라우저에서 처리합니다.",
    how: "사용 방법", steps: ["PDF 파일을 선택합니다.", "텍스트·이미지·텍스트+이미지 중 추출 모드를 선택합니다.", "전체·선택·사용자 지정으로 처리할 페이지 범위를 정합니다.", "추출을 실행하고 페이지별 텍스트와 임베디드 이미지 결과를 확인합니다.", "텍스트는 TXT, 이미지는 개별 파일 또는 ZIP, 둘 다는 text/images 구조의 ZIP으로 저장합니다."],
    examples: [["보고서 텍스트를 페이지별 TXT로 정리", "복사하면 줄 순서가 흔들리는 보고서 PDF를 페이지 번호 구분자와 함께 TXT로 저장해 후처리 기준을 명확하게 만듭니다."], ["PDF 속 사진만 따로 모으기", "페이지 전체를 JPG로 캡처하지 않고 PDF 내부에서 사용된 raster image object를 찾아 페이지·순번 기준 파일명으로 분리합니다."], ["자료 전체를 한 ZIP으로 전달", "텍스트와 이미지가 모두 필요한 문서는 /text와 /images 구조로 묶어 원본 페이지 관계를 유지한 채 전달할 수 있습니다."]],
    expertTitle: "PDF 이미지 추출 기준", expertLead: "텍스트 레이어, 읽기 순서, PDF 이미지 객체, PNG fallback, 중복 이미지, 스캔 PDF와 OCR의 차이까지 결과를 해석할 때 필요한 실전 기준입니다.",
    expert: [["텍스트 추출과 OCR은 같은 기능이 아닙니다", "텍스트 PDF에는 글자 정보가 PDF 내부 객체로 저장되어 있어 PDF.js의 텍스트 API로 바로 읽을 수 있습니다. 반대로 스캔 PDF는 페이지가 사진 한 장처럼 저장되어 텍스트 레이어가 없을 수 있습니다. 035는 이 경우 임의로 OCR을 실행하지 않고 텍스트가 없다는 사실을 안내합니다."], ["PDF의 보이는 순서와 내부 저장 순서는 다를 수 있습니다", "다단 편집, 표, 떠 있는 텍스트 상자, 복잡한 폰트가 있는 PDF는 내부 text item 순서가 사람이 읽는 순서와 완전히 같지 않을 수 있습니다. 따라서 이 도구는 공백과 줄바꿈을 보수적으로 정리하며 완전한 레이아웃 재구성을 약속하지 않습니다."], ["이미지 추출은 페이지 전체 렌더링과 구분해야 합니다", "027 PDF 이미지 변환기는 사용자가 보는 페이지 전체를 JPG·PNG 픽셀 이미지로 만듭니다. 035는 페이지 캡처를 만드는 대신 PDF 연산자와 이미지 객체를 따라 실제 embedded raster image를 찾습니다."], ["원본 encoded stream을\n항상 그대로 꺼낼 수 있는 것은 아닙니다", "PDF 내부 이미지는 필터, 마스크, 색공간, soft mask와 함께 저장될 수 있습니다. 공개 API에서 원본 stream을 안정적으로 보존하기 어려운 객체는 PDF.js가 해석한 bitmap을 PNG로 저장하고 결과에 fallback임을 표시하는 편이 잘못된 원본 형식을 약속하는 것보다 안전합니다."], ["주요 이미지와 모든 이미지를 구분합니다", "PDF 내부에는 사진뿐 아니라 작은 아이콘·마스크·장식 조각·반복 로고가 매우 많이 들어갈 수 있습니다. 기본값은 보수적인 크기·마스크·중복 기준으로 주요 이미지를 보여주고, 모든 이미지 모드에서는 정상 디코딩된 객체를 가능한 한 모두 확인할 수 있습니다."], ["반복 XObject는 전체 모드에서 다시 확인할 수 있습니다", "기본 주요 이미지 보기에서는 동일 bitmap 중복을 숨겨 결과를 정리합니다. 모든 이미지 모드로 바꾸면 페이지별 반복 객체까지 다시 확인할 수 있습니다."], ["대용량 PDF는 페이지 순차 처리가 안전합니다", "텍스트와 여러 이미지 blob을 한꺼번에 만들어 두면 모바일 메모리가 급격히 늘 수 있습니다. 페이지를 순서대로 처리하고 각 페이지가 끝난 뒤 불필요한 page object를 정리하는 흐름이 브라우저 로컬 도구에 적합합니다."], ["ZIP 구조와 파일명은 후처리 품질에 영향을 줍니다", "page-001-image-001.png처럼 고정 자릿수 파일명을 사용하면 파일 탐색기에서도 페이지 순서가 유지됩니다. text와 images 폴더를 분리하면 자동화나 문서 정리 작업에서 재사용하기도 쉽습니다."]],
    caution: "주의사항", cautions: ["이 도구는 OCR을 실행하지 않습니다. 텍스트 레이어가 없는 스캔 PDF는 텍스트 결과가 비어 있을 수 있습니다.", "복잡한 다단·표·특수 font encoding 문서는 사람이 보는 순서와 추출 문자열 순서가 일부 다를 수 있습니다.", "이미지는 원본 encoded stream을 안전하게 복원할 수 없을 때 decoded bitmap을 PNG로 저장하며 결과에 fallback으로 표시합니다.", "암호·권한·손상·특수 구조 PDF는 열리지 않거나 일부 페이지·이미지 객체만 실패할 수 있습니다.", "서비스 한도는 PDF 1개·50MB·200페이지입니다. 추출 이미지가 500개를 넘으면 경고하고 1,000개에 도달하면 브라우저 안정성을 위해 추가 이미지 추출을 중단합니다."],
    faq: "자주 묻는 질문", more: "FAQ 더보기", less: "FAQ 접기", faqs: [["스캔 PDF도 글자를 추출할 수 있나요?", "텍스트 레이어가 있는 스캔 PDF라면 가능합니다. 이미지로만 된 스캔 문서는 OCR이 필요하며 035는 OCR을 자동 실행하지 않습니다."], ["PDF 안의 사진 원본만 꺼내나요?", "페이지 전체 캡처가 아니라 PDF 내부 raster image object를 추출합니다. 다만 PDF 저장 방식에 따라 원본 encoded stream 대신 decoded PNG fallback으로 저장될 수 있습니다."], ["PDF 페이지 전체를 JPG로 만들 수 있나요?", "아니요. 페이지 전체 이미지 변환은 027 PDF 이미지 변환기의 역할입니다."], ["특정 페이지만 추출할 수 있나요?", "예. 전체, 체크 선택, 1-3,5,8 같은 사용자 지정 범위를 사용할 수 있습니다."], ["작은 아이콘도 결과에 나오나요?", "기본 주요 이미지 보기에서는 아주 작은 장식 객체와 마스크를 숨깁니다. 모든 이미지로 전환하면 정상 디코딩된 작은 객체도 확인할 수 있습니다."], ["같은 로고가 여러 페이지에 있으면 모두 나오나요?", "동일 bitmap 중복은 주요 이미지와 모든 이미지에서 모두 자동 제거합니다. 같은 그림을 반복 저장하지 않아 결과와 ZIP을 가볍게 유지합니다."], ["텍스트와 이미지를 한 번에 받을 수 있나요?", "예. 텍스트+이미지 모드는 TXT와 images 폴더를 하나의 ZIP으로 구성합니다."], ["서비스 한도는 얼마인가요?", "PDF 1개, 최대 50MB, 최대 200페이지입니다. 추출 이미지가 500개를 넘으면 경고하고 1,000개에 도달하면 현재 결과를 유지한 채 추가 이미지 추출을 안전 중단합니다."], ["파일이 서버에 올라가나요?", "아니요. 구현된 PDF parsing과 결과 생성은 현재 브라우저에서 처리하며 사용자 PDF·텍스트·이미지를 서버에 저장하지 않습니다."]],
    related: "관련 도구", next: "다음 작업", coming: "준비 중",
  },
  en: {
    back: "PDF Tools", title: "PDF Text & Image Extractor", desc: "Extract the PDF text layer and actual embedded images by page, then save them as TXT, individual images, or ZIP files.",
    local: "Your PDF and extracted results are processed in the current browser and are not uploaded or stored on a server.",
    how: "How to use", steps: ["Choose a PDF file.", "Select Text, Images, or Text + Images.", "Choose all pages, checked pages, or a custom page range.", "Run extraction and review page-level text and embedded-image results.", "Download text as TXT, images individually or as ZIP, or save both under text/images folders in one ZIP."],
    examples: [["Organize report text by page", "Save a report as TXT with explicit page markers when normal copy/paste mixes line or column order."], ["Collect photos embedded in a PDF", "Find raster image objects used inside the PDF instead of turning the full visible page into a screenshot."], ["Deliver all extracted material in one ZIP", "Bundle text and images under separate folders while keeping deterministic page-based filenames for downstream work."]],
    expertTitle: "Practical standards for extracting PDF text and embedded images", expertLead: "Text layers, reading order, PDF image objects, PNG fallback, duplicate resources, scanned PDFs, and OCR boundaries all affect how extraction results should be interpreted.",
    expert: [["Text extraction is not OCR", "A text PDF stores character information as document objects that PDF.js can read directly. A scan may contain only page images and no text layer. Tool 035 reports that state rather than silently running OCR."], ["Visual reading order can differ from internal order", "Columns, tables, floating text boxes, and unusual font encodings can make PDF text-item order differ from the way a person reads the page. The tool therefore reconstructs spacing conservatively and does not promise perfect layout recovery."], ["Image extraction is different from full-page rendering", "Tool 027 rasterizes the complete visible PDF page. Tool 035 instead follows PDF operators and image objects to find embedded raster content."], ["The original encoded stream is not always safely recoverable", "DCTDecode JPEG resources are exported from their original compressed stream as JPG without re-encoding. Other raster images that cannot be preserved safely because of filters, masks, or color spaces use a decoded PNG fallback."], ["Major images and all images serve different needs", "PDFs can contain photos alongside tiny icons, masks, decorative fragments, and repeated logos. The default Major images view applies conservative size, mask, and duplicate rules; All images exposes as many successfully decoded objects as possible."], ["Repeated XObjects are deduplicated automatically", "Identical bitmaps are removed in both Major images and All images to reduce result count and ZIP size. Images with different dimensions or actual pixel content remain separate results."], ["Sequential page processing is safer for large PDFs", "Keeping many text structures, bitmaps, blobs, and previews alive at once can cause sharp memory growth. Processing one page at a time and releasing page objects is better suited to local browser tools."], ["ZIP paths and deterministic filenames matter", "Names such as page-001-image-001.png preserve page order in file explorers. Separating text and images also makes the bundle easier to reuse in scripts and document workflows."]],
    caution: "Important notes", cautions: ["This tool does not run OCR. Image-only scanned PDFs may have no extractable text.", "Complex columns, tables, and unusual font encodings can produce a text order different from the visual page.", "Images are saved as decoded PNG fallback when the original encoded stream cannot be recovered safely, and the result is labeled accordingly.", "Password-protected, restricted, damaged, or unusual PDFs may fail entirely or on individual pages/resources.", "Service limits are 1 PDF, 50MB, and 200 pages. A warning appears after 500 extracted images, and additional image extraction stops at 1,000 for browser stability."],
    faq: "FAQ", more: "Show more FAQ", less: "Hide FAQ", faqs: [["Can it extract text from scanned PDFs?", "Only when the PDF already contains a text layer. Image-only scans require OCR, which Tool 035 does not run automatically."], ["Does it extract original photos from the PDF?", "It extracts embedded raster image objects rather than full-page screenshots. Depending on the PDF structure, an image may be delivered as a decoded PNG fallback instead of the original encoded stream."], ["Can it turn every PDF page into JPG?", "No. Full-page conversion belongs to Tool 027 PDF to Image Converter."], ["Can I extract only certain pages?", "Yes. Use all pages, checked pages, or a custom range such as 1-3,5,8."], ["Are tiny icons included?", "The default Major images view hides very small decorative objects and masks. Switch to All images to inspect small successfully decoded resources."], ["What happens to a logo reused on many pages?", "Identical bitmap duplicates are removed automatically in both Major images and All images so repeated copies do not inflate the result or ZIP."], ["Can I download text and images together?", "Yes. Text + Images creates one ZIP with separate text and images folders."], ["What are the service limits?", "One PDF up to 50MB and 200 pages. A warning appears after 500 extracted images; at 1,000 images, further image extraction stops safely while keeping existing results."], ["Is my PDF uploaded?", "No. Implemented parsing and output creation run in the current browser and the PDF, extracted text, and images are not stored on the server."]],
    related: "Related tools", next: "Next work", coming: "COMING SOON",
  },
  ja: {
    back: "PDFツール", title: "PDFテキスト・画像抽出ツール", desc: "PDF内部のテキストレイヤーと実際の埋め込み画像をページ別に抽出し、TXT・個別画像・ZIPで保存できます。",
    local: "PDFと抽出結果はサーバーへ送信・保存せず、現在のブラウザ内で処理します。",
    how: "使い方", steps: ["PDFファイルを選択します。", "テキスト・画像・テキスト+画像の抽出モードを選びます。", "すべて・選択・指定範囲から処理ページを決めます。", "抽出を実行し、ページ別テキストと埋め込み画像を確認します。", "テキストはTXT、画像は個別またはZIP、両方はtext/images構成のZIPで保存します。"],
    examples: [["レポート本文をページ別TXTに整理", "通常のコピーで行・列の順番が崩れる資料をページ区切り付きTXTとして保存します。"], ["PDF内の写真だけをまとめる", "ページ全体をJPG化せず、PDF内部で使用されるラスター画像オブジェクトをページ・連番で分離します。"], ["抽出資料を1つのZIPで共有", "テキストと画像を/text・/imagesに分け、ページ関係を保ったファイル名でまとめます。"]],
    expertTitle: "PDFテキストと埋め込み画像を正しく抽出する基準", expertLead: "テキストレイヤー、読み順、PDF画像オブジェクト、PNG fallback、重複画像、スキャンPDFとOCRの違いを理解するための実践基準です。",
    expert: [["テキスト抽出とOCRは同じではありません", "テキストPDFは文字情報を内部オブジェクトとして持つためPDF.jsのAPIで読み取れます。画像だけのスキャンPDFにはテキストレイヤーがない場合があり、035はその状態を案内してOCRを勝手に実行しません。"], ["見た目の読み順と内部保存順は異なる場合があります", "段組み、表、浮動テキスト、複雑なフォントでは内部text itemの順番が人の読み順と一致しないことがあります。空白と改行を保守的に整え、完全なレイアウト復元は約束しません。"], ["画像抽出とページ全体レンダリングを分けます", "027は表示されるPDFページ全体を画像に変換します。035はページキャプチャではなくPDFの演算子と画像オブジェクトをたどって埋め込みラスター画像を探します。"], ["元のencoded streamを常にそのまま保存できるわけではありません", "DCTDecodeのJPEGは元の圧縮streamをJPGのまま抽出して再エンコードを避けます。フィルター・マスク・色空間などで元streamを安全に保持できない他のラスター画像のみdecoded PNG fallbackで保存します。"], ["主要画像とすべての画像を分けて表示します", "PDF内部には写真だけでなく、小さなアイコン・マスク・装飾断片・繰り返しロゴが多数含まれることがあります。初期値の主要画像では保守的なサイズ・マスク・重複基準を使い、すべての画像では正常にデコードできたオブジェクトを可能な限り確認できます。"], ["繰り返しXObjectは自動で重複除外します", "同一bitmapは主要画像とすべての画像の両方で自動除外し、結果数とZIP容量を抑えます。サイズや実際のピクセル内容が異なる画像は別結果として保持します。"], ["大きいPDFはページ順処理が安全です", "大量のテキスト・bitmap・Blobを同時に保持するとモバイルでメモリが急増します。ページごとに処理して不要なpage objectを解放する流れが適しています。"], ["ZIP構造と決定的ファイル名が後処理を助けます", "page-001-image-001.pngのように桁をそろえるとファイル一覧でも順番を保てます。textとimagesを分けると自動処理にも再利用しやすくなります。"]],
    caution: "注意事項", cautions: ["このツールはOCRを実行しません。テキストレイヤーのないスキャンPDFはテキスト結果が空になる場合があります。", "複雑な段組み・表・特殊なfont encodingでは見た目と抽出文字列の順番が一部異なる場合があります。", "元encoded streamを安全に復元できない画像はdecoded PNG fallbackで保存し、その状態を表示します。", "パスワード・権限・破損・特殊構造のPDFは全体または一部ページ・画像で失敗する場合があります。", "サービス上限はPDF 1件・50MB・200ページです。抽出画像が500件を超えると警告し、1,000件に達するとブラウザ安定性のため追加抽出を停止します。"],
    faq: "よくある質問", more: "FAQをもっと見る", less: "FAQを閉じる", faqs: [["スキャンPDFから文字を抽出できますか？", "すでにテキストレイヤーがある場合は可能です。画像だけのスキャンはOCRが必要で、035は自動OCRを行いません。"], ["PDF内の元写真だけを抽出しますか？", "ページ全体のスクリーンショットではなく埋め込みラスター画像を抽出します。PDF構造によっては元streamではなくdecoded PNG fallbackになります。"], ["PDF全ページをJPGにできますか？", "いいえ。ページ全体の画像変換は027 PDF画像変換ツールの役割です。"], ["特定ページだけ抽出できますか？", "はい。すべて、チェック選択、1-3,5,8のような指定範囲を使用できます。"], ["小さいアイコンも出ますか？", "初期値の主要画像では極小の装飾オブジェクトやマスクを隠します。すべての画像に切り替えると正常にデコードできた小さいリソースも確認できます。"], ["同じロゴが複数ページにある場合は？", "同一bitmapの重複は主要画像とすべての画像の両方で自動除外し、同じ画像を繰り返し保存しません。"], ["テキストと画像を一緒に保存できますか？", "はい。テキスト+画像モードではtextとimagesフォルダーを1つのZIPにします。"], ["サービス上限はどのくらいですか？", "PDF 1件、最大50MB、最大200ページです。抽出画像が500件を超えると警告し、1,000件に達すると既存結果を保持したまま追加画像抽出を安全停止します。"], ["ファイルはサーバーへ送られますか？", "いいえ。実装された解析と結果生成は現在のブラウザ内で行い、PDF・テキスト・画像をサーバーに保存しません。"]],
    related: "関連ツール", next: "次の作業", coming: "準備中",
  },
} as const;

export function PdfTextImageExtractorPage({ locale }: { locale: Locale }) {
  const t = copy[locale];
  const url = `https://toolbox.fixlgs.com/${locale}/pdf-text-image-extractor`;
  const jsonLd = { "@context": "https://schema.org", "@graph": [{ "@type": "WebApplication", name: t.title, applicationCategory: "UtilitiesApplication", operatingSystem: "Any", url, description: t.desc, offers: { "@type": "Offer", price: "0", priceCurrency: "USD" }, featureList: ["Extract PDF text", "Extract embedded PDF images", "Group results by page", "TXT download", "Image ZIP download", "Text and images ZIP", "Local browser processing"] }, { "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "TOOLBOX", item: `https://toolbox.fixlgs.com/${locale}` }, { "@type": "ListItem", position: 2, name: t.back, item: `https://toolbox.fixlgs.com/${locale}/category/pdf` }, { "@type": "ListItem", position: 3, name: t.title, item: url }] }, { "@type": "FAQPage", mainEntity: t.faqs.map(([q, a]) => ({ "@type": "Question", name: q, acceptedAnswer: { "@type": "Answer", text: a } })) }] };
  const related = [
    { n: "001", name: locale === "ko" ? "JPG·PNG·WebP 이미지 변환기" : locale === "en" ? "JPG, PNG & WebP Image Converter" : "JPG・PNG・WebP画像変換ツール", href: `/${locale}/jpg-png-webp-image-converter` },
    { n: "027", name: locale === "ko" ? "PDF 이미지 변환기" : locale === "en" ? "PDF to Image Converter" : "PDF 画像変換ツール", href: `/${locale}/pdf-to-image-converter` },
    { n: "029", name: locale === "ko" ? "PDF 분할·페이지 추출기" : locale === "en" ? "Split & Extract PDF" : "PDF 分割・ページ抽出ツール", href: `/${locale}/split-extract-pdf` },
    { n: "030", name: locale === "ko" ? "PDF 페이지 정리 도구" : locale === "en" ? "PDF Page Organizer" : "PDF ページ整理ツール", href: `/${locale}/pdf-page-organizer` },
  ];
  return <ToolboxSubpageShell locale={locale} appName={t.title}>
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} />
    <section className="toolbox-tool-detail-hero toolbox-tool-detail-hero--single-line-description"><Link className="toolbox-subpage-back" href={`/${locale}/category/pdf`}>← {t.back}</Link><p className="toolbox-subpage-eyebrow">035 · PDF</p><div className="toolbox-tool-detail-heading"><h1><span className="toolbox-tool-title-line">{t.title}</span></h1><p>{t.desc}</p></div><div className="toolbox-tool-detail-badge"><strong>LOCAL</strong><span>{t.local}</span></div></section>
    <section className="toolbox-tool-detail-body"><div><PdfTextImageExtractorTool locale={locale} />
      <section className="toolbox-next-work"><div className="toolbox-next-work-head"><p>NEXT WORK</p><h2>{t.next}</h2></div><div className="toolbox-next-work-grid"><div className="toolbox-next-work-card is-disabled"><span>036</span><h3>{locale === "ko" ? "글자 수·문서 통계 계산기" : locale === "en" ? "Character & Document Statistics Calculator" : "文字数・文書統計計算ツール"}</h3><div className="toolbox-next-work-card-foot"><span>{t.coming}</span><strong>·</strong></div></div></div></section>
      <section className="toolbox-next-work"><div className="toolbox-next-work-head"><p>RELATED TOOLS</p><h2>{t.related}</h2></div><div className="toolbox-next-work-grid">{related.map((x) => <Link key={x.n} href={x.href} className="toolbox-next-work-card"><span>{x.n}</span><h3>{x.name}</h3><div className="toolbox-next-work-card-foot"><span>{locale === "ko" ? "사용 가능" : locale === "en" ? "AVAILABLE" : "利用可能"}</span><strong>↗</strong></div></Link>)}</div></section>
    </div></section>
    <section className="toolbox-tool-guide toolbox-tool-guide--five"><div className="toolbox-tool-guide-head"><p>HOW TO USE</p><h2>{t.how}</h2></div><ol>{t.steps.map((s, i) => <li key={s}><span>{String(i + 1).padStart(2, "0")}</span><p>{s}</p></li>)}</ol></section>
    <section className="toolbox-tool-format-guide toolbox-tool-use-cases--editorial"><div className="toolbox-tool-format-guide-head"><p>USE CASES</p><h2>{locale === "ko" ? "활용 예시" : locale === "en" ? "Use cases" : "活用例"}</h2></div><div className="toolbox-tool-format-body"><div className="toolbox-tool-format-grid">{t.examples.map(([title, description], i) => <article key={title}><strong>{String(i + 1).padStart(2, "0")}</strong><h3>{title}</h3><p>{description}</p></article>)}</div></div></section>
    <section className="toolbox-tool-format-guide toolbox-tool-expert-post toolbox-tool-expert-post--wide-head toolbox-tool-expert-post--compact-copy"><div className="toolbox-tool-format-guide-head"><p>EXPERT POST</p><h2>{t.expertTitle}</h2><span>{t.expertLead}</span></div><div className="toolbox-tool-format-body"><div className="toolbox-tool-direction-grid toolbox-tool-practical-grid">{t.expert.map(([title, description]) => <article key={title}><h4>{title.split("\n").map((line, i) => <span key={`${title}-${i}`}>{i > 0 && <br />}{line}</span>)}</h4><p>{description}</p></article>)}</div></div></section>
    <section className="toolbox-tool-info-band toolbox-tool-info-band--section-start toolbox-tool-info-band--bottom-gap toolbox-tool-info-band--left-head toolbox-tool-info-band--format-head"><div className="toolbox-tool-info-band-head"><p>IMPORTANT NOTES</p><h2>{t.caution}</h2><span>{t.local}</span></div><ul className="toolbox-tool-info-band-list">{t.cautions.map((x) => <li key={x}>{x}</li>)}</ul></section>
    <section className="toolbox-tool-faq"><div className="toolbox-tool-guide-head"><p>FAQ</p><h2>{t.faq}</h2></div><ToolboxFaqList items={t.faqs.map(([q, a]): readonly [string, string] => [q, a])} initialCount={5} moreLabel={t.more} collapseLabel={t.less} className="toolbox-tool-faq-list" /></section>
    <section className="toolbox-tool-processing-note"><p>{t.local}</p></section>
  </ToolboxSubpageShell>;
}
