/* eslint-disable @next/next/no-img-element */
"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { createStoredZip } from "@/lib/zip";
import type { Locale } from "@/lib/site";

type OutputFormat = "image/png" | "image/jpeg" | "image/webp";
type Status = "idle" | "processing" | "done" | "error" | "cancelled";
type InputKind = "svg" | "bmp" | "tiff";
type QualityMode = "auto" | "high" | "balanced" | "space";
type ResultItem = { id:string; blob:Blob; url:string; name:string; width:number; height:number; page?:number };
type Item = {
  id:string; file:File; kind:InputKind; output:OutputFormat; status:Status;
  previewUrl?:string; safeSvgText?:string; results:ResultItem[];
  width?:number; height?:number; pageCount?:number; selectedPages?:number[];
  pageThumbs?:Record<number,string>; error?:string; isNew?:boolean;
};

declare global { interface Window { UTIF?: { decode:(b:ArrayBuffer)=>Array<Record<string,unknown>>; decodeImage:(b:ArrayBuffer,ifd:Record<string,unknown>)=>void; toRGBA8:(ifd:Record<string,unknown>)=>Uint8Array } } }

const MAX_FILES=10, MAX_FILE=20*1024*1024, MAX_TOTAL=60*1024*1024, MAX_PIXELS=40_000_000, MAX_TIFF_TOTAL_PIXELS=80_000_000;
// 003 운영 안전선: 10개, 파일당 20MB, 전체 60MB, 출력당 40MP, TIFF 선택 페이지 합계 80MP.
const TIFF_CDN="https://cdn.jsdelivr.net/npm/utif@3.1.0/UTIF.min.js";

const copy={
 ko:{workspace:"SVG·BMP·TIFF 이미지 변환 작업장",drop:"이미지를 여기에 놓으세요",help:"여러 파일을 한 번에 추가하거나 아래 버튼으로 선택할 수 있습니다.",select:"이미지 선택",add:"이미지 추가",supported:"SVG, BMP, TIFF, TIF 지원",limit:"최대 10개 · 파일당 20MB · 전체 60MB",output:"출력 형식",size:"출력 크기",ratio:"비율 유지",quality:"품질",auto:"자동 추천",high:"고화질",balanced:"균형",space:"용량 절약",convert:"변환하기",convertNew:"추가한 이미지만 변환",reconvert:"전체 다시 변환",cancel:"취소",zip:"전체 ZIP 다운로드",zipping:"ZIP 생성 중...",retryZip:"ZIP 다시 만들기",reset:"전체 초기화",download:"다운로드",remove:"삭제",pages:"페이지 선택",all:"전체",processing:"변환 중",done:"완료",failed:"실패",cancelled:"취소됨",idle:"대기",notice:"안내",local:"파일은 서버로 전송되지 않고 브라우저에서 처리됩니다. TIFF 변환 기능 코드는 외부 CDN에서 불러옵니다.",jpgBg:"JPG 배경색",width:"너비",height:"높이",custom:"사용자 지정",oneX:"1x",twoX:"2x",threeX:"3x",noFiles:"먼저 파일을 추가하세요.",tiffLoad:"TIFF 변환 모듈을 불러오지 못했습니다. 네트워크 연결을 확인한 뒤 다시 시도하세요.",retry:"다시 불러오기",badSvg:"안전하지 않거나 손상된 SVG입니다.",tooLarge:"파일 제한을 초과했습니다.",unsupported:"지원하지 않거나 손상된 파일입니다.",progress:(n:number,total:number)=>`${n} / ${total}개 처리 중`,pageProgress:(n:number,total:number)=>`${total}페이지 중 ${n}페이지 변환 중`,summary:(ok:number,fail:number,cancel:number)=>`${ok}개 완료 · ${fail}개 실패${cancel?` · ${cancel}개 취소`:""}`},
 en:{workspace:"SVG, BMP & TIFF conversion workspace",drop:"Drop images here",help:"Add several files at once, or choose them below.",select:"Choose Images",add:"Add Images",supported:"SVG, BMP, TIFF and TIF",limit:"Up to 10 files · 20 MB each · 60 MB total",output:"Output format",size:"Output size",ratio:"Keep aspect ratio",quality:"Quality",auto:"Recommended",high:"High",balanced:"Balanced",space:"Smaller",convert:"Convert Images",convertNew:"Convert Added Images",reconvert:"Reconvert All",cancel:"Cancel",zip:"Download ZIP",zipping:"Creating ZIP...",retryZip:"Create ZIP Again",reset:"Reset All",download:"Download",remove:"Remove",pages:"Select pages",all:"All",processing:"Processing",done:"Done",failed:"Failed",cancelled:"Cancelled",idle:"Ready",notice:"Notice",local:"Files stay in your browser. TIFF conversion code is loaded from an external CDN.",jpgBg:"JPG background",width:"Width",height:"Height",custom:"Custom",oneX:"1x",twoX:"2x",threeX:"3x",noFiles:"Add files first.",tiffLoad:"The TIFF module could not load. Check your connection and try again.",retry:"Retry loading",badSvg:"This SVG is unsafe or damaged.",tooLarge:"The file limit was exceeded.",unsupported:"This file is unsupported or damaged.",progress:(n:number,total:number)=>`Processing ${n} of ${total}`,pageProgress:(n:number,total:number)=>`Converting page ${n} of ${total}`,summary:(ok:number,fail:number,cancel:number)=>`${ok} done · ${fail} failed${cancel?` · ${cancel} cancelled`:""}`},
 ja:{workspace:"SVG・BMP・TIFF画像変換ワークスペース",drop:"画像をここにドロップ",help:"複数ファイルをまとめて追加するか、下のボタンから選択できます。",select:"画像を選択",add:"画像を追加",supported:"SVG・BMP・TIFF・TIF対応",limit:"最大10件・1件20MB・合計60MB",output:"出力形式",size:"出力サイズ",ratio:"縦横比を維持",quality:"画質",auto:"自動推奨",high:"高画質",balanced:"バランス",space:"容量節約",convert:"画像を変換",convertNew:"追加画像のみ変換",reconvert:"すべて再変換",cancel:"キャンセル",zip:"ZIPで保存",zipping:"ZIPを作成中...",retryZip:"ZIPを再作成",reset:"すべて初期化",download:"ダウンロード",remove:"削除",pages:"ページ選択",all:"すべて",processing:"変換中",done:"完了",failed:"失敗",cancelled:"キャンセル",idle:"待機",notice:"案内",local:"ファイルはサーバーへ送信されず、ブラウザ内で処理されます。TIFF変換コードは外部CDNから読み込みます。",jpgBg:"JPG背景色",width:"幅",height:"高さ",custom:"指定",oneX:"1x",twoX:"2x",threeX:"3x",noFiles:"先にファイルを追加してください。",tiffLoad:"TIFF変換モジュールを読み込めませんでした。接続を確認して再試行してください。",retry:"再読み込み",badSvg:"安全でない、または破損したSVGです。",tooLarge:"ファイル制限を超えています。",unsupported:"対応していない、または破損したファイルです。",progress:(n:number,total:number)=>`${n} / ${total}件を処理中`,pageProgress:(n:number,total:number)=>`${total}ページ中${n}ページを変換中`,summary:(ok:number,fail:number,cancel:number)=>`${ok}件完了・${fail}件失敗${cancel?`・${cancel}件キャンセル`:""}`}
} as const;

function expectedKind(file:File):InputKind|null { const e=file.name.split(".").pop()?.toLowerCase(); return e==="svg"?"svg":e==="bmp"?"bmp":e==="tif"||e==="tiff"?"tiff":null; }
function duplicateKey(file:File){return `${file.name.toLowerCase()}|${file.size}|${file.lastModified}`}
async function kindOf(file:File):Promise<InputKind|null>{
 const expected=expectedKind(file);if(!expected||file.size===0)return null;
 if(expected==="svg"){try{const text=await file.slice(0,Math.min(file.size,65536)).text();return /<svg[\s>]/i.test(text)?"svg":null}catch{return null}}
 const b=new Uint8Array(await file.slice(0,16).arrayBuffer());
 if(expected==="bmp")return b[0]===0x42&&b[1]===0x4d?"bmp":null;
 const little=b[0]===0x49&&b[1]===0x49, big=b[0]===0x4d&&b[1]===0x4d;
 if(!little&&!big)return null;
 const version=little?(b[2]|(b[3]<<8)):((b[2]<<8)|b[3]);
 return version===42?"tiff":null;
}
function formats(k:InputKind):OutputFormat[]{return k==="bmp"?["image/png","image/jpeg","image/webp"]:["image/png","image/jpeg"]}
function ext(f:OutputFormat){return f==="image/jpeg"?"jpg":f==="image/webp"?"webp":"png"}
function base(n:string){return n.replace(/\.[^.]+$/,'')}
function bytes(n:number){if(n<1024)return`${n} B`;if(n<1048576)return`${(n/1024).toFixed(1)} KB`;return`${(n/1048576).toFixed(1)} MB`}
function download(blob:Blob,name:string){const u=URL.createObjectURL(blob);const a=document.createElement("a");a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
function canvasBlob(c:HTMLCanvasElement,type:OutputFormat,q:number){return new Promise<Blob>((resolve,reject)=>c.toBlob(b=>b?resolve(b):reject(new Error("encode")),type,q))}
async function loadImage(url:string){return new Promise<HTMLImageElement>((res,rej)=>{const i=new Image();i.onload=()=>res(i);i.onerror=()=>rej(new Error("decode"));i.src=url})}
function revokeResults(results:ResultItem[]){results.forEach(r=>URL.revokeObjectURL(r.url))}
function uniqueName(desired:string,used:Map<string,number>){const dot=desired.lastIndexOf(".");const stem=dot>0?desired.slice(0,dot):desired;const extension=dot>0?desired.slice(dot):"";const key=desired.toLowerCase();const n=(used.get(key)||0)+1;used.set(key,n);return n===1?desired:`${stem}-${n}${extension}`}
function sanitizeSvg(raw:string){
 const doc=new DOMParser().parseFromString(raw,"image/svg+xml");
 if(doc.querySelector("parsererror"))throw new Error("svg");
 doc.querySelectorAll("script,iframe,foreignObject,style,animate,animateMotion,animateTransform,set").forEach(n=>n.remove());
 doc.querySelectorAll("*").forEach(el=>{[...el.attributes].forEach(a=>{
  const n=a.name.toLowerCase(),v=a.value.trim(); const lower=v.toLowerCase();
  if(n.startsWith("on")||lower.includes("javascript:")){el.removeAttribute(a.name);return}
  if(n==="href"||n==="xlink:href"){if(!v.startsWith("#"))el.removeAttribute(a.name);return}
  if(lower.includes("url(")){const refs=[...v.matchAll(/url\(([^)]+)\)/gi)].map(m=>m[1].replace(/["']/g,"").trim());if(refs.some(ref=>!ref.startsWith("#")))el.removeAttribute(a.name)}
 })});
 return new XMLSerializer().serializeToString(doc.documentElement);
}
function svgSize(safe:string){const doc=new DOMParser().parseFromString(safe,"image/svg+xml");const root=doc.documentElement;const parse=(v:string|null)=>v?Number.parseFloat(v):NaN;let w=parse(root.getAttribute("width")),h=parse(root.getAttribute("height"));if((!Number.isFinite(w)||!Number.isFinite(h))&&root.getAttribute("viewBox")){const p=root.getAttribute("viewBox")!.trim().split(/[ ,]+/).map(Number);if(p.length===4){w=p[2];h=p[3]}}return{width:Number.isFinite(w)&&w>0?w:300,height:Number.isFinite(h)&&h>0?h:150}}
async function ensureUtif(force=false){
 if(force){delete window.UTIF;document.querySelectorAll(`script[src="${TIFF_CDN}"]`).forEach(n=>n.remove())}
 if(window.UTIF)return window.UTIF;
 await new Promise<void>((res,rej)=>{const old=document.querySelector(`script[src="${TIFF_CDN}"]`) as HTMLScriptElement|null;if(old){old.addEventListener("load",()=>res(),{once:true});old.addEventListener("error",()=>rej(),{once:true});return}const s=document.createElement("script");s.src=TIFF_CDN;s.async=true;s.onload=()=>res();s.onerror=()=>rej();document.head.appendChild(s)});
 if(!window.UTIF)throw new Error("utif");return window.UTIF;
}
async function tiffThumbs(file:File,selected:number[],existing:Record<number,string>={}){const UTIF=await ensureUtif();const buf=await file.arrayBuffer();const ifds=UTIF.decode(buf);const next={...existing};for(const idx of selected){if(next[idx])continue;const ifd=ifds[idx];UTIF.decodeImage(buf,ifd);const rgba=UTIF.toRGBA8(ifd);const w=Number(ifd.width||0),h=Number(ifd.height||0);if(!w||!h)continue;const scale=Math.min(1,220/Math.max(w,h));const src=document.createElement("canvas");src.width=w;src.height=h;src.getContext("2d")!.putImageData(new ImageData(new Uint8ClampedArray(rgba),w,h),0,0);const thumb=document.createElement("canvas");thumb.width=Math.max(1,Math.round(w*scale));thumb.height=Math.max(1,Math.round(h*scale));thumb.getContext("2d")!.drawImage(src,0,0,thumb.width,thumb.height);const blob=await canvasBlob(thumb,"image/png",1);next[idx]=URL.createObjectURL(blob);await new Promise(r=>setTimeout(r,0))}return next}

export function SvgBmpTiffConverterTool({locale}:{locale:Locale}){
 const t=copy[locale], inputRef=useRef<HTMLInputElement>(null),itemsRef=useRef<Item[]>([]),cancelRef=useRef(false);
 const [items,setItems]=useState<Item[]>([]),[drag,setDrag]=useState(false),[processing,setProcessing]=useState(false),[message,setMessage]=useState(""),[quality,setQuality]=useState<QualityMode>("auto"),[scale,setScale]=useState<1|2|3|"custom">(1),[customW,setCustomW]=useState(1200),[customH,setCustomH]=useState(1200),[keepRatio,setKeepRatio]=useState(true),[bg,setBg]=useState("#ffffff"),[zipState,setZipState]=useState<"idle"|"working"|"error">("idle");
 useEffect(()=>{itemsRef.current=items},[items]);
 useEffect(()=>()=>itemsRef.current.forEach(i=>{if(i.previewUrl)URL.revokeObjectURL(i.previewUrl);Object.values(i.pageThumbs||{}).forEach(URL.revokeObjectURL);revokeResults(i.results)}),[]);
 const completed=items.filter(i=>i.status==="done"&&i.results.length),newCount=items.filter(i=>i.isNew&&i.status!=="processing").length;
 const hasSvg=items.some(i=>i.kind==="svg"),lossy=items.some(i=>i.output!=="image/png");
 const q=quality==="high"?.94:quality==="space"?.68:quality==="balanced"?.82:.86;
 const resultStats=useMemo(()=>({ok:items.reduce((s,i)=>s+(i.status==="done"?i.results.length:0),0),fail:items.filter(i=>i.status==="error").length,cancel:items.filter(i=>i.status==="cancelled").length,size:items.reduce((s,i)=>s+i.results.reduce((a,r)=>a+r.blob.size,0),0)}),[items]);
 function patch(id:string,p:Partial<Item>){setItems(v=>v.map(i=>i.id===id?{...i,...p}:i))}
 async function addFiles(list:FileList|File[]){setMessage("");const incoming=[...Array.from(list)];let total=items.reduce((sum,item)=>sum+item.file.size,0),duplicates=0,rejected=0;const next:Item[]=[];const seen=new Set(items.map(item=>duplicateKey(item.file)));for(const file of incoming){if(items.length+next.length>=MAX_FILES||file.size>MAX_FILE||total+file.size>MAX_TOTAL){rejected++;continue}const key=duplicateKey(file);if(seen.has(key)){duplicates++;continue}const kind=await kindOf(file);if(!kind){rejected++;continue}total+=file.size;seen.add(key);const item:Item={id:crypto.randomUUID(),file,kind,output:"image/png",status:"idle",results:[],isNew:true};try{
   if(kind==="svg"){const safe=sanitizeSvg(await file.text());const sz=svgSize(safe);const blob=new Blob([safe],{type:"image/svg+xml"});item.safeSvgText=safe;item.previewUrl=URL.createObjectURL(blob);item.width=sz.width;item.height=sz.height}
   else if(kind==="bmp"){const objectUrl=URL.createObjectURL(file);try{const img=await loadImage(objectUrl);if(!img.naturalWidth||!img.naturalHeight||img.naturalWidth*img.naturalHeight>MAX_PIXELS)throw new Error("pixels");item.width=img.naturalWidth;item.height=img.naturalHeight;item.previewUrl=URL.createObjectURL(file)}finally{URL.revokeObjectURL(objectUrl)}}
   else {const UTIF=await ensureUtif();const ifds=UTIF.decode(await file.arrayBuffer());if(!ifds.length)throw new Error("tiff");item.pageCount=ifds.length;item.selectedPages=ifds.map((_,index)=>index);item.pageThumbs=await tiffThumbs(file,item.selectedPages.slice(0,Math.min(6,ifds.length)))}
  }catch(error){item.status="error";item.error=error instanceof Error&&error.message==="utif"?t.tiffLoad:kind==="svg"?t.badSvg:t.unsupported}
  next.push(item)}setItems(value=>[...value,...next]);const notes=[duplicates?`${locale==="ko"?"중복":locale==="en"?"Duplicates":"重複"} ${duplicates}`:"",rejected?`${t.unsupported} (${rejected})`:""].filter(Boolean);if(notes.length)setMessage(notes.join(" · "))}
 function clearItemResults(item:Item){revokeResults(item.results);return{results:[],status:"idle" as Status,error:undefined,isNew:item.isNew}}
 function move(index:number,direction:-1|1){setItems(value=>{const target=index+direction;if(target<0||target>=value.length)return value;const next=[...value];[next[index],next[target]]=[next[target],next[index]];return next})}
 async function retryItem(id:string){const item=itemsRef.current.find(value=>value.id===id);if(!item||processing)return;patch(id,{status:"idle",error:undefined,isNew:true});await convert(true)}
 function remove(id:string){setItems(v=>{const i=v.find(x=>x.id===id);if(i?.previewUrl)URL.revokeObjectURL(i.previewUrl);Object.values(i?.pageThumbs||{}).forEach(URL.revokeObjectURL);if(i)revokeResults(i.results);return v.filter(x=>x.id!==id)})}
 function reset(){itemsRef.current.forEach(i=>{if(i.previewUrl)URL.revokeObjectURL(i.previewUrl);Object.values(i.pageThumbs||{}).forEach(URL.revokeObjectURL);revokeResults(i.results)});setItems([]);setMessage("");setScale(1);setCustomW(1200);setCustomH(1200);setKeepRatio(true);setQuality("auto");setBg("#ffffff");setZipState("idle")}
 async function retryTiff(id:string){patch(id,{error:undefined,status:"idle"});try{await ensureUtif(true);const item=itemsRef.current.find(i=>i.id===id);if(!item)return;const UTIF=await ensureUtif();const ifds=UTIF.decode(await item.file.arrayBuffer());const pages=ifds.map((_,i)=>i);const thumbs=await tiffThumbs(item.file,pages.slice(0,Math.min(6,pages.length)));patch(id,{pageCount:pages.length,selectedPages:pages,pageThumbs:thumbs})}catch{patch(id,{status:"error",error:t.tiffLoad})}}
 async function renderItem(item:Item,onPage?:(n:number,total:number)=>void):Promise<ResultItem[]>{
  if(item.kind==="svg"){const safe=item.safeSvgText||sanitizeSvg(await item.file.text());const u=URL.createObjectURL(new Blob([safe],{type:"image/svg+xml"}));try{const img=await loadImage(u);const sz=svgSize(safe);const naturalW=img.naturalWidth||sz.width,naturalH=img.naturalHeight||sz.height;const w=Math.max(1,Math.round(scale==="custom"?customW:naturalW*scale));const h=Math.max(1,Math.round(scale==="custom"?(keepRatio?w*naturalH/naturalW:customH):naturalH*scale));if(w*h>MAX_PIXELS)throw new Error("pixels");const c=document.createElement("canvas");c.width=w;c.height=h;const ctx=c.getContext("2d")!;if(item.output==="image/jpeg"){ctx.fillStyle=bg;ctx.fillRect(0,0,w,h)}ctx.drawImage(img,0,0,w,h);const blob=await canvasBlob(c,item.output,q);return[{id:crypto.randomUUID(),blob,name:`${base(item.file.name)}.${ext(item.output)}`,url:URL.createObjectURL(blob),width:w,height:h}]}finally{URL.revokeObjectURL(u)}}
  if(item.kind==="bmp"){const u=URL.createObjectURL(item.file);try{const img=await loadImage(u);const w=img.naturalWidth,h=img.naturalHeight;if(!w||!h||w*h>MAX_PIXELS)throw new Error("pixels");const c=document.createElement("canvas");c.width=w;c.height=h;const ctx=c.getContext("2d")!;if(item.output==="image/jpeg"){ctx.fillStyle=bg;ctx.fillRect(0,0,w,h)}ctx.drawImage(img,0,0);const blob=await canvasBlob(c,item.output,q);return[{id:crypto.randomUUID(),blob,name:`${base(item.file.name)}.${ext(item.output)}`,url:URL.createObjectURL(blob),width:w,height:h}]}finally{URL.revokeObjectURL(u)}}
  const UTIF=await ensureUtif();const buf=await item.file.arrayBuffer();const ifds=UTIF.decode(buf);if(!ifds.length)throw new Error("tiff");let totalPixels=0;const selected=item.selectedPages||[];if(!selected.length)throw new Error("pages");const out:ResultItem[]=[];for(let pos=0;pos<selected.length;pos++){const idx=selected[pos];onPage?.(pos+1,selected.length);const ifd=ifds[idx];UTIF.decodeImage(buf,ifd);const rgba=UTIF.toRGBA8(ifd);const w=Number(ifd.width||0),h=Number(ifd.height||0);totalPixels+=w*h;if(!w||!h||w*h>MAX_PIXELS||totalPixels>MAX_TIFF_TOTAL_PIXELS)throw new Error("pixels");const c=document.createElement("canvas");c.width=w;c.height=h;c.getContext("2d")!.putImageData(new ImageData(new Uint8ClampedArray(rgba),w,h),0,0);let target=c;if(item.output==="image/jpeg"){const flat=document.createElement("canvas");flat.width=w;flat.height=h;const f=flat.getContext("2d")!;f.fillStyle=bg;f.fillRect(0,0,w,h);f.drawImage(c,0,0);target=flat}const blob=await canvasBlob(target,item.output,q);out.push({id:crypto.randomUUID(),blob,name:`${base(item.file.name)}-page-${idx+1}.${ext(item.output)}`,url:URL.createObjectURL(blob),width:w,height:h,page:idx+1});await new Promise(r=>setTimeout(r,0))}return out;
 }
 async function convert(onlyNew=false){if(!items.length){setMessage(t.noFiles);return}cancelRef.current=false;setProcessing(true);setZipState("idle");const targets=itemsRef.current.filter(i=>!onlyNew||i.isNew);const used=new Map<string,number>();itemsRef.current.filter(i=>!targets.some(ti=>ti.id===i.id)).flatMap(i=>i.results).forEach(r=>used.set(r.name.toLowerCase(),1));for(let index=0;index<targets.length;index++){const item=itemsRef.current.find(i=>i.id===targets[index].id)||targets[index];if(cancelRef.current){patch(item.id,{status:"cancelled",isNew:false});continue}revokeResults(item.results);patch(item.id,{...clearItemResults(item),status:"processing"});setMessage(t.progress(index+1,targets.length));try{const results=await renderItem(item,(n,total)=>setMessage(`${t.progress(index+1,targets.length)} · ${t.pageProgress(n,total)}`));const named=results.map(r=>({...r,name:uniqueName(r.name,used)}));patch(item.id,{status:"done",results:named,width:named[0]?.width,height:named[0]?.height,isNew:false})}catch(e){const msg=e instanceof Error&&e.message==="utif"?t.tiffLoad:e instanceof Error&&e.message==="pages"?(locale==="ko"?"변환할 TIFF 페이지를 하나 이상 선택하세요.":locale==="en"?"Select at least one TIFF page.":"変換するTIFFページを1つ以上選択してください。") : item.kind==="svg"?t.badSvg:t.unsupported;patch(item.id,{status:"error",error:msg,isNew:false})}}setProcessing(false);setMessage(t.summary(itemsRef.current.reduce((s,i)=>s+(i.status==="done"?i.results.length:0),0),itemsRef.current.filter(i=>i.status==="error").length,itemsRef.current.filter(i=>i.status==="cancelled").length))}
 async function zip(){const files=itemsRef.current.flatMap(i=>i.results.map(r=>({name:r.name,blob:r.blob})));if(!files.length)return;setZipState("working");try{download(await createStoredZip(files),"fixlgs-svg-bmp-tiff-converter.zip");setZipState("idle")}catch{setZipState("error")}}
 async function togglePage(item:Item,page:number){const current=item.selectedPages||[];const selected=current.includes(page)?current.filter(n=>n!==page):[...current,page].sort((a,b)=>a-b);patch(item.id,{selectedPages:selected});if(!item.pageThumbs?.[page]){try{const thumbs=await tiffThumbs(item.file,[page],item.pageThumbs);patch(item.id,{pageThumbs:thumbs})}catch{setMessage(t.tiffLoad)}}}
 return <div className="toolbox-tool-runtime"><section className="toolbox-workbench">
  <div className={`toolbox-workbench-upload ${drag?"is-dragging":""}`} onDragOver={e=>{e.preventDefault();setDrag(true)}} onDragLeave={()=>setDrag(false)} onDrop={e=>{e.preventDefault();setDrag(false);void addFiles(e.dataTransfer.files)}}>
   <div className="toolbox-workbench-topline"><div><span>WORKSPACE</span><strong>{t.workspace}</strong></div></div>
   <input data-testid="svg-file-input" ref={inputRef} hidden type="file" multiple accept=".svg,.bmp,.tif,.tiff,image/svg+xml,image/bmp,image/tiff" onChange={e=>{if(e.target.files)void addFiles(e.target.files);e.currentTarget.value=""}}/>
   {items.length===0?<div className="toolbox-upload-focus"><span className="toolbox-upload-icon">＋</span><h2>{t.drop}</h2><p>{t.help}</p><button type="button" onClick={()=>inputRef.current?.click()}>{t.select}</button><small>{t.supported}<br/>{t.limit}</small></div>:<div className="toolbox-upload-active">
    <div className="toolbox-upload-active-head"><div><span>{items.length} FILES</span><p>{t.local}</p></div><div className="toolbox-upload-active-actions"><button type="button" onClick={()=>inputRef.current?.click()}>＋ {t.add}</button></div></div>
    <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{items.map((i,index)=><article key={i.id} data-testid="svg-file-card" data-status={i.status} className="overflow-hidden rounded-[1.5rem] border border-border bg-surface-2">
     <div className="aspect-[4/3] bg-black/5 dark:bg-white/5">{i.results[0]?.url||i.previewUrl?<img src={i.results[0]?.url||i.previewUrl} alt={i.file.name} className="h-full w-full object-contain"/>:<div className="grid h-full place-items-center text-sm font-bold tracking-[.12em] text-muted">{i.kind.toUpperCase()}</div>}</div>
     <div className="space-y-3 p-4"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><h3 className="truncate text-sm font-semibold">{i.file.name}</h3><p className="mt-1 text-xs text-muted">{i.kind.toUpperCase()} · {bytes(i.file.size)}{i.width&&i.height?` · ${i.width}×${i.height}`:""}</p></div><span className="text-xs font-semibold">{i.status==="processing"?t.processing:i.status==="done"?t.done:i.status==="error"?t.failed:i.status==="cancelled"?t.cancelled:t.idle}</span></div>
      <div><p className="mb-2 text-xs text-muted">{t.output}</p><div className="flex flex-wrap gap-2">{formats(i.kind).map(f=><button type="button" key={f} disabled={processing} onClick={()=>{revokeResults(i.results);patch(i.id,{output:f,status:"idle",results:[]})}} className={`rounded-full px-3 py-1.5 text-xs font-semibold ${i.output===f?"bg-foreground text-background dark:bg-white dark:text-black":"border border-border bg-surface"}`}>{ext(f).toUpperCase()}</button>)}</div></div>
      {i.kind==="tiff"&&<div><p className="mb-2 text-xs text-muted">{t.pages}{i.pageCount?` · ${i.pageCount}`:""}</p><div className="flex flex-wrap gap-2"><button type="button" onClick={()=>patch(i.id,{selectedPages:Array.from({length:i.pageCount||0},(_,n)=>n)})} className="rounded-full border border-border px-3 py-1.5 text-xs">{t.all}</button>{Array.from({length:i.pageCount||0},(_,page)=><button type="button" key={page} onClick={()=>void togglePage(i,page)} className={`rounded-full px-3 py-1.5 text-xs ${(i.selectedPages||[]).includes(page)?"bg-foreground text-background dark:bg-white dark:text-black":"border border-border"}`}>{page+1}</button>)}</div>{Object.keys(i.pageThumbs||{}).length>0&&<div className="mt-3 grid grid-cols-3 gap-2">{Object.entries(i.pageThumbs||{}).map(([page,url])=><div key={page} className="overflow-hidden rounded-xl border border-border bg-surface"><img src={url} alt={`${i.file.name} page ${Number(page)+1}`} className="aspect-square h-full w-full object-contain"/><span className="block px-2 py-1 text-center text-[10px] text-muted">{Number(page)+1}</span></div>)}</div>}</div>}
      {i.results.length>0&&<div className="grid gap-2">{i.results.map(r=><div key={r.id} className="flex items-center gap-3 rounded-2xl border border-border bg-surface p-2"><img src={r.url} alt={r.name} className="h-14 w-14 rounded-xl object-contain"/><div className="min-w-0 flex-1"><p className="truncate text-xs font-semibold">{r.name}</p><p className="text-[11px] text-muted">{r.width}×{r.height} · {bytes(r.blob.size)}</p></div><button type="button" onClick={()=>download(r.blob,r.name)} className="rounded-full bg-foreground px-3 py-1.5 text-xs font-semibold text-background dark:bg-white dark:text-black">{t.download}</button></div>)}</div>}
      {i.error&&<div className="rounded-2xl border border-warning/30 bg-warning/10 p-3 text-xs text-warning">{i.error}{i.kind==="tiff"&&<button type="button" onClick={()=>void retryTiff(i.id)} className="ml-2 underline">{t.retry}</button>}<button type="button" onClick={()=>void retryItem(i.id)} disabled={processing} className="ml-2 underline">{locale==="ko"?"다시 시도":locale==="en"?"Retry":"再試行"}</button></div>}
      <div className="flex flex-wrap gap-2"><button type="button" onClick={()=>move(index,-1)} disabled={processing||index===0} className="rounded-full border border-border px-3 py-1.5 text-xs">↑</button><button type="button" onClick={()=>move(index,1)} disabled={processing||index===items.length-1} className="rounded-full border border-border px-3 py-1.5 text-xs">↓</button><button type="button" onClick={()=>remove(i.id)} disabled={processing} className="rounded-full border border-border px-3 py-1.5 text-xs">{t.remove}</button></div>
     </div></article>)}</div>
   </div>}
  </div>
  {hasSvg&&<div className="mt-5 rounded-2xl border border-border bg-surface-2 p-4"><p className="font-medium">{t.size}</p><div className="mt-3 flex flex-wrap gap-2">{([1,2,3,"custom"] as const).map(v=><button type="button" key={v} onClick={()=>setScale(v)} className={`rounded-full px-3 py-1.5 text-sm ${scale===v?"bg-foreground text-background dark:bg-white dark:text-black":"border border-border"}`}>{v===1?t.oneX:v===2?t.twoX:v===3?t.threeX:t.custom}</button>)}</div>{scale==="custom"&&<div className="mt-4 grid gap-3 sm:grid-cols-2"><label className="text-sm">{t.width}<input type="number" min="1" max="8000" value={customW} onChange={e=>setCustomW(Number(e.target.value)||1)} className="mt-1 w-full rounded-xl border border-border bg-surface p-2"/></label><label className="text-sm">{t.height}<input type="number" min="1" max="8000" value={customH} disabled={keepRatio} onChange={e=>setCustomH(Number(e.target.value)||1)} className="mt-1 w-full rounded-xl border border-border bg-surface p-2"/></label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={keepRatio} onChange={e=>setKeepRatio(e.target.checked)}/>{t.ratio}</label></div>}</div>}
  {lossy&&<div className="mt-5 rounded-2xl border border-border bg-surface-2 p-4"><p className="font-medium">{t.quality}</p><div className="mt-3 flex flex-wrap gap-2">{(["auto","high","balanced","space"] as const).map(v=><button type="button" key={v} onClick={()=>setQuality(v)} className={`rounded-full px-3 py-1.5 text-sm ${quality===v?"bg-foreground text-background dark:bg-white dark:text-black":"border border-border"}`}>{t[v]}</button>)}</div><label className="mt-4 flex items-center gap-3 text-sm">{t.jpgBg}<input type="color" value={bg} onChange={e=>setBg(e.target.value)}/></label></div>}
  {message&&<div className="toolbox-workbench-notice" aria-live="polite"><strong>{t.notice}</strong> {message}</div>}
  {resultStats.ok>0&&<div className="toolbox-workbench-summary"><span>{t.summary(resultStats.ok,resultStats.fail,resultStats.cancel)}</span><strong>·</strong><span>{bytes(resultStats.size)}</span></div>}
  {items.length>0&&<div className="toolbox-workbench-actions">{processing?<button type="button" className="toolbox-primary-action" onClick={()=>{cancelRef.current=true}}>{t.cancel}</button>:<><button data-testid="svg-run" type="button" className="toolbox-primary-action" onClick={()=>void convert(false)}>{completed.length?t.reconvert:t.convert}</button>{newCount>0&&completed.length>0&&<button type="button" onClick={()=>void convert(true)}>{t.convertNew}</button>}</>}<button type="button" className="toolbox-zip-action" onClick={()=>void zip()} disabled={!resultStats.ok||zipState==="working"}>{zipState==="working"?t.zipping:zipState==="error"?t.retryZip:t.zip}</button><button type="button" className="toolbox-restart-action" onClick={reset} disabled={processing}>{t.reset}</button></div>}
 </section><button className="toolbox-converter-mobile-add" type="button" onClick={()=>inputRef.current?.click()}>{t.add}</button></div>
}
