import Link from "next/link";
import { TextExtractorTool } from "@/components/text-extractor-tool";
import { ToolboxFaqList } from "@/components/toolbox-faq-list";
import { ToolboxSubpageShell } from "@/components/toolbox-subpage-shell";
import type { Locale } from "@/lib/site";

const copy = {
  ko:{back:"텍스트 도구",title:"텍스트 추출기",desc:"긴 텍스트에서 숫자, 한글·영어, 이메일, URL, 전화번호, 해시태그를 유형별로 빠르게 추출하세요.",local:"원문과 추출 결과는 브라우저 로컬에서만 처리하며 서버로 전송하거나 저장하지 않습니다.",next:"다음 작업",related:"관련 도구",available:"사용 가능",coming:"준비 중",how:"사용 방법",guide:"텍스트 추출을 정확하게 사용하는 방법",guideDesc:"원문을 바꾸지 않고 필요한 문자열 패턴만 유형별로 분리해 확인하는 기준을 정리했습니다.",caution:"주의사항",faq:"자주 묻는 질문",steps:["텍스트를 직접 입력·붙여넣거나 TXT·MD·CSV 파일을 불러옵니다.","숫자·한글·영어·이메일·URL·전화번호·해시태그 중 필요한 유형을 선택합니다.","추출을 실행해 유형별 결과와 건수를 확인합니다.","필요한 결과를 복사하거나 TXT로 다운로드합니다."],points:[["이메일","연락처·문의 주소 분리","메일·공지·CSV·로그처럼 긴 문서에서 이메일 형태 문자열만 빠르게 모을 수 있습니다."],["URL","링크 목록 정리","http·https·www로 시작하는 URL을 찾아 문서와 게시물에서 링크만 분리할 수 있습니다."],["전화번호","연락처 문자열 찾기","국내 번호와 실용적인 국제번호 패턴을 찾아 연락처 문서에서 전화번호만 확인할 수 있습니다."],["숫자","수치 토큰 확인","정수·소수·천 단위 쉼표·퍼센트 형태의 숫자 토큰을 찾아 주문·가격·로그 텍스트를 살펴볼 수 있습니다."],["한글·영어","문자군 분리","Hangul과 Latin 문자군을 각각 추출해 혼합 문서에서 필요한 언어 문자열을 확인할 수 있습니다."],["해시태그","SNS 태그 수집","Unicode 문자·숫자·밑줄을 포함한 해시태그를 찾아 한국어·영어·일본어 태그를 분리할 수 있습니다."]],cautions:["이메일·URL·전화번호는 실용적인 문자열 패턴을 추출하며 실제 계정 존재 여부나 접속 가능 여부를 검증하지 않습니다.","각 유형은 독립적으로 추출하므로 같은 원문 일부가 여러 유형 결과에 동시에 포함될 수 있습니다.","유형별 결과는 해당 유형 안에서 원문에 등장한 순서를 유지합니다.","서비스 상한은 입력 300,000자, 유형당 10,000건, 전체 30,000건으로 적용합니다."],faqs:[["입력한 내용이 서버로 전송되나요?","아니요. 입력 원문과 추출 결과는 현재 브라우저에서만 처리합니다."],["이메일이나 URL을 완전히 검증하나요?","아니요. 실용적인 문자열 추출 도구이며 최종 유효성 검증 도구는 아닙니다."],["일본어 해시태그도 추출하나요?","네. Unicode 문자 기반 해시태그를 추출하므로 일본어 태그도 대상에 포함됩니다."],["결과 순서는 어떻게 되나요?","각 추출 유형 안에서는 원문에 등장한 순서를 유지합니다."],["파일을 불러온 뒤 다른 파일로 바꾸면 어떻게 되나요?","현재 원문·결과·추출 유형이 초기화될 수 있어 교체 확인창에서 확인 후 새 파일을 불러옵니다."],["결과를 파일로 저장할 수 있나요?","네. 추출 결과를 복사하거나 UTF-8 TXT 파일로 다운로드할 수 있습니다."]]},
  en:{back:"Text Tools",title:"Text Data Extractor",desc:"Extract numbers, Korean, English, emails, URLs, phone numbers, and hashtags from long text by type.",local:"Your source text and extracted results are processed locally in the browser and are not sent to or stored on a server.",next:"Next work",related:"Related tools",available:"Available",coming:"Coming soon",how:"How to use",guide:"How to extract text patterns reliably",guideDesc:"These notes explain how the tool separates useful string patterns by type without changing the source text.",caution:"Important notes",faq:"Frequently asked questions",steps:["Type or paste text, or load a TXT, MD, or CSV file.","Select the extraction types you need: numbers, Korean, English, emails, URLs, phone numbers, or hashtags.","Run Extract and review each result group and count.","Copy the results or download them as a TXT file."],points:[["Emails","Collect contact addresses","Pull email-like strings from mail, notices, CSV exports, logs, and long documents."],["URLs","Build a link list","Find URLs beginning with http, https, or www and separate links from posts or documents."],["Phone numbers","Find contact strings","Locate practical Korean and international phone-number patterns in contact text."],["Numbers","Inspect numeric tokens","Find integers, decimals, grouped numbers, and percentage-like numeric tokens in orders, prices, and logs."],["Korean / English","Separate scripts","Extract Hangul and Latin runs independently from mixed-language documents."],["Hashtags","Collect social tags","Extract Unicode hashtags containing letters, numbers, and underscores, including Korean and Japanese tags."]],cautions:["Email, URL, and phone extraction uses practical string patterns and does not verify account existence or connectivity.","Each type is extracted independently, so the same source span may appear in more than one result type.","Within each type, results keep their original source order.","Service limits are 300,000 input characters, 10,000 matches per type, and 30,000 total matches."],faqs:[["Is my text sent to a server?","No. Your source text and extracted results are processed in the current browser only."],["Does it fully validate emails or URLs?","No. It is a practical extraction tool, not a final validity checker."],["Are Japanese hashtags supported?","Yes. Unicode hashtag characters include Japanese tags."],["What order are results shown in?","Within each extraction type, results keep their original occurrence order."],["What happens when I load another file?","Because the current source, results, and extraction types may reset, the tool asks for confirmation before replacing the file."],["Can I save the results?","Yes. You can copy extracted results or download them as a UTF-8 TXT file."]]},
  ja:{back:"テキストツール",title:"テキスト抽出ツール",desc:"長い文章から数字、韓国語・英語、メール、URL、電話番号、ハッシュタグを種類別に抽出します。",local:"原文と抽出結果はブラウザ内だけで処理し、サーバーへ送信・保存しません。",next:"次の作業",related:"関連ツール",available:"利用可能",coming:"準備中",how:"使い方",guide:"テキスト抽出を正確に使う方法",guideDesc:"原文を変更せず、必要な文字列パターンだけを種類別に分けて確認する基準です。",caution:"注意事項",faq:"よくある質問",steps:["テキストを入力・貼り付けるか、TXT・MD・CSVファイルを読み込みます。","数字・韓国語・英語・メール・URL・電話番号・ハッシュタグから必要な種類を選択します。","抽出を実行し、種類別の結果と件数を確認します。","結果をコピーするかTXTで保存します。"],points:[["メール","連絡先アドレスを分離","メール・お知らせ・CSV・ログなどの長い文書からメール形式の文字列だけを集められます。"],["URL","リンク一覧を整理","http・https・wwwで始まるURLを探し、投稿や文書からリンクだけを分離できます。"],["電話番号","連絡先文字列を検索","韓国内番号と実用的な国際番号パターンを探し、連絡先文書から電話番号を確認できます。"],["数字","数値トークンを確認","整数・小数・桁区切り・パーセント形式の数値トークンを注文・価格・ログから探せます。"],["韓国語・英語","文字種を分離","HangulとLatin文字列をそれぞれ抽出し、混在文書から必要な文字を確認できます。"],["ハッシュタグ","SNSタグを収集","Unicode文字・数字・アンダースコアを含むハッシュタグを抽出し、日本語タグも分離できます。"]],cautions:["メール・URL・電話番号は実用的な文字列パターンを抽出するもので、実在確認や接続確認は行いません。","各種類は独立して抽出するため、同じ原文の一部が複数種類の結果に含まれる場合があります。","各種類の結果は原文に登場した順序を保持します。","サービス上限は入力300,000文字、種類ごと10,000件、全体30,000件です。"],faqs:[["入力文はサーバーへ送信されますか？","いいえ。原文と抽出結果は現在のブラウザ内だけで処理します。"],["メールやURLを完全に検証しますか？","いいえ。実用的な文字列抽出用で、最終的な有効性判定ツールではありません。"],["日本語のハッシュタグに対応していますか？","はい。Unicode文字ベースのハッシュタグを抽出するため日本語タグも対象です。"],["結果の順番はどうなりますか？","各抽出タイプ内では原文に登場した順序を保持します。"],["別のファイルを読み込むとどうなりますか？","現在の原文・結果・抽出タイプが初期化される可能性があるため、置き換え確認後に読み込みます。"],["結果をファイル保存できますか？","はい。抽出結果をコピーするかUTF-8 TXTとして保存できます。"]]},
} as const;

export function TextExtractorPage({locale}:{locale:Locale}){
  const t=copy[locale];
  const url=`https://toolbox.fixlgs.com/${locale}/text-extractor`;
  const related=[
    {n:"040",slug:"delimiter-list-converter",name:locale==="ko"?"구분자·목록 변환기":locale==="ja"?"区切り文字・リスト変換ツール":"Delimiter & List Converter",active:true},
    {n:"042",slug:"text-find-replace",name:locale==="ko"?"텍스트 찾기·바꾸기":locale==="ja"?"テキスト検索・置換":"Text Find & Replace",active:true},
    {n:"043",slug:"text-compare",name:locale==="ko"?"두 텍스트 비교기":locale==="ja"?"2つのテキスト比較ツール":"Text Comparison Tool",active:false},
  ];
  const jsonLd={"@context":"https://schema.org","@graph":[{"@type":"WebApplication",name:t.title,applicationCategory:"UtilitiesApplication",operatingSystem:"Any",url,description:t.desc,offers:{"@type":"Offer",price:"0",priceCurrency:"USD"}},{"@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:"TOOLBOX",item:`https://toolbox.fixlgs.com/${locale}`},{"@type":"ListItem",position:2,name:t.back,item:`https://toolbox.fixlgs.com/${locale}/category/text`},{"@type":"ListItem",position:3,name:t.title,item:url}]},{"@type":"FAQPage",mainEntity:t.faqs.map(([q,a])=>({"@type":"Question",name:q,acceptedAnswer:{"@type":"Answer",text:a}}))}]};
  return <ToolboxSubpageShell locale={locale} appName={t.title}>
    <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(jsonLd)}}/>
    <section className="toolbox-tool-detail-hero toolbox-tool-detail-hero--single-line-description"><Link className="toolbox-subpage-back" href={`/${locale}/category/text`}>← {t.back}</Link><p className="toolbox-subpage-eyebrow">041 · TEXT</p><div className="toolbox-tool-detail-heading"><h1><span className="toolbox-tool-title-line">{t.title}</span></h1><p>{t.desc}</p></div><div className="toolbox-tool-detail-badge"><strong>LOCAL</strong><span>{t.local}</span></div></section>
    <section className="toolbox-tool-detail-body"><div><TextExtractorTool locale={locale}/><section className="toolbox-next-work"><div className="toolbox-next-work-head"><p>NEXT WORK</p><h2>{t.next}</h2></div><div className="toolbox-next-work-grid"><Link href={`/${locale}/${related[1].slug}`} className="toolbox-next-work-card"><span>042</span><h3>{related[1].name}</h3><div className="toolbox-next-work-card-foot"><span>{t.available}</span><strong>→</strong></div></Link></div></section><section className="toolbox-next-work"><div className="toolbox-next-work-head"><p>RELATED TOOLS</p><h2>{t.related}</h2></div><div className="toolbox-next-work-grid"><Link href={`/${locale}/${related[0].slug}`} className="toolbox-next-work-card"><span>{related[0].n}</span><h3>{related[0].name}</h3><div className="toolbox-next-work-card-foot"><span>{t.available}</span><strong>→</strong></div></Link><div className="toolbox-next-work-card is-disabled"><span>{related[2].n}</span><h3>{related[2].name}</h3><div className="toolbox-next-work-card-foot"><span>{t.coming}</span><strong>·</strong></div></div></div></section></div></section>
    <section className="toolbox-tool-guide toolbox-tool-guide--five"><div className="toolbox-tool-guide-head"><p>HOW TO USE</p><h2>{t.how}</h2></div><ol>{t.steps.map((step,index)=><li key={step}><span>{String(index+1).padStart(2,"0")}</span><p>{step}</p></li>)}</ol></section>
    <section className="toolbox-tool-format-guide toolbox-tool-expert-post toolbox-tool-expert-post--wide-head"><div className="toolbox-tool-format-guide-head"><p>EXTRACTION GUIDE</p><h2>{t.guide}</h2><span>{t.guideDesc}</span></div><div className="toolbox-tool-format-body"><div className="toolbox-tool-format-grid">{t.points.map(([n,h,p])=><article key={n}><strong>{n}</strong><h3>{h}</h3><p>{p}</p></article>)}</div></div></section>
    <section className="toolbox-tool-info-band toolbox-tool-info-band--section-start toolbox-tool-info-band--bottom-gap toolbox-tool-info-band--left-head toolbox-tool-info-band--format-head toolbox-tool-info-band--full-divider"><div className="toolbox-tool-info-band-head"><p>IMPORTANT NOTES</p><h2>{t.caution}</h2></div><ul className="toolbox-tool-info-band-list">{t.cautions.map((item)=><li key={item}>{item}</li>)}</ul></section>
    <section className="toolbox-tool-faq"><div className="toolbox-tool-guide-head"><p>FAQ</p><h2>{t.faq}</h2></div><ToolboxFaqList items={t.faqs.map(([q,a]):readonly[string,string]=>[q,a])} initialCount={5} moreLabel={locale==="ko"?"FAQ 더보기":locale==="ja"?"FAQをもっと見る":"Show more FAQs"} collapseLabel={locale==="ko"?"FAQ 접기":locale==="ja"?"FAQを閉じる":"Collapse FAQs"} className="toolbox-tool-faq-list"/></section>
  </ToolboxSubpageShell>;
}
