"use client";

import { useMemo, useRef, useState } from "react";
import type { DragEvent } from "react";
import type { Locale } from "@/lib/site";
import { replace042, TOOL042_SERVICE_LIMITS, validateTool042, type Tool042Rule, type Tool042Result } from "@/lib/tool-042-find-replace";
import styles from "./text-find-replace-tool.module.css";

const ACCEPTED_EXTENSIONS=["txt","md","csv"] as const;
type LoadedFile=Readonly<{name:string;size:number}>;
const EMPTY_RULE:Tool042Rule={find:"",replacement:""};

const copy={
ko:{local:"입력하거나 불러온 원문과 찾기·바꾸기 결과는 서버로 전송하거나 저장하지 않고 현재 브라우저에서만 처리합니다.",inputTitle:"텍스트를 입력·붙여넣거나 파일을 넣으세요",dropHint:"TXT · MD · CSV 파일을 이 작업영역에 끌어다 놓아도 됩니다.",chooseFile:"텍스트 파일 선택",replaceFile:"새 파일 불러오기",loadedFile:"불러온 파일",supported:".txt · .md · .csv",input:"원문 텍스트",inputHelp:"찾기·바꾸기를 적용할 원문을 입력하세요.",placeholder:"예) 고양이와 고양이가 있습니다.",privacy:"로컬 처리 · 서버 업로드 없음",rules:"찾기·바꾸기 규칙",rulesHelp:"여러 규칙은 원본 텍스트를 기준으로 동시에 계산합니다.",find:"찾기",replacement:"바꾸기",add:"규칙 추가",remove:"삭제",caseSensitive:"대소문자 구분",run:"찾기·바꾸기",sample:"예시 넣기",reset:"전체 지우기",result:"변경 결과",resultHelp:"원문은 유지되고 결과만 별도로 생성됩니다.",total:"총 변경 횟수",ruleCount:"규칙 수",chars:"결과 글자",copy:"결과 복사",save:"TXT 다운로드",copied:"결과를 복사했습니다.",saved:"TXT 파일을 저장했습니다.",copyFailed:"복사하지 못했습니다. 결과를 직접 선택해 복사해 주세요.",emptyInput:"원문 텍스트를 입력해 주세요.",emptyFind:"찾기 값은 비워둘 수 없습니다.",duplicate:"같은 찾기 값은 한 번만 사용할 수 있습니다.",inputTooLong:"입력이 서비스 상한을 초과했습니다.",ruleLimit:"규칙 수가 서비스 상한을 초과했습니다.",findLimit:"찾기 값이 서비스 상한을 초과했습니다.",replacementLimit:"바꾸기 값이 서비스 상한을 초과했습니다.",resultLimit:"결과가 서비스 상한을 초과해 실행할 수 없습니다.",invalidFile:"TXT, MD, CSV 텍스트 파일만 사용할 수 있습니다.",readFailed:"파일 내용을 읽지 못했습니다. 다른 파일로 다시 시도해 주세요.",replaceWarning:"새 파일을 불러오면 현재 원문, 규칙, 결과가 초기화됩니다. 계속하시겠습니까?",cancelReplace:"취소",confirmReplace:"확인",limit:`서비스 상한: 원문 ${TOOL042_SERVICE_LIMITS.maxInputCharacters.toLocaleString("ko-KR")}자 · 규칙 ${TOOL042_SERVICE_LIMITS.maxRules}개 · 찾기 ${TOOL042_SERVICE_LIMITS.maxFindLength.toLocaleString("ko-KR")}자 · 바꾸기 ${TOOL042_SERVICE_LIMITS.maxReplacementLength.toLocaleString("ko-KR")}자 · 결과 ${TOOL042_SERVICE_LIMITS.maxResultCharacters.toLocaleString("ko-KR")}자`,sampleText:"Hello hello HELLO\n고양이와 고양이가 있습니다."},
en:{local:"Text you type or load and find-and-replace results stay in this browser and are not sent to or stored on a server.",inputTitle:"Type, paste, or drop a text file",dropHint:"You can also drop a TXT, MD, or CSV file anywhere in this workspace.",chooseFile:"Choose text file",replaceFile:"Load another file",loadedFile:"Loaded file",supported:".txt · .md · .csv",input:"Source text",inputHelp:"Enter the source text to find and replace.",placeholder:"Example: The cat and another cat.",privacy:"Local processing · No server upload",rules:"Find & replace rules",rulesHelp:"Multiple rules are resolved simultaneously against the original text.",find:"Find",replacement:"Replace with",add:"Add rule",remove:"Remove",caseSensitive:"Case sensitive",run:"Find & replace",sample:"Insert sample",reset:"Clear all",result:"Changed result",resultHelp:"The source remains unchanged and the result is generated separately.",total:"Total replacements",ruleCount:"Rules",chars:"Result chars",copy:"Copy result",save:"Download TXT",copied:"Result copied.",saved:"TXT file saved.",copyFailed:"Could not write to the clipboard. Select and copy the result manually.",emptyInput:"Enter source text.",emptyFind:"Find text cannot be empty.",duplicate:"Each find text can only be used once.",inputTooLong:"The input exceeds the service limit.",ruleLimit:"The rule count exceeds the service limit.",findLimit:"A find value exceeds the service limit.",replacementLimit:"A replacement value exceeds the service limit.",resultLimit:"The result would exceed the service limit.",invalidFile:"Only TXT, MD, and CSV text files are supported.",readFailed:"Could not read this file. Please try another file.",replaceWarning:"Loading a new file will reset the current source, rules, and result. Continue?",cancelReplace:"Cancel",confirmReplace:"Continue",limit:`Service limit: ${TOOL042_SERVICE_LIMITS.maxInputCharacters.toLocaleString("en-US")} input characters · ${TOOL042_SERVICE_LIMITS.maxRules} rules · ${TOOL042_SERVICE_LIMITS.maxFindLength.toLocaleString("en-US")} find characters · ${TOOL042_SERVICE_LIMITS.maxReplacementLength.toLocaleString("en-US")} replacement characters · ${TOOL042_SERVICE_LIMITS.maxResultCharacters.toLocaleString("en-US")} result characters`,sampleText:"Hello hello HELLO\nThe cat and another cat."},
ja:{local:"入力・読込した原文と検索・置換結果はサーバーへ送信・保存せず、このブラウザ内だけで処理します。",inputTitle:"テキストを入力・貼り付け・ファイル読込",dropHint:"TXT・MD・CSVファイルをこの作業エリアへドラッグ＆ドロップできます。",chooseFile:"テキストファイルを選択",replaceFile:"別のファイルを読み込む",loadedFile:"読み込んだファイル",supported:".txt · .md · .csv",input:"原文テキスト",inputHelp:"検索・置換を適用する原文を入力します。",placeholder:"例: 猫ともう一匹の猫。",privacy:"ローカル処理 · サーバー送信なし",rules:"検索・置換ルール",rulesHelp:"複数ルールは原文を基準に同時に計算します。",find:"検索",replacement:"置換後",add:"ルール追加",remove:"削除",caseSensitive:"大文字・小文字を区別",run:"検索・置換",sample:"サンプルを入力",reset:"すべてクリア",result:"変更結果",resultHelp:"原文は保持し、結果だけを別に生成します。",total:"総置換回数",ruleCount:"ルール数",chars:"結果文字",copy:"結果をコピー",save:"TXTをダウンロード",copied:"結果をコピーしました。",saved:"TXTファイルを保存しました。",copyFailed:"クリップボードへコピーできませんでした。結果を選択して手動でコピーしてください。",emptyInput:"原文を入力してください。",emptyFind:"検索文字列は空にできません。",duplicate:"同じ検索文字列は1回だけ使用できます。",inputTooLong:"入力がサービス上限を超えています。",ruleLimit:"ルール数がサービス上限を超えています。",findLimit:"検索文字列がサービス上限を超えています。",replacementLimit:"置換文字列がサービス上限を超えています。",resultLimit:"結果がサービス上限を超えるため実行できません。",invalidFile:"TXT・MD・CSVのテキストファイルのみ使用できます。",readFailed:"ファイルを読み込めませんでした。別のファイルで再試行してください。",replaceWarning:"新しいファイルを読み込むと、現在の原文・ルール・結果が初期化されます。続けますか？",cancelReplace:"キャンセル",confirmReplace:"確認",limit:`サービス上限: 原文${TOOL042_SERVICE_LIMITS.maxInputCharacters.toLocaleString("ja-JP")}文字 · ルール${TOOL042_SERVICE_LIMITS.maxRules}件 · 検索${TOOL042_SERVICE_LIMITS.maxFindLength.toLocaleString("ja-JP")}文字 · 置換${TOOL042_SERVICE_LIMITS.maxReplacementLength.toLocaleString("ja-JP")}文字 · 結果${TOOL042_SERVICE_LIMITS.maxResultCharacters.toLocaleString("ja-JP")}文字`,sampleText:"Hello hello HELLO\n猫ともう一匹の猫。"}
} as const;

function isSupportedTextFile(file:File){const extension=file.name.split(".").pop()?.toLowerCase()??"";return ACCEPTED_EXTENSIONS.includes(extension as (typeof ACCEPTED_EXTENSIONS)[number]);}
function formatBytes(size:number,locale:Locale){if(size<1024)return `${size.toLocaleString()} B`;const localeId=locale==="ko"?"ko-KR":locale==="ja"?"ja-JP":"en-US";return `${(size/1024).toLocaleString(localeId,{maximumFractionDigits:1})} KB`;}

export function TextFindReplaceTool({locale}:{locale:Locale}){
 const t=copy[locale],localeId=locale==="ko"?"ko-KR":locale==="ja"?"ja-JP":"en-US";
 const [sourceText,setSourceText]=useState(""),[rules,setRules]=useState<Tool042Rule[]>([EMPTY_RULE]),[caseSensitive,setCaseSensitive]=useState(true),[result,setResult]=useState<Tool042Result|null>(null),[error,setError]=useState(""),[status,setStatus]=useState(""),[loadedFile,setLoadedFile]=useState<LoadedFile|null>(null),[hasStarted,setHasStarted]=useState(false),[dragActive,setDragActive]=useState(false),[pendingFile,setPendingFile]=useState<File|null>(null); const fileInput=useRef<HTMLInputElement>(null);
 const validationErrors=useMemo(()=>validateTool042(sourceText,rules,caseSensitive),[sourceText,rules,caseSensitive]);
 const hasCurrentWork=Boolean(hasStarted||sourceText||loadedFile||result||rules.length!==1||rules[0].find||rules[0].replacement||!caseSensitive);
 const invalidate=()=>{setResult(null);setStatus("");setError("");};
 const updateSource=(v:string)=>{setHasStarted(true);setSourceText(v);invalidate();};
 const updateRule=(i:number,key:keyof Tool042Rule,value:string)=>{setRules(cur=>cur.map((r,n)=>n===i?{...r,[key]:value}:r));invalidate();};
 const addRule=()=>{if(rules.length<TOOL042_SERVICE_LIMITS.maxRules){setRules(cur=>[...cur,EMPTY_RULE]);invalidate();}};
 const removeRule=(i:number)=>{setRules(cur=>cur.length===1?cur:cur.filter((_,n)=>n!==i));invalidate();};
 const errorText=(code:string)=>code==="EMPTY_FIND"?t.emptyFind:code==="DUPLICATE_FIND"?t.duplicate:code==="INPUT_LIMIT"?t.inputTooLong:code==="RULE_LIMIT"?t.ruleLimit:code==="FIND_LIMIT"?t.findLimit:code==="REPLACEMENT_LIMIT"?t.replacementLimit:t.resultLimit;
 const run=()=>{setStatus("");setError("");if(!sourceText){setError(t.emptyInput);setResult(null);return;}if(validationErrors.length){setError(errorText(validationErrors[0].code));setResult(null);return;}try{setResult(replace042(sourceText,rules,caseSensitive));}catch(e){setResult(null);setError(e instanceof RangeError&&String(e.message)==="RESULT_LIMIT"?t.resultLimit:t.resultLimit);}};
 const reset=()=>{setSourceText("");setRules([EMPTY_RULE]);setCaseSensitive(true);setResult(null);setError("");setStatus("");setLoadedFile(null);setHasStarted(false);setDragActive(false);setPendingFile(null);if(fileInput.current)fileInput.current.value="";};
 const copyResult=async()=>{if(!result)return;try{await navigator.clipboard.writeText(result.output);setStatus(t.copied);setError("");}catch{setStatus("");setError(t.copyFailed);}};
 const downloadResult=()=>{if(!result)return;const blob=new Blob([result.output],{type:"text/plain;charset=utf-8"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download="find-replace-result.txt";document.body.appendChild(a);a.click();a.remove();window.setTimeout(()=>URL.revokeObjectURL(url),0);setStatus(t.saved);setError("");};
 const loadFile=async(file:File)=>{setDragActive(false);setStatus("");try{const content=await file.text();setSourceText(content);setRules([EMPTY_RULE]);setCaseSensitive(true);setResult(null);setError("");setLoadedFile({name:file.name,size:file.size});setHasStarted(true);}catch{setError(t.readFailed);}finally{if(fileInput.current)fileInput.current.value="";}};
 const requestFileLoad=(file:File)=>{setDragActive(false);setStatus("");if(!isSupportedTextFile(file)){setError(t.invalidFile);if(fileInput.current)fileInput.current.value="";return;}if(hasCurrentWork){setPendingFile(file);return;}void loadFile(file);};
 const cancelFileReplace=()=>{setPendingFile(null);if(fileInput.current)fileInput.current.value="";}; const confirmFileReplace=()=>{const file=pendingFile;setPendingFile(null);if(file)void loadFile(file);};
 const onDragEnter=(e:DragEvent<HTMLElement>)=>{if(!Array.from(e.dataTransfer.types).includes("Files"))return;e.preventDefault();setDragActive(true);}; const onDragOver=(e:DragEvent<HTMLElement>)=>{if(!Array.from(e.dataTransfer.types).includes("Files"))return;e.preventDefault();e.dataTransfer.dropEffect="copy";setDragActive(true);}; const onDragLeave=(e:DragEvent<HTMLElement>)=>{const next=e.relatedTarget as Node|null;if(!next||!e.currentTarget.contains(next))setDragActive(false);}; const onDrop=(e:DragEvent<HTMLElement>)=>{if(!Array.from(e.dataTransfer.types).includes("Files"))return;e.preventDefault();setDragActive(false);const file=e.dataTransfer.files?.[0];if(file)requestFileLoad(file);};
 return <div className={styles.root} data-testid="tool042-root">
  <div className={styles.localNotice} data-testid="tool042-local-notice"><strong>LOCAL</strong><span>{t.local}</span></div>
  <input ref={fileInput} className={styles.hiddenInput} type="file" accept=".txt,.md,.csv,text/plain,text/markdown,text/csv" data-testid="tool042-file-input" onChange={e=>{const f=e.currentTarget.files?.[0];if(f)requestFileLoad(f)}}/>
  <section className={`${styles.activeWorkspace} ${dragActive?styles.workspaceDragging:""}`} data-testid="tool042-workspace" data-drag-active={dragActive?"true":"false"} onDragEnter={onDragEnter} onDragOver={onDragOver} onDragLeave={onDragLeave} onDrop={onDrop}>
   <div className={styles.editorCard} data-testid="tool042-input-zone">
    {loadedFile&&<div className={styles.fileBar} data-testid="tool042-file-info"><div><span>{t.loadedFile}</span><strong>{loadedFile.name}</strong><small>{formatBytes(loadedFile.size,locale)} · {t.supported}</small></div><button type="button" className={styles.button} onClick={()=>fileInput.current?.click()}>{t.replaceFile}</button></div>}
    <div className={styles.textareaShell}>{!hasStarted&&!loadedFile&&<div className={styles.startDropzone} data-testid="tool042-start-dropzone"><span className={styles.plusIcon} aria-hidden="true">+</span><h2>{t.inputTitle}</h2><p>{t.dropHint}</p><button type="button" className={styles.fileButton} onClick={()=>fileInput.current?.click()} data-testid="tool042-file-button">{t.chooseFile}</button></div>}<label className={styles.visibleLabel} htmlFor="tool042-source">{t.input}</label><textarea id="tool042-source" aria-label={t.input} className={`${styles.textarea} ${hasStarted||loadedFile?styles.textareaLoaded:styles.textareaInitial}`} value={sourceText} maxLength={TOOL042_SERVICE_LIMITS.maxInputCharacters+1} placeholder={t.placeholder} onChange={e=>updateSource(e.currentTarget.value)} data-testid="tool042-input"/><div className={styles.editorHead}><span>{t.inputHelp}</span><em>{sourceText.length.toLocaleString(localeId)} / {TOOL042_SERVICE_LIMITS.maxInputCharacters.toLocaleString(localeId)}</em></div></div>
    <div className={styles.editorFoot}><p className={styles.privacy}>{t.privacy} · {t.limit}</p><div className={styles.textActions}><button type="button" className={styles.button} onClick={()=>{setLoadedFile(null);setRules([{find:"hello",replacement:"FIX"},{find:"cat",replacement:"DOG"}]);setCaseSensitive(false);updateSource(t.sampleText);}} data-testid="tool042-sample">{t.sample}</button><button type="button" className={styles.button} onClick={reset} disabled={!hasCurrentWork} data-testid="tool042-reset">{t.reset}</button></div></div>
   </div>
   <details className={styles.optionsCard} open data-testid="tool042-rules"><summary className={styles.optionsSummary}><span>{t.rules}</span><em>{rules.length.toLocaleString(localeId)} / {TOOL042_SERVICE_LIMITS.maxRules.toLocaleString(localeId)} · {t.rulesHelp}</em></summary><div className={styles.optionsBody}><div className={styles.ruleList}>{rules.map((r,i)=>{const rowErrors=validationErrors.filter(e=>e.ruleIndex===i);return <div className={styles.ruleCard} key={i}><span className={styles.ruleIndex}>RULE {String(i+1).padStart(2,"0")}</span><div className={styles.ruleField}><input aria-label={`${t.find} ${i+1}`} className={styles.ruleInput} value={r.find} maxLength={TOOL042_SERVICE_LIMITS.maxFindLength+1} onChange={e=>updateRule(i,"find",e.currentTarget.value)} placeholder={t.find} data-testid={`tool042-find-${i}`}/>{rowErrors.map((e,j)=><span key={j} className={styles.ruleError} data-testid={`tool042-rule-error-${i}`}>{errorText(e.code)}</span>)}<span className={styles.ruleMeta}>{r.find.length.toLocaleString(localeId)} / {TOOL042_SERVICE_LIMITS.maxFindLength.toLocaleString(localeId)}</span></div><div className={styles.ruleField}><input aria-label={`${t.replacement} ${i+1}`} className={styles.ruleInput} value={r.replacement} maxLength={TOOL042_SERVICE_LIMITS.maxReplacementLength+1} onChange={e=>updateRule(i,"replacement",e.currentTarget.value)} placeholder={t.replacement} data-testid={`tool042-replace-${i}`}/><span className={styles.ruleMeta}>{r.replacement.length.toLocaleString(localeId)} / {TOOL042_SERVICE_LIMITS.maxReplacementLength.toLocaleString(localeId)}</span></div><button type="button" className={styles.button} disabled={rules.length===1} onClick={()=>removeRule(i)} data-testid={`tool042-remove-${i}`}>{t.remove}</button></div>})}</div><div className={styles.ruleFooter}><button type="button" className={styles.button} onClick={addRule} disabled={rules.length>=TOOL042_SERVICE_LIMITS.maxRules} data-testid="tool042-add-rule">{t.add}</button><label className={styles.caseRow}><input type="checkbox" checked={caseSensitive} onChange={e=>{setCaseSensitive(e.currentTarget.checked);invalidate();}} data-testid="tool042-case-sensitive"/>{t.caseSensitive}</label></div></div></details>
   <div className={styles.actionRow}><button type="button" className={styles.primaryButton} onClick={run} disabled={!sourceText||!rules.some(r=>r.find)} data-testid="tool042-run">{t.run}</button></div>
   <div className={styles.editorCard} data-testid="tool042-result-card"><div className={styles.resultHead}><span className={styles.visibleLabel}>{t.result}</span><span>{result?result.output.length.toLocaleString(localeId):0} {t.chars}</span></div><textarea aria-label={t.result} readOnly className={`${styles.textarea} ${styles.resultTextarea}`} value={result?.output??""} data-testid="tool042-result"/><p className={styles.notice}>{t.resultHelp}</p></div>
   <section className={styles.stats} aria-label={t.result} data-testid="tool042-summary"><div className={styles.secondaryGrid}><article className={styles.secondaryCard}><span>{t.total}</span><strong data-testid="tool042-total-count">{(result?.totalCount??0).toLocaleString(localeId)}</strong></article><article className={styles.secondaryCard}><span>{t.ruleCount}</span><strong>{rules.length.toLocaleString(localeId)}</strong></article><article className={styles.secondaryCard}><span>{t.chars}</span><strong>{(result?.output.length??0).toLocaleString(localeId)}</strong></article></div>{result&&<div className={styles.resultsGrid} data-testid="tool042-rule-counts">{result.ruleCounts.map((item,i)=><article className={styles.resultCard} key={i}><div className={styles.resultHead}><strong>{t.find} {i+1}</strong><span data-testid={`tool042-count-${i}`}>{item.count.toLocaleString(localeId)}</span></div><div className={styles.resultList}><div className={styles.resultItem}><span className={styles.index}>{t.find}</span><span className={styles.value}>{item.find}</span></div><div className={styles.resultItem}><span className={styles.index}>{t.replacement}</span><span className={styles.value}>{item.replacement}</span></div></div></article>)}</div>}</section>
   <div className={styles.actionRow}><button type="button" className={styles.button} onClick={()=>void copyResult()} disabled={!result} data-testid="tool042-copy">{t.copy}</button><button type="button" className={styles.primaryButton} onClick={downloadResult} disabled={!result} data-testid="tool042-download">{t.save}</button></div>
   {status&&<p className={styles.copyStatus} role="status" aria-live="polite" data-testid="tool042-status">{status}</p>}{error&&<p className={styles.error} role="alert" data-testid="tool042-error">{error}</p>}
  </section>
  {pendingFile&&<div className={styles.dialogBackdrop} onMouseDown={e=>{if(e.currentTarget===e.target)cancelFileReplace();}}><section className={styles.confirmDialog} role="dialog" aria-modal="true" aria-labelledby="tool042-replace-title" data-testid="tool042-replace-dialog"><h2 id="tool042-replace-title">{t.replaceFile}</h2><p>{t.replaceWarning}</p><div className={styles.dialogActions}><button type="button" className={styles.button} onClick={cancelFileReplace} data-testid="tool042-replace-cancel">{t.cancelReplace}</button><button type="button" className={styles.primaryButton} onClick={confirmFileReplace} data-testid="tool042-replace-confirm">{t.confirmReplace}</button></div></section></div>}
 </div>;
}
