import Link from "next/link";
import type { Locale } from "@/lib/site";
import { ToolboxFaqList } from "@/components/toolbox-faq-list";
import { ToolboxSubpageShell } from "@/components/toolbox-subpage-shell";
import { TextDiffCompareTool } from "@/components/text-diff-compare-tool";

const copy={
ko:{back:"텍스트 도구",title:"두 텍스트 비교기",desc:"두 버전의 텍스트를 비교해 추가·삭제·변경을 구분하고 줄 단위와 단어 단위 차이를 확인하세요.",next:"다음 작업",related:"관련 도구",how:"사용 방법",faq:"자주 묻는 질문",steps:["텍스트 A와 텍스트 B에 비교할 두 버전을 입력하거나 붙여넣습니다.","비교하기를 누르면 줄 단위로 추가·삭제·변경·동일 구간을 분류합니다.","단어 단위 탭에서 변경 블록 안의 실제 단어·구두점 차이를 확인합니다.","요약 통계와 줄 번호를 확인하고 비교 결과 복사로 plain-text 보고서를 복사합니다.","전체 지우기로 A/B 입력, 결과, 모드와 복사 상태를 모두 초기화합니다."],notes:["원문 A/B는 그대로 보존하며 Unicode normalization이나 공백 정규화를 자동 적용하지 않습니다.","빈 줄과 줄 끝 공백도 기본적으로 실제 차이로 취급합니다.","변경은 인접한 삭제+추가 블록을 같은 위치의 대체 관계로 묶어 표시합니다.","단어 비교는 변경 블록 내부에서만 계산하며 일본어·한글·영문·emoji 원문 재구성을 보존합니다.","브라우저 로컬 처리이며 입력 원문과 diff 보고서를 서버로 전송하거나 저장하지 않습니다."],faqs:[["줄 단위와 단어 단위의 차이는 무엇인가요?","줄 단위는 문서 구조의 추가·삭제·변경을 빠르게 보여주고, 단어 단위는 변경 블록 안에서 실제로 달라진 단어와 구두점을 더 자세히 보여줍니다."],["변경은 어떻게 판정하나요?","같은 위치에서 인접한 삭제 블록과 추가 블록이 나타나면 변경 블록으로 묶고 내부 원시 정보는 삭제와 추가 상태로 보존합니다."],["공백도 차이로 보나요?","네. 기본 비교에서는 공백·빈 줄·줄 끝 공백을 임의로 정규화하지 않아 실제 차이로 취급합니다."],["비교 결과를 복사할 수 있나요?","네. 색상이 없어도 이해할 수 있는 plain-text diff report를 만들어 클립보드로 복사합니다."],["입력한 텍스트가 서버에 저장되나요?","아니요. 비교 계산과 결과 생성은 현재 브라우저에서만 처리합니다."]]},
en:{back:"Text Tools",title:"Text Diff & Compare",desc:"Compare two text versions, classify additions, removals and changes, and inspect differences by line or word.",next:"Next work",related:"Related tools",how:"How to use",faq:"Frequently asked questions",steps:["Paste the two versions into Text A and Text B.","Choose Compare to classify line-level additions, removals, changes, and unchanged sections.","Switch to Word detail to inspect exact word and punctuation differences inside changed blocks.","Review summary counts and line references, then copy the plain-text diff report.","Use Clear all to reset both inputs, results, mode, and copy status."],notes:["Text A and B are preserved exactly; Unicode normalization and whitespace cleanup are not applied automatically.","Blank lines and trailing whitespace are treated as real differences by default.","Adjacent removal and addition blocks at the same position are grouped as a changed block.","Word detail is calculated only inside changed blocks and preserves Korean, English, Japanese, and emoji reconstruction.","Everything is processed locally in the browser; source text and reports are not sent to or stored on a server."],faqs:[["What is the difference between line and word modes?","Line mode shows document-level structure. Word detail shows the exact words and punctuation that changed inside replacement blocks."],["How is a change detected?","An adjacent removal and addition at the same diff position is grouped as a changed block while preserving the underlying remove/add data."],["Does whitespace count as a difference?","Yes. The default comparison does not normalize whitespace, blank lines, or trailing spaces."],["Can I copy the comparison result?","Yes. The tool generates a plain-text diff report that remains understandable without colors."],["Is my text stored on a server?","No. Comparison and report generation happen only in the current browser."]]},
ja:{back:"テキストツール",title:"2つのテキスト比較ツール",desc:"2つの文章を比較し、追加・削除・変更を分類して行単位と単語単位の差分を確認できます。",next:"次の作業",related:"関連ツール",how:"使い方",faq:"よくある質問",steps:["テキストAとテキストBに比較する2つの版を入力・貼り付けします。","比較を実行すると行単位で追加・削除・変更・同一を分類します。","単語詳細タブで変更ブロック内の実際の単語・句読点差分を確認します。","集計と行番号を確認し、比較結果をplain-textレポートとしてコピーします。","すべてクリアでA/B入力、結果、モード、コピー状態を初期化します。"],notes:["原文A/Bはそのまま保持し、Unicode正規化や空白の自動整理は行いません。","空行や行末スペースも既定では実際の差分として扱います。","同じ位置の隣接する削除+追加ブロックを変更としてまとめます。","単語差分は変更ブロック内だけで計算し、日本語・韓国語・英語・emojiの再構成を保ちます。","ブラウザ内ローカル処理で、原文や差分レポートをサーバーへ送信・保存しません。"],faqs:[["行単位と単語単位の違いは？","行単位は文書構造の差分を素早く表示し、単語詳細は変更ブロック内で実際に変わった単語や句読点を表示します。"],["変更はどのように判定しますか？","同じ差分位置で削除と追加が隣接した場合に変更ブロックとしてまとめ、内部の削除・追加情報は保持します。"],["空白も差分になりますか？","はい。既定では空白・空行・行末スペースを正規化せず実際の差分として扱います。"],["比較結果をコピーできますか？","はい。色がなくても理解できるplain-text差分レポートをクリップボードへコピーできます。"],["入力した文章はサーバーに保存されますか？","いいえ。比較とレポート生成は現在のブラウザ内だけで行います。"]]}
} as const;

export function TextDiffComparePage({locale}:{locale:Locale}){
 const t=copy[locale]; const faq=t.faqs;
 const expertTitle=locale==="ko"?"두 텍스트의 차이를 정확히 읽는 실전 기준":locale==="ja"?"2つのテキスト差分を正確に読む実践基準":"Practical standards for reading text differences accurately";
 const expertLead=locale==="ko"?"줄 단위 구조와 변경 블록 내부의 단어 차이를 분리해서 보고, 공백·구두점·Unicode 원문을 그대로 보존해야 비교 결과를 정확히 해석할 수 있습니다.":locale==="ja"?"行単位の構造と変更ブロック内の単語差分を分け、空白・句読点・Unicode原文を保持して比較結果を読みます。":"Separate line-level structure from word-level edits while preserving whitespace, punctuation, and Unicode source text for reliable comparison.";
 const expert=locale==="ko"?[
  ["줄 비교는 문서 구조를 먼저 보여줍니다","추가·삭제·동일 줄을 먼저 분류하면 긴 문서에서 어느 구간이 바뀌었는지 빠르게 찾을 수 있습니다. 단어 차이는 변경 블록 안에서만 추가 계산합니다."],
  ["변경은 삭제와 추가의 관계로 표현됩니다","같은 위치에서 인접한 삭제 블록과 추가 블록을 하나의 변경으로 묶어 보여주지만 내부 원시 상태는 삭제와 추가로 보존해 결과를 재구성할 수 있게 합니다."],
  ["공백과 빈 줄도 실제 차이입니다","기본 비교는 자동 공백 정리나 Unicode normalization을 하지 않습니다. 줄 끝 공백·빈 줄·구두점이 실제 문서에서 의미가 있다면 그대로 차이로 표시됩니다."],
  ["단어 비교는 원문 재구성이 가능해야 합니다","한글·영문·일본어·emoji가 섞인 변경에서도 토큰 표시 때문에 원문 문자 순서가 깨지지 않아야 합니다. 색상 없이도 추가와 삭제 상태를 읽을 수 있어야 합니다."],
  ["요약 숫자와 실제 블록을 함께 확인합니다","추가·삭제·변경 건수는 빠른 개요용입니다. 최종 판단은 줄 번호와 실제 변경 블록을 함께 확인해야 문장 이동이나 큰 블록 교체를 오해하지 않습니다."],
  ["비교 원문과 보고서는 브라우저에만 남습니다","A/B 원문과 생성된 plain-text diff 보고서는 외부 서버로 보내지지 않습니다. 민감한 문서를 비교할 때도 현재 브라우저 메모리에서 처리됩니다."]
 ]:locale==="ja"?[
  ["行比較で文書構造を先に確認します","追加・削除・同一行を先に分類し、単語差分は変更ブロック内だけで計算します。"],
  ["変更は削除と追加の関係として扱います","同じ位置の隣接する削除・追加を変更としてまとめつつ、内部状態は保持します。"],
  ["空白や空行も実際の差分です","自動的な空白整理やUnicode正規化を行わず、行末スペースや句読点もそのまま比較します。"],
  ["単語差分でも原文再構成を保ちます","日本語・韓国語・英語・emojiが混在しても元の文字順を壊さず差分を表示します。"],
  ["集計値と実際のブロックを一緒に確認します","追加・削除・変更の数だけでなく行番号と差分ブロックを見て最終判断します。"],
  ["原文とレポートはブラウザ内で処理します","A/B原文とplain-text差分レポートは外部サーバーへ送信しません。"]
 ]:[
  ["Line comparison reveals document structure first","Classifying added, removed, and unchanged lines makes large edits easier to locate. Word detail is calculated only inside changed blocks."],
  ["A change is represented by related remove/add blocks","Adjacent removal and addition blocks at the same position are grouped as a change while the underlying raw states remain available for reconstruction."],
  ["Whitespace and blank lines are real differences","The default comparison does not normalize whitespace or Unicode automatically, so trailing spaces, blank lines, and punctuation can remain visible differences."],
  ["Word detail must preserve source reconstruction","Mixed Korean, English, Japanese, punctuation, and emoji should retain their original order so tokenization never corrupts the displayed source."],
  ["Read summary counts together with actual blocks","Added, removed, and changed totals are an overview. Use line references and the actual blocks before deciding what materially changed."],
  ["Source text and reports stay in the browser","Both source versions and the generated plain-text diff report are processed in browser memory and are not sent to an external server."]
 ] as const;
 return <ToolboxSubpageShell locale={locale} appName={t.title}>
  <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify({"@context":"https://schema.org","@graph":[{"@type":"WebApplication",name:t.title,applicationCategory:"UtilitiesApplication",operatingSystem:"Any",url:`https://toolbox.fixlgs.com/${locale}/text-diff-compare`,description:t.desc,offers:{"@type":"Offer",price:"0",priceCurrency:"USD"}},{"@type":"FAQPage",mainEntity:faq.map(([q,a])=>({"@type":"Question",name:q,acceptedAnswer:{"@type":"Answer",text:a}}))}]})}}/>
  <section className="toolbox-tool-detail-hero toolbox-tool-detail-hero--single-line-description">
   <Link className="toolbox-subpage-back" href={`/${locale}/category/text`}>← {t.back}</Link><p className="toolbox-subpage-eyebrow">043 · TEXT</p>
   <div className="toolbox-tool-detail-heading"><h1><span className="toolbox-tool-title-line">{t.title}</span></h1><p>{t.desc}</p></div>
   <div className="toolbox-tool-detail-badge"><strong>LOCAL</strong><span>Browser-local processing</span></div>
  </section>
  <section className="toolbox-tool-detail-body"><div>
   <TextDiffCompareTool locale={locale}/>
   <section className="toolbox-next-work"><div className="toolbox-next-work-head"><p>NEXT WORK</p><h2>{t.next}</h2></div><div className="toolbox-next-work-grid"><Link className="toolbox-next-work-card" href={`/${locale}/keyword-frequency-duplicate-analyzer`}><span>044</span><h3>{locale==="ko"?"키워드 빈도·중복 분석기":locale==="ja"?"キーワード頻度・重複分析ツール":"Keyword Frequency & Duplicate Analyzer"}</h3><div className="toolbox-next-work-card-foot"><span>Available</span><strong>↗</strong></div></Link></div></section>
   <section className="toolbox-next-work"><div className="toolbox-next-work-head"><p>RELATED TOOLS</p><h2>{t.related}</h2></div><div className="toolbox-next-work-grid"><Link className="toolbox-next-work-card" href={`/${locale}/text-find-replace`}><span>042</span><h3>{locale==="ko"?"텍스트 찾기·바꾸기":locale==="ja"?"テキスト検索・置換":"Text Find & Replace"}</h3><div className="toolbox-next-work-card-foot"><span>Available</span><strong>↗</strong></div></Link><Link className="toolbox-next-work-card" href={`/${locale}/character-document-counter`}><span>036</span><h3>{locale==="ko"?"글자 수·문서 통계 계산기":locale==="ja"?"文字数・文書統計カウンター":"Character & Document Statistics"}</h3><div className="toolbox-next-work-card-foot"><span>Available</span><strong>↗</strong></div></Link></div></section>
  </div></section>
  <section className="toolbox-tool-guide toolbox-tool-guide--five"><div className="toolbox-tool-guide-head"><p>HOW TO USE</p><h2>{t.how}</h2></div><ol>{t.steps.map((x,i)=><li key={x}><span>{String(i+1).padStart(2,"0")}</span><p>{x}</p></li>)}</ol></section>
  <section className="toolbox-tool-format-guide toolbox-tool-expert-post toolbox-tool-expert-post--wide-head toolbox-tool-expert-post--compact-copy"><div className="toolbox-tool-format-guide-head"><p>EXPERT POST</p><h2>{expertTitle}</h2><span>{expertLead}</span></div><div className="toolbox-tool-format-body"><div className="toolbox-tool-direction-grid toolbox-tool-practical-grid">{expert.map(([title,description])=><article key={title}><h4>{title}</h4><p>{description}</p></article>)}</div></div></section>
  <section className="toolbox-tool-info-band toolbox-tool-info-band--section-start toolbox-tool-info-band--bottom-gap toolbox-tool-info-band--left-head toolbox-tool-info-band--format-head"><div className="toolbox-tool-info-band-head"><p>IMPORTANT NOTES</p><h2>{locale==="ko"?"주의사항":locale==="ja"?"注意事項":"Important notes"}</h2></div><ul className="toolbox-tool-info-band-list">{t.notes.map(x=><li key={x}>{x}</li>)}</ul></section>
  <section className="toolbox-tool-faq"><div className="toolbox-tool-guide-head"><p>FAQ</p><h2>{t.faq}</h2></div><ToolboxFaqList items={faq.map(([q,a]):readonly[string,string]=>[q,a])} initialCount={5} moreLabel={locale==="ko"?"FAQ 더보기":locale==="ja"?"FAQをもっと見る":"Show more FAQs"} collapseLabel={locale==="ko"?"FAQ 접기":locale==="ja"?"FAQを閉じる":"Collapse FAQs"} className="toolbox-tool-faq-list"/></section>
 </ToolboxSubpageShell>;
}
