"use client";
import {useCallback,useEffect,useMemo,useRef,useState} from "react";
import type {Locale} from "@/lib/site";
import {TOOL054_LIMITS,tool054FormatClock,tool054HmsToSeconds,tool054LapDuration,tool054ResolveRepeatElapsed,tool054ValidateRepeat} from "@/lib/tool-054-timer-stopwatch";
import styles from "./timer-stopwatch-tool.module.css";

type Mode="timer"|"stopwatch"|"repeat";
type RunState="ready"|"running"|"paused"|"completed";
type Lap={totalMs:number;lapMs:number};
const presets=[60,180,300,600,900,1500,1800,2700,3600] as const;
const copy={
 ko:{local:"타이머 설정과 구간 기록은 서버로 전송하거나 저장하지 않고 현재 브라우저에서만 처리합니다.",eyebrow:"LIVE TIME WORKSPACE",title:"지금 바로 시간을 재세요",timer:"타이머",stopwatch:"스톱워치",repeat:"반복 타이머",hours:"시간",minutes:"분",seconds:"초",work:"작업(초)",rest:"휴식(초)",rounds:"라운드",start:"시작",pause:"일시정지",resume:"재개",reset:"초기화",lap:"구간 기록",fullscreen:"전체 화면",copy:"결과 복사",copied:"결과를 복사했습니다.",copyFail:"복사 권한을 사용할 수 없습니다.",ready:"준비",running:"진행 중",paused:"일시정지",completed:"완료",round:"라운드",phaseWork:"WORK · 작업",phaseRest:"REST · 휴식",phaseDone:"COMPLETE",timerEmpty:"카운트다운 시간을 1초 이상 설정해 주세요.",timerLimit:"카운트다운은 최대 24:59:59까지 설정할 수 있습니다.",repeatInvalid:`작업은 1초 이상, 휴식은 0초 이상, 라운드는 1~${TOOL054_LIMITS.maxRepeatRounds}회로 입력해 주세요.`,laps:"구간 기록",lapHelp:"Lap은 직전 기록 이후 구간, Total은 시작 이후 전체 경과시간입니다.",lapLabel:"LAP",totalLabel:"TOTAL",lapLimit:`구간 기록은 최대 ${TOOL054_LIMITS.maxLaps.toLocaleString()}개입니다.`,doneTimer:"카운트다운이 완료되었습니다.",doneRepeat:"반복 타이머가 완료되었습니다.",background:"탭 전환 후에도 화면 tick이 아니라 실제 경과시간 기준으로 다시 계산합니다.",shortcuts:"단축키: Space 시작/일시정지 · L 구간 기록 · R 초기화 · F 전체 화면"},
 en:{local:"Timer settings and lap records stay in this browser and are not sent to or stored on a server.",eyebrow:"LIVE TIME WORKSPACE",title:"Start timing right away",timer:"Timer",stopwatch:"Stopwatch",repeat:"Repeat Timer",hours:"Hours",minutes:"Minutes",seconds:"Seconds",work:"Work (sec)",rest:"Rest (sec)",rounds:"Rounds",start:"Start",pause:"Pause",resume:"Resume",reset:"Reset",lap:"Lap",fullscreen:"Fullscreen",copy:"Copy result",copied:"Result copied.",copyFail:"Clipboard permission is unavailable.",ready:"Ready",running:"Running",paused:"Paused",completed:"Completed",round:"Round",phaseWork:"WORK",phaseRest:"REST",phaseDone:"COMPLETE",timerEmpty:"Set the countdown to at least 1 second.",timerLimit:"Countdown supports up to 24:59:59.",repeatInvalid:`Use at least 1 second of work, 0 or more seconds of rest, and 1-${TOOL054_LIMITS.maxRepeatRounds} rounds.`,laps:"Lap records",lapHelp:"Lap is the segment since the previous mark; Total is elapsed time since start.",lapLabel:"LAP",totalLabel:"TOTAL",lapLimit:`Up to ${TOOL054_LIMITS.maxLaps.toLocaleString()} laps can be recorded.`,doneTimer:"Countdown completed.",doneRepeat:"Repeat timer completed.",background:"After tab changes, time is recalculated from real elapsed time instead of display ticks.",shortcuts:"Shortcuts: Space start/pause · L lap · R reset · F fullscreen"},
 ja:{local:"タイマー設定とラップ記録はサーバーへ送信・保存せず、このブラウザ内だけで処理します。",eyebrow:"LIVE TIME WORKSPACE",title:"すぐに時間を計測",timer:"タイマー",stopwatch:"ストップウォッチ",repeat:"繰り返しタイマー",hours:"時間",minutes:"分",seconds:"秒",work:"作業(秒)",rest:"休憩(秒)",rounds:"ラウンド",start:"開始",pause:"一時停止",resume:"再開",reset:"リセット",lap:"ラップ",fullscreen:"全画面",copy:"結果をコピー",copied:"結果をコピーしました。",copyFail:"クリップボードの権限を使用できません。",ready:"準備",running:"計測中",paused:"一時停止",completed:"完了",round:"ラウンド",phaseWork:"WORK · 作業",phaseRest:"REST · 休憩",phaseDone:"COMPLETE",timerEmpty:"カウントダウンを1秒以上に設定してください。",timerLimit:"カウントダウンは最大24:59:59まで設定できます。",repeatInvalid:`作業は1秒以上、休憩は0秒以上、ラウンドは1〜${TOOL054_LIMITS.maxRepeatRounds}回で入力してください。`,laps:"ラップ記録",lapHelp:"Lapは直前の記録からの区間、Totalは開始からの合計経過時間です。",lapLabel:"LAP",totalLabel:"TOTAL",lapLimit:`ラップ記録は最大${TOOL054_LIMITS.maxLaps.toLocaleString()}件です。`,doneTimer:"カウントダウンが完了しました。",doneRepeat:"繰り返しタイマーが完了しました。",background:"タブ切り替え後も表示tickではなく実際の経過時間から再計算します。",shortcuts:"ショートカット: Space 開始/一時停止 · L ラップ · R リセット · F 全画面"}
} as const;

function editableTarget(target:EventTarget|null){const el=target as HTMLElement|null;if(!el)return false;return el.tagName==="INPUT"||el.tagName==="TEXTAREA"||el.tagName==="SELECT"||el.isContentEditable}
function safeNumber(value:string){const n=Number(value);return Number.isFinite(n)?Math.max(0,Math.floor(n)):0}

export function TimerStopwatchTool({locale}:{locale:Locale}){
 const t=copy[locale];
 const [mode,setMode]=useState<Mode>("timer");const [state,setState]=useState<RunState>("ready");
 const [hours,setHours]=useState("0"),[minutes,setMinutes]=useState("5"),[seconds,setSeconds]=useState("0");
 const [work,setWork]=useState("40"),[rest,setRest]=useState("20"),[rounds,setRounds]=useState("8");
 const [displayMs,setDisplayMs]=useState(300000);const [laps,setLaps]=useState<Lap[]>([]);const [error,setError]=useState("");const [status,setStatus]=useState("");
 const anchorRef=useRef(0),baseRef=useRef(0),durationRef=useRef(300000),repeatConfigRef=useRef({workSeconds:40,restSeconds:20,rounds:8});const alarmedRef=useRef(false);const rootRef=useRef<HTMLDivElement>(null);const audioRef=useRef<AudioContext|null>(null);
 const now=useCallback(()=>typeof performance!=="undefined"?performance.now():Date.now(),[]);
 const elapsed=useCallback(()=>Math.max(0,baseRef.current+(state==="running"?now()-anchorRef.current:0)),[now,state]);
 const ensureAudio=useCallback(()=>{try{const Ctx=window.AudioContext||(window as typeof window & {webkitAudioContext?:typeof AudioContext}).webkitAudioContext;if(Ctx&&!audioRef.current)audioRef.current=new Ctx();if(audioRef.current?.state==="suspended")void audioRef.current.resume()}catch{}},[]);
 const alertSound=useCallback(()=>{try{const ctx=audioRef.current;if(!ctx)return;if(ctx.state==="suspended")void ctx.resume();const osc=ctx.createOscillator(),gain=ctx.createGain();osc.frequency.value=880;gain.gain.setValueAtTime(.0001,ctx.currentTime);gain.gain.exponentialRampToValueAtTime(.16,ctx.currentTime+.02);gain.gain.exponentialRampToValueAtTime(.0001,ctx.currentTime+.45);osc.connect(gain).connect(ctx.destination);osc.start();osc.stop(ctx.currentTime+.46)}catch{}},[]);
 const reset=useCallback(()=>{setState("ready");baseRef.current=0;anchorRef.current=0;alarmedRef.current=false;setLaps([]);setError("");setStatus("");if(mode==="timer"){try{const total=tool054HmsToSeconds({hours:safeNumber(hours),minutes:safeNumber(minutes),seconds:safeNumber(seconds)});durationRef.current=total*1000;setDisplayMs(total*1000)}catch{setDisplayMs(0)}}else if(mode==="repeat"){setDisplayMs(safeNumber(work)*1000)}else setDisplayMs(0)},[hours,minutes,seconds,mode,work]);
 const switchMode=(next:Mode)=>{setMode(next);setState("ready");baseRef.current=0;anchorRef.current=0;alarmedRef.current=false;setLaps([]);setError("");setStatus("");if(next==="timer"){const total=Math.min(TOOL054_LIMITS.maxCountdownSeconds,safeNumber(hours)*3600+safeNumber(minutes)*60+safeNumber(seconds));durationRef.current=total*1000;setDisplayMs(total*1000)}else if(next==="repeat")setDisplayMs(safeNumber(work)*1000);else setDisplayMs(0)};
 const start=useCallback(()=>{setStatus("");setError("");ensureAudio();if(mode==="timer"){let total=0;try{total=tool054HmsToSeconds({hours:safeNumber(hours),minutes:safeNumber(minutes),seconds:safeNumber(seconds)})}catch(e){setError(e instanceof RangeError&&e.message==="COUNTDOWN_LIMIT"?t.timerLimit:t.timerEmpty);return}if(total<=0){setError(t.timerEmpty);return}if(state==="ready"||state==="completed"){durationRef.current=total*1000;baseRef.current=0;setDisplayMs(total*1000);alarmedRef.current=false}anchorRef.current=now();setState("running");return}
 if(mode==="stopwatch"){if(state==="completed"){baseRef.current=0;setLaps([]);setDisplayMs(0)}anchorRef.current=now();alarmedRef.current=false;setState("running");return}
 try{const config=tool054ValidateRepeat({workSeconds:safeNumber(work),restSeconds:safeNumber(rest),rounds:safeNumber(rounds)});repeatConfigRef.current=config;if(state==="ready"||state==="completed"){baseRef.current=0;setDisplayMs(config.workSeconds*1000);alarmedRef.current=false}anchorRef.current=now();setState("running")}catch{setError(t.repeatInvalid)}
 },[ensureAudio,hours,minutes,mode,now,rest,rounds,seconds,state,t.repeatInvalid,t.timerEmpty,t.timerLimit,work]);
 const pause=useCallback(()=>{if(state!=="running")return;baseRef.current=elapsed();anchorRef.current=0;setState("paused")},[elapsed,state]);
 const toggle=useCallback(()=>state==="running"?pause():start(),[pause,start,state]);
 const addLap=useCallback(()=>{if(mode!=="stopwatch"||state!=="running")return;if(laps.length>=TOOL054_LIMITS.maxLaps){setError(t.lapLimit);return}const total=Math.min(elapsed(),TOOL054_LIMITS.maxStopwatchMs),prev=laps.at(-1)?.totalMs??0;setLaps([...laps,{totalMs:total,lapMs:tool054LapDuration(total,prev)}])},[elapsed,laps,mode,state,t.lapLimit]);
 const fullscreen=useCallback(async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await rootRef.current?.requestFullscreen()}catch{}},[]);
 useEffect(()=>{if(state!=="running")return;let raf=0;const tick=()=>{const e=elapsed();if(mode==="timer"){const remaining=Math.max(0,durationRef.current-e);setDisplayMs(remaining);if(remaining<=0){baseRef.current=durationRef.current;setState("completed");if(!alarmedRef.current){alarmedRef.current=true;alertSound()};return}}else if(mode==="stopwatch"){const capped=Math.min(e,TOOL054_LIMITS.maxStopwatchMs);setDisplayMs(capped);if(capped>=TOOL054_LIMITS.maxStopwatchMs){baseRef.current=TOOL054_LIMITS.maxStopwatchMs;setState("completed");return}}else{const rs=tool054ResolveRepeatElapsed(repeatConfigRef.current,e);setDisplayMs(rs.phaseRemainingMs);if(rs.completed){baseRef.current=e;setState("completed");if(!alarmedRef.current){alarmedRef.current=true;alertSound()};return}}raf=requestAnimationFrame(tick)};raf=requestAnimationFrame(tick);const onVisible=()=>{if(document.visibilityState==="visible")tick()};document.addEventListener("visibilitychange",onVisible);return()=>{cancelAnimationFrame(raf);document.removeEventListener("visibilitychange",onVisible)}},[alertSound,elapsed,mode,state]);
 useEffect(()=>()=>{const ctx=audioRef.current;if(ctx&&ctx.state!=="closed")void ctx.close()},[]);
 useEffect(()=>{const onKey=(e:KeyboardEvent)=>{if(editableTarget(e.target))return;if(e.code==="Space"){e.preventDefault();toggle()}else if(e.key.toLowerCase()==="l"){e.preventDefault();addLap()}else if(e.key.toLowerCase()==="r"){e.preventDefault();reset()}else if(e.key.toLowerCase()==="f"){e.preventDefault();void fullscreen()}};window.addEventListener("keydown",onKey);return()=>window.removeEventListener("keydown",onKey)},[addLap,fullscreen,reset,toggle]);
 const repeatState=useMemo(()=>mode==="repeat"?(state==="completed"?{phase:"completed" as const,round:safeNumber(rounds),phaseRemainingMs:0,completed:true}:tool054ResolveRepeatElapsed(repeatConfigRef.current,state==="ready"?0:Math.min(baseRef.current+(state==="running"?Math.max(0,now()-anchorRef.current):0),Number.MAX_SAFE_INTEGER))):null,[displayMs,mode,now,rounds,state]);
 const stateText=state==="running"?t.running:state==="paused"?t.paused:state==="completed"?t.completed:t.ready;
 const phaseText=mode==="repeat"?(repeatState?.phase==="work"?t.phaseWork:repeatState?.phase==="rest"?t.phaseRest:t.phaseDone):mode==="stopwatch"?"STOPWATCH":"COUNTDOWN";
 const primaryLabel=state==="running"?t.pause:state==="paused"?t.resume:t.start;
 async function copyResult(){let text="";if(mode==="stopwatch"){text=`${t.stopwatch}: ${tool054FormatClock(displayMs,true)}`;if(laps.length)text+=`\n${laps.map((x,i)=>`${t.lapLabel} ${i+1}: ${tool054FormatClock(x.lapMs,true)} · ${t.totalLabel} ${tool054FormatClock(x.totalMs,true)}`).join("\n")}`}else if(mode==="timer")text=`${t.timer}: ${tool054FormatClock(displayMs)} · ${stateText}`;else text=`${t.repeat}: ${phaseText} · ${t.round} ${repeatState?.round??1}/${safeNumber(rounds)} · ${tool054FormatClock(displayMs)}`;setStatus("");try{if(!navigator.clipboard?.writeText)throw new Error("CLIPBOARD_UNAVAILABLE");await navigator.clipboard.writeText(text);setStatus(t.copied)}catch{setStatus(t.copyFail)}}
 return <div className={styles.root} ref={rootRef} data-testid="tool054-root"><div className={styles.localNotice}><strong>LOCAL</strong><span>{t.local}</span></div><section className={styles.workspace} data-testid="tool054-workspace"><div className={styles.workspaceHead}><div><span className={styles.eyebrow}>{t.eyebrow}</span><h2>{t.title}</h2></div><button type="button" className={styles.iconButton} onClick={()=>void fullscreen()} data-testid="tool054-fullscreen">{t.fullscreen}</button></div><div className={styles.modeTabs} role="tablist" aria-label={t.title}>{(["timer","stopwatch","repeat"] as Mode[]).map(m=><button key={m} type="button" role="tab" aria-selected={mode===m} data-active={mode===m} className={styles.modeTab} onClick={()=>switchMode(m)} data-testid={`tool054-mode-${m}`}>{m==="timer"?t.timer:m==="stopwatch"?t.stopwatch:t.repeat}</button>)}</div><div className={styles.clockPanel}><span className={styles.phase} data-testid="tool054-phase">{phaseText}</span><strong className={styles.clock} data-testid="tool054-clock">{tool054FormatClock(displayMs,mode==="stopwatch")}</strong><p className={styles.subStatus} data-testid="tool054-state">{mode==="repeat"?`${stateText} · ${t.round} ${repeatState?.round??1}/${Math.max(1,safeNumber(rounds))}`:stateText}</p></div>
 {mode==="timer"&&<><div className={styles.presetRow} aria-label="Presets">{presets.map(p=><button type="button" className={styles.preset} key={p} disabled={state==="running"} onClick={()=>{setHours(String(Math.floor(p/3600)));setMinutes(String(Math.floor((p%3600)/60)));setSeconds(String(p%60));durationRef.current=p*1000;setDisplayMs(p*1000);setState("ready");baseRef.current=0;setError("")}} data-testid={`tool054-preset-${p}`}>{p<3600?`${p/60}m`:`${p/3600}h`}</button>)}</div><div className={styles.fields}><label className={styles.field}><span>{t.hours}</span><input inputMode="numeric" type="number" min="0" max="24" value={hours} disabled={state==="running"} onChange={e=>{setHours(e.target.value);setState("ready")}} data-testid="tool054-hours"/></label><label className={styles.field}><span>{t.minutes}</span><input inputMode="numeric" type="number" min="0" max="59" value={minutes} disabled={state==="running"} onChange={e=>{setMinutes(e.target.value);setState("ready")}} data-testid="tool054-minutes"/></label><label className={styles.field}><span>{t.seconds}</span><input inputMode="numeric" type="number" min="0" max="59" value={seconds} disabled={state==="running"} onChange={e=>{setSeconds(e.target.value);setState("ready")}} data-testid="tool054-seconds"/></label></div></>}
 {mode==="repeat"&&<div className={styles.fields}><label className={styles.field}><span>{t.work}</span><input inputMode="numeric" type="number" min="1" max={TOOL054_LIMITS.maxCountdownSeconds} value={work} disabled={state==="running"} onChange={e=>{setWork(e.target.value);setState("ready");setDisplayMs(safeNumber(e.target.value)*1000)}} data-testid="tool054-work"/></label><label className={styles.field}><span>{t.rest}</span><input inputMode="numeric" type="number" min="0" max={TOOL054_LIMITS.maxCountdownSeconds} value={rest} disabled={state==="running"} onChange={e=>{setRest(e.target.value);setState("ready")}} data-testid="tool054-rest"/></label><label className={styles.field}><span>{t.rounds}</span><input inputMode="numeric" type="number" min="1" max={TOOL054_LIMITS.maxRepeatRounds} value={rounds} disabled={state==="running"} onChange={e=>{setRounds(e.target.value);setState("ready")}} data-testid="tool054-rounds"/></label></div>}
 <div className={styles.actions}><button type="button" className={styles.primary} onClick={toggle} data-testid="tool054-primary">{primaryLabel}</button><button type="button" className={styles.secondary} onClick={addLap} disabled={mode!=="stopwatch"||state!=="running"} data-testid="tool054-lap">{t.lap}</button><button type="button" className={styles.danger} onClick={reset} data-testid="tool054-reset">{t.reset}</button></div>{error&&<p className={styles.error} role="alert" data-testid="tool054-error">{error}</p>}{state==="completed"&&<p className={styles.completion} role="status" aria-live="assertive" data-testid="tool054-completed">{mode==="repeat"?t.doneRepeat:t.doneTimer}</p>}<p className={styles.hint}>{t.background}<br/>{t.shortcuts}</p></section>
 {mode==="stopwatch"&&laps.length>0&&<section className={styles.lapSection} data-testid="tool054-laps"><div className={styles.sectionHead}><div><span>LAP / SPLIT</span><h3>{t.laps}</h3></div><p>{t.lapHelp}</p></div><div className={styles.lapList}>{laps.map((x,i)=><div className={styles.lapRow} key={`${x.totalMs}-${i}`} data-testid={`tool054-lap-row-${i+1}`}><strong>#{String(i+1).padStart(2,"0")}</strong><span>{t.lapLabel} {tool054FormatClock(x.lapMs,true)}</span><span>{t.totalLabel} {tool054FormatClock(x.totalMs,true)}</span></div>)}</div></section>}
 <div className={styles.footerActions}><button type="button" className={styles.secondary} onClick={()=>void copyResult()} data-testid="tool054-copy">{t.copy}</button></div>{status&&<p className={styles.hint} role="status" data-testid="tool054-copy-status">{status}</p>}<span className={styles.srOnly} aria-live="polite">{stateText}</span></div>
}
