'use client';
import {useMemo,useState} from 'react';
import type {Locale} from '@/lib/site';
import {TOOL087_LIMITS,calculateTool087,formatTool087,parseTool087Number} from '@/lib/tool-087-masonry-quantity';
import styles from './tool-087-masonry-quantity.module.css';

const copy={
 ko:{local:'입력값은 서버로 전송하거나 저장하지 않고 현재 브라우저에서만 계산합니다.',wall:'벽 크기',wallLength:'벽 길이',wallHeight:'벽 높이',material:'자재 규격',materialWidth:'자재 길이',materialHeight:'자재 높이',joint:'줄눈',jointSame:'가로·세로 줄눈',splitJoint:'가로·세로 줄눈을 따로 입력',jointH:'가로 줄눈',jointV:'세로 줄눈',waste:'손실률',price:'개당 단가',optional:'선택 입력',advanced:'고급 설정',precision:'표시 소수점',reset:'초기화',copy:'결과 복사',copied:'복사됨',result:'계산 결과',wallArea:'벽 면적',module:'모듈 크기',raw:'손실 전 개수',lossAdjusted:'손실 적용 수량',recommended:'구매 권장 개수',cost:'예상 비용',formula:'계산식',warning:'이 결과는 단순 면적·줄눈 기준 참고값입니다. 실제 조적 배치, 절단, 문·창문 등 개구부, 코너, 구조안전 및 법정 기준은 자동 판정하지 않습니다.',empty:'벽과 자재 치수를 입력하면 결과가 표시됩니다.',invalid:'올바른 숫자를 입력하세요.',wallError:'벽 길이와 높이는 0보다 커야 합니다.',materialError:'자재 길이와 높이는 0보다 커야 합니다.',negative:'줄눈·손실률·단가는 음수가 될 수 없습니다.',limit:'입력값이 서비스 유효상한을 초과했습니다.'},
 en:{local:'Inputs are calculated only in this browser and are not sent to or stored on a server.',wall:'Wall size',wallLength:'Wall Length',wallHeight:'Wall Height',material:'Material Size',materialWidth:'Material Width',materialHeight:'Material Height',joint:'Mortar Joint',jointSame:'Horizontal & vertical joint',splitJoint:'Enter horizontal and vertical joints separately',jointH:'Horizontal Joint',jointV:'Vertical Joint',waste:'Waste Rate',price:'Unit Price',optional:'Optional',advanced:'Advanced settings',precision:'Display decimals',reset:'Reset',copy:'Copy result',copied:'Copied',result:'Calculation result',wallArea:'Wall Area',module:'Module Size',raw:'Raw Quantity',lossAdjusted:'Quantity incl. waste',recommended:'Recommended Purchase Quantity',cost:'Estimated Cost',formula:'Formula',warning:'This is a simple area-and-joint reference. It does not determine actual masonry layout, cuts, openings, corners, structural safety, or legal requirements.',empty:'Enter wall and material dimensions to see results.',invalid:'Enter valid numbers.',wallError:'Wall length and height must be greater than zero.',materialError:'Material width and height must be greater than zero.',negative:'Joint, waste rate, and unit price cannot be negative.',limit:'An input exceeds the service limit.'},
 ja:{local:'入力値はサーバーへ送信・保存せず、このブラウザ内だけで計算します。',wall:'壁サイズ',wallLength:'壁の長さ',wallHeight:'壁の高さ',material:'材料サイズ',materialWidth:'材料の長さ',materialHeight:'材料の高さ',joint:'目地幅',jointSame:'横・縦の目地幅',splitJoint:'横目地と縦目地を別々に入力',jointH:'横目地',jointV:'縦目地',waste:'ロス率',price:'1個単価',optional:'任意',advanced:'詳細設定',precision:'表示小数点',reset:'リセット',copy:'結果をコピー',copied:'コピー済み',result:'計算結果',wallArea:'壁面積',module:'モジュールサイズ',raw:'ロス前個数',lossAdjusted:'ロス適用数量',recommended:'推奨購入個数',cost:'予想費用',formula:'計算式',warning:'この結果は単純な面積・目地基準の参考値です。実際の積み方、切断、開口部、コーナー、構造安全、法的基準は自動判定しません。',empty:'壁と材料の寸法を入力すると結果が表示されます。',invalid:'有効な数値を入力してください。',wallError:'壁の長さと高さは0より大きくしてください。',materialError:'材料の長さと高さは0より大きくしてください。',negative:'目地・ロス率・単価は負の値にできません。',limit:'入力値がサービス上限を超えています。'}
} as const;
function localeCode(locale:Locale){return locale==='ko'?'ko-KR':locale==='ja'?'ja-JP':'en-US'}

export function Tool087MasonryQuantity({locale}:{locale:Locale}){
 const t=copy[locale];
 const [wallLength,setWallLength]=useState('5');const [wallHeight,setWallHeight]=useState('2.4');
 const [materialWidth,setMaterialWidth]=useState('190');const [materialHeight,setMaterialHeight]=useState('57');
 const [jointSame,setJointSame]=useState('10');const [splitJoint,setSplitJoint]=useState(false);const [jointH,setJointH]=useState('10');const [jointV,setJointV]=useState('10');
 const [waste,setWaste]=useState('5');const [unitPrice,setUnitPrice]=useState('500');const [precision,setPrecision]=useState(2);const [status,setStatus]=useState('');
 const calculation=useMemo(()=>{
  const values=[wallLength,wallHeight,materialWidth,materialHeight,waste];if(values.some(v=>parseTool087Number(v)===null))return {value:null,error:values.some(v=>v.trim())?t.invalid:''};
  const same=parseTool087Number(jointSame),jh=parseTool087Number(jointH),jv=parseTool087Number(jointV),price=unitPrice.trim()===''?null:parseTool087Number(unitPrice);
  if((!splitJoint&&same===null)||(splitJoint&&(jh===null||jv===null))||(unitPrice.trim()!==''&&price===null))return {value:null,error:t.invalid};
  try{return {value:calculateTool087({wallLengthM:parseTool087Number(wallLength)!,wallHeightM:parseTool087Number(wallHeight)!,materialWidthMm:parseTool087Number(materialWidth)!,materialHeightMm:parseTool087Number(materialHeight)!,jointHorizontalMm:splitJoint?jh!:same!,jointVerticalMm:splitJoint?jv!:same!,wasteRate:parseTool087Number(waste)!,unitPrice:price}),error:''}}catch(e){const c=e instanceof Error?e.message:'';return {value:null,error:c==='WALL_DIMENSION'?t.wallError:c==='MATERIAL_DIMENSION'?t.materialError:c.includes('NEGATIVE')?t.negative:c.includes('LIMIT')?t.limit:t.invalid}}
 },[wallLength,wallHeight,materialWidth,materialHeight,jointSame,splitJoint,jointH,jointV,waste,unitPrice,t]);
 const r=calculation.value;const f=(n:number)=>formatTool087(n,precision,localeCode(locale));
 function reset(){setWallLength('5');setWallHeight('2.4');setMaterialWidth('190');setMaterialHeight('57');setJointSame('10');setSplitJoint(false);setJointH('10');setJointV('10');setWaste('5');setUnitPrice('500');setPrecision(2);setStatus('')}
 async function copyResult(){if(!r)return;const text=[`${t.wallArea}: ${f(r.wallAreaM2)} m²`,`${t.module}: ${f(r.moduleWidthM*1000)} × ${f(r.moduleHeightM*1000)} mm`,`${t.raw}: ${f(r.rawQuantity)}`,`${t.lossAdjusted}: ${f(r.lossAdjustedQuantity)}`,`${t.recommended}: ${r.recommendedPurchaseQuantity}`,r.estimatedCost==null?'':`${t.cost}: ${f(r.estimatedCost)}`].filter(Boolean).join('\n');try{await navigator.clipboard.writeText(text);setStatus(t.copied)}catch{setStatus('')}}
 const num=(label:string,value:string,setter:(v:string)=>void,suffix:string,testid:string)=><label className={styles.field}>{label}<span className={styles.withSuffix}><input inputMode="decimal" maxLength={TOOL087_LIMITS.maxInputChars} value={value} onChange={e=>setter(e.target.value)} data-testid={testid}/><span>{suffix}</span></span></label>;
 return <div className={styles.root} data-testid="tool087-root">
  <div className={styles.localNotice}><strong>LOCAL</strong><span>{t.local}</span></div>
  <section className={styles.workspace} data-testid="tool087-workspace"><div className={styles.workspaceGrid}>
   <div className={styles.card}><div className={styles.cardHead}><strong>WALL</strong><span>{t.wall}</span></div><div className={styles.inputGrid}>{num(t.wallLength,wallLength,setWallLength,'m','tool087-wall-length')}{num(t.wallHeight,wallHeight,setWallHeight,'m','tool087-wall-height')}</div></div>
   <div className={styles.card}><div className={styles.cardHead}><strong>MATERIAL</strong><span>{t.material}</span></div><div className={styles.inputGrid}>{num(t.materialWidth,materialWidth,setMaterialWidth,'mm','tool087-material-width')}{num(t.materialHeight,materialHeight,setMaterialHeight,'mm','tool087-material-height')}</div></div>
   <div className={styles.card}><div className={styles.cardHead}><strong>JOINT</strong><span>{t.joint}</span></div>{!splitJoint?<div className={styles.inputGrid}>{num(t.jointSame,jointSame,setJointSame,'mm','tool087-joint-same')}</div>:<div className={styles.inputGrid}>{num(t.jointH,jointH,setJointH,'mm','tool087-joint-horizontal')}{num(t.jointV,jointV,setJointV,'mm','tool087-joint-vertical')}</div>}<label className={styles.jointToggle}><input type="checkbox" checked={splitJoint} onChange={e=>setSplitJoint(e.target.checked)} data-testid="tool087-split-joint"/>{t.splitJoint}</label></div>
   <div className={styles.card}><div className={styles.cardHead}><strong>WASTE & COST</strong><span>{t.optional}</span></div><div className={styles.inputGrid}>{num(t.waste,waste,setWaste,'%','tool087-waste-rate')}{num(t.price,unitPrice,setUnitPrice,locale==='ko'?'원':locale==='ja'?'円/通貨':'/ unit','tool087-unit-price')}</div></div>
  </div><div className={styles.actionRow}><button type="button" className={styles.button} onClick={reset} data-testid="tool087-reset">{t.reset}</button><button type="button" className={styles.primaryButton} disabled={!r} onClick={copyResult} data-testid="tool087-copy">{t.copy}</button></div>{calculation.error&&<p className={styles.error} role="alert" data-testid="tool087-error">{calculation.error}</p>}</section>
  <details className={styles.advanced}><summary>{t.advanced} · {t.precision}</summary><div className={styles.advancedBody}><div className={styles.precisionRow}><input type="range" min="0" max={TOOL087_LIMITS.maxDisplayPrecision} value={precision} onChange={e=>setPrecision(Number(e.target.value))} data-testid="tool087-precision"/><span className={styles.precisionValue}>{precision}</span></div></div></details>
  <section className={styles.resultCard} aria-live="polite" data-testid="tool087-result"><div className={styles.resultHead}><p className={styles.resultLabel}>RESULT · {t.result}</p></div>{!r?<p className={styles.hint}>{calculation.error||t.empty}</p>:<><div className={styles.resultGrid}><div className={styles.resultItem}><span>{t.wallArea}</span><strong data-testid="tool087-wall-area">{f(r.wallAreaM2)}</strong><em>m²</em></div><div className={styles.resultItem}><span>{t.module}</span><strong data-testid="tool087-module-size">{f(r.moduleWidthM*1000)} × {f(r.moduleHeightM*1000)}</strong><em>mm</em></div><div className={styles.resultItem}><span>{t.raw}</span><strong data-testid="tool087-raw-quantity">{f(r.rawQuantity)}</strong><em>pcs</em></div><div className={styles.resultItem}><span>{t.lossAdjusted}</span><strong data-testid="tool087-loss-adjusted">{f(r.lossAdjustedQuantity)}</strong><em>pcs</em></div><div className={`${styles.resultItem} ${styles.heroResult}`}><span>{t.recommended}</span><strong data-testid="tool087-recommended">{r.recommendedPurchaseQuantity}</strong><em>pcs</em></div>{r.estimatedCost!=null&&<div className={styles.resultItem}><span>{t.cost}</span><strong data-testid="tool087-cost">{f(r.estimatedCost)}</strong><em>{locale==='ko'?'입력 통화':locale==='ja'?'入力通貨':'input currency'}</em></div>}</div><div className={styles.formulaBox}><strong>{t.formula}</strong><code data-testid="tool087-formula">Wall Area = length × height · Module = (material width + joint) × (material height + joint) · Quantity = ceil((Wall Area ÷ Module Area) × (1 + Waste ÷ 100))</code></div><div className={styles.warning} data-testid="tool087-warning">{t.warning}</div></>}{status&&<p className={styles.status}>{status}</p>}</section>
 </div>
}
