'use client';

import { useEffect, useMemo, useState } from 'react';
import { TOOL052_CITIES, TOOL052_TZ_DATASET } from '@/lib/tool-052-timezone-data';
import { TOOL052_SERVICE_LIMITS, differenceLabelMinutes, dstStatus, formatLocal, formatOffset, meetingOverlap, parseDateTime, resolveLocalDateTime, searchCities, type Tool052HourCycle } from '@/lib/tool-052-timezone';
import styles from './tool-052-world-time-tool.module.css';

type Locale = 'ko' | 'en' | 'ja';
type ReferenceZone = 'UTC' | string;

const text = {
  ko: { local:'도시와 시간 입력값은 서버로 전송하지 않고 브라우저에서만 계산합니다.', now:'현재 시간', specified:'지정 시간', refTime:'기준 시간', refZone:'기준 도시 / UTC', date:'날짜', time:'시간', h12:'12시간제', h24:'24시간제', add:'도시 추가', search:'도시·국가·타임존 검색', selected:'선택 도시', compare:'도시 비교', remove:'삭제', ahead:'앞', behind:'뒤', same:'같은 시간', dst:'DST 적용', standard:'표준시', nextDay:'다음 날', prevDay:'이전 날', sameDay:'같은 날', copy:'결과 복사', copied:'복사됨', copyFail:'복사 실패', reset:'초기화', meeting:'공통 회의시간', compareMode:'시간 비교', work:'업무시간', noMeeting:'공통 회의시간 없음', ambiguous:'이 시각은 DST 종료로 두 번 존재합니다. 어느 시각인지 선택하세요.', first:'첫 번째 시각', second:'두 번째 시각', nonexistent:'이 시각은 DST 전환으로 존재하지 않습니다. 다른 시각을 선택하세요.', invalid:'날짜와 시간을 확인하세요.', max:'도시는 최대 12개까지 비교할 수 있습니다.', duplicate:'이미 추가한 도시입니다.', noResult:'검색 결과가 없습니다.', dataset:'타임존 데이터 기준', utc:'UTC', reference:'기준', meetingHint:'선택 도시의 업무시간이 모두 겹치는 구간을 30분 단위로 찾습니다.' },
  en: { local:'City and time inputs are calculated only in your browser and are not sent to a server.', now:'Now', specified:'Specified time', refTime:'Reference time', refZone:'Reference city / UTC', date:'Date', time:'Time', h12:'12-hour', h24:'24-hour', add:'Add city', search:'Search city, country, or time zone', selected:'Selected cities', compare:'City comparison', remove:'Remove', ahead:'ahead', behind:'behind', same:'same time', dst:'DST active', standard:'Standard time', nextDay:'Next day', prevDay:'Previous day', sameDay:'Same day', copy:'Copy results', copied:'Copied', copyFail:'Copy failed', reset:'Reset', meeting:'Common meeting time', compareMode:'Time comparison', work:'Working hours', noMeeting:'No common meeting time', ambiguous:'This local time occurs twice during a DST fall-back. Choose which instant you mean.', first:'First occurrence', second:'Second occurrence', nonexistent:'This local time does not exist because of a DST transition. Choose another time.', invalid:'Check the date and time.', max:'You can compare up to 12 cities.', duplicate:'This city is already selected.', noResult:'No matching city found.', dataset:'Time zone data baseline', utc:'UTC', reference:'Reference', meetingHint:'Finds intervals where every selected city is within its working hours, in 30-minute steps.' },
  ja: { local:'都市と時刻の入力値はサーバーへ送信せず、ブラウザ内だけで計算します。', now:'現在時刻', specified:'指定時刻', refTime:'基準時刻', refZone:'基準都市 / UTC', date:'日付', time:'時刻', h12:'12時間制', h24:'24時間制', add:'都市を追加', search:'都市・国・タイムゾーンを検索', selected:'選択した都市', compare:'都市比較', remove:'削除', ahead:'進んでいます', behind:'遅れています', same:'同じ時刻', dst:'夏時間(DST)', standard:'標準時', nextDay:'翌日', prevDay:'前日', sameDay:'同日', copy:'結果をコピー', copied:'コピー済み', copyFail:'コピー失敗', reset:'リセット', meeting:'共通会議時間', compareMode:'時刻比較', work:'業務時間', noMeeting:'共通会議時間なし', ambiguous:'DST終了により、この現地時刻は2回存在します。どちらかを選択してください。', first:'1回目', second:'2回目', nonexistent:'DST切替により、この現地時刻は存在しません。別の時刻を選択してください。', invalid:'日付と時刻を確認してください。', max:'都市は最大12件まで比較できます。', duplicate:'すでに追加済みの都市です。', noResult:'検索結果がありません。', dataset:'タイムゾーンデータ基準', utc:'UTC', reference:'基準', meetingHint:'選択した全都市が業務時間内になる区間を30分単位で検索します。' },
} as const;

function localInputNow() { const d = new Date(); return { date: `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`, time: `${String(d.getHours()).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')}` }; }
function cityLabel(id: string, locale: Locale) { const c = TOOL052_CITIES.find((x)=>x.id===id); return c ? `${c.city[locale]}, ${c.country[locale]}` : id; }
function diffText(locale: Locale, minutes: number, t: typeof text[Locale]) { if (minutes === 0) return t.same; const abs=Math.abs(minutes); const h=Math.floor(abs/60), m=abs%60; const body=locale==='ko'?`${h}시간${m?` ${m}분`:''}`:locale==='ja'?`${h}時間${m?`${m}分`:''}`:`${h}h${m?` ${m}m`:''}`; return `${body} ${minutes>0?t.ahead:t.behind}`; }

export function Tool052WorldTimeTool({ locale }: { locale: Locale }) {
  const t=text[locale], initial=useMemo(localInputNow,[]);
  const [mode,setMode]=useState<'now'|'specified'>('now');
  const [nowMs,setNowMs]=useState(()=>Date.now());
  const [view,setView]=useState<'compare'|'meeting'>('compare');
  const [date,setDate]=useState(initial.date); const [time,setTime]=useState(initial.time);
  const [referenceZone,setReferenceZone]=useState<ReferenceZone>('Asia/Seoul');
  const [hourCycle,setHourCycle]=useState<Tool052HourCycle>('24');
  const [selected,setSelected]=useState(['seoul','new-york','london','tokyo']);
  const [query,setQuery]=useState(''); const [message,setMessage]=useState(''); const [copyState,setCopyState]=useState(''); const [ambiguityIndex,setAmbiguityIndex]=useState(0);
  const [workingHours,setWorkingHours]=useState<Record<string,{start:string;end:string}>>(()=>Object.fromEntries(TOOL052_CITIES.map(c=>[c.id,{start:'09:00',end:'18:00'}])));

  useEffect(()=>{ if(mode!=='now') return; const id=window.setInterval(()=>setNowMs(Date.now()),60000); return ()=>window.clearInterval(id); },[mode]);
  const resolution=useMemo(()=>{ if(mode==='now') return {kind:'exact' as const,candidates:[nowMs]}; const p=parseDateTime(date,time); if(!p) return {kind:'invalid' as const,candidates:[] as number[]}; if(referenceZone==='UTC') return {kind:'exact' as const,candidates:[Date.UTC(p.year,p.month-1,p.day,p.hour,p.minute)]}; return resolveLocalDateTime(p,referenceZone); },[mode,date,time,referenceZone,nowMs]);
  const instant=resolution.candidates[Math.min(ambiguityIndex,Math.max(0,resolution.candidates.length-1))] ?? null;
  const referenceDateParts=instant!==null?(referenceZone==='UTC'?{year:new Date(instant).getUTCFullYear(),month:new Date(instant).getUTCMonth()+1,day:new Date(instant).getUTCDate()}:formatLocal(instant,referenceZone,locale,hourCycle).parts):null;
  const results=instant===null?[]:selected.map(id=>{const city=TOOL052_CITIES.find(c=>c.id===id)!;const local=formatLocal(instant,city.zone,locale,hourCycle);const ds=dstStatus(instant,city.zone);const refOffset=referenceZone==='UTC'?0:dstStatus(instant,referenceZone).offset;const diff=ds.offset-refOffset;const rel=referenceDateParts?Math.sign(Date.UTC(local.parts.year,local.parts.month-1,local.parts.day)-Date.UTC(referenceDateParts.year,referenceDateParts.month-1,referenceDateParts.day)):0;return {city,local,ds,diff,rel};});
  const search=useMemo(()=>searchCities(query),[query]);
  const meetingDate=useMemo(()=>{if(mode==='specified'||instant===null||referenceZone==='UTC')return date;const p=formatLocal(instant,referenceZone,locale,'24').parts;return `${p.year}-${String(p.month).padStart(2,'0')}-${String(p.day).padStart(2,'0')}`;},[mode,instant,referenceZone,locale,date]);
  const meetingRanges=useMemo(()=>view==='meeting'&&referenceZone!=='UTC'?meetingOverlap({referenceDate:meetingDate,referenceZone,cityIds:selected,workingHours}):[],[view,meetingDate,referenceZone,selected,workingHours]);

  const addCity=(id:string)=>{ if(selected.includes(id)){setMessage(t.duplicate);return;} if(selected.length>=TOOL052_SERVICE_LIMITS.maxCities){setMessage(t.max);return;} setSelected(v=>[...v,id]);setMessage('');setQuery(''); };
  const removeCity=(id:string)=>{ if(selected.length<=2)return;setSelected(v=>v.filter(x=>x!==id)); };
  const moveCity=(id:string,dir:-1|1)=>setSelected(v=>{const i=v.indexOf(id),j=i+dir;if(i<0||j<0||j>=v.length)return v;const n=[...v];[n[i],n[j]]=[n[j],n[i]];return n;});
  const reset=()=>{setMode('now');setNowMs(Date.now());setView('compare');setDate(initial.date);setTime(initial.time);setReferenceZone('Asia/Seoul');setHourCycle('24');setSelected(['seoul','new-york','london','tokyo']);setQuery('');setMessage('');setCopyState('');setAmbiguityIndex(0);};
  const copy=async()=>{if(!results.length)return;const lines=results.map(r=>`${r.city.city[locale]}, ${r.city.country[locale]} — ${r.local.date} ${r.local.time} · ${formatOffset(r.ds.offset)} · ${r.ds.active?t.dst:t.standard}`);try{await navigator.clipboard.writeText(lines.join('\n'));setCopyState(t.copied);window.setTimeout(()=>setCopyState(''),1200);}catch{setCopyState(t.copyFail);}};
  const referenceOptions=[{value:'UTC',label:'UTC'},...TOOL052_CITIES.map(c=>({value:c.zone,label:`${c.city[locale]}, ${c.country[locale]}`}))];
  const error=resolution.kind==='invalid'?t.invalid:resolution.kind==='nonexistent'?t.nonexistent:'';

  return <div className={styles.tool} data-testid="tool052-root">
    <div className={styles.localNotice}><strong>LOCAL</strong><span>{t.local}</span><small>{t.dataset}: {TOOL052_TZ_DATASET.release}</small></div>
    <div className={styles.topModes}><div className={styles.segment} role="tablist" aria-label={t.refTime}><button type="button" role="tab" aria-selected={mode==='now'} className={mode==='now'?styles.active:''} onClick={()=>{setNowMs(Date.now());setMode('now');setAmbiguityIndex(0)}} data-testid="tool052-mode-now">{t.now}</button><button type="button" role="tab" aria-selected={mode==='specified'} className={mode==='specified'?styles.active:''} onClick={()=>{setMode('specified');setAmbiguityIndex(0)}} data-testid="tool052-mode-specified">{t.specified}</button></div><div className={styles.segment} role="tablist" aria-label="Display"><button type="button" role="tab" aria-selected={hourCycle==='24'} className={hourCycle==='24'?styles.active:''} onClick={()=>setHourCycle('24')}>{t.h24}</button><button type="button" role="tab" aria-selected={hourCycle==='12'} className={hourCycle==='12'?styles.active:''} onClick={()=>setHourCycle('12')}>{t.h12}</button></div></div>
    <section className={styles.workspace} data-testid="tool052-workspace"><div className={styles.workspaceHead}><div><span>WORLD TIME WORKSPACE</span><h2>{t.refTime}</h2></div><button type="button" className={styles.reset} onClick={reset} data-testid="tool052-reset">{t.reset}</button></div>
      <div className={styles.referenceGrid}><label className={styles.field}><span>{t.refZone}</span><select value={referenceZone} onChange={e=>{setReferenceZone(e.target.value);setAmbiguityIndex(0)}} data-testid="tool052-reference-zone">{referenceOptions.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select></label>{mode==='specified'&&<><label className={styles.field}><span>{t.date}</span><input type="date" min="1900-01-01" max="2100-12-31" value={date} onChange={e=>{setDate(e.target.value);setAmbiguityIndex(0)}} data-testid="tool052-date"/></label><label className={styles.field}><span>{t.time}</span><input type="time" value={time} onChange={e=>{setTime(e.target.value);setAmbiguityIndex(0)}} data-testid="tool052-time"/></label></>}</div>
      {resolution.kind==='ambiguous'&&<div className={styles.warning} data-testid="tool052-ambiguous"><p>{t.ambiguous}</p><div><button type="button" className={ambiguityIndex===0?styles.choiceActive:''} onClick={()=>setAmbiguityIndex(0)}>{t.first}</button><button type="button" className={ambiguityIndex===1?styles.choiceActive:''} onClick={()=>setAmbiguityIndex(1)}>{t.second}</button></div></div>}
      {error&&<p className={styles.error} role="alert" data-testid="tool052-error">{error}</p>}
      <div className={styles.cityAdd}><div><span>{t.add}</span><strong>{selected.length}/{TOOL052_SERVICE_LIMITS.maxCities}</strong></div><input aria-label={t.search} placeholder={t.search} value={query} onChange={e=>setQuery(e.target.value)} data-testid="tool052-city-search"/>{query&&<div className={styles.searchResults} data-testid="tool052-search-results">{search.length?search.map(c=><button type="button" key={c.id} onClick={()=>addCity(c.id)}><span>{c.city[locale]}, {c.country[locale]}</span><small>{c.zone}</small></button>):<p>{t.noResult}</p>}</div>}{message&&<p className={styles.message}>{message}</p>}</div>
    </section>
    <div className={styles.viewTabs} role="tablist"><button type="button" role="tab" aria-selected={view==='compare'} className={view==='compare'?styles.active:''} onClick={()=>setView('compare')}>{t.compareMode}</button><button type="button" role="tab" aria-selected={view==='meeting'} className={view==='meeting'?styles.active:''} onClick={()=>setView('meeting')}>{t.meeting}</button></div>
    {view==='compare'&&<section className={styles.compareSection}><div className={styles.sectionHead}><div><span>COMPARE</span><h2>{t.compare}</h2></div><button type="button" onClick={copy} disabled={!results.length} className={styles.copy}>{t.copy}</button></div>{copyState&&<p className={styles.copyState}>{copyState}</p>}<div className={styles.cityGrid} data-testid="tool052-results">{results.map(r=><article className={styles.cityCard} key={r.city.id} data-testid={`tool052-city-${r.city.id}`}><div className={styles.cityCardHead}><div><strong>{r.city.city[locale]}</strong><span>{r.city.country[locale]}</span></div><div className={styles.cardActions}><button type="button" aria-label={`${r.city.city[locale]} ↑`} onClick={()=>moveCity(r.city.id,-1)}>↑</button><button type="button" aria-label={`${r.city.city[locale]} ↓`} onClick={()=>moveCity(r.city.id,1)}>↓</button>{selected.length>2&&<button type="button" aria-label={`${t.remove} ${r.city.city[locale]}`} onClick={()=>removeCity(r.city.id)}>×</button>}</div></div><div className={styles.timeValue}>{r.local.time}</div><div className={styles.dateLine}><span>{r.local.date}</span><em className={r.rel>0?styles.dayNext:r.rel<0?styles.dayPrev:styles.daySame}>{r.rel>0?t.nextDay:r.rel<0?t.prevDay:t.sameDay}</em></div><div className={styles.meta}><span>{formatOffset(r.ds.offset)}</span><span>{r.ds.active?t.dst:t.standard}</span><span>{diffText(locale,r.diff,t)}</span></div></article>)}</div></section>}
    {view==='meeting'&&<section className={styles.meetingSection} data-testid="tool052-meeting"><div className={styles.sectionHead}><div><span>MEETING PLANNER</span><h2>{t.meeting}</h2><p>{t.meetingHint}</p></div></div>{referenceZone==='UTC'?<p className={styles.error}>{locale==='ko'?'회의시간 모드에서는 기준 도시를 선택하세요.':locale==='ja'?'会議時間モードでは基準都市を選択してください。':'Choose a reference city for meeting mode.'}</p>:<><div className={styles.hoursGrid}>{selected.map(id=><label key={id} className={styles.hoursCard}><strong>{cityLabel(id,locale)}</strong><span>{t.work}</span><div><input type="time" value={workingHours[id].start} onChange={e=>setWorkingHours(v=>({...v,[id]:{...v[id],start:e.target.value}}))}/><b>–</b><input type="time" value={workingHours[id].end} onChange={e=>setWorkingHours(v=>({...v,[id]:{...v[id],end:e.target.value}}))}/></div></label>)}</div><div className={styles.meetingResults}>{meetingRanges.length?meetingRanges.map((range,i)=><article key={range.start}><strong>{i+1}</strong><div>{selected.map(id=>{const c=TOOL052_CITIES.find(x=>x.id===id)!;const a=formatLocal(range.start,c.zone,locale,hourCycle);const b=formatLocal(range.end,c.zone,locale,hourCycle);return <p key={id}><span>{c.city[locale]}</span><b>{a.date} {a.time} – {b.time}</b></p>})}</div></article>):<p className={styles.noMeeting}>{t.noMeeting}</p>}</div></>}</section>}
  </div>;
}
