'use client';
import {useMemo,useState} from 'react';
import type {Locale} from '@/lib/site';
import {TOOL060_SYSTEMS,findTool060BySize,findTool060ShoeByFootLength,getTool060Rows,measurementText,type Tool060Gender,type Tool060Item,type Tool060Mode,type Tool060System,type Tool060ShoeRow,type Tool060ClothingRow} from '@/lib/tool-060-sizes';
import styles from './tool-060-shoe-clothing-size-converter.module.css';
const copy={
 ko:{shoes:'신발',clothing:'의류',men:'남성',women:'여성',kids:'아동',tops:'상의',bottoms:'하의',system:'기준 국가·체계',size:'기준 사이즈',foot:'발길이로 찾기',footUnit:'발길이 (mm)',result:'국제 사이즈 참고표',empty:'기준 사이즈를 선택하면 5개 국가 결과가 표시됩니다.',none:'지원 범위에 없는 사이즈입니다.',measurement:'기준 신체치수',brand:'참고 환산입니다. 실제 구매 전 상품 페이지의 브랜드 사이즈표와 본인 실측을 확인하세요.',copy:'결과 복사',reset:'초기화',copied:'복사했습니다.',table:'전체 사이즈표 보기',reference:'일반 국제 참고표',selected:'선택 기준'},
 en:{shoes:'Shoes',clothing:'Clothing',men:'Men',women:'Women',kids:'Kids',tops:'Tops',bottoms:'Bottoms',system:'From system',size:'From size',foot:'Find by foot length',footUnit:'Foot length (mm)',result:'International size reference',empty:'Choose a reference size to compare all five systems.',none:'This size is outside the supported reference range.',measurement:'Body measurement reference',brand:'Reference conversion only. Check the product brand size chart and your measurements before purchase.',copy:'Copy result',reset:'Reset',copied:'Copied.',table:'View full size table',reference:'General international reference',selected:'Selected reference'},
 ja:{shoes:'靴',clothing:'衣類',men:'メンズ',women:'レディース',kids:'キッズ',tops:'トップス',bottoms:'ボトムス',system:'基準の国・体系',size:'基準サイズ',foot:'足長から探す',footUnit:'足長 (mm)',result:'国際サイズ参考表',empty:'基準サイズを選ぶと5体系の結果を表示します。',none:'対応範囲外のサイズです。',measurement:'身体寸法の目安',brand:'参考換算です。購入前に商品ページのブランドサイズ表と実測値を確認してください。',copy:'結果をコピー',reset:'リセット',copied:'コピーしました。',table:'サイズ表をすべて表示',reference:'一般国際参考表',selected:'選択基準'}
} as const;
export function Tool060ShoeClothingSizeConverter({locale}:{locale:Locale}){
 const t=copy[locale]; const [mode,setMode]=useState<Tool060Mode>('shoes'); const [gender,setGender]=useState<Tool060Gender>('men'); const [item,setItem]=useState<Tool060Item>('tops'); const [system,setSystem]=useState<Tool060System>('KR'); const [selectedId,setSelectedId]=useState(''); const [foot,setFoot]=useState(''); const [status,setStatus]=useState('');
 const rows=getTool060Rows(mode,gender,item); const selected=useMemo(()=>rows.find(r=>r.id===selectedId)||null,[rows,selectedId]);
 const choose=(id:string)=>{setSelectedId(id);setFoot('');setStatus('')};
 const reset=()=>{setMode('shoes');setGender('men');setItem('tops');setSystem('KR');setSelectedId('');setFoot('');setStatus('')};
 const findFoot=()=>{const matches=findTool060ShoeByFootLength(gender,Number(foot));setSelectedId(matches[0]?.id||'');setStatus(matches.length?'':t.none)};
 const summary=selected?TOOL060_SYSTEMS.map(s=>`${s} ${selected.sizes[s]}`).join(' · '):'';
 const copyResult=async()=>{if(!selected)return;const extra=mode==='shoes'?`Foot length ${(selected as Tool060ShoeRow).footLengthMm} mm`:measurementText(selected as Tool060ClothingRow,locale);try{await navigator.clipboard.writeText(`${summary}\n${extra}\n${t.brand}`);setStatus(t.copied)}catch{setStatus(summary)}};
 const changeContext=(next:{mode?:Tool060Mode;gender?:Tool060Gender;item?:Tool060Item})=>{if(next.mode)setMode(next.mode);if(next.gender)setGender(next.gender);if(next.item)setItem(next.item);setSelectedId('');setFoot('');setStatus('')};
 return <div className={styles.root} data-testid="tool060-root"><div className={styles.notice}><strong>REFERENCE</strong><span>{t.brand}</span></div><section className={styles.workspace}>
  <div className={styles.step}><span>01</span><div className={styles.tabs}>{(['shoes','clothing'] as Tool060Mode[]).map(v=><button key={v} className={`${styles.tab} ${mode===v?styles.active:''}`} aria-pressed={mode===v} onClick={()=>changeContext({mode:v})} data-testid={`tool060-mode-${v}`}>{t[v]}</button>)}</div></div>
  <div className={styles.step}><span>02</span><div className={styles.tabs3}>{(['men','women','kids'] as Tool060Gender[]).map(v=><button key={v} className={`${styles.tab} ${gender===v?styles.active:''}`} aria-pressed={gender===v} onClick={()=>changeContext({gender:v})} data-testid={`tool060-gender-${v}`}>{t[v]}</button>)}</div></div>
  {mode==='clothing'&&<div className={styles.step}><span>03</span><div className={styles.tabs}>{(['tops','bottoms'] as Tool060Item[]).map(v=><button key={v} className={`${styles.tab} ${item===v?styles.active:''}`} aria-pressed={item===v} onClick={()=>changeContext({item:v})} data-testid={`tool060-item-${v}`}>{t[v]}</button>)}</div></div>}
  <div className={styles.card}><div className={styles.inputGrid}><label>{t.system}<select value={system} onChange={e=>{setSystem(e.target.value as Tool060System);setSelectedId('');setStatus('')}} data-testid="tool060-system">{TOOL060_SYSTEMS.map(s=><option key={s}>{s}</option>)}</select></label><label>{t.size}<select value={selectedId} onChange={e=>choose(e.target.value)} data-testid="tool060-size"><option value="">—</option>{rows.map(r=><option key={r.id} value={r.id}>{r.sizes[system]}</option>)}</select></label></div>{mode==='shoes'&&<div className={styles.footRow}><label>{t.footUnit}<input type="number" min="1" step="1" value={foot} onChange={e=>setFoot(e.target.value)} data-testid="tool060-foot"/></label><button type="button" onClick={findFoot} data-testid="tool060-foot-find">{t.foot}</button></div>}<div className={styles.actions}><button onClick={reset} data-testid="tool060-reset">{t.reset}</button><button className={styles.primary} onClick={copyResult} disabled={!selected} data-testid="tool060-copy">{t.copy}</button></div></div>
  <section className={styles.result} aria-live="polite" data-testid="tool060-result"><div className={styles.resultHead}><div><p>RESULT</p><h2>{t.result}</h2></div><span>{t.reference}</span></div>{!selected?<p className={styles.empty}>{status||t.empty}</p>:<><div className={styles.countryGrid}>{TOOL060_SYSTEMS.map(s=><article key={s} data-testid={`tool060-result-${s}`}><span>{s}</span><strong>{selected.sizes[s]}</strong></article>)}</div><div className={styles.measurement}><strong>{t.measurement}</strong><span>{mode==='shoes'?`${(selected as Tool060ShoeRow).footLengthMm} mm · ${((selected as Tool060ShoeRow).footLengthMm/10).toFixed(1)} cm`:measurementText(selected as Tool060ClothingRow,locale)}</span></div><p className={styles.warning}>{t.brand}</p></>}{status&&selected&&<p className={styles.status}>{status}</p>}</section>
  <details className={styles.fullTable}><summary>{t.table}</summary><div className={styles.tableWrap}><table><thead><tr>{TOOL060_SYSTEMS.map(s=><th key={s}>{s}</th>)}<th>{t.measurement}</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}>{TOOL060_SYSTEMS.map(s=><td key={s}>{r.sizes[s]}</td>)}<td>{mode==='shoes'?`${(r as Tool060ShoeRow).footLengthMm} mm`:measurementText(r as Tool060ClothingRow,locale)}</td></tr>)}</tbody></table></div></details>
 </section></div>
}
