'use client';
import {useMemo,useState} from 'react';
import type {Locale} from '@/lib/site';
import {TOOL070_LIMITS,allowedDisplayUnits,compareTool070,defaultDisplayUnit,formatTool070,parseTool070Number,type Tool070DisplayUnit,type Tool070Mode,type Tool070Unit} from '@/lib/tool-070-unit-price';
import styles from './tool-070-unit-price-comparison.module.css';

const copy={
 ko:{modes:{items:'개수',weight:'무게',volume:'부피','bundle-weight':'묶음·무게','bundle-volume':'묶음·부피'},local:'입력한 가격과 수량은 서버로 전송하거나 저장하지 않고 현재 브라우저에서만 계산합니다.',display:'비교 기준',price:'총가격',quantity:'수량',weight:'총무게',volume:'총부피',count:'묶음 개수',perWeight:'개당 무게',perVolume:'개당 부피',optionA:'상품 A',optionB:'상품 B',reset:'초기화',copy:'결과 복사',copied:'복사됨',precision:'표시 소수점',result:'비교 결과',unitPrice:'단가',cheaperA:'A가 더 저렴',cheaperB:'B가 더 저렴',equal:'단가가 같음',difference:'단가 차이',savings:'절약액',rate:'절약률',sameAmount:'동일 기준량 비용',formula:'계산식',empty:'모든 필수 값을 입력하세요.',invalid:'올바른 숫자를 입력하세요.',zero:'수량·무게·부피는 0보다 커야 합니다.',negative:'가격은 0 이상이어야 합니다.',limit:'입력값이 서비스 유효상한을 초과했습니다.',bundleLimit:'묶음 개수는 1,000,000 이하로 입력하세요.',itemsHint:'가격과 개수를 입력하면 개당 가격으로 비교합니다.',weightHint:'g 또는 kg을 g 기준으로 정규화해 100g·1kg 단가를 비교합니다.',volumeHint:'mL 또는 L를 mL 기준으로 정규화해 100mL·1L 단가를 비교합니다.',bundleWeightHint:'묶음 개수×개당 무게로 실제 총중량을 만든 뒤 비교합니다.',bundleVolumeHint:'묶음 개수×개당 부피로 실제 총부피를 만든 뒤 비교합니다.'},
 en:{modes:{items:'Items',weight:'Weight',volume:'Volume','bundle-weight':'Pack · Weight','bundle-volume':'Pack · Volume'},local:'Prices and quantities are calculated only in this browser and are not sent to or stored on a server.',display:'Comparison basis',price:'Total Price',quantity:'Quantity',weight:'Total Weight',volume:'Total Volume',count:'Pack Count',perWeight:'Weight per Item',perVolume:'Volume per Item',optionA:'Option A',optionB:'Option B',reset:'Reset',copy:'Copy result',copied:'Copied',precision:'Display decimals',result:'Comparison result',unitPrice:'Unit Price',cheaperA:'A is cheaper',cheaperB:'B is cheaper',equal:'Same unit price',difference:'Unit-price difference',savings:'Savings',rate:'Savings rate',sameAmount:'Equal-quantity cost',formula:'Formula',empty:'Enter all required values.',invalid:'Enter valid numbers.',zero:'Quantity, weight, and volume must be greater than zero.',negative:'Price must be zero or greater.',limit:'An input exceeds the service limit.',bundleLimit:'Pack count must be 1,000,000 or less.',itemsHint:'Compare total price and item count as price per item.',weightHint:'Normalize g or kg to grams, then compare price per 100 g or 1 kg.',volumeHint:'Normalize mL or L to milliliters, then compare price per 100 mL or 1 L.',bundleWeightHint:'Calculate real total weight as pack count × weight per item.',bundleVolumeHint:'Calculate real total volume as pack count × volume per item.'},
 ja:{modes:{items:'個数',weight:'重量',volume:'容量','bundle-weight':'セット・重量','bundle-volume':'セット・容量'},local:'入力した価格と数量はサーバーへ送信・保存せず、このブラウザ内だけで計算します。',display:'比較基準',price:'合計価格',quantity:'数量',weight:'総重量',volume:'総容量',count:'セット数',perWeight:'1個あたり重量',perVolume:'1個あたり容量',optionA:'商品 A',optionB:'商品 B',reset:'リセット',copy:'結果をコピー',copied:'コピー済み',precision:'表示小数点',result:'比較結果',unitPrice:'単価',cheaperA:'Aの方が安い',cheaperB:'Bの方が安い',equal:'単価は同じ',difference:'単価差',savings:'節約額',rate:'節約率',sameAmount:'同量の費用',formula:'計算式',empty:'必須項目をすべて入力してください。',invalid:'有効な数値を入力してください。',zero:'数量・重量・容量は0より大きくしてください。',negative:'価格は0以上にしてください。',limit:'入力値がサービス上限を超えています。',bundleLimit:'セット数は1,000,000以下にしてください。',itemsHint:'合計価格と個数から1個あたり価格を比較します。',weightHint:'g・kgをg基準に正規化し、100g・1kgあたりを比較します。',volumeHint:'mL・LをmL基準に正規化し、100mL・1Lあたりを比較します。',bundleWeightHint:'セット数×1個あたり重量で実際の総重量を計算して比較します。',bundleVolumeHint:'セット数×1個あたり容量で実際の総容量を計算して比較します。'}
} as const;

type OptionState={price:string;quantity:string;unit:Tool070Unit;count:string};
const INITIAL:Record<Tool070Mode,[OptionState,OptionState]>={
 items:[{price:'9900',quantity:'10',unit:'item',count:'1'},{price:'17800',quantity:'20',unit:'item',count:'1'}],
 weight:[{price:'6000',quantity:'500',unit:'g',count:'1'},{price:'10000',quantity:'1',unit:'kg',count:'1'}],
 volume:[{price:'1500',quantity:'300',unit:'mL',count:'1'},{price:'4200',quantity:'1',unit:'L',count:'1'}],
 'bundle-weight':[{price:'9000',quantity:'250',unit:'g',count:'6'},{price:'11000',quantity:'2',unit:'kg',count:'1'}],
 'bundle-volume':[{price:'2500',quantity:'250',unit:'mL',count:'6'},{price:'4200',quantity:'1',unit:'L',count:'1'}]
};
function localeCode(locale:Locale){return locale==='ko'?'ko-KR':locale==='ja'?'ja-JP':'en-US'}
function unitLabel(unit:Tool070DisplayUnit){return unit==='item'?'/ item':unit==='100g'?'/ 100g':unit==='1kg'?'/ 1kg':unit==='100mL'?'/ 100mL':'/ 1L'}

export function Tool070UnitPriceComparison({locale}:{locale:Locale}){
 const t=copy[locale];const [mode,setMode]=useState<Tool070Mode>('items');const [displayUnit,setDisplayUnit]=useState<Tool070DisplayUnit>('item');const [a,setA]=useState<OptionState>({...INITIAL.items[0]});const [b,setB]=useState<OptionState>({...INITIAL.items[1]});const [precision,setPrecision]=useState(2);const [status,setStatus]=useState('');
 function changeMode(next:Tool070Mode){setMode(next);setDisplayUnit(defaultDisplayUnit(next));setA({...INITIAL[next][0]});setB({...INITIAL[next][1]});setStatus('')}
 function parseOption(s:OptionState){const price=parseTool070Number(s.price);const quantity=parseTool070Number(s.quantity);const count=parseTool070Number(s.count);return {price,quantity,count}}
 const calculation=useMemo(()=>{const pa=parseOption(a),pb=parseOption(b);if(pa.price===null||pa.quantity===null||pb.price===null||pb.quantity===null||((mode==='bundle-weight'||mode==='bundle-volume')&&(pa.count===null||pb.count===null)))return {result:null,error:t.empty};try{return {result:compareTool070(mode,{price:pa.price,quantity:pa.quantity,unit:a.unit,count:pa.count??undefined},{price:pb.price,quantity:pb.quantity,unit:b.unit,count:pb.count??undefined},displayUnit),error:''}}catch(e){const code=e instanceof Error?e.message:'';return {result:null,error:code==='NEGATIVE'?t.negative:code.includes('ZERO')?t.zero:code==='BUNDLE_COUNT_LIMIT'?t.bundleLimit:code.includes('LIMIT')?t.limit:t.invalid}}},[a,b,mode,displayUnit,t]);
 const result=calculation.result;const f=(v:number)=>formatTool070(v,precision,localeCode(locale));
 function reset(){changeMode('items');setPrecision(2)}
 async function copyResult(){if(!result)return;const winner=result.winner==='A'?t.cheaperA:result.winner==='B'?t.cheaperB:t.equal;const text=`${t.optionA} ${t.unitPrice}: ${f(result.a.displayUnitPrice)} ${unitLabel(displayUnit)} | ${t.optionB} ${t.unitPrice}: ${f(result.b.displayUnitPrice)} ${unitLabel(displayUnit)} | ${winner} | ${t.difference}: ${f(result.difference)} | ${t.savings}: ${f(result.savings)} (${formatTool070(result.savingsRate,2,localeCode(locale))}%)`;try{await navigator.clipboard.writeText(text);setStatus(t.copied)}catch{setStatus('')}}
 const hint=mode==='items'?t.itemsHint:mode==='weight'?t.weightHint:mode==='volume'?t.volumeHint:mode==='bundle-weight'?t.bundleWeightHint:t.bundleVolumeHint;
 function card(label:string,state:OptionState,setState:(s:OptionState)=>void,prefix:'a'|'b'){
  const bundle=mode==='bundle-weight'||mode==='bundle-volume';const isWeight=mode==='weight'||mode==='bundle-weight';const qLabel=mode==='items'?t.quantity:mode==='weight'?t.weight:mode==='volume'?t.volume:isWeight?t.perWeight:t.perVolume;const units:Tool070Unit[]=mode==='items'?['item']:isWeight?['g','kg']:['mL','L'];
  return <div className={styles.optionCard}><div className={styles.optionHead}><strong>{label}</strong><span>{prefix.toUpperCase()}</span></div><div className={styles.inputGrid}><label className={styles.field}>{t.price}<input inputMode="decimal" maxLength={TOOL070_LIMITS.maxInputChars} value={state.price} onChange={e=>setState({...state,price:e.target.value})} data-testid={`tool070-${prefix}-price`}/></label>{bundle&&<label className={styles.field}>{t.count}<input inputMode="decimal" maxLength={TOOL070_LIMITS.maxInputChars} value={state.count} onChange={e=>setState({...state,count:e.target.value})} data-testid={`tool070-${prefix}-count`}/></label>}<label className={styles.field}>{qLabel}<span className={styles.quantityWithUnit}><input inputMode="decimal" maxLength={TOOL070_LIMITS.maxInputChars} value={state.quantity} onChange={e=>setState({...state,quantity:e.target.value})} data-testid={`tool070-${prefix}-quantity`}/><select value={state.unit} onChange={e=>setState({...state,unit:e.target.value as Tool070Unit})} aria-label={`${label} unit`} data-testid={`tool070-${prefix}-unit`}>{units.map(u=><option key={u} value={u}>{u}</option>)}</select></span></label></div></div>
 }
 return <div className={styles.root} data-testid="tool070-root" data-mode={mode}>
  <div className={styles.localNotice}><strong>LOCAL</strong><span>{t.local}</span></div>
  <div className={styles.tabs} role="tablist" aria-label="comparison mode">{(Object.keys(t.modes) as Tool070Mode[]).map(id=><button key={id} type="button" role="tab" aria-selected={mode===id} className={`${styles.tab} ${mode===id?styles.tabActive:''}`} onClick={()=>changeMode(id)} data-testid={`tool070-mode-${id}`}>{t.modes[id]}</button>)}</div>
  <section className={styles.workspace} data-testid="tool070-workspace"><div className={styles.modeRow}><p className={styles.modeHint}>{hint}</p><label className={styles.displaySelect}>{t.display}<select value={displayUnit} onChange={e=>setDisplayUnit(e.target.value as Tool070DisplayUnit)} data-testid="tool070-display-unit">{allowedDisplayUnits(mode).map(u=><option key={u} value={u}>{u}</option>)}</select></label></div><div className={styles.options}>{card(t.optionA,a,setA,'a')}{card(t.optionB,b,setB,'b')}</div><div className={styles.actionRow}><button type="button" className={styles.button} onClick={reset} data-testid="tool070-reset">{t.reset}</button><button type="button" className={styles.primaryButton} disabled={!result} onClick={copyResult} data-testid="tool070-copy">{t.copy}</button></div>{calculation.error&&<p className={styles.error} role="alert" data-testid="tool070-error">{calculation.error}</p>}</section>
  <details className={styles.advanced}><summary>{t.precision}</summary><div className={styles.precisionRow}><input aria-label={t.precision} type="range" min="0" max={TOOL070_LIMITS.maxDisplayPrecision} value={precision} onChange={e=>setPrecision(Number(e.target.value))} data-testid="tool070-precision"/><span className={styles.precisionValue}>{precision}</span></div></details>
  <section className={styles.resultCard} aria-live="polite" data-testid="tool070-result"><div className={styles.resultHead}><p className={styles.resultLabel}>RESULT · {t.result}</p>{result&&<span className={styles.winner} data-testid="tool070-winner">{result.winner==='A'?t.cheaperA:result.winner==='B'?t.cheaperB:t.equal}</span>}</div>{!result?<p className={styles.hint}>{calculation.error||t.empty}</p>:<><div className={styles.resultGrid}><div className={styles.resultItem}><span>{t.optionA} · {t.unitPrice}</span><strong data-testid="tool070-result-a">{f(result.a.displayUnitPrice)}</strong><em>{unitLabel(displayUnit)}</em></div><div className={styles.resultItem}><span>{t.optionB} · {t.unitPrice}</span><strong data-testid="tool070-result-b">{f(result.b.displayUnitPrice)}</strong><em>{unitLabel(displayUnit)}</em></div></div><div className={styles.metrics}><div className={styles.metric}><span>{t.difference}</span><strong data-testid="tool070-difference">{f(result.difference)}</strong></div><div className={styles.metric}><span>{t.savings}</span><strong data-testid="tool070-savings">{f(result.savings)}</strong></div><div className={styles.metric}><span>{t.rate}</span><strong data-testid="tool070-savings-rate">{formatTool070(result.savingsRate,2,localeCode(locale))}%</strong></div></div><div className={styles.formulaBox}><strong>{t.sameAmount}</strong><code data-testid="tool070-equal-quantity">A {f(result.a.displayUnitPrice)} / B {f(result.b.displayUnitPrice)} · {displayUnit}</code><strong>{t.formula}</strong><code data-testid="tool070-formula">{result.a.formula}</code></div></>}{status&&<p className={styles.status} aria-live="polite">{status}</p>}</section>
 </div>
}
