import { ToolNavigation } from "@/components/tool-navigation";
import Link from 'next/link';
import type {Locale} from '@/lib/site';
import {Tool066VatCalculator} from '@/components/tool-066-vat-calculator';
import {ToolboxFaqList} from '@/components/toolbox-faq-list';
import {ToolboxSubpageShell} from '@/components/toolbox-subpage-shell';

const copy={
 ko:{title:'부가세 계산기',desc:'공급가액에서 부가세·합계금액을 계산하고, 부가세 포함 금액에서 공급가액과 세액을 정확히 역산합니다.',back:'사업·금융 계산기',local:'브라우저에서 바로 계산',next:'다음 작업',related:'관련 도구',how:'사용 방법',steps:['공급가액 기준 또는 부가세 포함 합계금액 기준을 선택합니다.','기본 세율 10%를 확인하고 필요할 때만 세율을 직접 바꿉니다.','금액을 입력하면 공급가액·부가세액·합계금액이 즉시 표시됩니다.','포함 금액 역산에서는 총액을 1.1로 나누어 공급가액을 계산합니다.','필요하면 세율 확인 모드에서 공급가액과 부가세액으로 유효 세율을 확인하고 결과를 복사합니다.','계산 결과를 실제 거래명세서·세금계산서와 비교할 때는 공급가액과 VAT가 같은 기준으로 적혀 있는지 확인합니다.'],notes:['대한민국 일반과세자 기본 부가가치세율 10%를 기본값으로 사용합니다.','부가세 포함 총액에서 세액을 구할 때 총액의 10%를 단순히 빼는 방식이 아니라 총액×10/110 또는 총액÷1.1 역산을 사용합니다.','이 도구의 부가세액은 거래금액의 VAT 구성요소이며 최종 납부세액과 동일하지 않습니다.','영세율·면세 적용 여부, 간이과세자의 실제 납부세액, 매입세액 공제는 자동 판정하지 않습니다.','기본 10% 외 사용자가 직접 입력한 세율은 참고 계산으로 표시합니다.','법적 신고용 최종 세액은 최신 세무 기준과 공식 신고 시스템을 우선하세요.','가격 비교나 견적 검토에서는 부가세 포함·별도 조건을 먼저 맞춘 뒤 금액을 비교해야 단가를 잘못 판단하지 않습니다.'],faqs:[['공급가액 10만원의 부가세는 얼마인가요?','기본 10% 기준이면 부가세는 1만원이고 합계금액은 11만원입니다.'],['11만원이 부가세 포함이면 공급가액은 얼마인가요?','11만원÷1.1=10만원이 공급가액이고 부가세는 1만원입니다.'],['포함가격에서 10%만 빼면 되나요?','아닙니다. 포함가격의 VAT는 총액×10/110으로 계산해야 합니다.'],['이 계산기의 부가세가 곧 납부할 세금인가요?','아닙니다. 이 도구는 거래금액의 VAT 구성요소를 계산하며 최종 납부세액 신고 계산기는 아닙니다.'],['모든 거래에 10%가 적용되나요?','일반과세자 기본 세율은 10%지만 영세율·면세 등 별도 법적 요건이 존재합니다. 이 도구는 해당 적용 여부를 판정하지 않습니다.'],['세율을 바꿀 수 있나요?','가능합니다. 다만 기본 10% 이외의 값은 참고 계산으로 표시합니다.'],['부가세 포함 55만원이면 공급가액은 얼마인가요?','기본 10% 기준으로 550,000÷1.1=500,000원이 공급가액이고 VAT는 50,000원입니다.'],['두 견적을 비교할 때 한쪽만 부가세 포함이면 어떻게 하나요?','두 견적 모두 포함금액 또는 공급가액 기준으로 맞춘 뒤 비교해야 합니다. 기준이 다르면 실제 가격 차이를 잘못 판단할 수 있습니다.']]},
 en:{title:'VAT Calculator',desc:'Calculate VAT and totals from net amounts, or reverse VAT-inclusive totals into net amount and tax.',back:'Business & Finance',local:'CALCULATE IN YOUR BROWSER',next:'Next work',related:'Related tools',how:'How to use',steps:['Choose Net amount or VAT-inclusive total as the calculation basis.','Confirm the default 10% rate and change it only when a reference calculation is needed.','Enter the amount to see Net Amount, VAT, and Total Amount immediately.','For VAT-inclusive totals, the tool divides by 1.1 at the default rate instead of simply subtracting 10%.','Use Reverse Tax Rate to derive the effective rate from a net amount and VAT, then copy the summary if needed.','When comparing the result with an invoice or quote, confirm that net amount and VAT are stated on the same basis.'],notes:['The default preset is 10%, matching the standard VAT rate described for general taxable businesses in the source brief.','For a VAT-inclusive total, VAT is total×10/110 at the default rate, not simply total×10%.','The VAT shown here is the tax component of a transaction and is not the final tax payable on a VAT filing.','Zero-rated/exempt eligibility, simplified-taxpayer payable amounts, and input-tax credits are not automatically determined.','A manually entered rate other than the default 10% is labeled as a reference calculation.','Use current official tax guidance and filing systems for legal filing amounts.','For price comparisons, first normalize whether each price is VAT-inclusive or VAT-exclusive before comparing unit costs.'],faqs:[['What is the VAT on a net amount of 100,000?','At the default 10% rate, VAT is 10,000 and the total is 110,000.'],['What is the net amount in a VAT-inclusive total of 110,000?','110,000÷1.1=100,000 net amount, with 10,000 VAT.'],['Can I just subtract 10% from an inclusive price?','No. At the default rate, the VAT component is total×10/110.'],['Is the VAT result the same as my final tax payable?','No. This tool calculates the VAT component of a transaction, not a final VAT filing liability.'],['Does 10% apply to every transaction?','No. Zero-rated or exempt cases can exist under separate legal conditions, which this calculator does not determine.'],['Can I change the tax rate?','Yes. Rates other than the default 10% are shown as reference calculations.'],['What is the net amount inside a VAT-inclusive total of 550,000?','At 10%, 550,000÷1.1 = 500,000 net amount and VAT is 50,000.'],['How should I compare two quotes if only one includes VAT?','Convert both to the same basis—either VAT-inclusive totals or net amounts—before comparing them.']]},
 ja:{title:'消費税計算ツール',desc:'税抜価格から消費税・税込価格を計算し、税込価格から税抜価格と税額を正確に逆算します。',back:'事業・金融',local:'ブラウザ内で計算',next:'次の作業',related:'関連ツール',how:'使い方',steps:['税抜価格基準または税込価格基準を選びます。','基本税率10%を確認し、参考計算が必要な場合だけ税率を変更します。','金額を入力すると税抜価格・消費税・税込価格がすぐ表示されます。','税込価格からの逆算では、基本10%の場合は単純に10%を引かず1.1で割ります。','必要なら税率を逆算モードで税抜価格と消費税から適用税率を確認し、結果をコピーします。','計算結果を請求書や見積書と比べるときは、税抜価格と消費税が同じ基準で表示されているか確認します。'],notes:['基本値は10%です。これは制作資料で示された一般課税事業者向けの標準VAT計算基準です。','税込価格から税額を出すときは、基本10%なら総額×10/110を使います。','このツールの消費税額は取引金額に含まれる税部分であり、最終的な納付税額とは異なります。','ゼロ税率・免税の適用判定、簡易課税の実納付額、仕入税額控除は自動判定しません。','基本10%以外の手入力税率は参考計算として表示します。','法的な申告額は最新の公式税務基準と申告システムを優先してください。','価格比較では、税込・税抜の条件を先にそろえてから単価を比べる必要があります。'],faqs:[['税抜10万円の消費税はいくらですか？','基本10%なら消費税は1万円、税込価格は11万円です。'],['11万円が税込なら税抜価格はいくらですか？','11万円÷1.1=10万円で、消費税は1万円です。'],['税込価格から10%だけ引けばよいですか？','いいえ。基本10%なら税込総額×10/110で税額を計算します。'],['表示された消費税がそのまま納付税額ですか？','いいえ。このツールは取引金額の税部分を計算するもので、最終申告の納付税額計算ではありません。'],['すべての取引に10%が適用されますか？','いいえ。ゼロ税率・免税など別の法的条件があり、このツールは適用可否を判定しません。'],['税率を変更できますか？','できます。基本10%以外の値は参考計算として表示します。'],['税込55万円なら税抜価格はいくらですか？','基本10%なら550,000÷1.1=500,000が税抜価格で、消費税は50,000です。'],['一方だけ税込の見積りはどう比較しますか？','両方を税込総額または税抜価格の同じ基準にそろえてから比較します。']]}
} as const;

export function Tool066VatCalculatorPage({locale}:{locale:Locale}){
 const t=copy[locale];
 const url=`https://toolbox.fixlgs.com/${locale}/vat-calculator`;
 const nextName=locale==='ko'?'판매가격·마진 계산기':locale==='ja'?'販売価格・マージン計算ツール':'Sales Price & Margin Calculator';
 const related=[['061',locale==='ko'?'퍼센트·증감률 계산기':locale==='ja'?'パーセント・増減率計算ツール':'Percentage & Change Calculator'],['062',locale==='ko'?'할인 가격 계산기':locale==='ja'?'割引価格計算ツール':'Discount Price Calculator'],['067',nextName]] as const;
 const jsonLd={"@context":"https://schema.org","@graph":[{"@type":"WebApplication",name:t.title,applicationCategory:'FinanceApplication',operatingSystem:'Any',url,description:t.desc,offers:{'@type':'Offer',price:'0',priceCurrency:'USD'}},{"@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:'TOOLBOX',item:`https://toolbox.fixlgs.com/${locale}`},{"@type":"ListItem",position:2,name:t.back,item:`https://toolbox.fixlgs.com/${locale}/category/business-finance`},{"@type":"ListItem",position:3,name:t.title,item:url}]},{"@type":"FAQPage",mainEntity:t.faqs.map(([q,a])=>({"@type":"Question",name:q,acceptedAnswer:{"@type":"Answer",text:a}}))}]};
 return <ToolboxSubpageShell locale={locale} appName={t.title}>
  <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(jsonLd)}}/>
  <section className={`toolbox-tool-detail-hero${locale==='en'?'':' toolbox-tool-detail-hero--single-line-description'}`}><Link className="toolbox-subpage-back" href={`/${locale}/category/business-finance`}>← {t.back}</Link><p className="toolbox-subpage-eyebrow">066 · BUSINESS & FINANCE</p><div className="toolbox-tool-detail-heading"><h1><span className="toolbox-tool-title-line">{t.title}</span></h1><p>{t.desc}</p></div><div className="toolbox-tool-detail-badge"><strong>LOCAL</strong><span>{t.local}</span></div></section>
  <section className="toolbox-tool-detail-body"><div><Tool066VatCalculator locale={locale}/><ToolNavigation locale={locale} currentTool={66} /></div></section>
  <section className="toolbox-tool-guide toolbox-tool-guide--five"><div className="toolbox-tool-guide-head"><p>HOW TO USE</p><h2>{t.how}</h2></div><ol>{t.steps.map((s,i)=><li key={s}><span>{String(i+1).padStart(2,'0')}</span><p>{s}</p></li>)}</ol></section>
  <section className="toolbox-tool-format-guide toolbox-tool-expert-post toolbox-tool-expert-post--wide-head"><div className="toolbox-tool-format-guide-head"><p>VAT FORMULA</p><h2>{locale==='ko'?'포함가격에서는 10%를 단순 차감하지 않습니다':locale==='ja'?'税込価格から単純に10%を引きません':'Do not simply subtract 10% from a VAT-inclusive total'}</h2><span>{locale==='ko'?'공급가액 기준과 포함금액 역산 공식을 분리해 같은 10%라도 계산 방향이 다름을 명확히 보여줍니다.':locale==='ja'?'税抜基準と税込総額からの逆算式を分け、同じ10%でも計算方向が異なることを明確にします。':'The calculator separates net-to-total and inclusive-total reverse formulas so the calculation direction stays explicit.'}</span></div><div className="toolbox-tool-format-body"><div className="toolbox-tool-format-grid">{(locale==='ko'?[['EXCLUDED','부가세 별도','VAT=공급가액×세율, 합계=공급가액+VAT입니다. 100,000원과 10%라면 VAT 10,000원, 합계 110,000원입니다.'],['INCLUDED','부가세 포함','공급가액=총액÷(1+세율), VAT=총액−공급가액입니다. 110,000원과 10%라면 공급가액 100,000원입니다.'],['10 / 110','포함가격의 세액','10% 포함 총액의 VAT는 총액×10/110입니다. 총액×10%로 계산하면 세액을 크게 계산하게 됩니다.'],['RATE','세율 역산','공급가액과 부가세액을 알고 있다면 세율=VAT÷공급가액×100으로 유효 세율을 확인할 수 있습니다.'],['ROUNDING','반올림','내부 계산은 가능한 정밀도를 유지하고 원화 표시층에서 기본 0자리, 최대 2자리까지 표시합니다.'],['SCOPE','납부세액과 구분','최종 납부세액은 매입세액 등 별도 요소가 포함되므로 이 페이지의 거래금액 VAT 결과와 구분해야 합니다.']]:locale==='ja'?[['EXCLUDED','税抜','消費税=税抜価格×税率、税込価格=税抜価格+消費税です。100,000と10%なら税額10,000、税込110,000です。'],['INCLUDED','税込','税抜価格=総額÷(1+税率)、消費税=総額−税抜価格です。110,000と10%なら税抜価格100,000です。'],['10 / 110','税込価格の税額','10%税込総額の税額は総額×10/110です。総額×10%ではありません。'],['RATE','税率逆算','税抜価格と消費税が分かれば、税率=消費税÷税抜価格×100で有効税率を確認できます。'],['ROUNDING','丸め表示','内部計算は精度を保持し、表示は基本0桁、最大2桁まで選択できます。'],['SCOPE','納付税額とは別','最終的な納付税額には仕入税額など別要素があるため、このページの取引VAT結果とは分けて扱います。']]:[['EXCLUDED','VAT excluded','VAT = net amount × rate; total = net amount + VAT. At 100,000 and 10%, VAT is 10,000 and total is 110,000.'],['INCLUDED','VAT included','Net amount = total ÷ (1 + rate); VAT = total − net amount. At 110,000 and 10%, net amount is 100,000.'],['10 / 110','VAT inside a total','At 10%, the VAT component of an inclusive total is total×10/110, not total×10%.'],['RATE','Reverse rate','When net amount and VAT are known, effective rate = VAT ÷ net amount × 100.'],['ROUNDING','Display rounding','Internal math keeps precision while the KRW display starts at 0 decimals and allows up to 2 decimals.'],['SCOPE','Not tax payable','Final tax payable can include input-tax and filing rules, so it must be distinguished from this transaction VAT calculation.']]).map(([k,h,p])=><article key={k}><strong>{k}</strong><h3>{h}</h3><p>{p}</p></article>)}</div></div></section>
  <section className="toolbox-tool-info-band toolbox-tool-info-band--section-start toolbox-tool-info-band--bottom-gap toolbox-tool-info-band--left-head toolbox-tool-info-band--format-head"><div className="toolbox-tool-info-band-head"><p>IMPORTANT NOTES</p><h2>{locale==='ko'?'주의사항':locale==='ja'?'注意事項':'Important notes'}</h2></div><ul className="toolbox-tool-info-band-list">{t.notes.map(n=><li key={n}>{n}</li>)}</ul></section>
  <section className="toolbox-tool-faq"><div className="toolbox-tool-guide-head"><p>FAQ</p><h2>{locale==='ko'?'자주 묻는 질문':locale==='ja'?'よくある質問':'Frequently asked questions'}</h2></div><ToolboxFaqList items={t.faqs.map(([q,a]):readonly[string,string]=>[q,a])} initialCount={5} moreLabel={locale==='ko'?'FAQ 더보기':locale==='ja'?'FAQをもっと見る':'Show more FAQs'} collapseLabel={locale==='ko'?'FAQ 접기':locale==='ja'?'FAQを閉じる':'Collapse FAQs'} className="toolbox-tool-faq-list"/></section>
 </ToolboxSubpageShell>;
}
