'use client';
import {useMemo,useState} from 'react';
import type {Locale} from '@/lib/site';
import {TOOL068_LIMITS,calculateTool068,formatTool068,parseTool068Number,requiredSaleForTarget,type Tool068Mode} from '@/lib/tool-068-seller-fee';
import styles from './tool-068-seller-fee-settlement-calculator.module.css';
const copy={
ko:{m1:'정산금',m2:'순이익',m3:'목표 순이익',sale:'판매금액',rate:'수수료율',fixed:'고정 수수료',sellerShip:'판매자 부담 배송비',other:'기타 비용',buyerShip:'고객에게 받은 배송비',cost:'상품원가',target:'목표 순이익',fee:'수수료액',settlement:'정산금',profit:'순이익',margin:'순이익률',effective:'실효 수수료율',breakdown:'비용 내역',reset:'초기화',copy:'결과 복사',copied:'복사됨',local:'입력값과 결과는 서버로 전송하지 않고 브라우저에서만 계산합니다.',invalid:'올바른 숫자를 입력하세요.',negative:'금액은 0 이상이어야 합니다.',limit:'금액은 1e15 이하로 입력하세요.',rateLimit:'수수료율은 0~100%로 입력하세요.',unavailable:'수수료율 100%에서는 목표 순이익 판매가를 역산할 수 없습니다.',notice:'플랫폼·카테고리·계약에 따라 실제 수수료 산정 기준과 VAT 포함 여부가 다를 수 있습니다. 실제 계약 요율을 입력하세요.',formula:'계산식',required:'필요 최소 판매금액'},
en:{m1:'Settlement',m2:'Net profit',m3:'Target profit',sale:'Sale Amount',rate:'Commission Rate',fixed:'Fixed Fee',sellerShip:'Seller Shipping',other:'Other Costs',buyerShip:'Buyer Shipping',cost:'Product Cost',target:'Target Profit',fee:'Commission',settlement:'Settlement',profit:'Net Profit',margin:'Net Margin',effective:'Effective Fee Rate',breakdown:'Cost breakdown',reset:'Reset',copy:'Copy result',copied:'Copied',local:'Inputs and results stay in this browser and are not sent to a server.',invalid:'Enter a valid number.',negative:'Amounts must be zero or greater.',limit:'Amounts must be no greater than 1e15.',rateLimit:'Commission rate must be 0–100%.',unavailable:'Target-price reverse calculation is unavailable at a 100% fee rate.',notice:'Fee bases, VAT treatment, categories, and contract rates vary by platform. Enter the rate from your actual seller agreement.',formula:'Formula',required:'Required Sale Amount'},
ja:{m1:'精算金',m2:'純利益',m3:'目標利益',sale:'販売金額',rate:'手数料率',fixed:'固定手数料',sellerShip:'販売者負担送料',other:'その他費用',buyerShip:'購入者負担送料',cost:'商品原価',target:'目標利益',fee:'手数料',settlement:'精算金',profit:'純利益',margin:'純利益率',effective:'実効手数料率',breakdown:'費用内訳',reset:'リセット',copy:'結果をコピー',copied:'コピー済み',local:'入力値と結果はサーバーへ送信せず、このブラウザ内だけで計算します。',invalid:'有効な数値を入力してください。',negative:'金額は0以上にしてください。',limit:'金額は1e15以下で入力してください。',rateLimit:'手数料率は0〜100%で入力してください。',unavailable:'手数料率100%では目標利益から販売金額を逆算できません。',notice:'プラットフォーム・カテゴリ・契約により手数料基準やVATの扱いは異なります。実際の契約料率を入力してください。',formula:'計算式',required:'必要最低販売金額'}} as const;
function lc(l:Locale){return l==='ko'?'ko-KR':l==='ja'?'ja-JP':'en-US'}
const defaults={sale:'100000',rate:'10',fixed:'0',sellerShipping:'3000',other:'2000',buyerShipping:'0',productCost:'50000',targetProfit:'20000'};
export function Tool068SellerFeeSettlementCalculator({locale}:{locale:Locale}){const t=copy[locale];const [mode,setMode]=useState<Tool068Mode>('settlement');const [v,setV]=useState(defaults);const [status,setStatus]=useState('');const parsed=useMemo(()=>{const vals=Object.fromEntries(Object.entries(v).map(([k,x])=>[k,parseTool068Number(x)]));if(Object.values(vals).some(x=>x===null))return{error:t.invalid,result:null,required:null};try{const base={sale:vals.sale!,rate:vals.rate!,fixedFee:vals.fixed!,sellerShipping:vals.sellerShipping!,otherCost:vals.other!,buyerShipping:vals.buyerShipping!,productCost:vals.productCost!};const result=calculateTool068(base);const required=mode==='target-profit'?requiredSaleForTarget({...base,targetProfit:vals.targetProfit!}):null;return{error:'',result,required}}catch(e){const c=e instanceof Error?e.message:'';return{error:c.includes('NEGATIVE')?t.negative:c.includes('LIMIT')&&c!=='RATE_LIMIT'?t.limit:c==='RATE_LIMIT'?t.rateLimit:c==='TARGET_UNAVAILABLE'?t.unavailable:t.invalid,result:null,required:null}}},[v,mode,t]);const result=parsed.result;const set=(k:keyof typeof v)=>(e:React.ChangeEvent<HTMLInputElement>)=>{setV(s=>({...s,[k]:e.target.value}));setStatus('')};const f=(n:number)=>formatTool068(n,lc(locale));function reset(){setMode('settlement');setV(defaults);setStatus('')}async function copyResult(){if(!result)return;const text=`${t.sale}: ${f(result.sale)} | ${t.fee}: ${f(result.totalFee)} | ${t.settlement}: ${f(result.settlement)} | ${t.profit}: ${f(result.netProfit)}`;try{await navigator.clipboard.writeText(text);setStatus(t.copied)}catch{setStatus('')}}return <div className={styles.root} data-testid="tool068-root" data-mode={mode}>
<div className={styles.localNotice}><strong>LOCAL</strong><span>{t.local}</span></div>
<div className={styles.tabs} role="tablist">{([['settlement',t.m1],['profit',t.m2],['target-profit',t.m3]] as const).map(([id,label])=><button key={id} type="button" role="tab" aria-selected={mode===id} className={`${styles.tab} ${mode===id?styles.tabActive:''}`} onClick={()=>{setMode(id);setStatus('')}} data-testid={`tool068-mode-${id}`}>{label}</button>)}</div>
<section className={styles.workspace} data-testid="tool068-workspace"><div className={styles.card}><div className={styles.inputGrid}>
<label className={styles.field}>{t.sale}<input inputMode="decimal" maxLength={TOOL068_LIMITS.maxInputChars} value={v.sale} onChange={set('sale')} data-testid="tool068-sale"/></label>
<label className={styles.field}>{t.rate} (%)<input inputMode="decimal" maxLength={TOOL068_LIMITS.maxInputChars} value={v.rate} onChange={set('rate')} data-testid="tool068-rate"/></label>
<label className={styles.field}>{t.fixed}<input inputMode="decimal" maxLength={TOOL068_LIMITS.maxInputChars} value={v.fixed} onChange={set('fixed')} data-testid="tool068-fixed-fee"/></label>
<label className={styles.field}>{t.sellerShip}<input inputMode="decimal" maxLength={TOOL068_LIMITS.maxInputChars} value={v.sellerShipping} onChange={set('sellerShipping')} data-testid="tool068-seller-shipping"/></label>
<label className={styles.field}>{t.other}<input inputMode="decimal" maxLength={TOOL068_LIMITS.maxInputChars} value={v.other} onChange={set('other')} data-testid="tool068-other-cost"/></label>
<label className={styles.field}>{t.buyerShip}<input inputMode="decimal" maxLength={TOOL068_LIMITS.maxInputChars} value={v.buyerShipping} onChange={set('buyerShipping')} data-testid="tool068-buyer-shipping"/></label>
{mode!=='settlement'&&<label className={styles.field}>{t.cost}<input inputMode="decimal" maxLength={TOOL068_LIMITS.maxInputChars} value={v.productCost} onChange={set('productCost')} data-testid="tool068-product-cost"/></label>}
{mode==='target-profit'&&<label className={styles.field}>{t.target}<input inputMode="decimal" maxLength={TOOL068_LIMITS.maxInputChars} value={v.targetProfit} onChange={set('targetProfit')} data-testid="tool068-target-profit"/></label>}
</div><div className={styles.actionRow}><button type="button" className={styles.button} onClick={reset} data-testid="tool068-reset">{t.reset}</button><button type="button" className={styles.primaryButton} disabled={!result} onClick={copyResult} data-testid="tool068-copy">{t.copy}</button></div>{parsed.error&&<p role="alert" className={styles.error} data-testid="tool068-error">{parsed.error}</p>}</div>
<section className={styles.resultCard} aria-live="polite" data-testid="tool068-result"><div className={styles.resultGrid}><div className={styles.resultItem}><span>{t.fee}</span><strong data-testid="tool068-result-fee">{result?f(result.totalFee):'—'}</strong></div><div className={styles.resultItem}><span>{t.settlement}</span><strong data-testid="tool068-result-settlement">{result?f(result.settlement):'—'}</strong></div>{mode!=='settlement'&&<div className={`${styles.resultItem} ${result&&result.netProfit<0?styles.loss:''}`}><span>{t.profit}</span><strong data-testid="tool068-result-profit">{result?f(result.netProfit):'—'}</strong></div>}{mode==='target-profit'&&<div className={styles.resultItem}><span>{t.required}</span><strong data-testid="tool068-result-required-sale">{parsed.required!==null?f(parsed.required):'—'}</strong></div>}</div>{result&&<><div className={styles.metrics}><span>{t.effective}<strong data-testid="tool068-effective-rate">{formatTool068(result.effectiveFeeRate,lc(locale))}%</strong></span>{mode!=='settlement'&&<span>{t.margin}<strong data-testid="tool068-net-margin">{formatTool068(result.netMargin,lc(locale))}%</strong></span>}</div><div className={styles.breakdown} data-testid="tool068-breakdown"><strong>{t.breakdown}</strong><ul><li>{t.sale}: +{f(result.sale)}</li>{result.buyerShipping>0&&<li>{t.buyerShip}: +{f(result.buyerShipping)}</li>}<li>{t.fee}: −{f(result.totalFee)}</li><li>{t.sellerShip}: −{f(result.sellerShipping)}</li><li>{t.other}: −{f(result.otherCost)}</li>{mode!=='settlement'&&<li>{t.cost}: −{f(result.productCost)}</li>}</ul></div><div className={styles.formula} data-testid="tool068-formula"><strong>{t.formula}</strong><code>settlement = sale + buyer shipping − commission − fixed fee − seller shipping − other costs</code>{mode!=='settlement'&&<code>net profit = settlement − product cost</code>}</div></>}</section><p className={styles.notice} data-testid="tool068-rate-notice">{t.notice}</p>{status&&<p className={styles.status}>{status}</p>}</section></div>}
