'use client';
import {useMemo,useState} from 'react';
import type {Locale} from '@/lib/site';
import {TOOL058_COOKING_REFERENCE,TOOL058_COOKING_UNITS,TOOL058_DATA_UNITS,TOOL058_DEFAULT_PRECISION,TOOL058_DEFAULTS,TOOL058_LIMITS,convertTool058Cooking,convertTool058Data,formatTool058,getTool058CookingUnit,getTool058DataSymbol,getTool058DataUnit,parseTool058Number,summarizeTool058Cooking,summarizeTool058Data,type Tool058Category,type Tool058CookingUnitId,type Tool058DataUnitId,type Tool058Notation} from '@/lib/tool-058-units';
import styles from './tool-058-data-cooking-unit-converter.module.css';

const copy={
 ko:{data:'데이터',cooking:'요리',local:'입력값과 변환 결과는 서버로 전송하거나 저장하지 않고 현재 브라우저에서만 계산합니다.',value:'입력값',from:'변환 전',to:'변환 후',swap:'단위 교환',reset:'초기화',copy:'결과 복사',copied:'복사됨',common:'대표 단위',precision:'정밀도',advanced:'표시 설정',empty:'변환할 숫자를 입력하세요.',invalid:'올바른 숫자를 입력하세요.',negative:'데이터 용량과 요리 계량값은 0 이상으로 입력하세요.',limit:`입력값은 ${TOOL058_LIMITS.maxAbsInput.toExponential(0)} 이하로 입력하세요.`,result:'변환 결과',quick:'빠른 단위',notation:'계산 기준',decimal:'1000 기준',binary:'1024 기준',decimalHelp:'SI decimal 기준: KB=1000B, MB=1000²B, GB=1000³B.',binaryHelp:'Binary 기준: KiB=1024B, MiB=1024²B, GiB=1024³B. 선택한 KB/MB/GB/TB 입력을 이 기준으로 해석합니다.',cookingRef:'요리 기준',cookingHelp:'FDA nutrition-labeling reference: 1 cup=240mL, 1 tbsp=15mL, 1 tsp=5mL. 지역별 레시피 기준과 다를 수 있습니다.',dataCase:'bit(b)와 byte(B)는 8배 차이가 있습니다.',iec:'IEC 표기'},
 en:{data:'Data',cooking:'Cooking',local:'Values and conversion results are calculated only in this browser and are not sent to or stored on a server.',value:'Value',from:'From',to:'To',swap:'Swap units',reset:'Reset',copy:'Copy result',copied:'Copied',common:'Common Units',precision:'Precision',advanced:'Display settings',empty:'Enter a number to convert.',invalid:'Enter a valid number.',negative:'Data sizes and cooking measures must be zero or greater.',limit:`Enter a value no greater than ${TOOL058_LIMITS.maxAbsInput.toExponential(0)}.`,result:'Conversion result',quick:'Quick units',notation:'Calculation basis',decimal:'Decimal 1000',binary:'Binary 1024',decimalHelp:'SI decimal basis: KB=1000B, MB=1000²B, GB=1000³B.',binaryHelp:'Binary basis: KiB=1024B, MiB=1024²B, GiB=1024³B. KB/MB/GB/TB selections are interpreted using this basis.',cookingRef:'Cooking reference',cookingHelp:'FDA nutrition-labeling reference: 1 cup=240mL, 1 tbsp=15mL, 1 tsp=5mL. Regional recipe measures may differ.',dataCase:'bit (b) and byte (B) differ by a factor of 8.',iec:'IEC notation'},
 ja:{data:'データ',cooking:'料理',local:'入力値と変換結果はサーバーに送信・保存せず、このブラウザ内だけで計算します。',value:'値',from:'変換前',to:'変換後',swap:'単位を入れ替え',reset:'リセット',copy:'結果をコピー',copied:'コピー済み',common:'代表単位',precision:'精度',advanced:'表示設定',empty:'変換する数値を入力してください。',invalid:'有効な数値を入力してください。',negative:'データ容量と料理の計量値は0以上で入力してください。',limit:`入力値は${TOOL058_LIMITS.maxAbsInput.toExponential(0)}以下にしてください。`,result:'変換結果',quick:'クイック単位',notation:'計算基準',decimal:'1000 基準',binary:'1024 基準',decimalHelp:'SI decimal基準: KB=1000B、MB=1000²B、GB=1000³B。',binaryHelp:'Binary基準: KiB=1024B、MiB=1024²B、GiB=1024³B。KB/MB/GB/TBの選択はこの基準で解釈します。',cookingRef:'料理基準',cookingHelp:'FDA nutrition-labeling reference: 1 cup=240mL、1 tbsp=15mL、1 tsp=5mL。地域別レシピの基準とは異なる場合があります。',dataCase:'bit（b）とbyte（B）は8倍異なります。',iec:'IEC表記'}
} as const;
function errorMessage(code:string,t:(typeof copy)[Locale]){return code==='NEGATIVE_VALUE'?t.negative:code==='VALUE_LIMIT'?t.limit:t.invalid}

export function Tool058DataCookingUnitConverter({locale}:{locale:Locale}){
 const t=copy[locale];
 const [category,setCategory]=useState<Tool058Category>('data');
 const [notation,setNotation]=useState<Tool058Notation>('decimal');
 const [raw,setRaw]=useState('1');
 const [dataFrom,setDataFrom]=useState<Tool058DataUnitId>(TOOL058_DEFAULTS.data.from);
 const [dataTo,setDataTo]=useState<Tool058DataUnitId>(TOOL058_DEFAULTS.data.to);
 const [cookingFrom,setCookingFrom]=useState<Tool058CookingUnitId>(TOOL058_DEFAULTS.cooking.from);
 const [cookingTo,setCookingTo]=useState<Tool058CookingUnitId>(TOOL058_DEFAULTS.cooking.to);
 const [precision,setPrecision]=useState(TOOL058_DEFAULT_PRECISION);
 const [status,setStatus]=useState('');
 const parsed=parseTool058Number(raw);let error='';let result:number|null=null;
 if(raw.trim()==='')error=t.empty;else if(parsed===null)error=t.invalid;else{try{result=category==='data'?convertTool058Data(parsed,notation,dataFrom,dataTo):convertTool058Cooking(parsed,cookingFrom,cookingTo)}catch(e){error=errorMessage(e instanceof Error?e.message:'',t)}}
 const dataSummary=useMemo(()=>{if(category!=='data'||parsed===null||parsed<0||Math.abs(parsed)>TOOL058_LIMITS.maxAbsInput)return[];try{return summarizeTool058Data(parsed,notation,dataFrom)}catch{return[]}},[category,parsed,notation,dataFrom]);
 const cookingSummary=useMemo(()=>{if(category!=='cooking'||parsed===null||parsed<0||Math.abs(parsed)>TOOL058_LIMITS.maxAbsInput)return[];try{return summarizeTool058Cooking(parsed,cookingFrom)}catch{return[]}},[category,parsed,cookingFrom]);
 function switchCategory(next:Tool058Category){setCategory(next);setRaw('1');setStatus('')}
 function swap(){if(category==='data'){setDataFrom(dataTo);setDataTo(dataFrom)}else{setCookingFrom(cookingTo);setCookingTo(cookingFrom)}setStatus('')}
 function reset(){setCategory('data');setNotation('decimal');setRaw('1');setDataFrom(TOOL058_DEFAULTS.data.from);setDataTo(TOOL058_DEFAULTS.data.to);setCookingFrom(TOOL058_DEFAULTS.cooking.from);setCookingTo(TOOL058_DEFAULTS.cooking.to);setPrecision(TOOL058_DEFAULT_PRECISION);setStatus('')}
 async function copyResult(){if(result===null)return;const fromSymbol=category==='data'?getTool058DataSymbol(dataFrom,notation):getTool058CookingUnit(cookingFrom).symbol;const toSymbol=category==='data'?getTool058DataSymbol(dataTo,notation):getTool058CookingUnit(cookingTo).symbol;const basis=category==='data'?` · ${notation==='decimal'?t.decimal:t.binary}`:` · ${t.cookingRef}`;try{await navigator.clipboard.writeText(`${raw} ${fromSymbol} = ${formatTool058(result,precision)} ${toSymbol}${basis}`);setStatus(t.copied)}catch{setStatus('')}}
 const fromSymbol=category==='data'?getTool058DataSymbol(dataFrom,notation):getTool058CookingUnit(cookingFrom).symbol;
 const toSymbol=category==='data'?getTool058DataSymbol(dataTo,notation):getTool058CookingUnit(cookingTo).symbol;
 return <div className={styles.root} data-testid="tool058-root" data-category={category} data-notation={notation}>
  <div className={styles.localNotice}><strong>LOCAL</strong><span>{t.local}</span></div>
  <div className={styles.tabs} role="tablist" aria-label="category">{(['data','cooking'] as Tool058Category[]).map(c=><button key={c} type="button" role="tab" aria-selected={category===c} className={`${styles.tab} ${category===c?styles.tabActive:''}`} onClick={()=>switchCategory(c)} data-testid={`tool058-tab-${c}`}>{t[c]}</button>)}</div>
  <section className={styles.workspace} data-testid="tool058-workspace">
   <div className={styles.card}>
    {category==='data'?<div className={styles.basisBlock}><p className={styles.summaryTitle}>{t.notation}</p><div className={styles.notation} role="group" aria-label={t.notation}>{(['decimal','binary'] as Tool058Notation[]).map(n=><button key={n} type="button" aria-pressed={notation===n} className={`${styles.notationButton} ${notation===n?styles.notationActive:''}`} onClick={()=>{setNotation(n);setStatus('')}} data-testid={`tool058-notation-${n}`}>{n==='decimal'?t.decimal:t.binary}</button>)}</div><p className={styles.info}>{notation==='decimal'?t.decimalHelp:t.binaryHelp}</p></div>:<div className={styles.reference}><strong>{t.cookingRef}</strong><span>240 / 15 / 5 mL</span></div>}
    <div className={styles.inputGrid}>
     <label className={`${styles.field} ${styles.valueField}`}>{t.value}<input inputMode="decimal" value={raw} onChange={e=>{setRaw(e.target.value);setStatus('')}} aria-invalid={Boolean(error)} data-testid="tool058-value"/></label>
     {category==='data'?<label className={styles.field}>{t.from}<select value={dataFrom} onChange={e=>{setDataFrom(e.target.value as Tool058DataUnitId);setStatus('')}} data-testid="tool058-from">{TOOL058_DATA_UNITS.map(u=><option key={u.id} value={u.id}>{u.names[locale]} ({getTool058DataSymbol(u.id,notation)})</option>)}</select></label>:<label className={styles.field}>{t.from}<select value={cookingFrom} onChange={e=>{setCookingFrom(e.target.value as Tool058CookingUnitId);setStatus('')}} data-testid="tool058-from">{TOOL058_COOKING_UNITS.map(u=><option key={u.id} value={u.id}>{u.names[locale]} ({u.symbol})</option>)}</select></label>}
     <button type="button" className={styles.swap} onClick={swap} aria-label={t.swap} title={t.swap} data-testid="tool058-swap">⇄</button>
     {category==='data'?<label className={styles.field}>{t.to}<select value={dataTo} onChange={e=>{setDataTo(e.target.value as Tool058DataUnitId);setStatus('')}} data-testid="tool058-to">{TOOL058_DATA_UNITS.map(u=><option key={u.id} value={u.id}>{u.names[locale]} ({getTool058DataSymbol(u.id,notation)})</option>)}</select></label>:<label className={styles.field}>{t.to}<select value={cookingTo} onChange={e=>{setCookingTo(e.target.value as Tool058CookingUnitId);setStatus('')}} data-testid="tool058-to">{TOOL058_COOKING_UNITS.map(u=><option key={u.id} value={u.id}>{u.names[locale]} ({u.symbol})</option>)}</select></label>}
    </div>
    <div><p className={styles.summaryTitle}>{t.quick}</p><div className={styles.quickRow}>{category==='data'?TOOL058_DEFAULTS.data.summary.map(id=><button type="button" key={id} className={`${styles.preset} ${dataTo===id?styles.presetActive:''}`} onClick={()=>setDataTo(id)}>{getTool058DataSymbol(id,notation)}</button>):TOOL058_DEFAULTS.cooking.summary.map(id=><button type="button" key={id} className={`${styles.preset} ${cookingTo===id?styles.presetActive:''}`} onClick={()=>setCookingTo(id)}>{getTool058CookingUnit(id).symbol}</button>)}</div></div>
    <p className={styles.info}>{category==='data'?t.dataCase:t.cookingHelp}</p>
    <div className={styles.actionRow}><button type="button" className={styles.button} onClick={reset} data-testid="tool058-reset">{t.reset}</button><button type="button" className={styles.primaryButton} onClick={copyResult} disabled={result===null} data-testid="tool058-copy">{t.copy}</button></div>
    {error&&<p className={styles.error} role="alert" data-testid="tool058-error">{error}</p>}
   </div>
   <details className={styles.advanced}><summary>{t.advanced} · {t.precision}</summary><div className={styles.precisionRow}><input aria-label={t.precision} type="range" min="0" max={TOOL058_LIMITS.maxPrecision} value={precision} onChange={e=>setPrecision(Number(e.target.value))} data-testid="tool058-precision"/><span className={styles.precisionValue}>{precision}</span></div></details>
   <section className={styles.resultCard} aria-live="polite" data-testid="tool058-result"><div className={styles.resultHead}><p className={styles.resultLabel}>RESULT · {t.result}</p><span className={styles.basisTag}>{category==='data'?(notation==='decimal'?t.decimal:t.binary):'FDA 240/15/5 mL'}</span></div>{result===null?<p className={styles.hint}>{error||t.empty}</p>:<><p className={styles.resultValue} data-testid="tool058-main-result">{formatTool058(result,precision)}<span>{toSymbol}</span></p><p className={styles.equation}>{formatTool058(parsed!,precision)} {fromSymbol} → {toSymbol}</p><p className={styles.summaryTitle}>{t.common}</p><div className={styles.summaryGrid} data-testid="tool058-summary">{(category==='data'?dataSummary:cookingSummary).map(({unit,value,symbol})=><div className={styles.summaryItem} key={unit.id} data-unit={unit.id}><strong>{formatTool058(value,precision)}</strong><span>{unit.names[locale]} · {symbol}</span></div>)}</div>{category==='data'&&notation==='binary'&&<p className={styles.iecNote}>{t.iec}: KiB · MiB · GiB · TiB</p>}</>}{status&&<p className={styles.status} role="status">{status}</p>}</section>
  </section>
 </div>
}
