"use client";
import {useEffect,useState} from 'react';
import type {Locale} from '@/lib/site';
import {TOOL050_LIMITS,addBusinessDays,calculateBusinessRange,holidayCoverage,normalizeCustomDates,type Tool050Country,type Tool050Direction} from '@/lib/tool-050-business-day';
import styles from './tool-050-business-day-calculator.module.css';

type Mode='between'|'target';
const copy={
 ko:{between:'두 날짜 사이',target:'N 영업일 후·전',local:'선택한 날짜와 사용자 지정 휴일은 서버로 전송하거나 저장하지 않고 현재 브라우저에서만 계산합니다.',country:'국가·지역',kr:'한국',us:'미국',jp:'일본',start:'시작일',end:'종료일',base:'기준일',count:'영업일 수',direction:'방향',after:'후',before:'전',exclude:'공휴일 제외',include:'공휴일 포함',calculate:'계산',reset:'초기화',today:'오늘',copy:'결과 복사',copied:'복사됨',business:'영업일',calendar:'총 달력일',weekend:'제외 주말',holiday:'제외 공휴일',resultDate:'목표 날짜',details:'제외된 공휴일',advanced:'사용자 지정 공휴일',addHoliday:'추가',customHint:`최대 ${TOOL050_LIMITS.maxCustomHolidays}개`,empty:'날짜와 입력값을 확인하세요.',reversed:'종료일은 시작일보다 빠를 수 없습니다.',range:`계산 범위는 최대 ${TOOL050_LIMITS.maxRangeYears}년입니다.`,invalidCount:'영업일 수는 0 이상의 정수로 입력하세요.',coverage:(a:number,b:number)=>`내장 공휴일 데이터: ${a}~${b}년. 이 범위 밖에서는 주말과 사용자 지정 휴일만 반영될 수 있습니다.`,summary:(n:number)=>`${n} 영업일`,zero:'0 영업일이면 기준일 자체를 반환합니다.',weekday:['일','월','화','수','목','금','토']},
 en:{between:'Between Dates',target:'Add Business Days',local:'Selected dates and custom holidays are calculated only in this browser and are not sent to or stored on a server.',country:'Country / Region',kr:'Korea',us:'United States',jp:'Japan',start:'Start Date',end:'End Date',base:'Base Date',count:'Business Days',direction:'Direction',after:'After',before:'Before',exclude:'Exclude holidays',include:'Include holidays',calculate:'Calculate',reset:'Reset',today:'Today',copy:'Copy result',copied:'Copied',business:'Business days',calendar:'Calendar days',weekend:'Weekends excluded',holiday:'Holidays excluded',resultDate:'Target Date',details:'Excluded holidays',advanced:'Custom holidays',addHoliday:'Add',customHint:`Up to ${TOOL050_LIMITS.maxCustomHolidays}`,empty:'Check the dates and inputs.',reversed:'End date cannot be earlier than start date.',range:`Maximum calculation span is ${TOOL050_LIMITS.maxRangeYears} years.`,invalidCount:'Business days must be a non-negative whole number.',coverage:(a:number,b:number)=>`Built-in holiday data: ${a}–${b}. Outside this range, only weekends and custom holidays may be reflected.`,summary:(n:number)=>`${n} business days`,zero:'Zero business days returns the base date itself.',weekday:['Sun','Mon','Tue','Wed','Thu','Fri','Sat']},
 ja:{between:'2つの日付の間',target:'N営業日後・前',local:'選択した日付とユーザー指定休日はサーバーへ送信・保存せず、このブラウザ内だけで計算します。',country:'国・地域',kr:'韓国',us:'米国',jp:'日本',start:'開始日',end:'終了日',base:'基準日',count:'営業日数',direction:'方向',after:'後',before:'前',exclude:'祝日を除外',include:'祝日を含む',calculate:'計算',reset:'リセット',today:'今日',copy:'結果をコピー',copied:'コピー済み',business:'営業日数',calendar:'総暦日数',weekend:'除外した土日',holiday:'除外した祝日',resultDate:'目標日',details:'除外した祝日',advanced:'ユーザー指定休日',addHoliday:'追加',customHint:`最大${TOOL050_LIMITS.maxCustomHolidays}件`,empty:'日付と入力値を確認してください。',reversed:'終了日は開始日より前にできません。',range:`計算範囲は最大${TOOL050_LIMITS.maxRangeYears}年です。`,invalidCount:'営業日数は0以上の整数で入力してください。',coverage:(a:number,b:number)=>`内蔵祝日データ: ${a}〜${b}年。この範囲外では土日とユーザー指定休日のみ反映される場合があります。`,summary:(n:number)=>`${n}営業日`,zero:'0営業日は基準日そのものを返します。',weekday:['日','月','火','水','木','金','土']}
} satisfies Record<Locale,any>;
function todayISO(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function weekdayIndex(v:string){return new Date(`${v}T00:00:00Z`).getUTCDay()}
export function Tool050BusinessDayCalculator({locale}:{locale:Locale}){
 const t=copy[locale]; const [today,setToday]=useState(''); const [mode,setMode]=useState<Mode>('between'); const [country,setCountry]=useState<Tool050Country>('KR'); const [start,setStart]=useState(''); const [end,setEnd]=useState(''); const [base,setBase]=useState(''); const [count,setCount]=useState('5'); const [direction,setDirection]=useState<Tool050Direction>('after'); const [excludeHolidays,setExcludeHolidays]=useState(true); const [customInput,setCustomInput]=useState(''); const [custom,setCustom]=useState<string[]>([]); const [result,setResult]=useState<any>(null); const [error,setError]=useState(''); const [status,setStatus]=useState('');
 const coverage=holidayCoverage(country);
 useEffect(()=>{const now=todayISO();setToday(now);setStart(now);setEnd(now);setBase(now)},[]);
 function changeMode(next:Mode){setMode(next);setResult(null);setError('');setStatus('')}
 function runWith(nextCountry:Tool050Country=country,nextExclude:boolean=excludeHolidays){setError('');setStatus('');try{const normalized=normalizeCustomDates(custom);if(mode==='between')setResult({kind:'between',...calculateBusinessRange(start,end,nextCountry,nextExclude,normalized)});else{const n=Number(count);if(!Number.isInteger(n)||n<0)throw new Error('COUNT');const date=addBusinessDays(base,n,direction,nextCountry,nextExclude,normalized);setResult({kind:'target',date,count:n});}}catch(e:any){setResult(null);if(e instanceof RangeError)setError(t.range);else if(e?.message==='REVERSED')setError(t.reversed);else if(e?.message==='COUNT'||e?.message==='INVALID_COUNT')setError(t.invalidCount);else setError(t.empty)}}
 function run(){runWith()}
 function reset(){setMode('between');setCountry('KR');setStart(today);setEnd(today);setBase(today);setCount('5');setDirection('after');setExcludeHolidays(true);setCustomInput('');setCustom([]);setResult(null);setError('');setStatus('')}
 function addCustom(){if(!customInput)return;try{const next=normalizeCustomDates([...custom,customInput]);setCustom(next);setCustomInput('');setResult(null);setError('')}catch{setError(t.empty)}}
 async function copyResult(){if(!result)return;const text=result.kind==='between'?`${result.businessDays} ${t.business} · ${result.calendarDays} ${t.calendar} · ${country}`:`${result.date} (${t.weekday[weekdayIndex(result.date)]}) · ${result.count} ${t.business} · ${country}`;await navigator.clipboard.writeText(text);setStatus(t.copied)}
 return <div className={styles.root} data-testid="tool050-root">
  <div className={styles.localNotice}><strong>LOCAL</strong><span>{t.local}</span></div>
  <div className={styles.modeRow} role="tablist" aria-label={t.calculate}><button type="button" role="tab" aria-selected={mode==='between'} className={`${styles.modeButton} ${mode==='between'?styles.modeButtonActive:''}`} onClick={()=>changeMode('between')} data-testid="tool050-mode-between">{t.between}</button><button type="button" role="tab" aria-selected={mode==='target'} className={`${styles.modeButton} ${mode==='target'?styles.modeButtonActive:''}`} onClick={()=>changeMode('target')} data-testid="tool050-mode-target">{t.target}</button></div>
  <section className={styles.workspace} data-testid="tool050-workspace">
   <div className={styles.card}>
    <div className={styles.inputGrid}><label className={styles.field}>{t.country}<select value={country} onChange={e=>{const next=e.target.value as Tool050Country;setCountry(next);if(result)runWith(next,excludeHolidays)}} data-testid="tool050-country"><option value="KR">{t.kr}</option><option value="US">{t.us}</option><option value="JP">{t.jp}</option></select></label>{mode==='between'?<><label className={styles.field}>{t.start}<input type="date" value={start} onChange={e=>setStart(e.target.value)} data-testid="tool050-start"/></label><label className={styles.field}>{t.end}<input type="date" value={end} onChange={e=>setEnd(e.target.value)} data-testid="tool050-end"/></label></>:<><label className={styles.field}>{t.base}<input type="date" value={base} onChange={e=>setBase(e.target.value)} data-testid="tool050-base"/></label><label className={styles.field}>{t.count}<input type="number" min="0" step="1" value={count} onChange={e=>setCount(e.target.value)} data-testid="tool050-count"/></label><label className={styles.field}>{t.direction}<select value={direction} onChange={e=>setDirection(e.target.value as Tool050Direction)} data-testid="tool050-direction"><option value="after">{t.after}</option><option value="before">{t.before}</option></select></label></>}</div>
    <div className={styles.optionRow}><label className={styles.check}><input type="checkbox" checked={excludeHolidays} onChange={e=>{const next=e.target.checked;setExcludeHolidays(next);if(result)runWith(country,next)}} data-testid="tool050-exclude-holidays"/>{excludeHolidays?t.exclude:t.include}</label><button type="button" className={styles.button} onClick={()=>{if(mode==='between'){setStart(today);setEnd(today)}else setBase(today)}}>{t.today}</button></div>
    {mode==='target'&&<div className={styles.presets}>{[5,10,20].map(n=><button className={styles.preset} type="button" key={n} onClick={()=>setCount(String(n))}>{n} {t.business}</button>)}</div>}
    <p className={styles.coverage} data-testid="tool050-coverage">{t.coverage(coverage.min,coverage.max)}</p>
    <div className={styles.actionRow}><button type="button" className={styles.button} onClick={reset} data-testid="tool050-reset">{t.reset}</button><button type="button" className={styles.primaryButton} onClick={run} data-testid="tool050-calculate">{t.calculate}</button></div>{error&&<p className={styles.error} role="alert" data-testid="tool050-error">{error}</p>}
   </div>
   <details className={styles.advanced}><summary>{t.advanced} · {t.customHint}</summary><div className={styles.customRow}><input type="date" value={customInput} onChange={e=>setCustomInput(e.target.value)} data-testid="tool050-custom-input"/><button type="button" className={styles.button} onClick={addCustom} data-testid="tool050-custom-add">{t.addHoliday}</button></div><div className={styles.customTags}>{custom.map(d=><span className={styles.tag} key={d}>{d}<button type="button" aria-label={`${d} remove`} onClick={()=>setCustom(custom.filter(x=>x!==d))}>×</button></span>)}</div></details>
   <section className={styles.resultCard} aria-live="polite" data-testid="tool050-result"><div className={styles.resultHead}><p className={styles.resultLabel}>RESULT</p>{result&&<button type="button" className={styles.button} onClick={copyResult} data-testid="tool050-copy">{t.copy}</button>}</div>{!result?<p className={styles.hint}>{mode==='target'?t.zero:t.empty}</p>:result.kind==='between'?<><p className={styles.resultValue} data-testid="tool050-business-days">{result.businessDays}</p><p className={styles.hint}>{t.summary(result.businessDays)}</p><div className={styles.summaryGrid}><div className={styles.summaryItem}><strong>{result.calendarDays}</strong><span>{t.calendar}</span></div><div className={styles.summaryItem}><strong>{result.weekendDays}</strong><span>{t.weekend}</span></div><div className={styles.summaryItem}><strong>{result.holidayDays}</strong><span>{t.holiday}</span></div></div>{result.excludedHolidays.length>0&&<details><summary>{t.details} ({result.excludedHolidays.length})</summary><ul className={styles.holidayList} data-testid="tool050-holiday-list">{result.excludedHolidays.map((h:any)=><li key={h.date}><strong>{h.date}</strong><span>{h.name[locale]}</span></li>)}</ul></details>}</>:<><p className={styles.resultDate} data-testid="tool050-target-date">{result.date}</p><p className={styles.hint}>{t.weekday[weekdayIndex(result.date)]} · {direction==='after'?t.after:t.before} · {t.summary(result.count)}</p></>}{status&&<p className={styles.status} role="status">{status}</p>}</section>
  </section>
 </div>
}
