import Link from 'next/link';
import type {Locale} from '@/lib/site';
import {Tool087MasonryQuantity} from '@/components/tool-087-masonry-quantity';
import {ToolboxFaqList} from '@/components/toolbox-faq-list';
import {ToolboxSubpageShell} from '@/components/toolbox-subpage-shell';

const copy={
 ko:{title:'벽돌·블록 수량 계산기',desc:'벽 길이와 높이, 벽돌·블록 규격, 줄눈, 손실률을 입력해 필요한 수량과 구매 권장 개수를 계산합니다.',back:'부동산·건축 계산기',local:'브라우저에서 바로 계산',how:'사용 방법',steps:['벽 길이와 높이를 m 단위로 입력합니다.','벽돌·블록의 길이와 높이를 mm 단위로 입력합니다.','기본 줄눈 폭을 입력합니다. 필요한 경우 고급 입력에서 가로·세로 줄눈을 따로 입력할 수 있습니다.','현장 상황에 맞는 손실률을 입력합니다. 단가를 입력하면 구매 권장 개수 기준 예상 비용도 계산됩니다.','벽 면적, 모듈 크기, 손실 전 수량, 손실 적용 수량, 올림한 구매 권장 개수를 확인합니다.','실제 시공 전에는 문·창문 등 개구부, 코너, 절단, 배치 방식과 구조·법정 기준을 별도로 확인합니다.'],notes:['계산은 벽 면적을 자재와 줄눈을 합한 반복 모듈 면적으로 나누는 단순 reference 방식입니다.','마지막 행·열의 실제 줄눈 형상이나 자재 절단 배치는 자동 최적화하지 않습니다.','문·창문 등 개구부와 코너, L/T자 벽은 1차 계산 범위에서 제외됩니다.','손실률은 사용자가 직접 입력하는 참고값이며 실제 현장 손실을 보장하지 않습니다.','구조안전, 철근, 몰탈량, 시공법, 법정 기준은 자동 판정하지 않습니다.','단가 기반 예상 비용은 입력한 통화와 가격을 그대로 사용한 참고값입니다.'],faqs:[['벽돌 수량은 어떻게 계산하나요?','벽 면적을 벽돌과 줄눈을 포함한 반복 모듈 면적으로 나눈 뒤 손실률을 적용하고 올림합니다.'],['190×57mm 벽돌과 10mm 줄눈이면 모듈 크기는 얼마인가요?','가로·세로 줄눈을 모두 10mm로 쓰면 반복 모듈은 200×67mm입니다.'],['5m×2.4m 벽에는 몇 개가 필요한가요?','190×57mm 자재와 10mm 줄눈, 손실률 5% 기준으로 약 941개를 구매 권장 수량으로 계산합니다.'],['줄눈을 0으로 넣어도 되나요?','가능합니다. 0은 무줄눈 reference로 계산합니다.'],['문이나 창문 면적을 뺄 수 있나요?','1차 버전에서는 개구부 자동 차감 기능을 제공하지 않습니다. 실제 현장에서는 개구부와 코너를 별도로 검토하세요.'],['손실률은 몇 %를 넣어야 하나요?','도구는 특정 손실률을 권장하지 않습니다. 현장 조건과 자재 특성에 맞는 값을 사용자가 직접 입력합니다.'],['벽돌과 블록 모두 사용할 수 있나요?','가능합니다. 자재 길이와 높이를 직접 입력하므로 직사각형 반복 모듈로 볼 수 있는 벽돌·블록에 사용할 수 있습니다.'],['예상 비용은 어떻게 계산하나요?','올림한 구매 권장 개수에 사용자가 입력한 개당 단가를 곱합니다.']]},
 en:{title:'Brick & Block Quantity Calculator',desc:'Enter wall dimensions, brick or block size, mortar joint, and waste rate to estimate quantity and recommended purchase count.',back:'Real Estate & Build',local:'CALCULATE IN YOUR BROWSER',how:'How to use',steps:['Enter wall length and height in meters.','Enter brick or block width and height in millimeters.','Enter the default mortar joint. Use advanced input if horizontal and vertical joints differ.','Enter a waste rate for your reference. Add unit price to estimate purchase cost.','Review wall area, module size, raw quantity, waste-adjusted quantity, and the rounded recommended purchase count.','Before construction, separately verify openings, corners, cuts, layout, structural safety, and legal requirements.'],notes:['The calculator uses a simple reference model: wall area divided by the repeating material-plus-joint module area.','It does not optimize the actual last row or column, cuts, or on-site laying pattern.','Doors, windows, corners, and L/T-shaped walls are outside the first-version scope.','Waste rate is a user-entered reference and does not guarantee real-site waste.','Structural safety, reinforcement, mortar quantity, construction method, and legal requirements are not determined.','Estimated cost uses the entered unit price and currency as-is.'],faqs:[['How is brick quantity calculated?','Wall area is divided by the repeating brick-plus-joint module area, then the waste rate is applied and the result is rounded up.'],['What is the module size for a 190×57 mm brick with a 10 mm joint?','With 10 mm joints in both directions, the repeating module is 200×67 mm.'],['How many bricks for a 5 m × 2.4 m wall?','Using 190×57 mm material, a 10 mm joint, and 5% waste gives a recommended purchase count of about 941.'],['Can the joint be zero?','Yes. Zero is treated as a no-joint reference.'],['Can I subtract doors or windows?','Automatic opening deduction is not included in the first version. Review openings and corners separately for the actual job.'],['What waste rate should I use?','The tool does not prescribe a rate. Enter a value suitable for the material and site conditions.'],['Can I use it for both bricks and blocks?','Yes, when the material can be represented as a rectangular repeating module using the entered width and height.'],['How is estimated cost calculated?','Recommended purchase quantity is multiplied by the unit price you enter.']]},
 ja:{title:'レンガ・ブロック数量計算ツール',desc:'壁の長さ・高さ、レンガやブロックの寸法、目地幅、ロス率を入力して必要数量と推奨購入個数を計算します。',back:'不動産・建築',local:'ブラウザ内で計算',how:'使い方',steps:['壁の長さと高さをm単位で入力します。','レンガ・ブロックの長さと高さをmm単位で入力します。','基本の目地幅を入力します。横目地と縦目地が異なる場合は詳細入力で分けて指定できます。','参考ロス率を入力します。単価を入力すると推奨購入個数を基準に予想費用も計算します。','壁面積、モジュールサイズ、ロス前数量、ロス適用数量、切り上げた推奨購入個数を確認します。','施工前には開口部、コーナー、切断、積み方、構造安全、法的基準を別途確認してください。'],notes:['壁面積を材料と目地を含む反復モジュール面積で割る単純な参考計算です。','最終行・列の実際の目地形状や切断・配置は自動最適化しません。','ドア・窓などの開口部、コーナー、L/T字壁は初期版の範囲外です。','ロス率は利用者が入力する参考値であり、実際の現場ロスを保証しません。','構造安全、鉄筋、モルタル量、施工方法、法的基準は自動判定しません。','予想費用は入力した単価と通貨をそのまま使う参考値です。'],faqs:[['レンガ数量はどう計算しますか？','壁面積をレンガと目地を含む反復モジュール面積で割り、ロス率を適用して切り上げます。'],['190×57mmのレンガと10mm目地のモジュールは？','横・縦とも10mmなら反復モジュールは200×67mmです。'],['5m×2.4mの壁には何個必要ですか？','190×57mm、10mm目地、ロス率5%の場合、推奨購入個数は約941個です。'],['目地を0にできますか？','可能です。0は目地なしのreferenceとして計算します。'],['ドアや窓の面積を引けますか？','初期版では開口部の自動控除は含みません。実際の施工では開口部やコーナーを別途確認してください。'],['ロス率は何%にすべきですか？','ツールは特定の率を推奨しません。材料と現場条件に合う値を利用者が入力します。'],['レンガとブロックの両方に使えますか？','入力した長さと高さで長方形の反復モジュールとして扱える材料なら使用できます。'],['予想費用はどう計算しますか？','切り上げた推奨購入個数に入力した1個単価を掛けます。']]}
} as const;
const expert={
 ko:[['MODULE','줄눈까지 포함한 반복 모듈','190×57mm 벽돌에 10mm 줄눈을 적용하면 계산 모듈은 200×67mm입니다. 실제 마지막 행과 열의 줄눈 모양까지 재현하는 값은 아닙니다.'],['EXAMPLE','5m×2.4m 벽 예시','벽 면적 12㎡를 200×67mm 모듈로 나누면 손실 전 약 895.52개입니다. 손실률 5%를 적용하면 약 940.30개이고 구매 수량은 941개로 올림합니다.'],['WASTE','손실률과 올림','파손·절단·현장 여유를 하나의 손실률로 반영합니다. 손실률 적용 후 소수점 수량은 실제 구매 단위를 위해 올림합니다.'],['COST','개당 단가로 예상비용 계산','예를 들어 941개와 개당 500원을 입력하면 예상 비용은 470,500원입니다. 운송비·몰탈·인건비 등은 포함하지 않습니다.'],['JOINT','줄눈 1mm 차이도 반복되면 누적','벽돌 한 개에서는 작은 차이지만 벽 전체에서는 모듈 수가 반복됩니다. 실제 시공 줄눈 기준이 정해져 있다면 기본값 대신 그 값을 넣어 수량을 다시 비교하세요.'],['CHECK','구매 전 한 묶음 규격과 파손 여유 확인','계산 결과는 개수 기준입니다. 실제 주문은 팔레트·묶음 단위일 수 있으므로 판매 포장단위로 다시 올림하고, 운송 중 파손이나 현장 절단 여유를 손실률에 반영했는지 확인합니다.']],
 en:[['MODULE','Include the mortar joint in the repeating module','A 190×57 mm brick with 10 mm joints becomes a 200×67 mm calculation module. This does not reproduce the exact last-row or last-column joint layout.'],['EXAMPLE','5 m × 2.4 m wall example','A 12 m² wall divided by a 200×67 mm module gives about 895.52 pieces before waste. With 5% waste it becomes about 940.30, rounded up to 941 for purchase.'],['WASTE','Waste rate and rounding','Breakage, cutting, and site allowance are represented by one waste-rate input. The waste-adjusted decimal quantity is rounded up to a whole purchase unit.'],['COST','Estimate cost from unit price','For example, 941 pieces at 500 per piece gives an estimated cost of 470,500 in the entered currency. Delivery, mortar, and labor are not included.'],['JOINT','Small joint changes accumulate','A 1 mm change is small for one brick, but the module repeats across the wall. If the actual joint specification is known, enter it and compare the resulting count rather than relying on a default.'],['CHECK','Check package units and breakage allowance','The calculator returns pieces. Real orders may use pallet or bundle units, so round again to the supplier package and verify that cutting and breakage allowance is represented in the waste rate.']],
 ja:[['MODULE','目地を含む反復モジュール','190×57mmのレンガに10mm目地を加えると計算モジュールは200×67mmです。最終行・列の実際の目地形状を再現する値ではありません。'],['EXAMPLE','5m×2.4m壁の例','12㎡の壁を200×67mmモジュールで割るとロス前は約895.52個です。ロス率5%で約940.30個となり、購入数は941個に切り上げます。'],['WASTE','ロス率と切り上げ','破損・切断・現場余裕を1つのロス率入力で表します。ロス適用後の小数数量は購入単位として整数に切り上げます。'],['COST','1個単価から予想費用','例として941個・1個500の入力なら予想費用は470,500です。運送費、モルタル、人件費などは含みません。'],['JOINT','目地1mmの差も繰り返すと累積','1個では小さな差でも壁全体ではモジュールが繰り返されます。実際の目地寸法が決まっている場合は初期値ではなくその値で数量を比較してください。'],['CHECK','梱包単位と破損余裕を確認','計算結果は個数基準です。実際の注文がパレットや束単位なら販売梱包単位でもう一度切り上げ、切断・破損余裕がロス率に反映されているか確認します。']]
} as const;

export function Tool087MasonryQuantityPage({locale}:{locale:Locale}){
 const t=copy[locale],url=`https://toolbox.fixlgs.com/${locale}/brick-block-quantity-calculator`;
 const jsonLd={"@context":"https://schema.org","@graph":[{"@type":"WebApplication",name:t.title,applicationCategory:'UtilitiesApplication',operatingSystem:'Any',url,description:t.desc,offers:{'@type':'Offer',price:'0',priceCurrency:'USD'}},{"@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:'TOOLBOX',item:`https://toolbox.fixlgs.com/${locale}`},{"@type":"ListItem",position:2,name:t.back,item:`https://toolbox.fixlgs.com/${locale}/category/real-estate-build`},{"@type":"ListItem",position:3,name:t.title,item:url}]},{"@type":"FAQPage",mainEntity:t.faqs.map(([q,a])=>({"@type":"Question",name:q,acceptedAnswer:{"@type":"Answer",text:a}}))}]};
 return <ToolboxSubpageShell locale={locale} appName={t.title}>
  <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(jsonLd)}}/>
  <section className="toolbox-tool-detail-hero toolbox-tool-detail-hero--single-line-description"><Link className="toolbox-subpage-back" href={`/${locale}/category/real-estate-build`}>← {t.back}</Link><p className="toolbox-subpage-eyebrow">087 · REAL ESTATE & BUILD</p><div className="toolbox-tool-detail-heading"><h1><span className="toolbox-tool-title-line">{t.title}</span></h1><p>{t.desc}</p></div><div className="toolbox-tool-detail-badge"><strong>LOCAL</strong><span>{t.local}</span></div></section>
  <section className="toolbox-tool-detail-body"><div><Tool087MasonryQuantity locale={locale}/></div></section>
  <section className="toolbox-tool-guide toolbox-tool-guide--five"><div className="toolbox-tool-guide-head"><p>HOW TO USE</p><h2>{t.how}</h2></div><ol>{t.steps.map((s,i)=><li key={s}><span>{String(i+1).padStart(2,'0')}</span><p>{s}</p></li>)}</ol></section>
  <section className="toolbox-tool-format-guide toolbox-tool-expert-post toolbox-tool-expert-post--wide-head"><div className="toolbox-tool-format-guide-head"><p>MASONRY QUANTITY</p><h2>{locale==='ko'?'벽돌·블록 구매 수량 가이드':locale==='ja'?'レンガ・ブロック購入数量ガイド':'Brick and block quantity guide'}</h2></div><div className="toolbox-tool-format-body"><div className="toolbox-tool-format-grid">{expert[locale].map(([tag,title,desc])=><article key={tag}><strong>{tag}</strong><h3>{title}</h3><p>{desc}</p></article>)}</div></div></section>
  <section className="toolbox-tool-info-band toolbox-tool-info-band--section-start toolbox-tool-info-band--bottom-gap toolbox-tool-info-band--left-head toolbox-tool-info-band--format-head"><div className="toolbox-tool-info-band-head"><p>IMPORTANT NOTES</p><h2>{locale==='ko'?'주의사항':locale==='ja'?'注意事項':'Important notes'}</h2></div><ul className="toolbox-tool-info-band-list">{t.notes.map(n=><li key={n}>{n}</li>)}</ul></section>
  <section className="toolbox-tool-faq"><div className="toolbox-tool-guide-head"><p>FAQ</p><h2>{locale==='ko'?'자주 묻는 질문':locale==='ja'?'よくある質問':'Frequently asked questions'}</h2></div><ToolboxFaqList items={[...t.faqs]} initialCount={4} moreLabel={locale==='ko'?'FAQ 더보기':locale==='ja'?'FAQをもっと見る':'Show more FAQs'} collapseLabel={locale==='ko'?'FAQ 접기':locale==='ja'?'FAQを閉じる':'Collapse FAQs'} className="toolbox-tool-faq-list"/></section>
 </ToolboxSubpageShell>
}
