import Link from 'next/link';
import type {Locale} from '@/lib/site';
import {Tool088ConcreteVolumeCalculator} from '@/components/tool-088-concrete-volume-calculator';
import {ToolboxFaqList} from '@/components/toolbox-faq-list';
import {ToolboxSubpageShell} from '@/components/toolbox-subpage-shell';

const copy={
 ko:{title:'콘크리트 부피 계산기',desc:'길이·폭·두께를 입력해 콘크리트 기본 부피를 ㎥로 계산하고, 여유분과 사용자가 입력한 1회 공급 기준량으로 주문 참고 부피와 레미콘 참고 횟수를 확인합니다.',back:'부동산·건축 계산기',local:'브라우저에서 바로 계산',how:'사용 방법',steps:['타설할 구간의 길이·폭·두께를 입력하고 각 치수 단위를 mm, cm, m 중에서 선택합니다.','도구는 모든 길이를 내부적으로 m로 정규화한 뒤 길이×폭×두께로 기본 부피를 계산합니다.','현장 오차·잔량 등을 고려할 참고 여유분을 0~100% 범위에서 입력합니다. 예를 들어 3.0㎥에 5%를 더하면 3.15㎥입니다.','레미콘 참고 횟수까지 보고 싶다면 업체나 현장에서 확인한 1대·1회 기준 공급량을 직접 입력합니다.','여유 포함 부피를 1회 기준량으로 나눈 뒤 올림하여 참고 공급 횟수를 표시합니다. 기준량을 비우면 횟수는 계산하지 않습니다.','결과는 발주 참고용입니다. 실제 주문 전에는 현장 손실, 펌프·운반 조건, 업체 공급 기준을 별도로 확인하세요.'],notes:['이 도구는 부피 계산기이며 콘크리트 배합비·강도·슬럼프·구조 안전성을 판정하지 않습니다.','레미콘 1대 또는 1회의 공급량은 차량 규격과 업체 조건에 따라 달라질 수 있으므로 도구가 고정값을 자동 적용하지 않습니다.','여유분은 사용자가 정하는 주문 참고값이며 실제 현장 손실·잔량을 보장하지 않습니다.','두께 단위를 잘못 선택하면 결과가 크게 달라집니다. 150mm는 15cm 또는 0.15m와 같은 값입니다.','기본 부피와 여유 포함 부피를 구분해 확인하고, 실제 발주량은 현장 조건과 공급업체 기준을 함께 검토하세요.','계산은 내부 m 단위로 정규화한 뒤 중간 반올림 없이 처리하고 화면 표시 단계에서만 반올림합니다.'],faqs:[['콘크리트 부피는 어떻게 계산하나요?','길이×폭×두께로 계산합니다. 세 치수는 내부적으로 m로 바뀌므로 결과는 m³로 표시됩니다.'],['5m×4m×15cm는 몇 ㎥인가요?','15cm는 0.15m이므로 5×4×0.15=3.0㎥입니다.'],['3.0㎥에 여유 5%를 더하면 얼마인가요?','3.0×1.05=3.15㎥입니다. 여유분은 주문 참고값입니다.'],['레미콘 참고 횟수는 어떻게 계산하나요?','여유 포함 부피를 사용자가 입력한 1회 기준 공급량으로 나눈 뒤 올림합니다. 3.15㎥를 6㎥ 기준으로 보면 참고 1회입니다.'],['왜 레미콘 한 대 용량을 자동으로 넣지 않나요?','차량·업체·현장 조건에 따라 기준량이 달라질 수 있기 때문에 사용자가 확인한 값을 직접 입력하도록 설계했습니다.'],['mm, cm, m를 섞어 입력해도 되나요?','가능합니다. 길이·폭·두께 각각의 단위를 선택하면 내부 m로 정규화해 계산합니다.'],['여유분은 몇 %가 맞나요?','현장 조건에 따라 달라 이 도구가 적정 비율을 자동 판정하지 않습니다. 사용자가 필요한 참고 여유율을 직접 입력해야 합니다.'],['실제 발주량과 계산 결과가 같나요?','반드시 같지는 않습니다. 펌프·운반·잔량·현장 오차와 업체 공급 조건 등을 실제 발주 전에 별도로 확인해야 합니다.']]},
 en:{title:'Concrete Volume Calculator',desc:'Calculate concrete volume in m³ from length, width, and thickness, then add an allowance and optionally estimate reference deliveries using a per-delivery volume you enter.',back:'Real Estate & Build',local:'CALCULATE IN YOUR BROWSER',how:'How to use',steps:['Enter the length, width, and thickness of the pour and choose mm, cm, or m for each dimension.','The calculator normalizes every dimension to meters and calculates base volume as length × width × thickness.','Enter a reference allowance from 0% to 100%. For example, adding 5% to 3.0 m³ gives 3.15 m³.','To estimate delivery count, enter the ready-mix volume per truck or delivery using a value confirmed for your supplier or site.','The adjusted volume is divided by the per-delivery volume and rounded up. If the per-delivery field is blank, delivery count is not calculated.','Use the result as an ordering reference and confirm site loss, pumping, transport, and supplier conditions before placing an actual order.'],notes:['This tool calculates volume only; it does not design concrete mix, strength, slump, or structural safety.','Ready-mix capacity per truck or delivery varies by supplier and operating conditions, so no fixed vehicle capacity is assumed.','The allowance is a user-entered ordering reference and does not guarantee actual site loss or leftover volume.','Selecting the wrong thickness unit can change the result dramatically. 150 mm, 15 cm, and 0.15 m are equivalent.','Keep base volume separate from adjusted volume and confirm actual ordering quantities with site and supplier requirements.','Dimensions are normalized to meters and calculated without intermediate rounding; rounding is applied only for display.'],faqs:[['How is concrete volume calculated?','Multiply length × width × thickness. All dimensions are normalized to meters, so the result is shown in m³.'],['What is 5 m × 4 m × 15 cm?','15 cm equals 0.15 m, so 5 × 4 × 0.15 = 3.0 m³.'],['What is 3.0 m³ with a 5% allowance?','3.0 × 1.05 = 3.15 m³. The allowance is an ordering reference.'],['How are reference deliveries calculated?','Adjusted volume is divided by the per-delivery volume you enter and rounded up. 3.15 m³ with a 6 m³ delivery reference gives 1 delivery.'],['Why is truck capacity not filled automatically?','Capacity can differ by truck, supplier, and site, so the calculator requires a user-confirmed reference volume.'],['Can I mix mm, cm, and m inputs?','Yes. Choose the unit for each dimension and the calculator normalizes them to meters internally.'],['What allowance percentage should I use?','The appropriate allowance depends on site conditions, so the calculator does not choose one automatically. Enter your own reference percentage.'],['Will the result equal my final order quantity?','Not necessarily. Verify pumping, transport, leftovers, site variation, and supplier requirements before ordering.']]},
 ja:{title:'コンクリート体積計算ツール',desc:'長さ・幅・厚さからコンクリートの基本体積をm³で計算し、余裕率と入力した1回基準量から注文参考体積と生コン参考回数を確認できます。',back:'不動産・建築',local:'ブラウザ内で計算',how:'使い方',steps:['打設部分の長さ・幅・厚さを入力し、それぞれmm・cm・mから単位を選びます。','すべての寸法を内部でmに正規化し、長さ×幅×厚さで基本体積を計算します。','現場誤差や残量を考慮する参考余裕率を0〜100%で入力します。3.0m³に5%を加えると3.15m³です。','生コン参考回数も確認する場合は、業者や現場で確認した1台・1回あたりの基準供給量を入力します。','余裕込み体積を1回基準量で割って切り上げ、参考回数を表示します。基準量を空欄にすると回数は計算しません。','結果は発注参考値です。実際の注文前に現場損失、ポンプ・運搬条件、供給業者の基準を確認してください。'],notes:['このツールは体積計算用で、配合・強度・スランプ・構造安全性を判定しません。','生コン1台・1回の供給量は車両や業者条件で異なるため、固定値を自動設定しません。','余裕率はユーザーが入力する注文参考値で、実際の現場損失や残量を保証しません。','厚さの単位を誤ると結果が大きく変わります。150mm、15cm、0.15mは同じ長さです。','基本体積と余裕込み体積を分けて確認し、実際の発注量は現場条件と供給業者の基準を合わせて確認してください。','寸法は内部でmに正規化し、途中で丸めず、画面表示時だけ丸めます。'],faqs:[['コンクリート体積はどう計算しますか？','長さ×幅×厚さで計算します。各寸法は内部でmに正規化され、結果はm³で表示されます。'],['5m×4m×15cmは何m³ですか？','15cmは0.15mなので、5×4×0.15=3.0m³です。'],['3.0m³に余裕5%を加えると？','3.0×1.05=3.15m³です。余裕率は注文参考値です。'],['生コン参考回数はどう計算しますか？','余裕込み体積を入力した1回基準量で割り、切り上げます。3.15m³を6m³基準で見ると参考1回です。'],['なぜ生コン1台分を自動設定しないのですか？','車両・業者・現場条件で基準量が異なるため、確認した値をユーザーが入力する設計です。'],['mm、cm、mを混在して入力できますか？','できます。各寸法の単位を選ぶと内部でmに正規化して計算します。'],['余裕率は何%が適切ですか？','現場条件によって異なるため、このツールでは自動判定しません。必要な参考余裕率を入力してください。'],['計算結果と実際の発注量は同じですか？','必ずしも同じではありません。ポンプ・運搬・残量・現場誤差や供給業者の条件を発注前に確認してください。']]}
} as const;

const expert={ko:[['VOLUME','3차원 치수를 ㎥로 계산','5m×4m×0.15m는 3.0㎥입니다. 면적만으로는 콘크리트 양을 구할 수 없으며 반드시 두께까지 포함해야 합니다.'],['UNIT','mm·cm·m 단위를 먼저 맞추기','150mm, 15cm, 0.15m는 같은 두께입니다. 각 입력 단위를 따로 선택한 뒤 내부 m로 정규화하면 단위 혼용 실수를 줄일 수 있습니다.'],['ALLOWANCE','기본량과 여유 포함량 분리','기본 부피 3.0㎥에 여유 5%를 적용하면 주문 참고 부피는 3.15㎥입니다. 여유율은 현장 상황을 대신 판단하는 값이 아니라 사용자가 정하는 참고값입니다.'],['DELIVERY','레미콘 기준량은 직접 입력','1회 공급 기준량은 업체와 현장 조건에 따라 달라질 수 있습니다. 3.15㎥를 6㎥ 기준으로 나누면 올림하여 참고 1회로 표시합니다.'],['REFERENCE','발주량이 아니라 참고 계산','부피 계산 결과는 현장 조건을 자동 반영하지 않습니다. 실제 발주 전에는 운반·펌프·잔량·최소 주문 단위 등을 공급업체와 확인해야 합니다.'],['ROUNDING','중간 반올림 없이 계산','각 치수를 m로 정규화한 내부값으로 계산하고 마지막 표시 단계에서만 반올림합니다.']],en:[['VOLUME','Calculate a 3D volume in m³','5 m × 4 m × 0.15 m equals 3.0 m³. Surface area alone is not enough; thickness must be included.'],['UNIT','Normalize mm, cm, and m','150 mm, 15 cm, and 0.15 m are the same thickness. Selecting a unit for each dimension helps prevent unit-mixing mistakes.'],['ALLOWANCE','Separate base and adjusted volume','Adding a 5% allowance to 3.0 m³ gives 3.15 m³. The allowance is a user-selected reference, not an automatic judgment of site loss.'],['DELIVERY','Enter your own delivery reference','Per-delivery volume can vary by supplier and site. Dividing 3.15 m³ by a 6 m³ reference and rounding up gives 1 reference delivery.'],['REFERENCE','Treat it as an ordering reference','The volume result does not automatically include pumping, transport, leftovers, or minimum-order rules. Confirm them with the supplier before ordering.'],['ROUNDING','Avoid intermediate rounding','The calculator normalizes dimensions to meters and retains internal precision until the display stage.']],ja:[['VOLUME','3次元寸法からm³を計算','5m×4m×0.15mは3.0m³です。面積だけではなく厚さまで含める必要があります。'],['UNIT','mm・cm・mを正規化','150mm、15cm、0.15mは同じ厚さです。各寸法の単位を選び、内部mに正規化して単位混在のミスを減らします。'],['ALLOWANCE','基本量と余裕込み量を分ける','基本体積3.0m³に余裕5%を加えると3.15m³です。余裕率は現場損失を自動判定する値ではなく、ユーザーが決める参考値です。'],['DELIVERY','生コン基準量は自分で入力','1回供給量は業者や現場条件で異なります。3.15m³を6m³基準で割り、切り上げると参考1回です。'],['REFERENCE','発注確定量ではなく参考値','計算結果にはポンプ・運搬・残量・最低注文量などが自動反映されません。実際の発注前に供給業者へ確認してください。'],['ROUNDING','途中で丸めず計算','各寸法をmに正規化した内部値で計算し、最終表示時のみ丸めます。']]} as const;

export function Tool088ConcreteVolumeCalculatorPage({locale}:{locale:Locale}){
 const t=copy[locale];const url=`https://toolbox.fixlgs.com/${locale}/concrete-volume-calculator`;
 const jsonLd={"@context":"https://schema.org","@graph":[{"@type":"WebApplication",name:t.title,applicationCategory:'UtilitiesApplication',operatingSystem:'Any',url,description:t.desc,offers:{'@type':'Offer',price:'0',priceCurrency:'USD'}},{"@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:'TOOLBOX',item:`https://toolbox.fixlgs.com/${locale}`},{"@type":"ListItem",position:2,name:t.back,item:`https://toolbox.fixlgs.com/${locale}/category/real-estate-build`},{"@type":"ListItem",position:3,name:t.title,item:url}]},{"@type":"FAQPage",mainEntity:t.faqs.map(([q,a])=>({"@type":"Question",name:q,acceptedAnswer:{"@type":"Answer",text:a}}))}]};
 return <ToolboxSubpageShell locale={locale} appName={t.title}>
  <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(jsonLd)}}/>
  <section className="toolbox-tool-detail-hero toolbox-tool-detail-hero--single-line-description"><Link className="toolbox-subpage-back" href={`/${locale}/category/real-estate-build`}>← {t.back}</Link><p className="toolbox-subpage-eyebrow">088 · REAL ESTATE & BUILD</p><div className="toolbox-tool-detail-heading"><h1><span className="toolbox-tool-title-line">{t.title}</span></h1><p>{t.desc}</p></div><div className="toolbox-tool-detail-badge"><strong>LOCAL</strong><span>{t.local}</span></div></section>
  <section className="toolbox-tool-detail-body"><div><Tool088ConcreteVolumeCalculator locale={locale}/></div></section>
  <section className="toolbox-tool-guide toolbox-tool-guide--five"><div className="toolbox-tool-guide-head"><p>HOW TO USE</p><h2>{t.how}</h2></div><ol>{t.steps.map((s,i)=><li key={s}><span>{String(i+1).padStart(2,'0')}</span><p>{s}</p></li>)}</ol></section>
  <section className="toolbox-tool-format-guide toolbox-tool-expert-post toolbox-tool-expert-post--wide-head"><div className="toolbox-tool-format-guide-head"><p>CONCRETE VOLUME</p><h2>{locale==='ko'?'콘크리트 주문량 계산 가이드':locale==='ja'?'コンクリート注文量の計算ガイド':'Concrete ordering quantity guide'}</h2></div><div className="toolbox-tool-format-body"><div className="toolbox-tool-format-grid">{expert[locale].map(([tag,title,desc])=><article key={tag}><strong>{tag}</strong><h3>{title}</h3><p>{desc}</p></article>)}</div></div></section>
  <section className="toolbox-tool-info-band toolbox-tool-info-band--section-start toolbox-tool-info-band--bottom-gap toolbox-tool-info-band--left-head toolbox-tool-info-band--format-head"><div className="toolbox-tool-info-band-head"><p>IMPORTANT NOTES</p><h2>{locale==='ko'?'주의사항':locale==='ja'?'注意事項':'Important notes'}</h2></div><ul className="toolbox-tool-info-band-list">{t.notes.map(n=><li key={n}>{n}</li>)}</ul></section>
  <section className="toolbox-tool-faq"><div className="toolbox-tool-guide-head"><p>FAQ</p><h2>{locale==='ko'?'자주 묻는 질문':locale==='ja'?'よくある質問':'Frequently asked questions'}</h2></div><ToolboxFaqList items={[...t.faqs]} initialCount={4} moreLabel={locale==='ko'?'FAQ 더보기':locale==='ja'?'FAQをもっと見る':'Show more FAQs'} collapseLabel={locale==='ko'?'FAQ 접기':locale==='ja'?'FAQを閉じる':'Collapse FAQs'} className="toolbox-tool-faq-list"/></section>
 </ToolboxSubpageShell>
}
