'use client';
import {useMemo,useState} from 'react';
import type {Locale} from '@/lib/site';
import {TOOL090_LIMITS,calculateTool090Ramp,calculateTool090Stair,formatTool090,fromTool090Meters,parseTool090Number,type Tool090LengthUnit,type Tool090RampBasis,type Tool090RampResult,type Tool090StairBasis,type Tool090StairResult} from '@/lib/tool-090-stair-ramp';
import styles from './tool-090-stair-ramp-calculator.module.css';

const copy={
 ko:{local:'입력한 치수는 서버로 전송하거나 저장하지 않고 현재 브라우저에서만 계산합니다.',stair:'계단',ramp:'경사로',unit:'길이 단위',height:'전체 높이',steps:'계단 수',basis:'입력 기준',tread:'단너비',run:'수평거리',slope:'경사율',angle:'경사각',length:'경사길이',riser:'단높이',reset:'초기화',copy:'결과 복사',copied:'복사됨',precision:'표시 소수점',result:'계산 결과',formula:'계산식',empty:'치수를 입력하면 결과가 표시됩니다.',invalid:'올바른 숫자를 입력하세요.',zero:'0보다 큰 값을 입력하세요.',stepsError:'계단 수는 1 이상의 정수여야 합니다.',limit:'입력값이 서비스 유효상한을 초과했습니다.',legal:'이 결과는 기하 계산 참고값이며 건축법·장애인 편의기준·구조 안전의 적합 여부를 자동 판정하지 않습니다.',treadBasis:'단너비로 계산',runBasis:'수평거리로 계산',slopeBasis:'경사율로 역산',angleBasis:'경사각으로 역산'},
 en:{local:'Dimensions are calculated only in this browser and are not sent to or stored on a server.',stair:'Stairs',ramp:'Ramp',unit:'Length unit',height:'Total Height',steps:'Number of Steps',basis:'Input basis',tread:'Tread Depth',run:'Horizontal Run',slope:'Slope %',angle:'Slope Angle',length:'Sloped Length',riser:'Riser Height',reset:'Reset',copy:'Copy result',copied:'Copied',precision:'Display decimals',result:'Result',formula:'Formula',empty:'Enter dimensions to see results.',invalid:'Enter valid numbers.',zero:'Enter values greater than zero.',stepsError:'Number of steps must be a positive integer.',limit:'An input exceeds the service limit.',legal:'This is a geometry reference and does not determine compliance with building, accessibility, railing, landing, or structural-safety rules.',treadBasis:'Calculate from tread',runBasis:'Calculate from run',slopeBasis:'Back-calculate from slope',angleBasis:'Back-calculate from angle'},
 ja:{local:'入力した寸法はサーバーへ送信・保存せず、このブラウザ内だけで計算します。',stair:'階段',ramp:'スロープ',unit:'長さ単位',height:'全高',steps:'段数',basis:'入力基準',tread:'踏面',run:'水平距離',slope:'勾配率',angle:'勾配角',length:'斜長',riser:'蹴上げ',reset:'リセット',copy:'結果をコピー',copied:'コピー済み',precision:'表示小数点',result:'計算結果',formula:'計算式',empty:'寸法を入力すると結果が表示されます。',invalid:'有効な数値を入力してください。',zero:'0より大きい値を入力してください。',stepsError:'段数は1以上の整数にしてください。',limit:'入力値がサービス上限を超えています。',legal:'この結果は幾何計算の参考値であり、建築法規・バリアフリー基準・手すり・踊り場・構造安全への適合を自動判定しません。',treadBasis:'踏面から計算',runBasis:'水平距離から計算',slopeBasis:'勾配率から逆算',angleBasis:'勾配角から逆算'}
} as const;
function localeCode(locale:Locale){return locale==='ko'?'ko-KR':locale==='ja'?'ja-JP':'en-US'}

export function Tool090StairRampCalculator({locale}:{locale:Locale}){
 const t=copy[locale];const [mode,setMode]=useState<'stair'|'ramp'>('stair');const [unit,setUnit]=useState<Tool090LengthUnit>('m');const [height,setHeight]=useState('2.4');const [steps,setSteps]=useState('12');const [stairBasis,setStairBasis]=useState<Tool090StairBasis>('tread');const [stairValue,setStairValue]=useState('0.28');const [rampBasis,setRampBasis]=useState<Tool090RampBasis>('run');const [rampValue,setRampValue]=useState('4');const [precision,setPrecision]=useState(3);const [status,setStatus]=useState('');
 const calculation=useMemo<{value:Tool090StairResult|Tool090RampResult|null;error:string}>(()=>{const h=parseTool090Number(height);if(h===null)return {value:null,error:height.trim()?t.invalid:''};try{if(mode==='stair'){const s=parseTool090Number(steps),v=parseTool090Number(stairValue);if(s===null||v===null)return {value:null,error:(steps.trim()||stairValue.trim())?t.invalid:''};return {value:calculateTool090Stair({height:h,unit,steps:s,basis:stairBasis,treadOrRun:v}),error:''}}const v=parseTool090Number(rampValue);if(v===null)return {value:null,error:rampValue.trim()?t.invalid:''};return {value:calculateTool090Ramp({height:h,unit,basis:rampBasis,value:v}),error:''}}catch(e){const c=e instanceof Error?e.message:'';if(c==='STEPS_INVALID')return {value:null,error:t.stepsError};if(c.includes('LIMIT'))return {value:null,error:t.limit};if(c.includes('ZERO'))return {value:null,error:t.zero};return {value:null,error:t.invalid}}},[mode,unit,height,steps,stairBasis,stairValue,rampBasis,rampValue,t]);
 const f=(v:number)=>formatTool090(v,precision,localeCode(locale));const result=calculation.value;const length=(m:number)=>`${f(fromTool090Meters(m,unit))} ${unit}`;
 function reset(){setMode('stair');setUnit('m');setHeight('2.4');setSteps('12');setStairBasis('tread');setStairValue('0.28');setRampBasis('run');setRampValue('4');setPrecision(3);setStatus('')}
 async function copyResult(){if(!result)return;const lines=[`${t.height}: ${length(result.riseM)}`,`${t.run}: ${length(result.runM)}`,`${t.length}: ${length(result.lengthM)}`,`${t.slope}: ${f(result.slopePct)}%`,`${t.angle}: ${f(result.angleDeg)}°`];if('steps'in result)lines.push(`${t.steps}: ${result.steps}`,`${t.riser}: ${length(result.riserM)}`,`${t.tread}: ${length(result.treadM)}`);try{await navigator.clipboard.writeText(lines.join('\n'));setStatus(t.copied)}catch{setStatus('')}}
 const resultItem=(label:string,value:string,id:string)=><div className={styles.resultItem}><span>{label}</span><strong data-testid={id}>{value}</strong></div>;
 return <div className={styles.root} data-testid="tool090-root">
  <div className={styles.localNotice}><strong>LOCAL</strong><span>{t.local}</span></div>
  <div className={styles.modeRow} role="tablist" aria-label={t.basis}><button type="button" className={`${styles.modeButton} ${mode==='stair'?styles.modeButtonActive:''}`} onClick={()=>setMode('stair')} data-testid="tool090-mode-stair">{t.stair}</button><button type="button" className={`${styles.modeButton} ${mode==='ramp'?styles.modeButtonActive:''}`} onClick={()=>setMode('ramp')} data-testid="tool090-mode-ramp">{t.ramp}</button></div>
  <section className={styles.workspace} data-testid="tool090-workspace"><div className={styles.workspaceGrid}><div className={styles.card}><div className={styles.cardHead}><strong>{mode==='stair'?'STAIR INPUT':'RAMP INPUT'}</strong><span>{mode==='stair'?t.stair:t.ramp}</span></div><div className={styles.inputGrid}>
   <label className={styles.field}>{t.height}<span className={styles.withUnit}><input inputMode="decimal" maxLength={TOOL090_LIMITS.maxInputChars} value={height} onChange={e=>setHeight(e.target.value)} data-testid="tool090-height"/><select value={unit} onChange={e=>setUnit(e.target.value as Tool090LengthUnit)} aria-label={t.unit} data-testid="tool090-unit"><option value="mm">mm</option><option value="cm">cm</option><option value="m">m</option></select></span></label>
   {mode==='stair'?<><label className={styles.field}>{t.steps}<input inputMode="numeric" maxLength={TOOL090_LIMITS.maxInputChars} value={steps} onChange={e=>setSteps(e.target.value)} data-testid="tool090-steps"/></label><label className={styles.field}>{t.basis}<select value={stairBasis} onChange={e=>setStairBasis(e.target.value as Tool090StairBasis)} data-testid="tool090-stair-basis"><option value="tread">{t.treadBasis}</option><option value="run">{t.runBasis}</option></select></label><label className={styles.field}>{stairBasis==='tread'?t.tread:t.run}<input inputMode="decimal" maxLength={TOOL090_LIMITS.maxInputChars} value={stairValue} onChange={e=>setStairValue(e.target.value)} data-testid="tool090-stair-value"/></label></>:<><label className={styles.field}>{t.basis}<select value={rampBasis} onChange={e=>setRampBasis(e.target.value as Tool090RampBasis)} data-testid="tool090-ramp-basis"><option value="run">{t.runBasis}</option><option value="slope">{t.slopeBasis}</option><option value="angle">{t.angleBasis}</option></select></label><label className={`${styles.field} ${styles.fieldFull}`}>{rampBasis==='run'?t.run:rampBasis==='slope'?`${t.slope} (%)`:`${t.angle} (°)`}<input inputMode="decimal" maxLength={TOOL090_LIMITS.maxInputChars} value={rampValue} onChange={e=>setRampValue(e.target.value)} data-testid="tool090-ramp-value"/></label></>}
  </div></div><section className={styles.resultCard} aria-live="polite" data-testid="tool090-result"><div className={styles.resultHead}><p className={styles.resultLabel}>RESULT · {t.result}</p></div>{!result?<p className={styles.hint}>{calculation.error||t.empty}</p>:<><div className={styles.resultGrid}>{resultItem(t.height,length(result.riseM),'tool090-result-height')}{resultItem(t.run,length(result.runM),'tool090-result-run')}{resultItem(t.length,length(result.lengthM),'tool090-result-length')}{resultItem(t.slope,`${f(result.slopePct)}%`,'tool090-result-slope')}{resultItem(t.angle,`${f(result.angleDeg)}°`,'tool090-result-angle')}{'steps'in result&&<>{resultItem(t.steps,String(result.steps),'tool090-result-steps')}{resultItem(t.riser,length(result.riserM),'tool090-result-riser')}{resultItem(t.tread,length(result.treadM),'tool090-result-tread')}</>}</div><div className={styles.formulaBox}><strong>{t.formula}</strong><code data-testid="tool090-formula">{mode==='stair'?`${t.riser} = ${t.height} ÷ ${t.steps} · ${t.slope} = ${t.height} ÷ ${t.run} × 100 · ${t.angle} = atan(${t.height} ÷ ${t.run})`:`${t.slope} = ${t.height} ÷ ${t.run} × 100 · ${t.angle} = atan(${t.height} ÷ ${t.run}) · ${t.length} = √(${t.height}² + ${t.run}²)`}</code></div></>}{status&&<p className={styles.status}>{status}</p>}</section></div><div className={styles.actionRow}><button type="button" className={styles.button} onClick={reset} data-testid="tool090-reset">{t.reset}</button><button type="button" className={styles.primaryButton} disabled={!result} onClick={copyResult} data-testid="tool090-copy">{t.copy}</button></div>{calculation.error&&<p className={styles.error} role="alert" data-testid="tool090-error">{calculation.error}</p>}<p className={styles.hint} data-testid="tool090-legal-note">{t.legal}</p></section>
  <details className={styles.advanced}><summary>{t.precision}</summary><div className={styles.precisionRow}><input type="range" min="0" max={TOOL090_LIMITS.maxPrecision} value={precision} onChange={e=>setPrecision(Number(e.target.value))} data-testid="tool090-precision"/><span className={styles.precisionValue}>{precision}</span></div></details>
 </div>
}
