'use client';
import {useMemo,useState} from 'react';
import type {Locale} from '@/lib/site';
import {calculateTool077,formatTool077,parseTool077Number,type Tool077PeriodUnit} from '@/lib/tool-077-investment-return';
import styles from './tool-077-investment-return-calculator.module.css';

const copy={
 ko:{local:'입력한 투자금액은 서버로 전송하지 않고 브라우저 안에서만 계산됩니다.',purchase:'매입금액',current:'현재 평가금',period:'보유기간',days:'일',months:'월',years:'년',reset:'초기화',copy:'결과 복사',result:'계산 결과',principal:'투자원금',value:'현재 평가금',gain:'평가이익·손실',total:'총 수익률',annual:'연환산수익률',normalized:'보유기간(연)',formula:'계산식',note:'현재 평가금 기준 참고 계산이며 세금·수수료·배당·추가매수·현금 입출금은 자동 반영하지 않습니다.',empty:'값을 입력하면 결과가 표시됩니다.',purchaseError:'매입금액은 0보다 큰 유효한 숫자여야 합니다.',currentError:'현재 평가금은 0 이상의 유효한 숫자여야 합니다.',periodError:'보유기간은 0보다 커야 합니다.',limit:'서비스 유효상한을 초과했습니다.',overflow:'해당 기간에서는 연환산수익률을 안정적으로 표시할 수 없습니다.',profit:'평가이익',loss:'평가손실',even:'변동 없음',compare:'투자 A/B 비교',compareDesc:'같은 계산식을 사용해 두 투자 시나리오의 총 수익률과 연환산수익률을 비교합니다.',setA:'투자 A',setB:'투자 B',precision:'표시 소수점 최대 자리',copied:'결과를 복사했습니다.'},
 en:{local:'Your investment inputs stay in your browser and are not sent to a server.',purchase:'Purchase amount',current:'Current value',period:'Holding period',days:'Days',months:'Months',years:'Years',reset:'Reset',copy:'Copy result',result:'Result',principal:'Invested amount',value:'Current value',gain:'Gain / loss',total:'Total return',annual:'Annualized return',normalized:'Holding period (years)',formula:'Formula',note:'Reference calculation based on current value. Taxes, fees, dividends, additional purchases, and cash flows are not included automatically.',empty:'Enter values to see the result.',purchaseError:'Purchase amount must be a valid number greater than zero.',currentError:'Current value must be a valid non-negative number.',periodError:'Holding period must be greater than zero.',limit:'An input exceeds the service limit.',overflow:'The annualized return cannot be displayed reliably for this period.',profit:'Gain',loss:'Loss',even:'No change',compare:'Investment A/B comparison',compareDesc:'Compare total and annualized returns for two scenarios using the same formula.',setA:'Investment A',setB:'Investment B',precision:'Maximum display decimals',copied:'Result copied.'},
 ja:{local:'入力した投資金額はサーバーへ送信せず、ブラウザ内だけで計算します。',purchase:'購入金額',current:'現在評価額',period:'保有期間',days:'日',months:'月',years:'年',reset:'リセット',copy:'結果をコピー',result:'計算結果',principal:'投資元本',value:'現在評価額',gain:'評価益・評価損',total:'収益率',annual:'年率換算収益率',normalized:'保有期間（年）',formula:'計算式',note:'現在評価額を基準にした参考計算です。税金・手数料・配当・追加購入・入出金は自動反映しません。',empty:'値を入力すると結果が表示されます。',purchaseError:'購入金額は0より大きい有効な数値を入力してください。',currentError:'現在評価額は0以上の有効な数値を入力してください。',periodError:'保有期間は0より大きい必要があります。',limit:'入力値がサービス上限を超えています。',overflow:'この保有期間では年率換算収益率を安定して表示できません。',profit:'評価益',loss:'評価損',even:'変動なし',compare:'投資A/B比較',compareDesc:'同じ計算式で2つの投資シナリオの収益率と年率換算収益率を比較します。',setA:'投資A',setB:'投資B',precision:'表示小数点の最大桁数',copied:'結果をコピーしました。'}
} as const;
const lc=(l:Locale)=>l==='ko'?'ko-KR':l==='ja'?'ja-JP':'en-US';
function errorText(code:string,t:(typeof copy)[Locale]){return code==='INVALID_PURCHASE'?t.purchaseError:code==='INVALID_CURRENT'?t.currentError:code==='INVALID_PERIOD'?t.periodError:code.includes('LIMIT')?t.limit:t.overflow}

export function Tool077InvestmentReturnCalculator({locale}:{locale:Locale}){
 const t=copy[locale]; const [purchase,setPurchase]=useState(''); const [current,setCurrent]=useState(''); const [period,setPeriod]=useState(''); const [unit,setUnit]=useState<Tool077PeriodUnit>('years'); const [precision,setPrecision]=useState(2); const [status,setStatus]=useState('');
 const calc=useMemo(()=>{const p=parseTool077Number(purchase),c=parseTool077Number(current),h=parseTool077Number(period);if(p===null||c===null||h===null)return {result:null,error:''};try{return {result:calculateTool077(p,c,h,unit),error:''}}catch(e){return {result:null,error:errorText(e instanceof Error?e.message:'',t)}}},[purchase,current,period,unit,t]);
 const fmt=(v:number)=>formatTool077(v,precision,lc(locale)); const money=(v:number)=>`${fmt(v)} ${locale==='ko'?'원':locale==='ja'?'通貨単位':'currency units'}`; const pct=(v:number)=>`${fmt(v)}%`;
 const reset=()=>{setPurchase('');setCurrent('');setPeriod('');setUnit('years');setStatus('')};
 const copyResult=async()=>{if(!calc.result)return;const r=calc.result;const text=`${t.principal}: ${money(r.invested)}\n${t.value}: ${money(r.current)}\n${t.gain}: ${money(r.gain)}\n${t.total}: ${pct(r.totalReturnPct)}\n${t.annual}: ${pct(r.annualizedReturnPct)}\n${t.normalized}: ${fmt(r.years)}`;try{await navigator.clipboard.writeText(text);setStatus(t.copied)}catch{setStatus(text)}};
 return <div className={styles.root} data-testid="tool077-root">
  <div className={styles.localNotice}><strong>LOCAL</strong><span>{t.local}</span></div>
  <section className={styles.workspace}>
   <div className={styles.card}>
    <div className={styles.inputGrid}>
     <label className={styles.field}><span>{t.purchase}</span><input data-testid="tool077-purchase" inputMode="decimal" maxLength={30} value={purchase} onChange={e=>setPurchase(e.target.value)} placeholder="10,000,000"/></label>
     <label className={styles.field}><span>{t.current}</span><input data-testid="tool077-current" inputMode="decimal" maxLength={30} value={current} onChange={e=>setCurrent(e.target.value)} placeholder="13,000,000"/></label>
     <label className={`${styles.field} ${styles.fieldFull}`}><span>{t.period}</span><div className={styles.periodRow}><input data-testid="tool077-period" inputMode="decimal" maxLength={30} value={period} onChange={e=>setPeriod(e.target.value)} placeholder="2"/><select data-testid="tool077-period-unit" value={unit} onChange={e=>setUnit(e.target.value as Tool077PeriodUnit)}><option value="days">{t.days}</option><option value="months">{t.months}</option><option value="years">{t.years}</option></select></div></label>
    </div>
    <div className={styles.formulaBox}><strong>{t.formula}</strong><code data-testid="tool077-formula-total">Total Return = (Current Value − Purchase Amount) ÷ Purchase Amount × 100</code><code data-testid="tool077-formula-annual">Annualized Return = (Current Value ÷ Purchase Amount)^(1 ÷ years) − 1</code></div>
    <p className={styles.hint}>{t.note}</p>{calc.error&&<p className={styles.error} role="alert" data-testid="tool077-error">{calc.error}</p>}
    <div className={styles.actionRow}><button className={styles.button} type="button" onClick={reset}>{t.reset}</button><button className={styles.primaryButton} type="button" onClick={copyResult} disabled={!calc.result}>{t.copy}</button></div>
   </div>
   <div className={styles.resultCard} aria-live="polite">
    <div className={styles.resultHead}><p className={styles.resultLabel}>RESULT · ROI</p>{calc.result&&<span className={styles.state} data-testid="tool077-state">{calc.result.state==='profit'?t.profit:calc.result.state==='loss'?t.loss:t.even}</span>}</div>
    {!calc.result?<p className={styles.hint}>{calc.error||t.empty}</p>:<><div className={styles.resultHero}><div><span>{t.total}</span><strong data-testid="tool077-total-return">{pct(calc.result.totalReturnPct)}</strong></div><div><span>{t.annual}</span><strong data-testid="tool077-annualized-return">{pct(calc.result.annualizedReturnPct)}</strong></div></div><div className={styles.metrics}><div className={styles.metric}><span>{t.principal}</span><strong data-testid="tool077-invested">{money(calc.result.invested)}</strong></div><div className={styles.metric}><span>{t.value}</span><strong data-testid="tool077-current-result">{money(calc.result.current)}</strong></div><div className={styles.metric}><span>{t.gain}</span><strong data-testid="tool077-gain">{money(calc.result.gain)}</strong></div><div className={styles.metric}><span>{t.normalized}</span><strong data-testid="tool077-years">{fmt(calc.result.years)}</strong></div></div></>}
    {status&&<p className={styles.status} role="status">{status}</p>}
   </div>
  </section>
  <details className={styles.advanced}><summary>{t.compare}</summary><p className={styles.hint}>{t.compareDesc}</p><Compare locale={locale} precision={precision} t={t}/><label className={styles.precisionRow}><span>{t.precision}</span><input data-testid="tool077-precision" type="range" min="0" max="8" value={precision} onChange={e=>setPrecision(Number(e.target.value))}/><strong className={styles.precisionValue}>{precision}</strong></label></details>
 </div>
}

function Compare({locale,precision,t}:{locale:Locale;precision:number;t:(typeof copy)[Locale]}){
 const [v,setV]=useState({ap:'',ac:'',ah:'',bp:'',bc:'',bh:''}); const [unit,setUnit]=useState<Tool077PeriodUnit>('years'); const fmt=(n:number)=>formatTool077(n,precision,lc(locale));
 const one=(p:string,c:string,h:string)=>{const pv=parseTool077Number(p),cv=parseTool077Number(c),hv=parseTool077Number(h);if(pv===null||cv===null||hv===null)return '—';try{const r=calculateTool077(pv,cv,hv,unit);return `${fmt(r.totalReturnPct)}% · ${fmt(r.annualizedReturnPct)}%`}catch{return '—'}};
 const box=(prefix:'a'|'b',title:string)=>{const P=`${prefix}p` as keyof typeof v,C=`${prefix}c` as keyof typeof v,H=`${prefix}h` as keyof typeof v;return <div className={styles.compareBox}><strong>{title}</strong><label className={styles.field}><span>{t.purchase}</span><input data-testid={`tool077-compare-${prefix}-purchase`} value={v[P]} onChange={e=>setV(x=>({...x,[P]:e.target.value}))}/></label><label className={styles.field}><span>{t.current}</span><input data-testid={`tool077-compare-${prefix}-current`} value={v[C]} onChange={e=>setV(x=>({...x,[C]:e.target.value}))}/></label><label className={styles.field}><span>{t.period}</span><input data-testid={`tool077-compare-${prefix}-period`} value={v[H]} onChange={e=>setV(x=>({...x,[H]:e.target.value}))}/></label><span className={styles.compareResult} data-testid={`tool077-compare-${prefix}-result`}>{one(v[P],v[C],v[H])}</span></div>};
 return <><label className={styles.field}><span>{t.period}</span><select value={unit} onChange={e=>setUnit(e.target.value as Tool077PeriodUnit)}><option value="days">{t.days}</option><option value="months">{t.months}</option><option value="years">{t.years}</option></select></label><div className={styles.compareGrid}>{box('a',t.setA)}{box('b',t.setB)}</div></>;
}
