"use client";

import { useEffect, useMemo, useState } from "react";
import { localDateTimeToTimestamp, normalizeIntegerInput, timestampToDate, unitMismatchHint, type TimestampUnit } from "@/lib/tool-053-unix-timestamp";
import styles from "./tool-053-unix-timestamp-tool.module.css";

const text={
 ko:{toDate:"Timestamp → 날짜",toTimestamp:"날짜 → Timestamp",local:"입력값은 서버로 전송하거나 저장하지 않고 현재 브라우저에서만 계산합니다.",current:"현재 Unix Timestamp",seconds:"초 (seconds)",milliseconds:"밀리초 (milliseconds)",now:"현재 시간 넣기",workspace:"TIMESTAMP WORKSPACE",enterTimestamp:"Timestamp와 단위를 선택하세요",enterDate:"날짜와 시간을 입력하세요",timestamp:"Unix timestamp",unit:"입력 단위",date:"날짜",time:"시간",reset:"초기화",result:"RESULT",utc:"UTC",localTime:"현지시간",iso:"ISO 8601",weekday:"요일",copy:"복사",copied:"복사됨",copyFail:"복사 실패",invalid:"정수 timestamp를 입력하세요.",range:"지원 가능한 날짜 범위를 벗어났습니다.",invalidDate:"올바른 날짜와 시간을 입력하세요.",warnMs:"입력값이 milliseconds일 가능성이 있습니다. 선택한 단위는 자동 변경하지 않습니다.",warnSec:"입력값이 seconds일 가능성이 있습니다. 선택한 단위는 자동 변경하지 않습니다.",tz:"Unix timestamp 자체에는 시간대가 없습니다. UTC와 현지시간은 같은 순간을 서로 다르게 표시한 값입니다."},
 en:{toDate:"Timestamp → Date",toTimestamp:"Date → Timestamp",local:"Inputs are calculated only in this browser and are not sent to or stored on a server.",current:"Current Unix Timestamp",seconds:"Seconds",milliseconds:"Milliseconds",now:"Use current time",workspace:"TIMESTAMP WORKSPACE",enterTimestamp:"Enter a timestamp and choose its unit",enterDate:"Enter a local date and time",timestamp:"Unix timestamp",unit:"Input unit",date:"Date",time:"Time",reset:"Reset",result:"RESULT",utc:"UTC",localTime:"Local Time",iso:"ISO 8601",weekday:"Weekday",copy:"Copy",copied:"Copied",copyFail:"Copy failed",invalid:"Enter a whole-number timestamp.",range:"The value is outside the supported date range.",invalidDate:"Enter a valid date and time.",warnMs:"This value may be milliseconds. Your selected unit was not changed.",warnSec:"This value may be seconds. Your selected unit was not changed.",tz:"A Unix timestamp has no timezone. UTC and Local Time are two displays of the same instant."},
 ja:{toDate:"タイムスタンプ → 日付",toTimestamp:"日付 → タイムスタンプ",local:"入力値はサーバーへ送信・保存せず、このブラウザ内だけで計算します。",current:"現在のUnixタイムスタンプ",seconds:"秒",milliseconds:"ミリ秒",now:"現在時刻を入力",workspace:"TIMESTAMP WORKSPACE",enterTimestamp:"タイムスタンプと単位を選択してください",enterDate:"日付と時刻を入力してください",timestamp:"Unixタイムスタンプ",unit:"入力単位",date:"日付",time:"時刻",reset:"リセット",result:"RESULT",utc:"UTC",localTime:"現地時刻",iso:"ISO 8601",weekday:"曜日",copy:"コピー",copied:"コピー済み",copyFail:"コピー失敗",invalid:"整数のタイムスタンプを入力してください。",range:"対応可能な日付範囲を超えています。",invalidDate:"正しい日付と時刻を入力してください。",warnMs:"入力値はミリ秒の可能性があります。選択した単位は自動変更しません。",warnSec:"入力値は秒の可能性があります。選択した単位は自動変更しません。",tz:"Unixタイムスタンプ自体にタイムゾーンはありません。UTCと現地時刻は同じ瞬間の異なる表示です。"}
} as const;
type Locale=keyof typeof text; type Mode="to-date"|"to-timestamp";
const pad=(n:number)=>String(n).padStart(2,"0");
function localNowParts(){const d=new Date();return {date:`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`,time:`${pad(d.getHours())}:${pad(d.getMinutes())}:${pad(d.getSeconds())}`};}

export function Tool053UnixTimestampTool({locale}:{locale:Locale}){
 const t=text[locale]; const [mode,setMode]=useState<Mode>("to-date"); const [unit,setUnit]=useState<TimestampUnit>("seconds"); const [timestamp,setTimestamp]=useState("0"); const [dateValue,setDateValue]=useState("1970-01-01"); const [timeValue,setTimeValue]=useState("00:00:00"); const [nowMs,setNowMs]=useState(0); const [copyState,setCopyState]=useState("");
 useEffect(()=>{const ms=Date.now();const p=localNowParts();setNowMs(ms);setTimestamp(String(Math.floor(ms/1000)));setDateValue(p.date);setTimeValue(p.time);const id=window.setInterval(()=>setNowMs(Date.now()),1000);return()=>window.clearInterval(id)},[]);
 const mismatch=mode==="to-date"?unitMismatchHint(timestamp,unit):null;
 const dateResult=useMemo(()=>{if(mode!=="to-date")return {value:null,error:""};const parsed=normalizeIntegerInput(timestamp);if(parsed===null)return {value:null,error:t.invalid};try{return {value:timestampToDate(parsed,unit,locale),error:""}}catch{return {value:null,error:t.range}}},[mode,timestamp,unit,locale,t.invalid,t.range]);
 const timestampResult=useMemo(()=>{if(mode!=="to-timestamp")return {value:null,error:""};try{return {value:localDateTimeToTimestamp(dateValue,timeValue),error:""}}catch{return {value:null,error:t.invalidDate}}},[mode,dateValue,timeValue,t.invalidDate]);
 const copy=async(value:string|number,key:string)=>{try{await navigator.clipboard.writeText(String(value));setCopyState(`${key}:${t.copied}`);window.setTimeout(()=>setCopyState(""),1200)}catch{setCopyState(`${key}:${t.copyFail}`)}};
 const useNow=()=>{const ms=Date.now();setNowMs(ms);setMode("to-date");setTimestamp(String(unit==="seconds"?Math.floor(ms/1000):ms));setCopyState("")};
 const reset=()=>{const p=localNowParts();setMode("to-date");setUnit("seconds");setTimestamp(String(Math.floor(Date.now()/1000)));setDateValue(p.date);setTimeValue(p.time);setCopyState("")};
 const rows=dateResult.value?[ [t.utc,dateResult.value.utc,"utc"],[t.localTime,dateResult.value.local,"local"],[t.iso,dateResult.value.iso,"iso"],[t.seconds,dateResult.value.seconds,"seconds"],[t.milliseconds,dateResult.value.milliseconds,"milliseconds"],[t.weekday,dateResult.value.weekday,"weekday"] ]:timestampResult.value?[ [t.seconds,timestampResult.value.seconds,"seconds"],[t.milliseconds,timestampResult.value.milliseconds,"milliseconds"],[t.iso,timestampResult.value.iso,"iso"] ]:[];
 const error=mode==="to-date"?dateResult.error:timestampResult.error;
 return <div className={styles.tool} data-testid="tool053-root">
  <div className={styles.localNotice}><strong>LOCAL</strong><span>{t.local}</span></div>
  <div className={styles.current} data-testid="tool053-current"><div className={styles.currentItem}><span>{t.seconds}</span><strong data-testid="tool053-current-seconds">{nowMs===0?"—":Math.floor(nowMs/1000)}</strong></div><div className={styles.currentItem}><span>{t.milliseconds}</span><strong data-testid="tool053-current-milliseconds">{nowMs===0?"—":nowMs}</strong></div><button type="button" className={styles.nowButton} data-testid="tool053-now" onClick={useNow}>{t.now}</button></div>
  <div className={styles.modeRow} role="tablist" aria-label="Conversion mode"><button type="button" role="tab" aria-selected={mode==="to-date"} data-testid="tool053-mode-to-date" className={`${styles.modeButton} ${mode==="to-date"?styles.active:""}`} onClick={()=>setMode("to-date")}>{t.toDate}</button><button type="button" role="tab" aria-selected={mode==="to-timestamp"} data-testid="tool053-mode-to-timestamp" className={`${styles.modeButton} ${mode==="to-timestamp"?styles.active:""}`} onClick={()=>setMode("to-timestamp")}>{t.toTimestamp}</button></div>
  <section className={styles.workspace} data-testid="tool053-workspace"><div className={styles.workspaceHead}><div><span>{t.workspace}</span><h2>{mode==="to-date"?t.enterTimestamp:t.enterDate}</h2></div><button type="button" className={styles.resetButton} data-testid="tool053-reset" onClick={reset}>{t.reset}</button></div>
   {mode==="to-date"?<div className={styles.fields}><label className={styles.field} htmlFor="tool053-timestamp"><span>{t.timestamp}</span><input id="tool053-timestamp" data-testid="tool053-timestamp" type="text" inputMode="numeric" value={timestamp} onChange={e=>setTimestamp(e.target.value)} /></label><div className={styles.unitBox}><span className={styles.unitLabel}>{t.unit}</span><div className={styles.unitRow} role="group" aria-label={t.unit}><button type="button" data-testid="tool053-unit-seconds" aria-pressed={unit==="seconds"} className={`${styles.unitButton} ${unit==="seconds"?styles.active:""}`} onClick={()=>setUnit("seconds")}>{t.seconds}</button><button type="button" data-testid="tool053-unit-milliseconds" aria-pressed={unit==="milliseconds"} className={`${styles.unitButton} ${unit==="milliseconds"?styles.active:""}`} onClick={()=>setUnit("milliseconds")}>{t.milliseconds}</button></div></div></div>:<div className={styles.fields}><label className={styles.field} htmlFor="tool053-date"><span>{t.date}</span><input id="tool053-date" data-testid="tool053-date" type="date" value={dateValue} onChange={e=>setDateValue(e.target.value)} /></label><label className={styles.field} htmlFor="tool053-time"><span>{t.time}</span><input id="tool053-time" data-testid="tool053-time" type="time" step="1" value={timeValue} onChange={e=>setTimeValue(e.target.value)} /></label></div>}
   {mismatch&&<p className={styles.warning} data-testid="tool053-unit-warning">{mismatch==="likely-milliseconds"?t.warnMs:t.warnSec}</p>}{error&&<p className={styles.error} role="alert" data-testid="tool053-error">{error}</p>}
  </section>
  <section className={styles.result} data-testid="tool053-result" aria-live="polite"><div className={styles.resultHead}><span>{t.result}</span></div><div className={styles.resultRows}>{rows.map(([label,value,key])=><div className={styles.resultRow} key={String(key)} data-testid={`tool053-result-${key}`}><span>{label}</span><code>{String(value)}</code><button type="button" className={styles.copyButton} aria-label={`${label} ${t.copy}`} onClick={()=>copy(value,String(key))}>{t.copy}</button></div>)}</div>{copyState&&<div className={styles.copyState} data-testid="tool053-copy-status">{copyState}</div>}<p className={styles.tzNote}>{t.tz}</p></section>
 </div>
}
