'use client';
import {useMemo,useState} from 'react';
import type {Locale} from '@/lib/site';
import {TOOL081_LIMITS,calculateTool081Comparison,convertTool081Area,formatTool081,parseTool081Number,type Tool081AreaUnit} from '@/lib/tool-081-area-price';
import styles from './tool-081-area-price-calculator.module.css';

const copy={
 ko:{local:'입력한 면적과 가격은 서버로 전송하거나 저장하지 않고 현재 브라우저에서만 계산합니다.',convert:'면적 변환',area:'면적',unit:'단위',sqm:'㎡',pyeong:'평',converted:'변환 결과',priceArea:'가격·면적 기준',totalPrice:'총가격',supply:'공급면적',exclusive:'전용면적',optional:'선택 입력',reset:'초기화',copy:'결과 복사',copied:'복사됨',precision:'표시 소수점',result:'단가 결과',priceSqm:'㎡당 가격',pricePyeong:'평당 가격',formula:'계산식',empty:'면적과 가격을 입력하면 결과가 표시됩니다.',invalid:'올바른 숫자를 입력하세요.',areaZero:'면적은 0보다 커야 합니다.',priceNegative:'가격은 0 이상이어야 합니다.',limit:'입력값이 서비스 유효상한을 초과했습니다.',needArea:'공급면적 또는 전용면적을 하나 이상 입력하세요.'},
 en:{local:'Areas and prices are calculated only in this browser and are not sent to or stored on a server.',convert:'Area conversion',area:'Area',unit:'Unit',sqm:'m²',pyeong:'Pyeong',converted:'Converted area',priceArea:'Price & area basis',totalPrice:'Total Price',supply:'Gross Area',exclusive:'Exclusive Area',optional:'Optional',reset:'Reset',copy:'Copy result',copied:'Copied',precision:'Display decimals',result:'Unit-price result',priceSqm:'Price per m²',pricePyeong:'Price per Pyeong',formula:'Formula',empty:'Enter area and price values to see results.',invalid:'Enter valid numbers.',areaZero:'Area must be greater than zero.',priceNegative:'Price must be zero or greater.',limit:'An input exceeds the service limit.',needArea:'Enter at least a gross area or an exclusive area.'},
 ja:{local:'入力した面積と価格はサーバーへ送信・保存せず、このブラウザ内だけで計算します。',convert:'面積変換',area:'面積',unit:'単位',sqm:'㎡',pyeong:'坪',converted:'変換結果',priceArea:'価格・面積基準',totalPrice:'総価格',supply:'供給面積',exclusive:'専有面積',optional:'任意',reset:'リセット',copy:'結果をコピー',copied:'コピー済み',precision:'表示小数点',result:'単価結果',priceSqm:'㎡単価',pricePyeong:'坪単価',formula:'計算式',empty:'面積と価格を入力すると結果が表示されます。',invalid:'有効な数値を入力してください。',areaZero:'面積は0より大きくしてください。',priceNegative:'価格は0以上にしてください。',limit:'入力値がサービス上限を超えています。',needArea:'供給面積または専有面積を1つ以上入力してください。'}
} as const;
function localeCode(locale:Locale){return locale==='ko'?'ko-KR':locale==='ja'?'ja-JP':'en-US'}
type AreaState={value:string;unit:Tool081AreaUnit};

export function Tool081AreaPriceCalculator({locale}:{locale:Locale}){
 const t=copy[locale];const [convertValue,setConvertValue]=useState('84');const [convertUnit,setConvertUnit]=useState<Tool081AreaUnit>('sqm');const [totalPrice,setTotalPrice]=useState('500000000');const [supply,setSupply]=useState<AreaState>({value:'100',unit:'sqm'});const [exclusive,setExclusive]=useState<AreaState>({value:'80',unit:'sqm'});const [precision,setPrecision]=useState(2);const [status,setStatus]=useState('');
 const converted=useMemo(()=>{const v=parseTool081Number(convertValue);if(v===null)return {value:null,error:''};try{return {value:convertTool081Area(v,convertUnit),error:''}}catch(e){const c=e instanceof Error?e.message:'';return {value:null,error:c==='AREA_ZERO'?t.areaZero:c.includes('LIMIT')?t.limit:t.invalid}}},[convertValue,convertUnit,t]);
 const calculation=useMemo(()=>{const price=parseTool081Number(totalPrice),sv=parseTool081Number(supply.value),ev=parseTool081Number(exclusive.value);if(price===null)return {value:null,error:totalPrice.trim()?t.invalid:''};if(supply.value.trim()&&sv===null||exclusive.value.trim()&&ev===null)return {value:null,error:t.invalid};try{return {value:calculateTool081Comparison(price,sv,supply.unit,ev,exclusive.unit),error:''}}catch(e){const c=e instanceof Error?e.message:'';return {value:null,error:c==='AREA_REQUIRED'?t.needArea:c==='AREA_ZERO'?t.areaZero:c==='PRICE_NEGATIVE'?t.priceNegative:c.includes('LIMIT')?t.limit:t.invalid}}},[totalPrice,supply,exclusive,t]);
 const f=(v:number)=>formatTool081(v,precision,localeCode(locale));const result=calculation.value;
 function reset(){setConvertValue('84');setConvertUnit('sqm');setTotalPrice('500000000');setSupply({value:'100',unit:'sqm'});setExclusive({value:'80',unit:'sqm'});setPrecision(2);setStatus('')}
 async function copyResult(){if(!result)return;const chunks:string[]=[];if(result.supply)chunks.push(`${t.supply}: ${f(result.supply.area.sqm)} ${t.sqm} / ${f(result.supply.area.pyeong)} ${t.pyeong} · ${t.priceSqm} ${f(result.supply.pricePerSqm)} · ${t.pricePyeong} ${f(result.supply.pricePerPyeong)}`);if(result.exclusive)chunks.push(`${t.exclusive}: ${f(result.exclusive.area.sqm)} ${t.sqm} / ${f(result.exclusive.area.pyeong)} ${t.pyeong} · ${t.priceSqm} ${f(result.exclusive.pricePerSqm)} · ${t.pricePyeong} ${f(result.exclusive.pricePerPyeong)}`);try{await navigator.clipboard.writeText(chunks.join('\n'));setStatus(t.copied)}catch{setStatus('')}}
 const areaInput=(label:string,state:AreaState,setState:(v:AreaState)=>void,prefix:'supply'|'exclusive')=><div className={styles.areaCard}><h3>{label}</h3><label className={styles.field}>{t.area}<span className={styles.withUnit}><input inputMode="decimal" maxLength={TOOL081_LIMITS.maxInputChars} value={state.value} onChange={e=>setState({...state,value:e.target.value})} data-testid={`tool081-${prefix}-area`}/><select value={state.unit} onChange={e=>setState({...state,unit:e.target.value as Tool081AreaUnit})} aria-label={`${label} ${t.unit}`} data-testid={`tool081-${prefix}-unit`}><option value="sqm">{t.sqm}</option><option value="pyeong">{t.pyeong}</option></select></span></label></div>;
 const group=(kind:'supply'|'exclusive')=>{const r=kind==='supply'?result?.supply:result?.exclusive;if(!r)return null;const label=kind==='supply'?t.supply:t.exclusive;return <div className={styles.resultGroup} data-testid={`tool081-${kind}-result`}><h3>{label} · {f(r.area.sqm)} {t.sqm} / {f(r.area.pyeong)} {t.pyeong}</h3><div className={styles.resultGrid}><div className={styles.resultItem}><span>{t.priceSqm}</span><strong data-testid={`tool081-${kind}-price-sqm`}>{f(r.pricePerSqm)}</strong><em>/ {t.sqm}</em></div><div className={styles.resultItem}><span>{t.pricePyeong}</span><strong data-testid={`tool081-${kind}-price-pyeong`}>{f(r.pricePerPyeong)}</strong><em>/ {t.pyeong}</em></div></div></div>};
 return <div className={styles.root} data-testid="tool081-root">
  <div className={styles.localNotice}><strong>LOCAL</strong><span>{t.local}</span></div>
  <section className={styles.workspace} data-testid="tool081-workspace"><div className={styles.workspaceGrid}><div className={styles.card}><div className={styles.cardHead}><strong>AREA CONVERTER</strong><span>{t.convert}</span></div><label className={styles.field}>{t.area}<span className={styles.withUnit}><input inputMode="decimal" maxLength={TOOL081_LIMITS.maxInputChars} value={convertValue} onChange={e=>setConvertValue(e.target.value)} data-testid="tool081-convert-area"/><select value={convertUnit} onChange={e=>setConvertUnit(e.target.value as Tool081AreaUnit)} aria-label={t.unit} data-testid="tool081-convert-unit"><option value="sqm">{t.sqm}</option><option value="pyeong">{t.pyeong}</option></select></span></label>{converted.error&&<p className={styles.error} role="alert" data-testid="tool081-convert-error">{converted.error}</p>}{converted.value&&<div className={styles.converted} aria-live="polite"><div><span>{t.sqm}</span><strong data-testid="tool081-convert-sqm">{f(converted.value.sqm)}</strong></div><div><span>{t.pyeong}</span><strong data-testid="tool081-convert-pyeong">{f(converted.value.pyeong)}</strong></div></div>}</div><div className={styles.card}><div className={styles.cardHead}><strong>UNIT PRICE</strong><span>{t.priceArea}</span></div><div className={styles.inputGrid}><label className={`${styles.field} ${styles.fieldFull}`}>{t.totalPrice}<input inputMode="decimal" maxLength={TOOL081_LIMITS.maxInputChars} value={totalPrice} onChange={e=>setTotalPrice(e.target.value)} data-testid="tool081-total-price"/></label></div><div className={styles.areaCards}>{areaInput(t.supply,supply,setSupply,'supply')}{areaInput(t.exclusive,exclusive,setExclusive,'exclusive')}</div></div></div><div className={styles.actionRow}><button type="button" className={styles.button} onClick={reset} data-testid="tool081-reset">{t.reset}</button><button type="button" className={styles.primaryButton} disabled={!result} onClick={copyResult} data-testid="tool081-copy">{t.copy}</button></div>{calculation.error&&<p className={styles.error} role="alert" data-testid="tool081-error">{calculation.error}</p>}</section>
  <details className={styles.advanced}><summary>{t.precision}</summary><div className={styles.precisionRow}><input type="range" min="0" max={TOOL081_LIMITS.maxDisplayPrecision} value={precision} onChange={e=>setPrecision(Number(e.target.value))} data-testid="tool081-precision"/><span className={styles.precisionValue}>{precision}</span></div></details>
  <section className={styles.resultCard} aria-live="polite" data-testid="tool081-result"><div className={styles.resultHead}><p className={styles.resultLabel}>RESULT · {t.result}</p></div>{!result?<p className={styles.hint}>{calculation.error||t.empty}</p>:<><div className={styles.resultGroups}>{group('supply')}{group('exclusive')}</div><div className={styles.formulaBox}><strong>{t.formula}</strong><code data-testid="tool081-formula">{t.priceSqm} = {t.totalPrice} ÷ {t.area}({t.sqm}) · {t.pricePyeong} = {t.totalPrice} ÷ {t.area}({t.pyeong}) · 1 {t.pyeong} = 3.305785 {t.sqm}</code></div></>}{status&&<p className={styles.status} aria-live="polite">{status}</p>}</section>
 </div>
}
