'use client';
import {useMemo,useState} from 'react';
import type {Locale} from '@/lib/site';
import {TOOL059_LIMITS,TOOL059_PPI_PRESETS,TOOL059_PRESETS,aspectRatio,effectivePpi,formatTool059,fromInches,megapixels,parseTool059,pixelsToPrint,printToPixels,ratioMismatch,readiness,toInches,type Tool059Mode,type Tool059Unit} from '@/lib/tool-059-pixel-print';
import styles from './tool-059-pixel-print-converter.module.css';
const copy={
 ko:{modes:['픽셀 → 인쇄 크기','인쇄 크기 → 픽셀','실제 PPI 계산'],local:'입력값과 계산 결과는 서버로 전송하거나 저장하지 않고 현재 브라우저에서만 계산합니다.',widthPx:'가로 픽셀',heightPx:'세로 픽셀',ppi:'PPI',width:'가로',height:'세로',unit:'단위',presets:'용지·사진 프리셋',ppiPreset:'PPI 빠른 선택',lock:'종횡비 잠금',lockWarn:'잠금을 끄면 가로·세로 비율이 달라져 인쇄 시 왜곡·잘림·여백이 생길 수 있습니다.',reset:'초기화',copy:'결과 복사',copied:'복사됨',result:'계산 결과',empty:'모든 필수 값을 0보다 크게 입력하세요.',invalid:'입력 범위 또는 숫자를 확인하세요.',mismatch:'픽셀 비율과 인쇄 비율이 다릅니다.',mp:'메가픽셀',ratio:'종횡비',orientation:'방향',required:'필요 픽셀',effective:'유효 PPI',printer:'이미지 해상도는 PPI를 기준으로 계산합니다. 프린터 장치 DPI는 별도 개념입니다.',ready:{good:'300 PPI 이상 · 고해상도 참고',caution:'200~299 PPI · 용도 확인',low:'200 PPI 미만 · 확대 인쇄 주의'}},
 en:{modes:['Pixels → Print Size','Print Size → Pixels','Effective PPI'],local:'Values and results are calculated only in this browser and are not sent to or stored on a server.',widthPx:'Pixel width',heightPx:'Pixel height',ppi:'PPI',width:'Width',height:'Height',unit:'Unit',presets:'Paper & photo presets',ppiPreset:'Quick PPI',lock:'Aspect ratio lock',lockWarn:'Turning the lock off can change the aspect ratio and may cause distortion, cropping, or blank margins.',reset:'Reset',copy:'Copy result',copied:'Copied',result:'Result',empty:'Enter every required value above zero.',invalid:'Check the number or supported range.',mismatch:'Pixel and print aspect ratios differ.',mp:'Megapixels',ratio:'Aspect ratio',orientation:'Orientation',required:'Required pixels',effective:'Effective PPI',printer:'Image resolution is calculated in PPI. Printer device DPI is a separate concept.',ready:{good:'300+ PPI · high-resolution reference',caution:'200–299 PPI · check intended use',low:'Below 200 PPI · caution for large prints'}},
 ja:{modes:['ピクセル → 印刷サイズ','印刷サイズ → ピクセル','実効PPI'],local:'入力値と計算結果はサーバーへ送信・保存せず、このブラウザ内だけで計算します。',widthPx:'横ピクセル',heightPx:'縦ピクセル',ppi:'PPI',width:'幅',height:'高さ',unit:'単位',presets:'用紙・写真プリセット',ppiPreset:'PPIクイック選択',lock:'アスペクト比を固定',lockWarn:'固定を解除すると縦横比が変わり、印刷時に歪み・トリミング・余白が生じる場合があります。',reset:'リセット',copy:'結果をコピー',copied:'コピー済み',result:'計算結果',empty:'必須値をすべて0より大きく入力してください。',invalid:'数値または対応範囲を確認してください。',mismatch:'ピクセル比率と印刷比率が異なります。',mp:'メガピクセル',ratio:'アスペクト比',orientation:'向き',required:'必要ピクセル',effective:'実効PPI',printer:'画像解像度はPPIで計算します。プリンター装置のDPIは別の概念です。',ready:{good:'300 PPI以上 · 高解像度の目安',caution:'200～299 PPI · 用途を確認',low:'200 PPI未満 · 大判印刷に注意'}}
} as const;
const num=(v:string)=>parseTool059(v);
export function Tool059PixelPrintConverter({locale}:{locale:Locale}){
 const t=copy[locale];const [mode,setMode]=useState<Tool059Mode>('pixels-to-print');const [wpx,setWpx]=useState('3000');const [hpx,setHpx]=useState('2000');const [ppi,setPpi]=useState('300');const [width,setWidth]=useState('210');const [height,setHeight]=useState('297');const [unit,setUnit]=useState<Tool059Unit>('mm');const [locked,setLocked]=useState(true);const [status,setStatus]=useState('');
 const calc=useMemo(()=>{try{const wp=num(wpx),hp=num(hpx),p=num(ppi),w=num(width),h=num(height);if(mode==='pixels-to-print'){if(wp===null||hp===null||p===null)return null;const r=pixelsToPrint(wp,hp,p);return{kind:'print' as const,...r,mp:megapixels(wp,hp),ratio:aspectRatio(wp,hp),ppi:p};}if(mode==='print-to-pixels'){if(w===null||h===null||p===null)return null;const r=printToPixels(w,h,unit,p);return{kind:'pixels' as const,...r,mp:megapixels(r.widthPx,r.heightPx),ratio:aspectRatio(r.widthPx,r.heightPx),ppi:p};}if(wp===null||hp===null||w===null||h===null)return null;const r=effectivePpi(wp,hp,w,h,unit);return{kind:'ppi' as const,...r,mp:megapixels(wp,hp),ratio:aspectRatio(wp,hp),mismatch:ratioMismatch(wp,hp,toInches(w,unit),toInches(h,unit))};}catch{return{kind:'error' as const};}},[mode,wpx,hpx,ppi,width,height,unit]);
 function reset(){setMode('pixels-to-print');setWpx('3000');setHpx('2000');setPpi('300');setWidth('210');setHeight('297');setUnit('mm');setLocked(true);setStatus('')}
 function applyPreset(id:string){const p=TOOL059_PRESETS.find(x=>x.id===id);if(!p)return;setWidth(String(p.width));setHeight(String(p.height));setUnit(p.unit);setStatus('')}
 function changePhysicalWidth(raw:string){setWidth(raw);if(!locked)return;const w=num(raw),h=num(height),oldW=num(width);if(w&&h&&oldW)setHeight(String(h*w/oldW));}
 function changePhysicalHeight(raw:string){setHeight(raw);if(!locked)return;const h=num(raw),w=num(width),oldH=num(height);if(h&&w&&oldH)setWidth(String(w*h/oldH));}
 function changePixelWidth(raw:string){setWpx(raw);if(!locked)return;const w=num(raw),h=num(hpx),oldW=num(wpx);if(w&&h&&oldW)setHpx(String(Math.round(h*w/oldW)));}
 function changePixelHeight(raw:string){setHpx(raw);if(!locked)return;const h=num(raw),w=num(wpx),oldH=num(hpx);if(h&&w&&oldH)setWpx(String(Math.round(w*h/oldH)));}
 async function copyResult(){if(!calc||calc.kind==='error')return;let text='';if(calc.kind==='print')text=`${wpx}×${hpx}px @ ${ppi} PPI = ${formatTool059(calc.widthIn)}×${formatTool059(calc.heightIn)} in = ${formatTool059(calc.widthCm)}×${formatTool059(calc.heightCm)} cm`;if(calc.kind==='pixels')text=`${width}×${height} ${unit} @ ${ppi} PPI = ${calc.widthPx}×${calc.heightPx}px`;if(calc.kind==='ppi')text=`${wpx}×${hpx}px over ${width}×${height} ${unit} = ${formatTool059(calc.effectivePpi,2)} PPI`;try{await navigator.clipboard.writeText(text);setStatus(t.copied)}catch{setStatus('')}}
 const error=calc?.kind==='error';const ready=calc&&calc.kind!=='error'?(calc.kind==='ppi'?readiness(calc.effectivePpi):readiness(calc.ppi)):null;
 return <div className={styles.root} data-testid="tool059-root" data-mode={mode}>
  <div className={styles.localNotice}><strong>LOCAL</strong><span>{t.local}</span></div>
  <div className={styles.tabs} role="tablist" aria-label="calculation mode">{(['pixels-to-print','print-to-pixels','effective-ppi'] as Tool059Mode[]).map((m,i)=><button key={m} type="button" role="tab" aria-selected={mode===m} className={`${styles.tab} ${mode===m?styles.tabActive:''}`} onClick={()=>{setMode(m);setStatus('')}} data-testid={`tool059-tab-${m}`}>{t.modes[i]}</button>)}</div>
  <section className={styles.workspace} data-testid="tool059-workspace"><div className={styles.card}>
   {(mode==='pixels-to-print'||mode==='effective-ppi')&&<div className={styles.grid}><label className={styles.field}>{t.widthPx}<input inputMode="numeric" value={wpx} onChange={e=>changePixelWidth(e.target.value)} data-testid="tool059-width-px"/></label><label className={styles.field}>{t.heightPx}<input inputMode="numeric" value={hpx} onChange={e=>changePixelHeight(e.target.value)} data-testid="tool059-height-px"/></label></div>}
   {(mode==='print-to-pixels'||mode==='effective-ppi')&&<><div className={styles.grid}><label className={styles.field}>{t.width}<input inputMode="decimal" value={width} onChange={e=>changePhysicalWidth(e.target.value)} data-testid="tool059-width-physical"/></label><label className={styles.field}>{t.height}<input inputMode="decimal" value={height} onChange={e=>changePhysicalHeight(e.target.value)} data-testid="tool059-height-physical"/></label><label className={`${styles.field} ${styles.full}`}>{t.unit}<select value={unit} onChange={e=>setUnit(e.target.value as Tool059Unit)} data-testid="tool059-unit"><option value="in">inch</option><option value="cm">cm</option><option value="mm">mm</option></select></label></div><p className={styles.sectionTitle}>{t.presets}</p><div className={styles.presetRow}>{TOOL059_PRESETS.map(p=><button key={p.id} type="button" className={styles.preset} onClick={()=>applyPreset(p.id)} data-testid={`tool059-preset-${p.id}`}>{p.label}</button>)}</div></>}
   {mode!=='effective-ppi'&&<><label className={styles.field}>{t.ppi}<input inputMode="decimal" value={ppi} onChange={e=>setPpi(e.target.value)} data-testid="tool059-ppi"/></label><p className={styles.sectionTitle}>{t.ppiPreset}</p><div className={styles.ppiRow}>{TOOL059_PPI_PRESETS.map(p=><button key={p} type="button" className={`${styles.preset} ${Number(ppi)===p?styles.presetActive:''}`} onClick={()=>setPpi(String(p))} data-testid={`tool059-ppi-${p}`}>{p}</button>)}</div></>}
   <div className={styles.lockRow}><span>{t.lock}</span><button type="button" role="switch" aria-checked={locked} aria-label={t.lock} className={`${styles.switch} ${locked?styles.switchOn:''}`} onClick={()=>setLocked(v=>!v)} data-testid="tool059-ratio-lock"/></div>{!locked&&<p className={styles.warning}>{t.lockWarn}</p>}
   <div className={styles.actionRow}><button type="button" className={styles.button} onClick={reset} data-testid="tool059-reset">{t.reset}</button><button type="button" className={styles.primaryButton} onClick={copyResult} disabled={!calc||error} data-testid="tool059-copy">{t.copy}</button></div>{error&&<p className={styles.error} role="alert" data-testid="tool059-error">{t.invalid} · px≤{TOOL059_LIMITS.maxPixels.toLocaleString()}, PPI≤{TOOL059_LIMITS.maxPpi}</p>}
  </div><section className={styles.resultCard} aria-live="polite" data-testid="tool059-result"><p className={styles.resultLabel}>RESULT · {t.result}</p>{!calc?<p className={styles.status}>{t.empty}</p>:error?<p className={styles.status}>{t.invalid}</p>:<>
   {calc.kind==='print'&&<><p className={styles.hero} data-testid="tool059-main-result">{formatTool059(calc.widthCm)} × {formatTool059(calc.heightCm)}<span>cm</span></p><div className={styles.resultGrid}><div className={styles.resultItem}><strong>{formatTool059(calc.widthIn)} × {formatTool059(calc.heightIn)}</strong><span>inch</span></div><div className={styles.resultItem}><strong>{formatTool059(calc.widthMm)} × {formatTool059(calc.heightMm)}</strong><span>mm</span></div></div></>}
   {calc.kind==='pixels'&&<p className={styles.hero} data-testid="tool059-main-result">{calc.widthPx.toLocaleString()} × {calc.heightPx.toLocaleString()}<span>px</span></p>}
   {calc.kind==='ppi'&&<><p className={styles.hero} data-testid="tool059-main-result">{formatTool059(calc.effectivePpi,2)}<span>PPI</span></p>{calc.mismatch&&<p className={styles.warning} data-testid="tool059-ratio-warning">{t.mismatch}</p>}</>}
   <div className={styles.resultGrid}><div className={styles.resultItem}><strong>{formatTool059(calc.mp,3)} MP</strong><span>{t.mp}</span></div><div className={styles.resultItem}><strong>{calc.ratio.label}</strong><span>{t.ratio} · {calc.ratio.orientation}</span></div></div>{ready&&<span className={styles.badge} data-testid="tool059-readiness">{t.ready[ready]}</span>}<p className={styles.status}>{t.printer}</p>{status&&<p className={styles.status} role="status">{status}</p>}</>}
  </section></section>
 </div>
}
