'use client';
import {useMemo,useState} from 'react';
import type {Locale} from '@/lib/site';
import {calculateTool079,formatTool079,parseTool079Number} from '@/lib/tool-079-dividend-yield';
import styles from './tool-079-dividend-yield-calculator.module.css';

const copy={
 ko:{local:'입력값은 서버로 전송하지 않고 브라우저에서 계산합니다.',title:'배당 기준 입력',annual:'연간 기준',price:'주가',dps:'연간 주당 배당금',shares:'보유 수량',priceHelp:'배당수익률의 분모가 되는 현재/기준 주가입니다.',dpsHelp:'월·분기 배당이 아니라 1년 기준 주당 배당금으로 입력하세요.',sharesHelp:'현재 보유한 주식 수입니다. 0주도 정상 입력입니다.',formula:'배당수익률 = 연간 주당 배당금 ÷ 주가 × 100 · 예상 연간 배당금 = 연간 주당 배당금 × 보유 수량',result:'계산 결과',yield:'배당수익률',annualDividend:'예상 연간 배당금',basis:'연간 기준 · 세전 reference',reset:'초기화',copy:'결과 복사',copied:'결과를 복사했습니다.',empty:'주가, 연간 주당 배당금, 보유 수량을 입력하면 결과가 즉시 표시됩니다.',priceError:'주가는 0보다 커야 합니다.',negative:'주당 배당금과 보유 수량은 0 이상이어야 합니다.',limit:'입력값이 서비스 유효상한을 초과했습니다.',invalid:'숫자 입력을 확인하세요.',scenario:'시나리오 비교',scenarioDesc:'같은 배당금에서 주가 변화에 따른 배당수익률을 비교합니다.',a:'시나리오 A',b:'시나리오 B'},
 en:{local:'Inputs stay in your browser and are not sent to a server.',title:'Dividend inputs',annual:'Annual basis',price:'Share price',dps:'Annual dividend per share',shares:'Shares held',priceHelp:'The current/reference share price used as the yield denominator.',dpsHelp:'Enter the annual dividend per share, not a monthly or quarterly payment.',sharesHelp:'Your current share count. Zero shares is a valid input.',formula:'Dividend yield = annual DPS ÷ share price × 100 · Expected annual dividend = annual DPS × shares',result:'Calculation result',yield:'Dividend yield',annualDividend:'Expected annual dividend',basis:'Annual basis · pre-tax reference',reset:'Reset',copy:'Copy result',copied:'Result copied.',empty:'Enter share price, annual dividend per share, and shares held to see results instantly.',priceError:'Share price must be greater than zero.',negative:'Dividend per share and shares held must be zero or greater.',limit:'An input exceeds the service limit.',invalid:'Check the numeric inputs.',scenario:'Scenario comparison',scenarioDesc:'Compare dividend yield at different share prices with the same annual dividend.',a:'Scenario A',b:'Scenario B'},
 ja:{local:'入力値はサーバーへ送信せず、ブラウザ内で計算します。',title:'配当基準の入力',annual:'年間基準',price:'株価',dps:'年間1株当たり配当金',shares:'保有株数',priceHelp:'配当利回りの分母となる現在・基準株価です。',dpsHelp:'月次・四半期配当ではなく、年間の1株当たり配当金を入力します。',sharesHelp:'現在の保有株数です。0株も有効な入力です。',formula:'配当利回り = 年間1株当たり配当金 ÷ 株価 × 100 · 予想年間配当金 = 年間1株当たり配当金 × 保有株数',result:'計算結果',yield:'配当利回り',annualDividend:'予想年間配当金',basis:'年間基準・税引前参考値',reset:'リセット',copy:'結果をコピー',copied:'結果をコピーしました。',empty:'株価、年間1株当たり配当金、保有株数を入力すると結果が表示されます。',priceError:'株価は0より大きい値を入力してください。',negative:'1株当たり配当金と保有株数は0以上で入力してください。',limit:'入力値がサービス上限を超えています。',invalid:'数値入力を確認してください。',scenario:'シナリオ比較',scenarioDesc:'同じ配当金で株価が変わった場合の配当利回りを比較します。',a:'シナリオA',b:'シナリオB'}
} as const;
const lc=(l:Locale)=>l==='ko'?'ko-KR':l==='ja'?'ja-JP':'en-US';

export function Tool079DividendYieldCalculator({locale}:{locale:Locale}){
 const t=copy[locale];const [price,setPrice]=useState('');const [dps,setDps]=useState('');const [shares,setShares]=useState('');const [status,setStatus]=useState('');
 const calc=useMemo(()=>{const p=parseTool079Number(price),d=parseTool079Number(dps),s=parseTool079Number(shares);if(p===null||d===null||s===null)return {result:null,error:''};try{return {result:calculateTool079({sharePrice:p,annualDps:d,shares:s}),error:''}}catch(e){const m=e instanceof Error?e.message:'';return {result:null,error:m==='SHARE_PRICE_ZERO_OR_NEGATIVE'?t.priceError:m.includes('NEGATIVE')?t.negative:m.includes('LIMIT')?t.limit:t.invalid}}},[price,dps,shares,t]);
 const reset=()=>{setPrice('');setDps('');setShares('');setStatus('')};
 const copyResult=async()=>{if(!calc.result)return;const r=calc.result;const text=`${t.yield}: ${formatTool079(r.dividendYield,2,lc(locale))}%\n${t.annualDividend}: ${formatTool079(r.expectedAnnualDividend,2,lc(locale))}\n${t.basis}`;try{await navigator.clipboard.writeText(text);setStatus(t.copied)}catch{setStatus(text)}};
 return <div className={styles.root} data-testid="tool079-root">
  <div className={styles.localNotice}><strong>LOCAL</strong><span>{t.local}</span></div>
  <div className={styles.workspace}>
   <section className={styles.card}><div className={styles.cardHead}><h3>{t.title}</h3><span className={styles.annualBadge} data-testid="tool079-annual-basis">{t.annual}</span></div><div className={styles.inputGrid}>
    <label className={styles.field}><span>{t.price}</span><input data-testid="tool079-share-price" inputMode="decimal" maxLength={30} value={price} onChange={e=>setPrice(e.target.value)} placeholder="0"/><small>{t.priceHelp}</small></label>
    <label className={styles.field}><span>{t.dps}</span><input data-testid="tool079-annual-dps" inputMode="decimal" maxLength={30} value={dps} onChange={e=>setDps(e.target.value)} placeholder="0"/><small>{t.dpsHelp}</small></label>
    <label className={styles.field}><span>{t.shares}</span><input data-testid="tool079-shares" inputMode="decimal" maxLength={30} value={shares} onChange={e=>setShares(e.target.value)} placeholder="0"/><small>{t.sharesHelp}</small></label>
   </div><p className={styles.formulaPreview} data-testid="tool079-formula">{t.formula}</p>{calc.error&&<p className={styles.error} role="alert" data-testid="tool079-error">{calc.error}</p>}<div className={styles.actionRow}><button className={styles.button} type="button" onClick={reset}>{t.reset}</button></div></section>
   <section className={styles.resultCard} aria-live="polite"><div className={styles.resultHead}><p className={styles.resultLabel}>{t.result}</p><span className={styles.annualBadge}>{t.basis}</span></div>{!calc.result?<p className={styles.hint}>{calc.error||t.empty}</p>:<><div className={styles.yieldValue}><strong data-testid="tool079-dividend-yield">{formatTool079(calc.result.dividendYield,2,lc(locale))}%</strong><span>{t.yield}</span></div><div className={styles.dividendCard}><b>{t.annualDividend}</b><strong data-testid="tool079-expected-dividend">{formatTool079(calc.result.expectedAnnualDividend,2,lc(locale))}</strong></div><div className={styles.resultGrid}><div><b>{t.price}</b><span>{formatTool079(calc.result.sharePrice,2,lc(locale))}</span></div><div><b>{t.dps}</b><span>{formatTool079(calc.result.annualDps,2,lc(locale))}</span></div><div><b>{t.shares}</b><span>{formatTool079(calc.result.shares,2,lc(locale))}</span></div><div><b>{t.annual}</b><strong>{t.basis}</strong></div></div><button className={styles.button} type="button" onClick={copyResult}>{t.copy}</button>{status&&<p className={styles.status}>{status}</p>}</>}
   </section>
  </div>
  <details className={styles.advanced}><summary>{t.scenario}</summary><p className={styles.hint}>{t.scenarioDesc}</p><ScenarioCompare locale={locale} titleA={t.a} titleB={t.b} labels={{price:t.price,dps:t.dps}}/></details>
 </div>
}
function ScenarioCompare({locale,titleA,titleB,labels}:{locale:Locale;titleA:string;titleB:string;labels:{price:string;dps:string}}){const [v,setV]=useState({ap:'',ad:'',bp:'',bd:''});const one=(p:string,d:string)=>{const price=parseTool079Number(p),dps=parseTool079Number(d);if(price===null||dps===null)return '—';try{return `${formatTool079(calculateTool079({sharePrice:price,annualDps:dps,shares:0}).dividendYield,2,lc(locale))}%`}catch{return '—'}};const box=(x:'a'|'b',title:string)=>{const pk=`${x}p` as keyof typeof v,dk=`${x}d` as keyof typeof v;return <div className={styles.scenarioBox}><strong>{title}</strong><label className={styles.field}><span>{labels.price}</span><input data-testid={`tool079-scenario-${x}-price`} value={v[pk]} onChange={e=>setV(o=>({...o,[pk]:e.target.value}))}/></label><label className={styles.field}><span>{labels.dps}</span><input data-testid={`tool079-scenario-${x}-dps`} value={v[dk]} onChange={e=>setV(o=>({...o,[dk]:e.target.value}))}/></label><span className={styles.scenarioResult} data-testid={`tool079-scenario-${x}-result`}>{one(v[pk],v[dk])}</span></div>};return <div className={styles.scenarioGrid}>{box('a',titleA)}{box('b',titleB)}</div>}
