'use client';
import {useMemo,useState} from 'react';
import type {Locale} from '@/lib/site';
import {calculateTool078,formatTool078,parseTool078Number,TOOL078_LIMITS,type Tool078PurchaseLot} from '@/lib/tool-078-stock-average-cost';
import styles from './tool-078-stock-average-cost-calculator.module.css';

type Row={id:number;qty:string;price:string};
const copy={
 ko:{local:'입력한 보유 수량과 매수가는 서버로 전송하거나 저장하지 않고 현재 브라우저에서만 계산합니다.',existing:'기존 포지션',existingHint:'현재 보유 중인 같은 종목의 수량과 평균 매수가를 입력합니다.',shares:'기존 수량',price:'기존 단가',additional:'추가 매수',additionalHint:'추가 매수는 여러 회차로 입력할 수 있으며 수량 가중평균으로 즉시 합산됩니다.',add:'추가 매수 행',addQty:'추가 수량',addPrice:'추가 단가',remove:'행 삭제',reset:'초기화',copy:'결과 복사',copied:'복사됨',precision:'표시 소수점',result:'평균단가 결과',avg:'평균단가',totalShares:'총 보유수량',totalCost:'총 매입금액',additionalShares:'추가매수 총수량',breakEven:'손익분기 가격',target:'목표 매도가',targetReturn:'목표수익률 (%)',targetPrice:'목표 매도가',formula:'계산식',lotSummary:'매수내역 요약',empty:'필수 값을 입력하세요.',invalid:'올바른 숫자를 입력하세요.',positive:'수량과 기존 단가는 0보다 커야 합니다.',negativePrice:'추가 매수 단가는 0 이상이어야 합니다.',limit:'입력값이 서비스 유효상한을 초과했습니다.',rowsLimit:'추가 매수는 최대 100회까지 입력할 수 있습니다.',reference:'수수료·세금을 반영하지 않은 비용 0 기준 reference입니다.',noAdditional:'추가매수 없음'},
 en:{local:'Share quantities and purchase prices are calculated only in this browser and are not sent to or stored on a server.',existing:'Existing Position',existingHint:'Enter the shares already held and their current average acquisition price.',shares:'Existing Shares',price:'Existing Price',additional:'Additional Buys',additionalHint:'Add multiple purchase lots. Each lot is combined by quantity-weighted average.',add:'Add purchase row',addQty:'Additional Shares',addPrice:'Additional Price',remove:'Remove row',reset:'Reset',copy:'Copy result',copied:'Copied',precision:'Display decimals',result:'Average-cost result',avg:'Average Cost',totalShares:'Total Shares',totalCost:'Total Cost',additionalShares:'Additional Shares',breakEven:'Break-even Price',target:'Target Sell Price',targetReturn:'Target Return (%)',targetPrice:'Target Sell Price',formula:'Formula',lotSummary:'Purchase summary',empty:'Enter the required values.',invalid:'Enter valid numbers.',positive:'Share quantities and existing price must be greater than zero.',negativePrice:'Additional purchase price must be zero or greater.',limit:'An input exceeds the service limit.',rowsLimit:'Up to 100 additional purchase rows are supported.',reference:'Reference assumes zero fees and taxes.',noAdditional:'No additional buys'},
 ja:{local:'入力した保有株数と取得価格はサーバーへ送信・保存せず、このブラウザ内だけで計算します。',existing:'既存ポジション',existingHint:'現在保有している同一銘柄の株数と平均取得単価を入力します。',shares:'保有株数',price:'既存単価',additional:'追加購入',additionalHint:'追加購入は複数回入力でき、株数で加重平均して即時集計します。',add:'追加購入行',addQty:'追加株数',addPrice:'追加単価',remove:'行を削除',reset:'リセット',copy:'結果をコピー',copied:'コピー済み',precision:'表示小数点',result:'平均取得単価の結果',avg:'平均取得単価',totalShares:'保有総株数',totalCost:'総取得金額',additionalShares:'追加購入総株数',breakEven:'損益分岐価格',target:'目標売却価格',targetReturn:'目標収益率 (%)',targetPrice:'目標売却価格',formula:'計算式',lotSummary:'購入履歴の概要',empty:'必須項目を入力してください。',invalid:'有効な数値を入力してください。',positive:'株数と既存単価は0より大きくしてください。',negativePrice:'追加購入単価は0以上にしてください。',limit:'入力値がサービス上限を超えています。',rowsLimit:'追加購入は最大100回まで入力できます。',reference:'手数料・税金を反映しないコスト0基準のreferenceです。',noAdditional:'追加購入なし'}
} as const;
const INITIAL_ROWS:Row[]=[{id:1,qty:'50',price:'8000'}];
function localeCode(locale:Locale){return locale==='ko'?'ko-KR':locale==='ja'?'ja-JP':'en-US'}

export function Tool078StockAverageCostCalculator({locale}:{locale:Locale}){
 const t=copy[locale];const [existingQty,setExistingQty]=useState('100');const [existingPrice,setExistingPrice]=useState('10000');const [rows,setRows]=useState<Row[]>(INITIAL_ROWS);const [targetReturn,setTargetReturn]=useState('10');const [precision,setPrecision]=useState(2);const [status,setStatus]=useState('');const [nextId,setNextId]=useState(2);
 const parsed=useMemo(()=>{
  const eq=parseTool078Number(existingQty),ep=parseTool078Number(existingPrice);const tr=targetReturn.trim()===''?null:parseTool078Number(targetReturn);
  if(eq===null||ep===null||tr===null&&targetReturn.trim()!=='')return {result:null,error:t.invalid,lots:[] as Tool078PurchaseLot[]};
  const lots:Tool078PurchaseLot[]=[];
  for(const row of rows){const blank=row.qty.trim()===''&&row.price.trim()==='';if(blank)continue;const qty=parseTool078Number(row.qty),price=parseTool078Number(row.price);if(qty===null||price===null)return {result:null,error:t.invalid,lots};lots.push({qty,price});}
  try{return {result:calculateTool078(eq,ep,lots,tr),error:'',lots}}catch(e){const code=e instanceof Error?e.message:'';return {result:null,error:code==='ROWS_LIMIT'?t.rowsLimit:code.includes('LIMIT')?t.limit:code.includes('PRICE_NEGATIVE')?t.negativePrice:code.includes('NON_POSITIVE')?t.positive:t.invalid,lots};}
 },[existingQty,existingPrice,rows,targetReturn,t]);
 const result=parsed.result;const f=(v:number)=>formatTool078(v,precision,localeCode(locale));
 function addRow(){if(rows.length>=TOOL078_LIMITS.maxRows){setStatus(t.rowsLimit);return}setRows([...rows,{id:nextId,qty:'',price:''}]);setNextId(nextId+1);setStatus('')}
 function removeRow(id:number){setRows(rows.filter(r=>r.id!==id));setStatus('')}
 function reset(){setExistingQty('100');setExistingPrice('10000');setRows(INITIAL_ROWS);setTargetReturn('10');setPrecision(2);setNextId(2);setStatus('')}
 async function copyResult(){if(!result)return;const lotText=parsed.lots.length?parsed.lots.map((lot,i)=>`#${i+1} ${f(lot.qty)} × ${f(lot.price)}`).join(' / '):t.noAdditional;const text=`${t.totalShares}: ${f(result.totalShares)} | ${t.totalCost}: ${f(result.totalCost)} | ${t.avg}: ${f(result.averageCost)} | ${t.breakEven}: ${f(result.breakEvenPrice)}${result.targetSellPrice!==null?` | ${t.targetPrice}: ${f(result.targetSellPrice)}`:''} | ${t.lotSummary}: ${lotText}`;try{await navigator.clipboard.writeText(text);setStatus(t.copied)}catch{setStatus('')}}
 return <div className={styles.root} data-testid="tool078-root">
  <div className={styles.localNotice}><strong>LOCAL</strong><span>{t.local}</span></div>
  <section className={styles.workspace} data-testid="tool078-workspace">
   <div className={styles.sectionCard}><div className={styles.sectionHead}><strong>{t.existing}</strong><span>{t.existingHint}</span></div><div className={styles.inputGrid}><label className={styles.field}>{t.shares}<input inputMode="decimal" maxLength={TOOL078_LIMITS.maxInputChars} value={existingQty} onChange={e=>setExistingQty(e.target.value)} data-testid="tool078-existing-qty"/></label><label className={styles.field}>{t.price}<input inputMode="decimal" maxLength={TOOL078_LIMITS.maxInputChars} value={existingPrice} onChange={e=>setExistingPrice(e.target.value)} data-testid="tool078-existing-price"/></label></div></div>
   <div className={styles.sectionCard}><div className={styles.sectionHead}><strong>{t.additional}</strong><span>{t.additionalHint}</span></div><div className={styles.rows}>{rows.map((row,index)=><div className={styles.purchaseRow} key={row.id} data-testid={`tool078-row-${index+1}`}><span className={styles.rowIndex}>BUY {String(index+1).padStart(2,'0')}</span><label className={styles.field}>{t.addQty}<input inputMode="decimal" maxLength={TOOL078_LIMITS.maxInputChars} value={row.qty} onChange={e=>setRows(rows.map(r=>r.id===row.id?{...r,qty:e.target.value}:r))} data-testid={`tool078-row-${index+1}-qty`}/></label><label className={styles.field}>{t.addPrice}<input inputMode="decimal" maxLength={TOOL078_LIMITS.maxInputChars} value={row.price} onChange={e=>setRows(rows.map(r=>r.id===row.id?{...r,price:e.target.value}:r))} data-testid={`tool078-row-${index+1}-price`}/></label><button type="button" className={styles.removeButton} onClick={()=>removeRow(row.id)} aria-label={`${t.remove} ${index+1}`} data-testid={`tool078-row-${index+1}-remove`}>{t.remove}</button></div>)}</div><button type="button" className={styles.addButton} onClick={addRow} data-testid="tool078-add-row">+ {t.add}</button></div>
   <div className={styles.actionRow}><button type="button" className={styles.button} onClick={reset} data-testid="tool078-reset">{t.reset}</button><button type="button" className={styles.primaryButton} disabled={!result} onClick={copyResult} data-testid="tool078-copy">{t.copy}</button></div>{parsed.error&&<p className={styles.error} role="alert" data-testid="tool078-error">{parsed.error}</p>}
  </section>
  <details className={styles.advanced}><summary>{t.precision}</summary><div className={styles.precisionRow}><input aria-label={t.precision} type="range" min="0" max={TOOL078_LIMITS.maxPrecision} value={precision} onChange={e=>setPrecision(Number(e.target.value))} data-testid="tool078-precision"/><span className={styles.precisionValue}>{precision}</span></div></details>
  <section className={styles.resultCard} aria-live="polite" data-testid="tool078-result"><div className={styles.resultHead}><p className={styles.resultLabel}>RESULT · {t.result}</p><span className={styles.averageCaption}>{t.reference}</span></div>{!result?<p className={styles.hint}>{parsed.error||t.empty}</p>:<><span className={styles.averageCaption}>{t.avg}</span><strong className={styles.averageValue} data-testid="tool078-average-cost">{f(result.averageCost)}</strong><div className={styles.metrics}><div className={styles.metric}><span>{t.totalShares}</span><strong data-testid="tool078-total-shares">{f(result.totalShares)}</strong></div><div className={styles.metric}><span>{t.totalCost}</span><strong data-testid="tool078-total-cost">{f(result.totalCost)}</strong></div><div className={styles.metric}><span>{t.additionalShares}</span><strong data-testid="tool078-additional-shares">{f(result.additionalQty)}</strong></div><div className={styles.metric}><span>{t.breakEven}</span><strong data-testid="tool078-break-even">{f(result.breakEvenPrice)}</strong></div></div><div className={styles.formulaBox}><strong>{t.formula}</strong><code data-testid="tool078-formula">Average Cost = Total Cost ÷ Total Shares = ({f(result.existingCost)} + {f(result.additionalCost)}) ÷ {f(result.totalShares)}</code><strong>{t.lotSummary}</strong><code>{parsed.lots.length?parsed.lots.map((lot,i)=>`#${i+1} ${f(lot.qty)} × ${f(lot.price)}`).join(' / '):t.noAdditional}</code></div></>}{status&&<p className={styles.status} aria-live="polite">{status}</p>}</section>
  <section className={styles.targetCard} data-testid="tool078-target-card"><div className={styles.sectionHead}><strong>{t.target}</strong><span>Average Cost × (1 + Return)</span></div><div className={styles.targetGrid}><label className={styles.field}>{t.targetReturn}<input inputMode="decimal" maxLength={TOOL078_LIMITS.maxInputChars} value={targetReturn} onChange={e=>setTargetReturn(e.target.value)} data-testid="tool078-target-return"/></label><div className={styles.targetValue}><span>{t.targetPrice}</span><strong data-testid="tool078-target-sell">{result?.targetSellPrice!==null&&result?.targetSellPrice!==undefined?f(result.targetSellPrice):'—'}</strong></div></div></section>
 </div>
}
