export const TOOL069_LIMITS={maxAmount:1e15,maxUnits:1e12,maxInputChars:30,maxPrecision:8} as const;
export type Tool069Mode='basic'|'target-profit'|'volume';
export type Tool069Result={fixedCost:number,sellingPrice:number,variableCost:number,contribution:number,contributionRatio:number,breakEvenUnits:number,practicalUnits:number,breakEvenRevenue:number,possible:boolean};
function assertAmount(v:number,label:string){if(!Number.isFinite(v))throw new Error(`${label}_INVALID`);if(v<0)throw new Error(`${label}_NEGATIVE`);if(Math.abs(v)>TOOL069_LIMITS.maxAmount)throw new Error(`${label}_LIMIT`)}
export function parseTool069Number(raw:string):number|null{const s=raw.replace(/[,_\s₩¥$€]/g,'').trim();if(!s||s.length>TOOL069_LIMITS.maxInputChars)return null;const v=Number(s);return Number.isFinite(v)?v:null}
export function calculateBreakEven(fixedCost:number,sellingPrice:number,variableCost:number):Tool069Result{assertAmount(fixedCost,'FIXED');assertAmount(sellingPrice,'SELLING');assertAmount(variableCost,'VARIABLE');const contribution=sellingPrice-variableCost;const possible=contribution>0&&sellingPrice>0;if(!possible)return{fixedCost,sellingPrice,variableCost,contribution,contributionRatio:sellingPrice>0?contribution/sellingPrice:0,breakEvenUnits:Infinity,practicalUnits:Infinity,breakEvenRevenue:Infinity,possible:false};const contributionRatio=contribution/sellingPrice;const breakEvenUnits=fixedCost/contribution;return{fixedCost,sellingPrice,variableCost,contribution,contributionRatio,breakEvenUnits,practicalUnits:Math.ceil(breakEvenUnits),breakEvenRevenue:fixedCost/contributionRatio,possible:true}}
export function calculateTargetProfitUnits(fixedCost:number,targetProfit:number,contribution:number){assertAmount(fixedCost,'FIXED');assertAmount(targetProfit,'TARGET');if(!Number.isFinite(contribution)||contribution<=0)throw new Error('CONTRIBUTION_IMPOSSIBLE');return(fixedCost+targetProfit)/contribution}
export function calculateProfitAtVolume(units:number,fixedCost:number,contribution:number){if(!Number.isFinite(units)||units<0||units>TOOL069_LIMITS.maxUnits)throw new Error('UNITS_LIMIT');assertAmount(fixedCost,'FIXED');if(!Number.isFinite(contribution))throw new Error('CONTRIBUTION_INVALID');return units*contribution-fixedCost}
export function calculateMarginOfSafety(units:number,breakEvenUnits:number){if(!Number.isFinite(units)||units<0||units>TOOL069_LIMITS.maxUnits)throw new Error('UNITS_LIMIT');if(!Number.isFinite(breakEvenUnits))return{units:NaN,ratio:NaN};const diff=units-breakEvenUnits;return{units:diff,ratio:units===0?0:diff/units}}
export function formatTool069(v:number,precision=2,locale='ko-KR'){if(!Number.isFinite(v))return '—';const d=Math.max(0,Math.min(TOOL069_LIMITS.maxPrecision,precision));return new Intl.NumberFormat(locale,{maximumFractionDigits:d}).format(v)}
