export const TOOL072_LIMITS={maxSalary:1e15,maxHoursPerDay:24,maxWorkdaysPerMonth:31,maxMonthsPerYear:12,maxAnnualPaidHours:8784,maxInputChars:30,maxDisplayPrecision:8} as const;
export type Tool072Unit='hourly'|'daily'|'monthly'|'annual';
export type Tool072Profile={hoursPerDay:number;workdaysPerMonth:number;monthsPerYear:number;monthlyPaidHours?:number|null;annualPaidHours?:number|null};
export type Tool072Result={hourly:number;daily:number;monthly:number;annual:number;monthlyPaidHours:number;annualPaidHours:number;monthlyHoursSource:'direct'|'derived';annualHoursSource:'direct'|'derived';formula:string};
function finitePositive(v:number,label:string,max:number){if(!Number.isFinite(v))throw new Error(`${label}_INVALID`);if(v<=0)throw new Error(`${label}_ZERO`);if(v>max)throw new Error(`${label}_LIMIT`)}
function salary(v:number){if(!Number.isFinite(v))throw new Error('SALARY_INVALID');if(v<0)throw new Error('SALARY_NEGATIVE');if(v>TOOL072_LIMITS.maxSalary)throw new Error('SALARY_LIMIT')}
export function parseTool072Number(raw:string):number|null{const s=raw.replace(/[,_\s₩¥$€]/g,'').trim();if(!s||s.length>TOOL072_LIMITS.maxInputChars)return null;const n=Number(s);return Number.isFinite(n)?n:null}
export function resolveTool072Profile(p:Tool072Profile){finitePositive(p.hoursPerDay,'HOURS_DAY',TOOL072_LIMITS.maxHoursPerDay);finitePositive(p.workdaysPerMonth,'WORKDAYS_MONTH',TOOL072_LIMITS.maxWorkdaysPerMonth);finitePositive(p.monthsPerYear,'MONTHS_YEAR',TOOL072_LIMITS.maxMonthsPerYear);const derivedMonthly=p.hoursPerDay*p.workdaysPerMonth;const monthly=p.monthlyPaidHours==null?derivedMonthly:p.monthlyPaidHours;finitePositive(monthly,'MONTHLY_HOURS',TOOL072_LIMITS.maxAnnualPaidHours);const derivedAnnual=p.hoursPerDay*p.workdaysPerMonth*p.monthsPerYear;const annual=p.annualPaidHours==null?derivedAnnual:p.annualPaidHours;finitePositive(annual,'ANNUAL_HOURS',TOOL072_LIMITS.maxAnnualPaidHours);const monthlyHoursSource:'direct'|'derived'=p.monthlyPaidHours==null?'derived':'direct';const annualHoursSource:'direct'|'derived'=p.annualPaidHours==null?'derived':'direct';return{monthlyPaidHours:monthly,annualPaidHours:annual,monthlyHoursSource,annualHoursSource}}
export function convertTool072(unit:Tool072Unit,amount:number,p:Tool072Profile):Tool072Result{salary(amount);const r=resolveTool072Profile(p);let hourly=0,daily=0,monthly=0,annual=0,formula='';if(unit==='hourly'){hourly=amount;daily=hourly*p.hoursPerDay;monthly=hourly*r.monthlyPaidHours;annual=hourly*r.annualPaidHours;formula='daily=hourly×hours/day; monthly=hourly×paid hours/month; annual=hourly×paid hours/year'}else if(unit==='daily'){daily=amount;hourly=daily/p.hoursPerDay;monthly=daily*p.workdaysPerMonth;annual=monthly*p.monthsPerYear;formula='hourly=daily÷hours/day; monthly=daily×workdays/month; annual=monthly×months/year'}else if(unit==='monthly'){monthly=amount;hourly=monthly/r.monthlyPaidHours;daily=monthly/p.workdaysPerMonth;annual=monthly*p.monthsPerYear;formula='hourly=monthly÷paid hours/month; daily=monthly÷workdays/month; annual=monthly×months/year'}else{annual=amount;hourly=annual/r.annualPaidHours;monthly=annual/p.monthsPerYear;daily=monthly/p.workdaysPerMonth;formula='hourly=annual÷paid hours/year; monthly=annual÷months/year; daily=monthly÷workdays/month'}return{hourly,daily,monthly,annual,...r,formula}}
export function formatTool072(v:number,precision=0,locale='ko-KR'){const d=Math.max(0,Math.min(TOOL072_LIMITS.maxDisplayPrecision,precision));return new Intl.NumberFormat(locale,{maximumFractionDigits:d,minimumFractionDigits:d}).format(v)}
