export const TOOL084_LIMITS={maxArea:1e9,maxCoats:100,maxCoverage:1e6,maxContainerVolume:1e9,maxRollArea:1e6,minWaste:0,maxWaste:100,maxDisplayPrecision:8,maxInputChars:30} as const;
export type PaintInput={area:number;coats:number;coverage:number;waste:number;containerVolume?:number|null};
export type PaintResult={baseArea:number;coats:number;totalSurface:number;adjustedSurface:number;paintVolume:number;containers:number|null;waste:number;coverage:number;containerVolume:number|null};
export type WallpaperInput={area:number;usableAreaPerRoll:number;waste:number};
export type WallpaperResult={baseArea:number;adjustedArea:number;rolls:number;waste:number;usableAreaPerRoll:number};
function finite(v:number,code:string){if(!Number.isFinite(v))throw new Error(`${code}_INVALID`)}
function positive(v:number,max:number,code:string){finite(v,code);if(v<=0)throw new Error(`${code}_REQUIRED`);if(v>max)throw new Error(`${code}_LIMIT`)}
function waste(v:number){finite(v,'WASTE');if(v<TOOL084_LIMITS.minWaste||v>TOOL084_LIMITS.maxWaste)throw new Error('WASTE_RANGE')}
export function parseTool084Number(raw:string):number|null{const s=raw.replace(/[,_\s㎡m²Ll%]/gi,'').trim();if(!s||s.length>TOOL084_LIMITS.maxInputChars)return null;const n=Number(s);return Number.isFinite(n)?n:null}
export function calculatePaint(input:PaintInput):PaintResult{positive(input.area,TOOL084_LIMITS.maxArea,'AREA');positive(input.coats,TOOL084_LIMITS.maxCoats,'COATS');if(!Number.isInteger(input.coats))throw new Error('COATS_INTEGER');positive(input.coverage,TOOL084_LIMITS.maxCoverage,'COVERAGE');waste(input.waste);if(input.containerVolume!=null)positive(input.containerVolume,TOOL084_LIMITS.maxContainerVolume,'CONTAINER');const totalSurface=input.area*input.coats;const adjustedSurface=totalSurface*(1+input.waste/100);const paintVolume=adjustedSurface/input.coverage;const containers=input.containerVolume==null?null:Math.ceil(paintVolume/input.containerVolume);if(![totalSurface,adjustedSurface,paintVolume].every(Number.isFinite))throw new Error('RESULT_INVALID');return{baseArea:input.area,coats:input.coats,totalSurface,adjustedSurface,paintVolume,containers,waste:input.waste,coverage:input.coverage,containerVolume:input.containerVolume??null}}
export function calculateWallpaper(input:WallpaperInput):WallpaperResult{positive(input.area,TOOL084_LIMITS.maxArea,'AREA');positive(input.usableAreaPerRoll,TOOL084_LIMITS.maxRollArea,'ROLL_AREA');waste(input.waste);const adjustedArea=input.area*(1+input.waste/100);const rolls=Math.ceil(adjustedArea/input.usableAreaPerRoll);if(!Number.isFinite(adjustedArea)||!Number.isFinite(rolls))throw new Error('RESULT_INVALID');return{baseArea:input.area,adjustedArea,rolls,waste:input.waste,usableAreaPerRoll:input.usableAreaPerRoll}}
export function formatTool084(value:number,precision=2,locale='ko-KR'){const d=Math.max(0,Math.min(TOOL084_LIMITS.maxDisplayPrecision,precision));return new Intl.NumberFormat(locale,{maximumFractionDigits:d,minimumFractionDigits:0}).format(value)}
