export const TOOL068_LIMITS={maxAmount:1e15,maxRate:100,maxInputChars:30,maxCostLines:10} as const;
export type Tool068Mode='settlement'|'profit'|'target-profit';
export type Tool068Input={sale:number;rate:number;fixedFee:number;sellerShipping:number;otherCost:number;buyerShipping:number;productCost:number};
export type Tool068Result=Tool068Input&{commission:number;totalFee:number;settlement:number;netProfit:number;netMargin:number;effectiveFeeRate:number;revenueBase:number};
function money(v:number,label:string){if(!Number.isFinite(v))throw new Error(`${label}_INVALID`);if(v<0)throw new Error(`${label}_NEGATIVE`);if(v>TOOL068_LIMITS.maxAmount)throw new Error(`${label}_LIMIT`)}
export function parseTool068Number(raw:string){const n=raw.replace(/[,_\s₩¥$€]/g,'').trim();if(!n||n.length>TOOL068_LIMITS.maxInputChars)return null;const v=Number(n);return Number.isFinite(v)?v:null}
export function validateTool068Input(i:Tool068Input){for(const [k,v] of Object.entries(i))if(k!=='rate')money(v,k.toUpperCase());if(!Number.isFinite(i.rate))throw new Error('RATE_INVALID');if(i.rate<0)throw new Error('RATE_NEGATIVE');if(i.rate>TOOL068_LIMITS.maxRate)throw new Error('RATE_LIMIT')}
export function calculateTool068(i:Tool068Input):Tool068Result{validateTool068Input(i);const commission=i.sale*(i.rate/100);const totalFee=commission+i.fixedFee;const revenueBase=i.sale+i.buyerShipping;const settlement=revenueBase-totalFee-i.sellerShipping-i.otherCost;const netProfit=settlement-i.productCost;const netMargin=revenueBase===0?0:(netProfit/revenueBase)*100;const effectiveFeeRate=i.sale===0?(totalFee===0?0:Infinity):(totalFee/i.sale)*100;return{...i,commission,totalFee,settlement,netProfit,netMargin,effectiveFeeRate,revenueBase}}
export function requiredSaleForTarget({rate,fixedFee,sellerShipping,otherCost,buyerShipping,productCost,targetProfit}:{rate:number;fixedFee:number;sellerShipping:number;otherCost:number;buyerShipping:number;productCost:number;targetProfit:number}){for(const [k,v] of Object.entries({fixedFee,sellerShipping,otherCost,buyerShipping,productCost,targetProfit}))money(v,k.toUpperCase());if(!Number.isFinite(rate)||rate<0||rate>100)throw new Error('RATE_LIMIT');const keep=1-rate/100;if(keep<=0)throw new Error('TARGET_UNAVAILABLE');const required=(productCost+sellerShipping+otherCost+fixedFee+targetProfit-buyerShipping)/keep;return Math.max(0,required)}
export function formatTool068(v:number,locale='ko-KR'){if(!Number.isFinite(v))return '—';return new Intl.NumberFormat(locale,{maximumFractionDigits:2}).format(v)}
