export const TOOL076_LIMITS={maxPurchase:1e15,maxRate:100,minMonths:1,maxMonths:120,maxScenarios:4,maxDisplayPrecision:8,maxInputChars:30} as const;
export type Tool076Result={purchase:number;months:number;rate:number;totalFee:number;totalPayment:number;monthlyPayment:number;interestFree:boolean;formula:string};
export type Tool076Scenario=Tool076Result&{isLowestMonthly:boolean;isLowestTotal:boolean};
function finite(value:number,label:string){if(!Number.isFinite(value))throw new Error(`${label}_INVALID`)}
export function parseTool076Number(raw:string){const normalized=raw.replace(/[,_\s₩¥$€]/g,'').trim();if(!normalized||normalized.length>TOOL076_LIMITS.maxInputChars)return null;const value=Number(normalized);return Number.isFinite(value)?value:null}
export function validateTool076Purchase(v:number){finite(v,'PURCHASE');if(v<0)throw new Error('PURCHASE_NEGATIVE');if(v>TOOL076_LIMITS.maxPurchase)throw new Error('PURCHASE_LIMIT')}
export function validateTool076Months(v:number){finite(v,'MONTHS');if(!Number.isInteger(v))throw new Error('MONTHS_INTEGER');if(v<TOOL076_LIMITS.minMonths||v>TOOL076_LIMITS.maxMonths)throw new Error('MONTHS_LIMIT')}
export function validateTool076Rate(v:number){finite(v,'RATE');if(v<0)throw new Error('RATE_NEGATIVE');if(v>TOOL076_LIMITS.maxRate)throw new Error('RATE_LIMIT')}
export function calculateTool076(purchase:number,months:number,rate:number):Tool076Result{validateTool076Purchase(purchase);validateTool076Months(months);validateTool076Rate(rate);const totalFee=purchase*(rate/100);const totalPayment=purchase+totalFee;const monthlyPayment=totalPayment/months;return{purchase,months,rate,totalFee,totalPayment,monthlyPayment,interestFree:rate===0,formula:'total fee = purchase × rate / 100; total payment = purchase + total fee; monthly payment = total payment ÷ months'}}
export function compareTool076(purchase:number,rate:number,monthsList=[3,6,12,24]):Tool076Scenario[]{if(monthsList.length<1||monthsList.length>TOOL076_LIMITS.maxScenarios)throw new Error('SCENARIO_LIMIT');const rows=monthsList.map(m=>calculateTool076(purchase,m,rate));const minMonthly=Math.min(...rows.map(r=>r.monthlyPayment));const minTotal=Math.min(...rows.map(r=>r.totalPayment));return rows.map(r=>({...r,isLowestMonthly:r.monthlyPayment===minMonthly,isLowestTotal:r.totalPayment===minTotal}))}
export function roundTool076(value:number,precision=2){const digits=Math.max(0,Math.min(TOOL076_LIMITS.maxDisplayPrecision,precision));const factor=10**digits;return Math.round((value+Number.EPSILON)*factor)/factor}
export function formatTool076(value:number,precision=2,locale='ko-KR'){const digits=Math.max(0,Math.min(TOOL076_LIMITS.maxDisplayPrecision,precision));return new Intl.NumberFormat(locale,{minimumFractionDigits:digits,maximumFractionDigits:digits}).format(value)}
