export type Tool089SlopeMode='angle'|'percent'|'riseRun';
export const TOOL089_LIMITS={maxDimensionM:1e6,maxAngleDeg:89.999,maxSlopePercent:10000,maxExtraPercent:100,maxInputChars:30,maxDisplayPrecision:8} as const;
export type Tool089Result={width:number;length:number;angleDeg:number;slopePercent:number;riseRunRatio:number;horizontalArea:number;slopedWidth:number;actualArea:number;extraPercent:number;materialArea:number};
export function parseTool089Number(raw:string):number|null{const v=raw.trim().replace(/,/g,'');if(!v||!/^(?:\d+\.?\d*|\.\d+)$/.test(v))return null;const n=Number(v);return Number.isFinite(n)?n:null}
function assertFinite(n:number){if(!Number.isFinite(n))throw new Error('INVALID')}
function validateDim(n:number){assertFinite(n);if(n<=0)throw new Error('DIMENSION_ZERO');if(n>TOOL089_LIMITS.maxDimensionM)throw new Error('DIMENSION_LIMIT')}
export function tool089AngleFromPercent(percent:number){assertFinite(percent);if(percent<0)throw new Error('SLOPE_NEGATIVE');if(percent>TOOL089_LIMITS.maxSlopePercent)throw new Error('SLOPE_LIMIT');return Math.atan(percent/100)*180/Math.PI}
export function tool089AngleFromRiseRun(rise:number,run:number){assertFinite(rise);assertFinite(run);if(rise<0)throw new Error('SLOPE_NEGATIVE');if(run<=0)throw new Error('RUN_ZERO');return Math.atan(rise/run)*180/Math.PI}
export function tool089SlopeToAngle(mode:Tool089SlopeMode,a:number,b?:number){let angle=mode==='angle'?a:mode==='percent'?tool089AngleFromPercent(a):tool089AngleFromRiseRun(a,b??0);assertFinite(angle);if(angle<0)throw new Error('SLOPE_NEGATIVE');if(angle>=TOOL089_LIMITS.maxAngleDeg)throw new Error('ANGLE_LIMIT');return angle}
export function calculateTool089(width:number,length:number,mode:Tool089SlopeMode,slopeA:number,slopeB:number|undefined,extraPercent:number):Tool089Result{validateDim(width);validateDim(length);assertFinite(extraPercent);if(extraPercent<0||extraPercent>TOOL089_LIMITS.maxExtraPercent)throw new Error('EXTRA_LIMIT');const angleDeg=tool089SlopeToAngle(mode,slopeA,slopeB);const rad=angleDeg*Math.PI/180;const cos=Math.cos(rad);if(cos<=0.00001)throw new Error('ANGLE_LIMIT');const horizontalArea=width*length;const slopedWidth=width/cos;const actualArea=horizontalArea/cos;return{width,length,angleDeg,slopePercent:Math.tan(rad)*100,riseRunRatio:Math.tan(rad),horizontalArea,slopedWidth,actualArea,extraPercent,materialArea:actualArea*(1+extraPercent/100)}}
export function formatTool089(value:number,precision=3,locale='ko-KR'){return new Intl.NumberFormat(locale,{maximumFractionDigits:Math.max(0,Math.min(TOOL089_LIMITS.maxDisplayPrecision,precision))}).format(value)}
