export const TOOL082_LIMITS={maxArea:1e9,maxRatio:1000,maxPrecision:8,maxInputChars:30,maxScenarios:4} as const;
export type Tool082CurrentResult={siteArea:number;buildingArea:number;grossFloorArea:number;coverage:number;far:number;coverageFormula:string;farFormula:string};
export type Tool082TargetResult={siteArea:number;targetCoverage:number|null;targetFar:number|null;possibleBuildingArea:number|null;possibleGrossFloorArea:number|null;buildingFormula:string|null;grossFormula:string|null};
function finite(value:number,label:string){if(!Number.isFinite(value))throw new Error(`${label}_INVALID`)}
export function parseTool082Number(raw:string){const normalized=raw.replace(/[,_\s㎡m²]/gi,'').trim();if(!normalized||normalized.length>TOOL082_LIMITS.maxInputChars)return null;const value=Number(normalized);return Number.isFinite(value)?value:null}
export function validateTool082SiteArea(value:number){finite(value,'SITE');if(value<=0)throw new Error('SITE_NON_POSITIVE');if(value>TOOL082_LIMITS.maxArea)throw new Error('SITE_LIMIT')}
export function validateTool082Area(value:number,label='AREA'){finite(value,label);if(value<0)throw new Error(`${label}_NEGATIVE`);if(value>TOOL082_LIMITS.maxArea)throw new Error(`${label}_LIMIT`)}
export function validateTool082Ratio(value:number,label='RATIO'){finite(value,label);if(value<0)throw new Error(`${label}_NEGATIVE`);if(value>TOOL082_LIMITS.maxRatio)throw new Error(`${label}_LIMIT`)}
export function calculateTool082Current(siteArea:number,buildingArea:number,grossFloorArea:number):Tool082CurrentResult{validateTool082SiteArea(siteArea);validateTool082Area(buildingArea,'BUILDING');validateTool082Area(grossFloorArea,'GROSS');const coverage=buildingArea/siteArea*100;const far=grossFloorArea/siteArea*100;return{siteArea,buildingArea,grossFloorArea,coverage,far,coverageFormula:'building area ÷ site area × 100',farFormula:'gross floor area ÷ site area × 100'}}
export function calculateTool082Target(siteArea:number,targetCoverage:number|null,targetFar:number|null):Tool082TargetResult{validateTool082SiteArea(siteArea);if(targetCoverage!==null)validateTool082Ratio(targetCoverage,'TARGET_COVERAGE');if(targetFar!==null)validateTool082Ratio(targetFar,'TARGET_FAR');const possibleBuildingArea=targetCoverage===null?null:siteArea*targetCoverage/100;const possibleGrossFloorArea=targetFar===null?null:siteArea*targetFar/100;return{siteArea,targetCoverage,targetFar,possibleBuildingArea,possibleGrossFloorArea,buildingFormula:targetCoverage===null?null:'site area × target coverage ÷ 100',grossFormula:targetFar===null?null:'site area × target FAR ÷ 100'}}
export function roundTool082(value:number,precision=2){const digits=Math.max(0,Math.min(TOOL082_LIMITS.maxPrecision,precision));const factor=10**digits;return Math.round((value+Number.EPSILON)*factor)/factor}
export function formatTool082(value:number,precision=2,locale='ko-KR'){const digits=Math.max(0,Math.min(TOOL082_LIMITS.maxPrecision,precision));return new Intl.NumberFormat(locale,{minimumFractionDigits:digits,maximumFractionDigits:digits}).format(value)}
