import fs from 'node:fs';
let pass=0,fail=0;const c=(n,v)=>{console.log(`${v?'PASS':'FAIL'} ${n}`);v?pass++:fail++;};
const required=['lib/tool-056-units.ts','components/tool-056-weight-temperature-pressure-converter.tsx','components/tool-056-weight-temperature-pressure-converter.module.css','components/tool-056-weight-temperature-pressure-converter-page.tsx','app/[locale]/weight-temperature-pressure-converter/page.tsx','tests/tool-056-preflight.spec.ts','tests/tool-056-design.spec.ts','tests/tool-056-core.spec.ts','tests/tool-056-feature.spec.ts','tests/tool-056-temperature.spec.ts','tests/tool-056-pressure.spec.ts','tests/tool-056-mass.spec.ts','tests/tool-056-boundary.spec.ts','tests/tool-056-regression.spec.ts','tests/tool-056-limit.spec.ts','tests/fixtures/tool-056/cases.json'];
for(const f of required)c(`required ${f}`,fs.existsSync(f));
const lib=fs.readFileSync('lib/tool-056-units.ts','utf8');for(const t of ['maxAbsInput:1e15','maxPrecision:8','factor:0.45359237','factor:101325','factor:6894.757293168','factor:133.3224','(value-32)/1.8','celsius*1.8+32','celsius+273.15'])c(`contract ${t}`,lib.includes(t));
const page=fs.readFileSync('components/tool-056-weight-temperature-pressure-converter-page.tsx','utf8');for(const t of ['무게·온도·압력 변환기','Weight, Temperature & Pressure Converter','重量・温度・圧力変換ツール','FAQPage','WebApplication'])c(`page ${t}`,page.includes(t));
const route=fs.readFileSync('app/[locale]/weight-temperature-pressure-converter/page.tsx','utf8');c('canonical languages',route.includes("'x-default':'/ko/weight-temperature-pressure-converter'")&&route.includes("canonical:path"));
const dedicated=['lib/tool-056-units.ts','components/tool-056-weight-temperature-pressure-converter.tsx'].map(f=>fs.readFileSync(f,'utf8')).join('\n');c('browser-local no network API',!/(?:fetch\s*\(|XMLHttpRequest|axios\.|navigator\.sendBeacon|WebSocket\s*\()/i.test(dedicated));c('scope excludes adjacent energy/data/cooking engines',!/(fuel economy|horsepower|byte converter|cooking unit)/i.test(dedicated));
const globals=fs.readFileSync('app/globals.css','utf8');c('no global TOOL056 css contamination',!/tool056|tool-056/i.test(globals));
for(const p of ['styles/global-base.css','styles/toolbox-common.css','styles/toolbox-detail-common.css','styles/theme.css','styles/toolbox-compat.css','styles/legacy-site-sealed.css','styles/legacy-tools-sealed.css']){if(fs.existsSync(p))c(`no global contamination ${p}`,!/tool056|tool-056/i.test(fs.readFileSync(p,'utf8')))}
console.log(`RESULT SOURCE PASS=${pass} FAIL=${fail}`);if(fail)process.exit(1);
