import fs from 'node:fs';
let pass=0,fail=0;const c=(n,v)=>{console.log(`${v?'PASS':'FAIL'} ${n}`);v?pass++:fail++;};const page=fs.readFileSync('components/tool-063-ratio-proportion-calculator-page.tsx','utf8'),css=fs.readFileSync('components/tool-063-ratio-proportion-calculator.module.css','utf8');
const how='toolbox-tool-guide toolbox-tool-guide--five',expert='toolbox-tool-format-guide toolbox-tool-expert-post toolbox-tool-expert-post--wide-head',notes='toolbox-tool-info-band toolbox-tool-info-band--section-start toolbox-tool-info-band--bottom-gap toolbox-tool-info-band--left-head toolbox-tool-info-band--format-head',faq='toolbox-tool-faq';
for(const k of ['ToolboxSubpageShell','toolbox-tool-detail-hero','toolbox-tool-detail-body','toolbox-next-work',how,expert,notes,faq])c(`design contract ${k}`,page.includes(k));
c('NEXT WORK before RELATED TOOLS',page.indexOf('NEXT WORK')<page.indexOf('RELATED TOOLS'));c('lower exact order HOW -> EXPERT -> NOTES -> FAQ',page.indexOf(how)<page.indexOf(expert)&&page.indexOf(expert)<page.indexOf(notes)&&page.indexOf(notes)<page.indexOf(faq));
c('category link exact',page.includes('href={`/${locale}/category/unit-calc`}'));c('expert cards source six',(page.match(/<article key={k}>/g)||[]).length===1&&page.includes('.map(([k,h,p])=>'));
c('expert marker SIMPLIFY',page.includes('SIMPLIFY'));
c('expert marker PROPORTION',page.includes('PROPORTION'));
c('expert marker EQUIVALENT',page.includes('EQUIVALENT'));
c('expert marker SCALE',page.includes('SCALE'));
c('expert marker 1:n / n:1',page.includes('1:n / n:1'));
c('expert marker THREE-PART',page.includes('THREE-PART'));
c('expert heading locale',page.includes('비율 문제를 검산할 수 있게 계산 근거를 함께 보여줍니다'));
c('expert heading locale',page.includes('Show the calculation basis so ratio answers can be checked'));
c('expert heading locale',page.includes('比率問題を確認できる計算根拠も表示します'));
for(const h of ['자주 묻는 질문','Frequently asked questions','よくある質問'])c('FAQ locale heading',page.includes(h));
c('responsive breakpoint 760px',css.includes('@media(max-width:760px)'));
c('responsive breakpoint 520px',css.includes('@media(max-width:520px)'));
c('blue token',css.includes('var(--blue)'));c('line token',css.includes('var(--tb-line)'));c('no !important',!css.includes('!important'));console.log(`RESULT DESIGN PASS=${pass} FAIL=${fail}`);if(fail)process.exit(1);
