import fs from 'node:fs';import path from 'node:path';const root=process.cwd();let pass=0,fail=0;const check=(n,o)=>{console.log(`${o?'PASS':'FAIL'} ${n}`);o?pass++:fail++};
const files=['app/[locale]/time-calculator/page.tsx','components/tool-051-time-calculator.tsx','components/tool-051-time-calculator.module.css','lib/tool-051-time-calculator.ts','tests/fixtures/tool-051/cases.json','docs/tool-051/REQ_MASTER_051.md'];for(const f of files)check(`file:${f}`,fs.existsSync(path.join(root,f)));
const product=fs.readFileSync(path.join(root,'components/tool-051-time-calculator.tsx'),'utf8');for(const token of ['tool051-root','tool051-cross-midnight','tool051-reset','tool051-copy','tool051-result-value'])check(`selector:${token}`,product.includes(token));
check('selector:dynamic mode ids',product.includes('data-testid={`tool051-mode-${m}`}')&&product.includes('["arithmetic","difference","convert"]'));
for(const old of ['tool047-','tool046-','TOOL047_SERVICE_LIMITS'])check(`no stale ${old}`,!product.includes(old));
const page=fs.readFileSync(path.join(root,'app/[locale]/time-calculator/page.tsx'),'utf8');for(const token of ['시간 계산기','Time Calculator','時間計算ツール','canonical','x-default','WebApplication','052','053','054'])check(`page:${token}`,page.includes(token));
const css=fs.readFileSync(path.join(root,'components/tool-051-time-calculator.module.css'),'utf8');check('css mobile 720',css.includes('@media(max-width:720px)'));check('css mobile compact 420',css.includes('@media(max-width:420px)'));check('css no global import',!css.includes('globals.css')&&!css.includes('legacy-'));
const protectedFiles=['app/globals.css','styles/global-base.css','styles/toolbox-common.css','styles/toolbox-detail-common.css','styles/theme.css','styles/toolbox-compat.css','styles/legacy-site-sealed.css','styles/legacy-tools-sealed.css'];for(const f of protectedFiles){const p=path.join(root,f);if(fs.existsSync(p)){const s=fs.readFileSync(p,'utf8');check(`protected no TOOL051 marker:${f}`,!s.includes('tool051')&&!s.includes('tool051Slug')&&!s.includes('time-calculator'));}}
const site=fs.readFileSync(path.join(root,'lib/site.ts'),'utf8');check('integration site tool051',site.includes('tool051Slug = "time-calculator"')&&site.includes('tool051Titles'));
const sitemap=fs.readFileSync(path.join(root,'app/sitemap.ts'),'utf8');check('integration sitemap tool051',sitemap.includes('tool051Slug')&&sitemap.includes('`${baseUrl}/${locale}/${tool051Slug}`'));
console.log(`RESULT SOURCE PASS=${pass} FAIL=${fail}`);if(fail)process.exit(1);
