import fs from 'node:fs';
let pass=0,fail=0;const c=(n,o)=>{console.log(`${o?'PASS':'FAIL'} ${n}`);o?pass++:fail++};
const page=fs.readFileSync('components/tool-082-building-ratio-page.tsx','utf8');
const ui=fs.readFileSync('components/tool-082-building-ratio.tsx','utf8');
const css=fs.readFileSync('components/tool-082-building-ratio.module.css','utf8');
const lower=['toolbox-tool-guide toolbox-tool-guide--five','toolbox-tool-format-guide toolbox-tool-expert-post','toolbox-tool-info-band toolbox-tool-info-band--section-start','toolbox-tool-faq'];
const pos=lower.map(x=>page.indexOf(x));
c('lower section order HOWTO>EXPERT>NOTES>FAQ',pos.every((v,i)=>v>=0&&(i===0||v>pos[i-1])));
c('common detail shell',page.includes('ToolboxSubpageShell')&&page.includes('toolbox-tool-detail-hero')&&page.includes('toolbox-tool-detail-body'));
c('navigation current tool 82',page.includes('currentTool={82}'));
c('category route real-estate-build',page.includes('/category/real-estate-build'));
c('expert guide six cards',['COVERAGE','FAR','EXAMPLE 01','EXAMPLE 02','COMPARE','LEGAL'].every(x=>page.includes(x)));
c('shared FAQ progressive disclosure',page.includes('ToolboxFaqList')&&page.includes('initialCount={4}'));
c('workspace current/target DOM',ui.includes('data-testid="tool082-workspace"')&&ui.includes('data-testid="tool082-current-card"')&&ui.includes('data-testid="tool082-target-card"'));
c('desktop two-column workspace',css.includes('grid-template-columns:repeat(2,minmax(0,1fr))'));
c('mobile single-column workspace',css.includes('@media(max-width:900px)')&&css.includes('.workspace{grid-template-columns:1fr}'));
c('result overflow protection',css.includes('overflow-wrap:anywhere'));
c('primary action black',css.includes('background:#111')&&css.includes('color:#fff'));
c('design tokens reused',['var(--tb-line)','var(--tb-panel)','var(--blue)'].every(x=>css.includes(x)));
c('no important/global mutation',!css.includes('!important')&&!css.includes(':global(')&&!css.includes('.toolbox-tool-'));
console.log(`RESULT TOOL082 DESIGN-CODE PASS=${pass} FAIL=${fail}`);process.exitCode=fail?1:0;
