import fs from 'node:fs';
let pass=0,fail=0;const c=(n,v)=>{console.log(`${v?'PASS':'FAIL'} ${n}`);v?pass++:fail++;};const page=fs.readFileSync('components/tool-061-percentage-percent-change-calculator-page.tsx','utf8'),css=fs.readFileSync('components/tool-061-percentage-percent-change-calculator.module.css','utf8');
const how='toolbox-tool-guide toolbox-tool-guide--five',expert='toolbox-tool-format-guide toolbox-tool-expert-post toolbox-tool-expert-post--wide-head',notes='toolbox-tool-info-band toolbox-tool-info-band--section-start toolbox-tool-info-band--bottom-gap toolbox-tool-info-band--left-head toolbox-tool-info-band--format-head',faq='toolbox-tool-faq';
for(const k of ['ToolboxSubpageShell','toolbox-tool-detail-hero','toolbox-tool-detail-body','toolbox-next-work',how,expert,notes,faq])c(`design contract ${k}`,page.includes(k));
c('NEXT WORK before RELATED TOOLS',page.indexOf('NEXT WORK')<page.indexOf('RELATED TOOLS'));c('lower exact order HOW -> EXPERT -> NOTES -> FAQ',page.indexOf(how)<page.indexOf(expert)&&page.indexOf(expert)<page.indexOf(notes)&&page.indexOf(notes)<page.indexOf(faq));
c('category link exact',page.includes('href={`/${locale}/category/unit-calc`}'));c('expert cards source six',(page.match(/<article key={k}>/g)||[]).length===1&&page.includes('.map(([k,h,p])=>'));
c('expert marker PART / WHOLE',page.includes('PART / WHOLE'));
c('expert marker PERCENT OF',page.includes('PERCENT OF'));
c('expert marker CHANGE',page.includes('CHANGE'));
c('expert marker APPLY',page.includes('APPLY'));
c('expert marker REVERSE',page.includes('REVERSE'));
c('expert marker PERCENT POINT',page.includes('PERCENT POINT'));
c('expert heading locale',page.includes('퍼센트는 기준값이 무엇인지부터 확인하세요'));
c('expert heading locale',page.includes('Start by identifying the percentage base'));
c('expert heading locale',page.includes('パーセントは基準値を先に確認してください'));
for(const h of ['자주 묻는 질문','Frequently asked questions','よくある質問'])c('FAQ locale heading',page.includes(h));
c('responsive breakpoint 900px',css.includes('@media(max-width:900px)'));
c('responsive breakpoint 520px',css.includes('@media(max-width:520px)'));
c('blue token',css.includes('var(--blue)'));c('line token',css.includes('var(--tb-line)'));c('no !important',!css.includes('!important'));console.log(`RESULT DESIGN PASS=${pass} FAIL=${fail}`);if(fail)process.exit(1);
