import fs from 'node:fs';
const css=fs.readFileSync('components/tool-073-deposit-savings-calculator.module.css','utf8');
const page=fs.readFileSync('components/tool-073-deposit-savings-calculator-page.tsx','utf8');
const ui=fs.readFileSync('components/tool-073-deposit-savings-calculator.tsx','utf8');
const main=fs.readFileSync('components/tool-066-vat-calculator.module.css','utf8');
let pass=0,fail=0;const check=(name,ok)=>{console.log(`${ok?'PASS':'FAIL'} ${name}`);ok?pass++:fail++};
for(const token of ['ToolboxSubpageShell','toolbox-tool-detail-hero','toolbox-tool-detail-body','toolbox-next-work','toolbox-tool-guide toolbox-tool-guide--five','toolbox-tool-format-guide toolbox-tool-expert-post toolbox-tool-expert-post--wide-head','toolbox-tool-info-band toolbox-tool-info-band--section-start toolbox-tool-info-band--bottom-gap toolbox-tool-info-band--left-head toolbox-tool-info-band--format-head','toolbox-tool-faq'])check(`common contract ${token}`,token==='toolbox-next-work'?(page.includes('toolbox-next-work')||page.includes('ToolNavigation')):page.includes(token));
const seq=['toolbox-tool-guide toolbox-tool-guide--five','toolbox-tool-format-guide toolbox-tool-expert-post','toolbox-tool-info-band toolbox-tool-info-band--section-start','toolbox-tool-faq'].map(x=>page.indexOf(x));check('lower section order',seq.every((v,i)=>v>=0&&(i===0||v>seq[i-1])));
check('expert 6-card common DOM',page.includes('toolbox-tool-format-grid')&&page.includes('<article key={tag}><strong>{tag}</strong><h3>{title}</h3><p>{body}</p></article>')&&/\['06','/.test(page));
check('important notes head/list exact DOM',page.includes('toolbox-tool-info-band-head')&&page.includes('toolbox-tool-info-band-list')&&page.includes('{t.notes.map(n=><li key={n}>{n}</li>)}'));
check('no old numbered info-band grid',!page.includes('toolbox-tool-info-band-grid'));
check('FAQ shared API exact',page.includes('initialCount={5}')&&page.includes('moreLabel={')&&page.includes('collapseLabel={')&&!page.includes('<ToolboxFaqList locale={locale}'));
check('MAIN TOOL066 workspace shell parity',main.includes('border-radius:22px')&&css.includes('border-radius:22px')&&main.includes('color-mix(in srgb,var(--blue) 4%,var(--tb-panel))')&&css.includes('color-mix(in srgb,var(--blue) 4%,var(--tb-panel))'));
check('MAIN TOOL066 local notice parity',main.includes('.localNotice{display:flex')&&css.includes('.localNotice{display:flex'));
check('desktop 5-result grid',css.includes('grid-template-columns:repeat(5,minmax(0,1fr))'));
check('tablet result reflow',css.includes('@media(max-width:980px)')&&css.includes('grid-template-columns:repeat(2,minmax(0,1fr))'));
check('mobile single result column',css.includes('@media(max-width:620px)')&&css.includes('.resultGrid{grid-template-columns:1fr}'));
check('mobile action grid',css.includes('.actionRow{display:grid;grid-template-columns:1fr 1fr}'));
check('long amount overflow protection',css.includes('overflow-wrap:anywhere'));
check('primary action contract',css.includes('.primaryButton{border:1px solid #111;background:#111;color:#fff}'));
check('no globals or sealed reference',!css.includes('globals.css')&&!css.includes('legacy-')&&!page.includes('legacy-')&&!ui.includes('legacy-'));
console.log(`RESULT DESIGN-CODE PASS=${pass} FAIL=${fail} MAIN=066 TOOL=073`);process.exitCode=fail?1:0;
