import fs from 'node:fs';
const read=p=>fs.readFileSync(p,'utf8'); let fail=0,pass=0; const check=(n,ok)=>{console.log(`[${ok?'PASS':'FAIL'}] ${n}`);ok?pass++:fail++;};
const required=['lib/tool-043-text-diff.ts','components/text-diff-compare-tool.tsx','components/text-diff-compare-tool.module.css','components/text-tool-input-common.module.css','components/text-find-replace-tool.tsx','components/text-find-replace-tool.module.css','components/text-diff-compare-page.tsx','app/[locale]/text-diff-compare/page.tsx','tests/fixtures/tool-043/core.json','tests/fixtures/tool-043/boundary.json','tests/fixtures/tool-043/file-a.txt','tests/fixtures/tool-043/file-b.txt','app/sitemap.ts','lib/site.ts','tests/helpers/tool-043.ts','tests/tool-043-preflight.spec.ts','tests/tool-043-core.spec.ts','tests/tool-043-boundary.spec.ts','tests/tool-043-regression.spec.ts','tests/tool-043-limit.spec.ts','playwright.tool043.config.ts'];
for(const f of required)check(`exists ${f}`,fs.existsSync(f));
const tool=read('components/text-diff-compare-tool.tsx'),page=read('components/text-diff-compare-page.tsx'),logic=read('lib/tool-043-text-diff.ts'),site=read('lib/site.ts'),map=read('app/sitemap.ts'),css=read('components/text-diff-compare-tool.module.css'),commonCss=read('components/text-tool-input-common.module.css'),tool042=read('components/text-find-replace-tool.tsx');
for(const [n,r] of [['empty A state',/tool043-empty-a/],['empty B state',/tool043-empty-b/],['A\/B active state',/activeA[\s\S]*activeB/],['blue empty workspace',/emptyStart/],['A input',/tool043-input-a/],['B input',/tool043-input-b/],['run action',/tool043-run/],['line mode',/tool043-mode-line/],['word mode',/tool043-mode-word/],['copy report',/navigator\.clipboard\.writeText\(report\)/],['reset complete',/setA\(""\).*setB\(""\).*setResult\(null\).*setMode\("line"\)/s],['disabled empty run',/disabled=\{!a&&!b\}/],['A file input',/tool043-file-a/],['B file input',/tool043-file-b/],['drag A zone',/tool043-drop-a/],['drag B zone',/tool043-drop-b/],['plain text extensions',/TXT · MD · CSV · JSON · XML · LOG/],['swap action',/tool043-swap/],['changes-only action',/tool043-changes-only/],['TXT download action',/tool043-download/],['line number renderer',/NumberedLines/],['paste activation',/pasteIntoSide/]])check(n,r.test(tool));
for(const [n,r,negate=false] of [['deterministic line engine',/myersDiff/],['changed grouping',/g\.kind === "delete" && next\?\.kind === "insert"/],['word segmenter',/Intl\.Segmenter/],['reconstruction helper',/reconstructTool043/],['no normalization',/normalize\(/,true],['candidate character limit',/maxCharactersPerText:\s*200_000/],['candidate line limit',/maxLinesPerText:\s*20_000/]])check(n,negate?!r.test(logic):r.test(logic));
check('MAIN shell',/toolbox-tool-detail-hero[\s\S]*toolbox-tool-detail-body/.test(page));check('KO EN JA page copy',/ko:\{[\s\S]*en:\{[\s\S]*ja:\{/.test(page));check('shared TOOL042 workspace CSS',/\.workspaceSurface[\s\S]*\.startDropzone[\s\S]*\.plusIcon[\s\S]*\.fileButton/.test(commonCss));check('043 uses shared workspace CSS',/inputCommon\.workspaceSurface[\s\S]*inputCommon\.startDropzone[\s\S]*inputCommon\.plusIcon[\s\S]*inputCommon\.fileButton/.test(tool));check('042 uses shared workspace CSS',/inputCommon\.workspaceSurface[\s\S]*inputCommon\.startDropzone[\s\S]*inputCommon\.plusIcon[\s\S]*inputCommon\.fileButton/.test(tool042));check('043 A B modifiers only',/\.sideBadge[\s\S]*\.emptyStartModifier/.test(css));check('responsive 720',/@media\(max-width:720px\)/.test(css));check('responsive 420',/@media\(max-width:420px\)/.test(css));check('site 043 LIVE',/tool043Slug[\s\S]*title:\s*tool043Titles[\s\S]*status:\s*"LIVE"/.test(site));check('sitemap 043',/\$\{tool043Slug\}/.test(map));check('042 next available 043',/text-diff-compare[\s\S]*Available/.test(read('components/text-find-replace-page.tsx')));check('approved service limit copy',/서비스 상한:[\s\S]*Service limit:[\s\S]*サービス上限:/.test(tool));check('core extra feature runtime cases',/setInputFiles[\s\S]*drag and drop[\s\S]*changes-only[\s\S]*download/i.test(read('tests/tool-043-core.spec.ts')));check('line limit runtime case',/line limit plus one/.test(read('tests/tool-043-limit.spec.ts')));
console.log(`TOOL043 STATIC PASS=${pass} FAIL=${fail}`);process.exitCode=fail?1:0;
