import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { ToolboxSubpageShell } from "@/components/toolbox-subpage-shell";
import { ToolboxFaqList } from "@/components/toolbox-faq-list";
import { Tool051TimeCalculator } from "@/components/tool-051-time-calculator";
import { locales, type Locale } from "@/lib/site";

const copy = {
  ko:{title:"시간 계산기",desc:"시간을 더하고 빼거나 두 시각의 차이를 계산하고 12·24시간제로 변환합니다.",back:"날짜·시간 도구",how:"사용 방법",next:"다음 작업",related:"관련 도구",steps:["시간 더하기·빼기, 두 시각 차이, 12·24시간 변환 중 목적을 선택합니다.","기준 시각이나 시작·종료 시각을 입력합니다.","자정을 넘는 차이라면 자정 넘김을 직접 켭니다.","결과 시각 또는 경과시간을 확인합니다.","필요하면 결과를 복사하거나 초기화합니다."],notes:["두 시각 차이에서 종료 시각이 더 이르면 자동으로 다음 날이라고 가정하지 않습니다.","12 AM은 00:00 자정이고 12 PM은 12:00 정오입니다.","시간량은 최대 999시간 59분 59초까지 입력하도록 설계했습니다.","타임존·도시 비교는 TOOL052, Unix Timestamp는 TOOL053, 타이머·스톱워치는 TOOL054의 역할입니다.","입력한 시각은 서버나 Analytics로 전송하지 않고 브라우저 로컬에서 계산합니다."],faqs:[["23:30에서 01:15까지 몇 시간인가요?","자정 넘김을 켜면 다음 날 01:15로 해석하여 1시간 45분으로 계산합니다."],["자정 넘김은 자동인가요?","아니요. 기본값은 OFF이며 종료 시각이 더 이르면 사용자가 직접 켭니다."],["12 AM은 몇 시인가요?","24시간제로 00:00, 즉 자정입니다. 12 PM은 12:00 정오입니다."],["시간 차이를 계산할 때 24시간 형식만 써야 하나요?","아니요. 계산 결과와 변환 기능에서 12시간제와 24시간제를 사용할 수 있습니다."],["타임존도 계산할 수 있나요?","아니요. 도시별 시각과 UTC/타임존 변환은 TOOL052의 역할입니다."]]},
  en:{title:"Time Calculator",desc:"Add or subtract time, calculate the difference between two times, and convert between 12-hour and 24-hour formats.",back:"Date & Time Tools",how:"How to use",next:"Next work",related:"Related tools",steps:["Choose Add/Subtract Time, Time Difference, or 12/24-hour Conversion.","Enter the base time or start and end times.","Enable Cross midnight explicitly when the interval passes midnight.","Review the resulting clock time or elapsed duration.","Copy the result or reset the calculator when needed."],notes:["When the end time is earlier, the calculator does not silently assume the next day.","12 AM is midnight (00:00), while 12 PM is noon (12:00).","Duration input is designed for up to 999 hours 59 minutes 59 seconds.","Time zones belong to TOOL052, Unix timestamps to TOOL053, and timers/stopwatches to TOOL054.","Entered times are calculated locally in the browser and are not sent to a server or Analytics."],faqs:[["How long is 23:30 to 01:15?","Enable Cross midnight and the interval is calculated as 1 hour 45 minutes."],["Is crossing midnight automatic?","No. It is OFF by default and must be enabled explicitly when the end time is earlier."],["What time is 12 AM?","It is 00:00, midnight. 12 PM is 12:00 noon."],["Do I have to use 24-hour time?","No. You can use the 12/24 conversion feature and choose the result format for arithmetic."],["Can this calculate time zones?","No. City, UTC, and time-zone conversion belong to TOOL052."]]},
  ja:{title:"時間計算ツール",desc:"時間の加算・減算、2つの時刻の差、12時間制と24時間制の変換に対応します。",back:"日付・時間ツール",how:"使い方",next:"次の作業",related:"関連ツール",steps:["時間の加算・減算、時刻の差、12・24時間制変換から目的を選びます。","基準時刻または開始・終了時刻を入力します。","日付をまたぐ場合は「日付をまたぐ」を明示的に有効にします。","結果の時刻または経過時間を確認します。","必要なら結果をコピーするかリセットします。"],notes:["終了時刻が早い場合でも自動で翌日とは判断しません。","12 AMは00:00の深夜0時、12 PMは12:00の正午です。","時間量は最大999時間59分59秒までを想定しています。","タイムゾーンはTOOL052、Unix TimestampはTOOL053、タイマー・ストップウォッチはTOOL054の役割です。","入力した時刻はサーバーやAnalyticsへ送信せずブラウザ内で計算します。"],faqs:[["23:30から01:15までは何時間ですか？","「日付をまたぐ」を有効にすると翌日01:15として1時間45分を計算します。"],["日付またぎは自動ですか？","いいえ。初期状態はOFFで、終了時刻が早い場合は利用者が明示的に有効にします。"],["12 AMは何時ですか？","24時間制では00:00、深夜0時です。12 PMは12:00の正午です。"],["24時間制だけを使う必要がありますか？","いいえ。12・24時間制変換と結果形式の切り替えを利用できます。"],["タイムゾーンも計算できますか？","いいえ。都市・UTC・タイムゾーン変換はTOOL052の役割です。"]]}
} as const;

export async function generateStaticParams(){return locales.map(locale=>({locale}));}
export async function generateMetadata({params}:{params:Promise<{locale:string}>}):Promise<Metadata>{const {locale}=await params;if(!locales.includes(locale as Locale))notFound();const l=locale as Locale,c=copy[l],url=`https://toolbox.fixlgs.com/${l}/time-calculator`;return{title:l==='ko'?"시간 계산기 | 시간 더하기·빼기·시각 차이":l==='ja'?"時間計算ツール | 加算・減算・時刻差":"Time Calculator | Add, Subtract & Time Difference",description:c.desc,alternates:{canonical:url,languages:{ko:"https://toolbox.fixlgs.com/ko/time-calculator",en:"https://toolbox.fixlgs.com/en/time-calculator",ja:"https://toolbox.fixlgs.com/ja/time-calculator","x-default":"https://toolbox.fixlgs.com/ko/time-calculator"}}};}

export default async function Page({params}:{params:Promise<{locale:string}>}){const {locale}=await params;if(!locales.includes(locale as Locale))notFound();const l=locale as Locale,c=copy[l];const related=l==='ko'?[['050','평일·영업일 계산기','business-day-calculator'],['052','세계시간·타임존 변환기','world-time-timezone-converter'],['053','Unix Timestamp 변환기','unix-timestamp-converter']]:l==='ja'?[['050','平日・営業日計算ツール','business-day-calculator'],['052','世界時間・タイムゾーン変換ツール','world-time-timezone-converter'],['053','Unix Timestamp変換ツール','unix-timestamp-converter']]:[['050','Weekday & Business Day Calculator','business-day-calculator'],['052','World Time & Time Zone Converter','world-time-timezone-converter'],['053','Unix Timestamp Converter','unix-timestamp-converter']];return <ToolboxSubpageShell locale={l} appName={c.title}>
<script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify({"@context":"https://schema.org","@type":"WebApplication",name:c.title,applicationCategory:"UtilitiesApplication",operatingSystem:"Any",offers:{"@type":"Offer",price:"0",priceCurrency:"USD"},url:`https://toolbox.fixlgs.com/${l}/time-calculator`,description:c.desc})}}/>
<section className="toolbox-tool-detail-hero toolbox-tool-detail-hero--single-line-description"><Link className="toolbox-subpage-back" href={`/${l}/category/date-time`}>← {c.back}</Link><p className="toolbox-subpage-eyebrow">051 · DATE & TIME</p><div className="toolbox-tool-detail-heading"><h1><span className="toolbox-tool-title-line">{c.title}</span></h1><p>{c.desc}</p></div><div className="toolbox-tool-detail-badge"><strong>LOCAL</strong><span>{l==='ko'?'브라우저에서 바로 계산':l==='ja'?'ブラウザ内で計算':'CALCULATE IN YOUR BROWSER'}</span></div></section>
<section className="toolbox-tool-detail-body"><div><Tool051TimeCalculator locale={l}/><section className="toolbox-next-work"><div className="toolbox-next-work-head"><p>NEXT WORK</p><h2>{c.next}</h2></div><div className="toolbox-next-work-grid"><Link href={`/${l}/${related[1][2]}`} className="toolbox-next-work-card"><span>052</span><h3>{related[1][1]}</h3><div className="toolbox-next-work-card-foot"><span>{l==='ko'?'사용 가능':l==='ja'?'利用可能':'Available'}</span><strong>↗</strong></div></Link></div></section><section className="toolbox-next-work"><div className="toolbox-next-work-head"><p>RELATED TOOLS</p><h2>{c.related}</h2></div><div className="toolbox-next-work-grid"><Link href={`/${l}/${related[0][2]}`} className="toolbox-next-work-card"><span>{related[0][0]}</span><h3>{related[0][1]}</h3><div className="toolbox-next-work-card-foot"><span>{l==='ko'?'사용 가능':l==='ja'?'利用可能':'Available'}</span><strong>↗</strong></div></Link><Link href={`/${l}/${related[2][2]}`} className="toolbox-next-work-card"><span>{related[2][0]}</span><h3>{related[2][1]}</h3><div className="toolbox-next-work-card-foot"><span>{l==='ko'?'사용 가능':l==='ja'?'利用可能':'Available'}</span><strong>↗</strong></div></Link></div></section></div></section>
<section className="toolbox-tool-guide toolbox-tool-guide--five"><div className="toolbox-tool-guide-head"><p>HOW TO USE</p><h2>{c.how}</h2></div><ol>{c.steps.map((s,i)=><li key={s}><span>{String(i+1).padStart(2,'0')}</span><p>{s}</p></li>)}</ol></section>
<section className="toolbox-tool-format-guide toolbox-tool-expert-post toolbox-tool-expert-post--wide-head"><div className="toolbox-tool-format-guide-head"><p>TIME CALCULATION GUIDE</p><h2>{l==='ko'?'시간 계산에서 자정과 12 AM/PM을 다루는 기준':l==='ja'?'時刻計算での日付またぎと12 AM/PMの基準':'Midnight and 12 AM/PM rules for time calculations'}</h2><span>{l==='ko'?'시각(clock time)과 시간량(duration)을 구분하고 모든 계산을 총 초로 정규화합니다.':l==='ja'?'時刻と時間量を分け、計算は合計秒に正規化します。':'Clock time and duration are separated, while calculations use normalized total seconds.'}</span></div><div className="toolbox-tool-format-body"><div className="toolbox-tool-format-grid"><article><strong>MIDNIGHT</strong><h3>{l==='ko'?'자정 넘김은 명시적으로':l==='ja'?'日付またぎは明示的に':'Cross midnight explicitly'}</h3><p>{l==='ko'?'종료가 시작보다 이르면 자동 추정하지 않고 자정 넘김 옵션을 사용합니다.':l==='ja'?'終了が開始より早い場合、自動推定せず日付またぎを選択します。':'An earlier end time is not silently treated as the next day.'}</p></article><article><strong>12 AM / PM</strong><h3>00:00 / 12:00</h3><p>{l==='ko'?'12 AM은 자정, 12 PM은 정오로 변환합니다.':l==='ja'?'12 AMは深夜0時、12 PMは正午です。':'12 AM maps to midnight; 12 PM maps to noon.'}</p></article><article><strong>NORMALIZE</strong><h3>{l==='ko'?'분·초 carry 자동 처리':l==='ja'?'分・秒の繰り上がり':'Automatic carry'}</h3><p>{l==='ko'?'59분·59초 경계도 총 초 계산 후 다시 시·분·초로 분해합니다.':l==='ja'?'合計秒で計算し、時・分・秒へ再分解します。':'Minute and second boundaries are normalized from total seconds.'}</p></article></div></div></section>
<section className="toolbox-tool-info-band toolbox-tool-info-band--section-start toolbox-tool-info-band--bottom-gap toolbox-tool-info-band--left-head toolbox-tool-info-band--format-head"><div className="toolbox-tool-info-band-head"><p>IMPORTANT NOTES</p><h2>{l==='ko'?'주의사항':l==='ja'?'注意事項':'Important notes'}</h2></div><ul className="toolbox-tool-info-band-list">{c.notes.map(n=><li key={n}>{n}</li>)}</ul></section>
<section className="toolbox-tool-faq"><div className="toolbox-tool-guide-head"><p>FAQ</p><h2>{l==='ko'?'자주 묻는 질문':l==='ja'?'よくある質問':'Frequently asked questions'}</h2></div><ToolboxFaqList items={c.faqs} initialCount={5} moreLabel={l==='ko'?'FAQ 더보기':l==='ja'?'FAQをもっと見る':'Show more FAQs'} collapseLabel={l==='ko'?'FAQ 접기':l==='ja'?'FAQを閉じる':'Collapse FAQs'} className="toolbox-tool-faq-list"/></section>
</ToolboxSubpageShell>}
