import fs from 'node:fs';
const page=fs.readFileSync('components/tool-071-ad-sales-performance-calculator-page.tsx','utf8');
const css=fs.readFileSync('components/tool-071-ad-sales-performance-calculator.module.css','utf8');
const commonCss=fs.readFileSync('styles/toolbox-common.css','utf8');
const detailCss=fs.readFileSync('styles/toolbox-detail-common.css','utf8');
let pass=0,fail=0;const check=(name,ok)=>{console.log(`${ok?'PASS':'FAIL'} ${name}`);ok?pass++:fail++};
const how='toolbox-tool-guide toolbox-tool-guide--five',expert='toolbox-tool-format-guide toolbox-tool-expert-post toolbox-tool-expert-post--wide-head',notes='toolbox-tool-info-band toolbox-tool-info-band--section-start toolbox-tool-info-band--bottom-gap toolbox-tool-info-band--left-head toolbox-tool-info-band--format-head',faq='toolbox-tool-faq';
for(const token of ['ToolboxSubpageShell','toolbox-tool-detail-hero','toolbox-tool-detail-body',how,expert,notes,faq])check(`common ${token}`,page.includes(token));
const seq=[how,'toolbox-tool-format-guide toolbox-tool-expert-post','toolbox-tool-info-band toolbox-tool-info-band--section-start',faq].map(x=>page.indexOf(x));check('HOW TO -> EXPERT -> NOTES -> FAQ',seq.every((v,i)=>v>=0&&(i===0||v>seq[i-1])));
check('approved KO expert headline',page.includes('광고·매출 지표 가이드'));
check('expert six article contract',page.includes('><article')&&['CTR','CPC / CPM','CVR','CAC','ROAS / ROI','AOV'].every(x=>page.includes(`'${x}'`)));
check('expert shared wide-head css exists',detailCss.includes('.toolbox-tool-expert-post--wide-head .toolbox-tool-format-guide-head')&&detailCss.includes('overflow-wrap:anywhere'));
check('expert shared grid article css exists',commonCss.includes('.toolbox-tool-format-grid article{')&&commonCss.includes('min-width:0'));
check('IMPORTANT NOTES separate',page.includes('<p>IMPORTANT NOTES</p>')&&page.includes('toolbox-tool-info-band-list'));
check('shared full-width divider contract',detailCss.includes('.toolbox-tool-info-band--format-head.toolbox-tool-info-band--section-start::before')&&detailCss.includes('width:100vw'));
check('FAQ common guide-head',page.includes('<section className="toolbox-tool-faq"><div className="toolbox-tool-guide-head"><p>FAQ</p>'));
check('FAQ localized proper heading',page.includes("'자주 묻는 질문'")&&page.includes("'よくある質問'")&&page.includes("'Frequently asked questions'"));
check('FAQ shared list initial 4',page.includes('<ToolboxFaqList')&&page.includes('initialCount={4}')&&page.includes('className="toolbox-tool-faq-list"'));
check('FAQ more/collapse labels',page.includes("'FAQ 더보기'")&&page.includes("'FAQ 접기'")&&page.includes("'FAQをもっと見る'")&&page.includes("'Collapse FAQs'"));
check('no legacy FAQ head',!page.includes('toolbox-tool-faq-head'));
check('no per-tool expert global css',!css.includes(':global(.toolbox-tool-expert-post')&&!css.includes('.toolbox-tool-expert-post'));
check('no per-tool FAQ global css',!css.includes(':global(.toolbox-tool-faq')&&!css.includes('.toolbox-tool-faq'));
console.log(`RESULT TOOL071 DESIGN-CODE PASS=${pass} FAIL=${fail}`);process.exitCode=fail?1:0;
